/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// resource.js -	다국어 지원용 resource 모음(China)
//					
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// 전체 적용되는 리소스 선언
var ID_RES_GLOBAL_DEFAULT_FONT_FAMILY = "Arial";
var ID_RES_GLOBAL_FONT_FAMILY_TYPE_1 = "Arial";

// ComboBox Size Layer(comboboxwin) 리소스 선언
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_8 = "一二三四 ABCD";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_24 = "一二三 ABC";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_36 = "一二 AB";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_MAX = "一二";
var ID_RES_COOMBOBOX_FONT_NAME_0 = "arial";
var ID_RES_COOMBOBOX_FONT_NAME_1 = "Tahoma";
var ID_RES_COOMBOBOX_FONT_NAME_2 = "times new roman";
var ID_RES_COOMBOBOX_FONT_NAME_3 = "verdana";					//10
var ID_RES_COOMBOBOX_FONT_NAME_4 = "comic sans ms";
var ID_RES_COOMBOBOX_FONT_NAME_5 = "courier new";
var ID_RES_COOMBOBOX_FONT_NAME_6 = "";
var ID_RES_COOMBOBOX_FONT_NAME_7 = "";
var ID_RES_COOMBOBOX_FONT_NAME_8 = "";
var ID_RES_COOMBOBOX_FONT_NAME_9 = "";
var ID_RES_COOMBOBOX_FONT_NAME_10 = "";

// 글관련 서식 제거 문구 선언
var ID_RES_COMBOBOX_REMOVE_FONT_FAMILY = "基本";
var ID_RES_COMBOBOX_REMOVE_FONT_SIZE = "基本";
var ID_RES_COMBOBOX_REMOVE_LETTER_SPACING = "基本";				//20
var ID_RES_COMBOBOX_REMOVE_LINE_HEIGHT = "基本";

// 에디터 문자상수(initconst) 리소스 선언
var ID_RES_CONST_STRING_BOLD = "加粗";
var ID_RES_CONST_STRING_ITALIC = "斜体";
var ID_RES_CONST_STRING_UNDERLINE = "下划线";
var ID_RES_CONST_STRING_JUSTIFYLEFT = "居左";
var ID_RES_CONST_STRING_JUSTIFYCENTER = "居中";
var ID_RES_CONST_STRING_JUSTIFYRIGHT = "居右";
var ID_RES_CONST_STRING_JUSTIFYJUSTIFY = "基准线对齐";
var ID_RES_CONST_STRING_ORDERLIST = "加序号";
var ID_RES_CONST_STRING_UNORDERLIST = "句首序号";				//30
var ID_RES_CONST_STRING_STRIKE = "删除线";
var ID_RES_CONST_STRING_SUBSCRIPT = "下添字";
var ID_RES_CONST_STRING_SUPERSCRIPT = "上添字";
var ID_RES_CONST_STRING_OUTDENT = "缩出";
var ID_RES_CONST_STRING_INDENT = "缩进";
var ID_RES_CONST_STRING_UNDO = "取消执行";
var ID_RES_CONST_STRING_REDO = "重新执行";
var ID_RES_CONST_STRING_FONT_NAME = "字体";
var ID_RES_CONST_STRING_FONT_SIZE = "大小";
var ID_RES_CONST_STRING_FORE_COLOR = "前景色";					//40	
var ID_RES_CONST_STRING_BACK_COLOR = "背景色";
var ID_RES_CONST_STRING_TABLE_CREATE = "创建表";
var ID_RES_CONST_STRING_TABLE_ADD_ROW = "加行(Up)";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_DOWN = "加行(Down)";
var ID_RES_CONST_STRING_TABLE_COPY_ROW_DOWN = "加行(Copy)";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW = "删行";
var ID_RES_CONST_STRING_TABLE_ADD_COL = "加列(Left)";
var ID_RES_CONST_STRING_TABLE_ADD_COL_RIGHT = "加列(Right)";
var ID_RES_CONST_STRING_TABLE_DELETE_COL = "删列";
var ID_RES_CONST_STRING_TABLE_MERGE_CELL = "表格合并";			//50
var ID_RES_CONST_STRING_TABLE_SPLIT_ROW = "分行";
var ID_RES_CONST_STRING_TABLE_SPLIT_COL = "分列";
var ID_RES_CONST_STRING_TABLE_SELECT = "选项";

var ID_RES_CONST_STRING_IMAGE_INSERT = "图像插入/属性";
var ID_RES_CONST_STRING_FLASH_INSERT = "FLASH插入/属性";
var ID_RES_CONST_STRING_MEDIA_INSERT = "视频插入/属性";
var ID_RES_CONST_STRING_FULLSCREEN = "全画面";
var ID_RES_CONST_STRING_TABLE_CELL_PROPERTY = "单元格属性";
var ID_RES_CONST_STRING_TABLE_PROPERTY = "表格属性";
var ID_RES_CONST_STRING_MARK_INSERT = "插入特殊字符";			//60
var ID_RES_CONST_STRING_TABLE_TEMPLETE_INSERT = "创建表(模板)";


var ID_RES_CONST_STRING_ADJUST_HWP_BASIC = "韩文更正";
var ID_RES_CONST_STRING_ADJUST_DOC_BASIC = "word更正";
var ID_RES_CONST_STRING_HORIZONTAL_RULE = "插入水平线";
var ID_RES_CONST_STRING_LETTER_SPACING = "字距";
var ID_RES_CONST_STRING_LINE_HEIGHT = "行距";
var ID_RES_CONST_STRING_BODY_BG_COLOR = "文档背景色";
var ID_RES_CONST_STRING_BODY_BG_IMAGE = "文档背景图像";
var ID_RES_CONST_STRING_DOC_TEMPLETE = "插入编辑模块";
var ID_RES_CONST_STRING_PREVIEW = "プレビュー";					//70
var ID_RES_CONST_STRING_HIDE_MINIBAR = "隐藏小框";
var ID_RES_CONST_STRING_WRITE_AREA_SET = "编辑领域设置";
var ID_RES_CONST_STRING_SHOW_EDITABLE_AREA = "编辑领域显示";
var ID_RES_CONST_STRING_SAVEAS = "存储";
var ID_RES_CONST_STRING_PRINT = "打印";
var ID_RES_CONST_STRING_Z_INDEX_SETTING = "设定z-Index";
var ID_RES_CONST_STRING_TEXT_BOX = "字箱";
var ID_RES_CONST_STRING_OBJECT_POSITION = "设定个体Position";
var ID_RES_CONST_STRING_RESPONSIVE_WIDTH = "确认反应性大小";
var ID_RES_CONST_STRING_DOC_LAYOUT = "设定布局";				//80
var ID_RES_CONST_STRING_HEADING_SIZE = "风格";
var ID_RES_CONST_STRING_RESPONSIVE_SET = "统一设定反应性";
var ID_RES_CONST_STRING_FORM_TABLE = "表格编辑模块";
var ID_RES_CONST_STRING_DRAW_TABLE = "绘制表格";


//파일 메뉴 
var ID_RES_CONST_STRING_FILE_NEW				= "新建";
var ID_RES_CONST_STRING_FILE_OPEN				= "打开文件";
var ID_RES_CONST_STRING_FILE_DOCFORM			= "格式样式";
var ID_RES_CONST_STRING_FILE_LAYOUT				= "布局";

//편집 메뉴 
var ID_RES_CONST_STRING_CUT						= "剪切";
var ID_RES_CONST_STRING_COPY					= "复制";		//90
var ID_RES_CONST_STRING_PASTE					= "粘帖";
var ID_RES_CONST_STRING_EDIT_PASTESPECIAL		= "选择粘贴";
var ID_RES_CONST_STRING_SELECT_ALL				= "全选";
var ID_RES_CONST_STRING_EDIT_SEARCH				= "查找";
var ID_RES_CONST_STRING_EDIT_REPLACE			= "替换";
var ID_RES_CONST_STRING_REPLACE_CASE			= "转换为大写/小写";

//보기 메뉴 
var ID_RES_CONST_STRING_VIEW_EDIT				= "编辑窗口";
var ID_RES_CONST_STRING_VIEW_HTML				= "代码窗口";

//삽입 메뉴 
var ID_RES_CONST_STRING_INSERT_IMAGE			= "图像";		//100
var ID_RES_CONST_STRING_INSERT_OBJECT			= "个体";
var ID_RES_CONST_STRING_INSERT_SPECIALCHARS		= "插入特殊字符";
var ID_RES_CONST_STRING_INSERT_BOOKMARK			= "书签";
var ID_RES_CONST_STRING_INSERT_EMOTICONS		= "表情符号";
var ID_RES_CONST_STRING_HYPERLINK_INSERT		= "超级链接";
var ID_RES_CONST_STRING_HYPERLINK_MODIFY		= "超级链接";
var ID_RES_CONST_STRING_HYPERLINK_REMOVE		= "删除链接";

//서식 메뉴 
var ID_RES_CONST_STRING_STYLE_FONT				= "文字模样";
var ID_RES_CONST_STRING_STYLE_PARAGRAPH			= "文段模样";
var ID_RES_CONST_STRING_STYLE_STYLE				= "风格";		//110
var ID_RES_CONST_STRING_STYLE_UNORDEREDLIST		= "句首序号";
var ID_RES_CONST_STRING_STYLE_ORDEREDLIST		= "加序号";
var ID_RES_CONST_STRING_STYLE_INCREASEORDER		= "增加一阶段";
var ID_RES_CONST_STRING_STYLE_DECREASEORDER		= "减少一阶段";

//표 메뉴 
var ID_RES_CONST_STRING_TABLE_CELL_STYLE		= "单元格边框 & 背景";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_COL		= "添加列/格";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL	= "删除列/格";
var ID_RES_CONST_STRING_TABLE_SPLIT_CELL		= "拆分单元格";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT	= "统一单元格的高度";	//120
var ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH	= "统一单元格的宽度";
var ID_RES_CONST_STRING_TABLE_CELL_ALIGN		= "整列单元格";
var ID_RES_CONST_STRING_TABLE_MADANG			= "表格";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "计算式";
var ID_RES_CONST_STRING_TABLE_NUMBER_FORMAT		= "区分1,000单位的逗号";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICALALIGN	= "纵向整列单元格";

var ID_RES_CONST_STRING_TABLE_BLOCK_FORMULA		= "模块计算式";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "计算式";
var ID_RES_CONST_STRING_TABLE_SELECT_FORMULA	= "选择计算式";
var ID_RES_CONST_STRING_TABLE_EASY_FORMULA	= "容易的计算式";

//도움말
var ID_RES_CONST_STRING_HELP_SHORTCUTS = "快捷键";				//130
var ID_RES_CONST_STRING_HELP = "产品帮助";
var ID_RES_CONST_STRING_PRODUCT_INFO = "产品信心";


//2depth 메뉴
var ID_RES_CONST_STRING_INSERT_OBJECT_MOVIE = "视频插入";
var ID_RES_CONST_STRING_INSERT_OBJECT_FILE = "文件";
var ID_RES_CONST_STRING_INSERT_OBJECT_HR = "插入水平线";

var ID_RES_CONST_STRING_STYLE_STYLE_BASIC = "基本";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT1 = "标题1";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT2 = "标题2";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT3 = "标题3";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT4 = "标题4";			//140
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT5 = "标题5";

var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_TOP = "上对齐对齐";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_MIDDLE = "居中对齐";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_BOTTOM = "下对齐对齐";

var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTALALIGN	= "横向整列单元格";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_LEFT = "左边";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_CENTER = "居中";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_RIGHT = "右边";

var ID_RES_CONST_STRING_TABLE_BLOCK_SUM = "模块合计";
var ID_RES_CONST_STRING_TABLE_BLOCK_AVG = "模块平均";				//150
var ID_RES_CONST_STRING_TABLE_BLOCK_MUL = "模块乘积";

var ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM = "横向合计";
var ID_RES_CONST_STRING_TABLE_VERTICAL_SUM = "纵向合计";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE = "横向平均";
var ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE = "纵向平均";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY = "横向乘积";
var ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY = "纵向乘积";

var ID_RES_CONST_STRING_TABLE_ADD_NUMBER_FORMAT = "插入定位点";
var ID_RES_CONST_STRING_TABLE_REMOVE_NUMBER_FORMAT = "抽出定位点";


//-- 툴바에만 존재하는 버튼
var ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE = "放大字体大小";	//160
var ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE = "缩小字体大小";

// 폼태그 버튼
var ID_RES_CONST_STRING_FORM_TAG_SWITCH = "选择转换样式控制";
var ID_RES_CONST_STRING_FORM_TAG_CHECKBOX = "被选箱子";
var ID_RES_CONST_STRING_FORM_TAG_SELECT = "目录箱子";

// 양식 템플릿
var ID_RES_CONST_STRING_TEMPLETE_FORM = "样式模板";

// 빈문단삽입
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_STARTPOINT = "插入开始点文段";
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_ENDPOINT = "插入结束点文段";

// 표 삭제
var ID_RES_CONST_STRING_TABLE_DELETE_TABLE = "删除表";

// 삽입 - 문단
var ID_RES_CONST_STRING_INSERT_PARAGRAPH = "文段";

// 서식 - 글자모양 - 보통모양 버튼 텍스트
var ID_RES_CONST_STRING_NORMAL = "普通模样";						//170

//표 - 표 텍스트로 변환
var ID_RES_CONST_STRING_TABLE_CONVERT_TEXT = "转换为表格文字";

// 테이블생성 Layer(tablesize) 리소스 선언
var ID_RES_TABLE_SIZE_SELECT = "选择";
var ID_RES_TABLE_SIZE_CANCEL = "取消";

// 툴빌더(toolbuilder) 리소스 선언
var ID_RES_TOOL_STRING_MENU_FILE = "文件";
var ID_RES_TOOL_STRING_MENU_EDIT = "编辑";
var ID_RES_TOOL_STRING_MENU_VIEW = "预览";
var ID_RES_TOOL_STRING_MENU_INSERT = "插入";
var ID_RES_TOOL_STRING_MENU_BASIC = "格式";
var ID_RES_TOOL_STRING_MENU_TABLE = "表格";
var ID_RES_TOOL_STRING_MENU_HELP = "帮助";						//180
var ID_RES_TOOL_STRING_TAB_PREVIEW = "预览";
var ID_RES_TOOL_STRING_TAB_EDIT = "编辑窗口";
var ID_RES_TOOL_STRING_TAB_SOURCE = "代码窗口";

// 사용자메세지(usermsg) 리소스 선언
var ID_RES_USER_MSG_STRING_ALERT_CUT = "因为浏览器安全设置问题, 不能执行\n可通过键盘按键Ctrl+X 执行命令";
var ID_RES_USER_MSG_STRING_ALERT_COPY = "因为浏览器安全设置问题, 不能执行\n可通过键盘按键Ctrl+C 执行命令";
var ID_RES_USER_MSG_STRING_ALERT_PASTE = "因为浏览器安全设置问题, 不能执行\n可通过键盘按键Ctrl+V 执行命令";
var ID_RES_USER_MSG_STRING_WARNING_SCRIPT = "代码中不能包括脚本\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_MEDIA = "视频插入仅支持IE 6,7,8\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_IFRAME = "代码中无能包括 iframe 标签\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_SOURCE_EDIT = "格式用户模式下不能使用代码窗口\n";	//190
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_2 = "支持 Firefox 3版本以上\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_EDIT = "不支持 Firefox 编辑模式设置\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_SUPPORT_FORM_MODE = "代码检查在格式管理员或用户模式下不能使用\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_ATTIRIBUTE_CHARACTER = "属性值不能使用 <,>,&,\',\" 等符号\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_COLOR_CODE = "유효한 색상코드를 입력하셔야 합니다.\n 예) #0099ff\n";
//var ID_RES_USER_MSG_STRING_WARNING_IN_CONTROL_KEY_NO_SOURCE_EDIT = "키보드 제어용에서는 소스창을 사용할 수 없습니다";

// 문서보정(leftviewui) 리소스 선언
var ID_RES_ADJUST_VIEW_CLOSE = "关闭";

// 편집창 Title 리소스 선언
var ID_RES_EDIT_TITLE_STRING = "文章输入部分";

var ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY = "适用";

// 양식 저작(Form Table) 리소스 선언
var ID_RES_PROP_FORM_WIN_TITLE = "样式布局";
var ID_RES_PROP_TAG_SELECT_WIN_TITLE = "目录箱子";
var ID_RES_PROP_MAPPING_CODE_WIN_TITLE = "样式代码";
var ID_RES_PROP_MAPPING_CSS_WIN_TITLE = "设定样式CSS";
var ID_RES_PROP_TEMPLETE_FORM_WIN_TITLE = "样式模板";

// 컨텍스트 메뉴
var ID_RES_PROP_INSERT_IMAGE = "图片属性";
var ID_RES_PROP_INSERT_FILE = "加载的文件属性";

var ID_RES_DIALOG_BTN_OK = "确认";
var ID_RES_DIALOG_BTN_CANCEL = "取消";
var ID_RES_DIALOG_BTN_NOCOLOR = "无颜色";							//210
var ID_RES_DIALOG_TAB_GENERAL = "一般";
var ID_RES_DIALOG_TAB_BORDER = "边框";
var ID_RES_DIALOG_TAB_BACKGROUND = "背景";
var ID_RES_DIALOG_FORM_LIST1 = "样本项目1";
var ID_RES_DIALOG_FORM_LIST2 = "样本项目2";
var ID_RES_DIALOG_FORM_LIST3 = "样本项目3";
var ID_RES_DIALOG_MAPPINGCODE_TAB1 = "电子审批样式";
var ID_RES_DIALOG_MAPPINGCODE_TAB2 = "公文样式";
var ID_RES_DIALOG_CONFIRM_SAVE = "<p>有正在编写中的内容。</p><p>要保存吗?</p>";
var ID_RES_DIALOG_CONFIRM_YES = "是";							//220
var ID_RES_DIALOG_CONFIRM_NO = "否";
var ID_RES_DIALOG_CONFIRM_EMPTY_DOC = "文件为空，请确认。";
var ID_RES_DIALOG_ALERT_SELECTFILE = "请选择文件。";
var ID_RES_DIALOG_CONFIRM_FILE_DELETE_CONTENT = "若读取文件，填写中的内容将会被删除，\n要读取文件吗？";
var ID_RES_DIALOG_ALERT_ALLOWFILES = "无法上传文件。\n可以上传的文件";
var ID_RES_DIALOG_ALERT_SELECTIMAGE = "请选择图片文件之后点击上传按键。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_IMAGE = "请插入正常图片。";
var ID_RES_DIALOG_ALERT_FIND_INPUT_TEXT = "请输入要查询的内容。";
var ID_RES_DIALOG_ALERT_FIND_ERROR = "搜索中发生错误。";
var ID_RES_DIALOG_ALERT_FIND_NOTHING = "没有找到该内容。";		//230
var ID_RES_DIALOG_CONFIRM_FIND_END = "已查找到文章最后。\n从文章开头开始继续查找吗？";
var ID_RES_DIALOG_CONFIRM_FIND_FIRST = "已查找到文章开头。\n从文章最后开始继续查找吗？";
var ID_RES_DIALOG_ALERT_REPLACE_INPUT_TEXT = "请输入要替换的内容。";
var ID_RES_DIALOG_ALERT_REPLACE_ERROR = "替换中发生错误。";
var ID_RES_DIALOG_ALERT_REPLACEALL_COMPLETE = "已替换所有。";
var ID_RES_DIALOG_ALERT_REPLACE_N = "替换   个项目。";
var ID_RES_DIALOG_TITLE_FIND_REPLACE = "查找/替换";
var ID_RES_DIALOG_BTN_REPLACEALL = "全部替换";
var ID_RES_DIALOG_BTN_FIND_NEXT = "查找";
var ID_RES_DIALOG_TITLE_EXT_MOVIE = "外部视频";					//240
var ID_RES_DIALOG_TITLE_FILE_INSERT = "导入自动保存内容";
var ID_RES_DIALOG_BTN_INSERT = "添加";
var ID_RES_DIALOG_TITLE_WEBEDITOR_INFO = "DOUZONE ONEFFICE 信息";

var ID_RES_DIALOG_LIST_TITLE_FORM_AREA = "样式领域";
var ID_RES_DIALOG_LIST_TITLE_FORM_SELECT = "选择样式";
var ID_RES_DIALOG_ALERT_SELECT_DOCFORM = "请选择格式样式。";
var ID_RES_DIALOG_CONFIRM_DOCFORM_DELETE_CONTENT = "若插入格式样式，编辑中的文件将会被删除，\n要插入吗？";
var ID_RES_DIALOG_ALERT_SELECT_LAYOUT_DESIGN = "请选择布局设计。";
var ID_RES_DIALOG_CONFIRM_LAYOUT_DELETE_CONTENT = "若插入布局，编辑中的文件将会被删除，\n要插入吗？";

var ID_RES_DIALOG_STRING_FILE_PATH = "文件路径";					//250
var ID_RES_DIALOG_STRING_URL_INPUT = "插入网址";
var ID_RES_DIALOG_STRING_UPLOAD = "上传";
var ID_RES_DIALOG_STRING_SIZE = "大小";
var ID_RES_DIALOG_STRING_WIDTH = "宽度";
var ID_RES_DIALOG_STRING_HEIGHT = "高度";
var ID_RES_DIALOG_STRING_KEEP_RATIO = "维持宽度/高度比例";
var ID_RES_DIALOG_STRING_SET_ORG = "保持其原始大小";
var ID_RES_DIALOG_STRING_MARGIN = "空白";
var ID_RES_DIALOG_STRING_MARGIN_LEFT = "左空白";
var ID_RES_DIALOG_STRING_MARGIN_TOP = "上空白";					//260
var ID_RES_DIALOG_STRING_MARGIN_RIGHT = "右空白";
var ID_RES_DIALOG_STRING_MARGIN_BOTTOM = "下空白";
var ID_RES_DIALOG_STRING_ALIGN_BASIC = "基本值";
var ID_RES_DIALOG_STRING_ALIGN_LEFT = "左边";
var ID_RES_DIALOG_STRING_ALIGN_CENTER = "居中";
var ID_RES_DIALOG_STRING_ALIGN_RIGHT = "右边";
var ID_RES_DIALOG_ALERT_MAX_VALUE = "已超过最大值。\n最大值：";
var ID_RES_DIALOG_ALERT_MIN_VALUE = "已超过最小值。\n最小值：";
var ID_RES_DIALOG_ALERT_NUMBER_ONLY = "只可以输入数字。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_URL = "请再次确认图片的URL！";	//270
var ID_RES_DIALOG_ALERT_UPLOAD_ERROR = "上传时发生错误，请重试。";
var ID_RES_DIALOG_ALERT_INSERT_IMAGE = "请先登录图片。";
var ID_RES_DIALOG_STRING_NO_STYLE_TEXT = "没有格式的文字";
var ID_RES_DIALOG_STRING_HTML_STYLE_TEXT = "HTML 形式";
var ID_RES_DIALOG_STRING_FIND_TEXT = "查找的内容";
var ID_RES_DIALOG_STRING_REPLACE_TEXT = "替换的内容";
var ID_RES_DIALOG_STRING_FIND_OPTION = "搜索选项";
var ID_RES_DIALOG_STRING_CASESENSITIVE = "大小写区分";
var ID_RES_DIALOG_STRING_COMPLETEWORD = "按词语单位";
var ID_RES_DIALOG_STRING_IGNORESPACE = "忽略空格";				//280
var ID_RES_DIALOG_STRING_FIND_DERECTION = "搜索方向";
var ID_RES_DIALOG_STRING_FIND_DOWN = "向下";
var ID_RES_DIALOG_STRING_FIND_UP = "向上";
var ID_RES_DIALOG_STRING_INPUT_SOURCE = "源输入";
var ID_RES_DIALOG_STRING_MOVIE_INPUT_GUIDE = "请输入object或者iframe来源代码。";
var ID_RES_DIALOG_STRING_INPUT_MOVIE_SOURCE = "请输入视频代码。";
var ID_RES_DIALOG_STRING_VIEW_TEXT = "显示的文本";
var ID_RES_DIALOG_ALERT_ALLOW_FORMAT = "只支持格式。";
var ID_RES_DIALOG_STRING_CHARACTER_AREA = "文字领域";
var ID_RES_DIALOG_STRING_CHARACTER_SELECT = "文字选择";			//290
var ID_RES_DIALOG_STRING_RECECT_USE_CHARACTER = "最近使用的文字";

var ID_RES_DIALOG_ALERT_SELECT_CHARACTER = "请选择文字。";
var ID_RES_CONST_STRING_CHARACTER_GENERAL = "一般/符号";
var ID_RES_CONST_STRING_CHARACTER_ENG_NUMBER = "英文/数字";
var ID_RES_CONST_STRING_CHARACTER_GREEK = "希腊语";
var ID_RES_CONST_STRING_CHARACTER_LINE = "线文字";
var ID_RES_CONST_STRING_CHARACTER_UNIT = "单位符号";
var ID_RES_CONST_STRING_CHARACTER_CIRCLE = "圆文字";
var ID_RES_CONST_STRING_CHARACTER_BRAKETCHAR = "括号文字";
var ID_RES_CONST_STRING_CHARACTER_FRACTION_SCRIPT = "分数/脚注";	//300
var ID_RES_CONST_STRING_CHARACTER_ARROW = "箭头";
var ID_RES_CONST_STRING_CHARACTER_BRAKET = "括号";
var ID_RES_CONST_STRING_CHARACTER_MATH = "数学演算";
var ID_RES_CONST_STRING_CHARACTER_PUNCTUATION_MARKS = "文章符号";
var ID_RES_CONST_STRING_CHARACTER_CURRENCY = "货币符号";

var ID_RES_DIALOG_STRING_BOOKMARK_NAME = "书签名称";
var ID_RES_DIALOG_STRING_BOOKMARK_LIST = "书签目录";
var ID_RES_DIALOG_STRING_MOVE = "移动";							//310
var ID_RES_DIALOG_STRING_BOOKMARK_SORT_STANDARD = "书签整列标准";
var ID_RES_DIALOG_STRING_NAME = "姓名";
var ID_RES_DIALOG_STRING_POSITION = "位置";
var ID_RES_DIALOG_ALERT_INPUT_BOOKMARK_NAME = "请输入书页的名字。";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_DELTE_BOOKMARK_ITEM = "在书签目录中请选择要删除的项目。";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_MOVE_BOOKMARK_ITEM = "在书签目录中请选择要移动的项目。";

var ID_RES_DIALOG_STRING_LINK_TYPE = "链接种类";
var ID_RES_DIALOG_STRING_WEB_ADDR = "网页地址";
var ID_RES_DIALOG_STRING_LINK_TARGET = "打开链接文件";
var ID_RES_DIALOG_STRING_LINK_CURRENT_WINDOW = "以同样的窗口";
var ID_RES_DIALOG_STRING_LINK_NEW_WINDOW = "打开新窗";
var ID_RES_DIALOG_STRING_LINK_NO_CONNECT = "不连接";				//320
var ID_RES_DIALOG_STRING_LIST_SELECT = "选择";
var ID_RES_DIALOG_ALERT_SELECT_BOOKMARK = "请选择书页。";
var ID_RES_DIALOG_ALERT_INPUT_WEB_ADDR = "请输入网页地址。";

var ID_RES_DIALOG_STRING_LETTERSPACING = "字间";
var ID_RES_DIALOG_STRING_BASIC = "基本";
var ID_RES_DIALOG_STRING_PROPERTY = "属性";
var ID_RES_DIALOG_STRING_FONT_STYLE_PREVIEW = "一二三ABCabc123※○";

var ID_RES_DIALOG_STRING_ALIGN_TYPE = "整列方式";
var ID_RES_DIALOG_STRING_NORMAL = "普通";
var ID_RES_DIALOG_STRING_SPACING = "间隔";						//330
var ID_RES_DIALOG_STRING_LINEHEIGHT = "行数";
var ID_RES_DIALOG_STRING_PARAGRAPH_TOP = "文章单位";
var ID_RES_DIALOG_STRING_PARAGRAPH_BOTTOM = "文段下面";
var ID_RES_DIALOG_STRING_FIRST_PARAGRAPH = "第一行";

var ID_RES_DIALOG_STRING_NONE = "无";
var ID_RES_DIALOG_STRING_VERSION = "版本";


var ID_RES_DIALOG_STRING_FORM_BASE_SIZE = "标准大小/高度";
var ID_RES_DIALOG_STRING_FORM_HEIGHT_MSG = "创建样式时反应高度设定";
var ID_RES_DIALOG_STRING_FORM_OUTLINE = "外界线";
var ID_RES_DIALOG_STRING_FORM_TYPE = "类型";						//340
var ID_RES_DIALOG_STRING_FORM_COLOR = "颜色";
var ID_RES_DIALOG_STRING_FORM_MULTI_SELECT = "多种选择：<br />&nbsp;&nbsp;Ctrl键+选择对象";
var ID_RES_DIALOG_STRING_FORM_MULTI_OTHER_SELECT = "多种选择：<br />&nbsp;&nbsp;选择对象->shift键-><br />&nbsp;&nbsp;选择其他对象";
var ID_RES_DIALOG_STRING_FORM_COPY_PASTE = "复制/粘贴 :<br />&nbsp;&nbsp;选择对象后Ctrl键+V";
var ID_RES_DIALOG_STRING_FORM_COPY_MOVE = "移动 :<br />&nbsp;&nbsp;上下左右箭头键";
var ID_RES_DIALOG_STRING_FORM_RESIZE = "调整大小 :<br />&nbsp;&nbsp;Ctrl键+箭头键";
var ID_RES_DIALOG_STRING_FORM_PRE_APPLY = "预先适用";
var ID_RES_DIALOG_ALERT_FORM_SIZE = "只支持大小(width)单位为%的情况。";

var ID_RES_PROP_TAG_STRING_ROW_NUM = "横线数";
var ID_RES_PROP_TAG_STRING_COL_NUM = "列数";						//350
var ID_RES_PROP_TAG_STRING_ROW_COL = "列/格";
var ID_RES_PROP_TAG_STRING_SIZE_DEFINE = "指定大小";
var ID_RES_PROP_TAG_STRING_WIDTH_UNIT = "宽度单位";
var ID_RES_PROP_TAG_STRING_ALL_CELL_INNER_MARGIN = "所有单元格的内白边";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN = "整列";

var ID_RES_PROP_TAG_STRING_FILL = "填充";						//360
var ID_RES_PROP_TAG_STRING_NO_COLOR_FILL = "没有填充颜色";
var ID_RES_PROP_TAG_STRING_COLOR = "色";
var ID_RES_PROP_TAG_STRING_FACE_COLOR = "面颜色";

var ID_RES_PROP_TAG_STRING_IMAGE = "图片";
var ID_RES_PROP_TAG_STRING_USER_IMAGE = "使用图片";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE = "图片文件";
var ID_RES_PROP_TAG_STRING_FILL_TYPE = "填充类型";
var ID_RES_PROP_TAG_STRING_REPEAT = "重复";
var ID_RES_PROP_TAG_STRING_REPEAT_HOR = "横向反复";
var ID_RES_PROP_TAG_STRING_REPEAT_VER = "纵向反复";				//370
var ID_RES_PROP_TAG_STRING_REPEAT_NO = "不反复";

var ID_RES_PROP_TAG_LIST_NUM = "目录个数";
var ID_RES_PROP_TAG_LIST_CONTENT = "目录内容";

var ID_RES_PROP_TAG_ADD_ROW = "添加列";
var ID_RES_PROP_TAG_UP = "向上";
var ID_RES_PROP_TAG_DOWN = "向下";
var ID_RES_PROP_TAG_ADD_COL = "添加列";

var ID_RES_PROP_TAG_SET_INNER_MARGIN = "指定内部白边";

var ID_RES_PROP_TAG_STRING_LEFT = "左对齐";
var ID_RES_PROP_TAG_STRING_TOP = "向上";						//380
var ID_RES_PROP_TAG_STRING_RIGHT = "右对齐";
var ID_RES_PROP_TAG_STRING_BOTTOM = "向下";
var ID_RES_PROP_TAG_STRING_CENTER = "中间";

var ID_RES_PROP_TAG_STRING_ALIGN_HOR = "水平对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_VER = "垂直对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_TOP = "上对齐对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_MIDDLE = "居中对齐";
var ID_RES_PROP_TAG_STRING_ALIGN_BOTTOM = "下对齐对齐";

var ID_RES_PROP_TAG_STRING_APPLY_RANGE= "适用范围";
var ID_RES_PROP_TAG_STRING_SELECTED_CELL = "被选的单元格";
var ID_RES_PROP_TAG_STRING_ALL_CELL = "所有单元格";					//390

var ID_RES_PROP_TAG_STRING_SELECT_CELL_EDITOR = "在编辑窗口中请选择要适用的单元格。";
var ID_RES_PROP_TAG_STRING_NO_CALC_SELECTED_CELL = "选择了无法计算的项目。";
var ID_RES_PROP_TAG_STRING_SELECT_CELL = "选择单元格";
var ID_RES_PROP_TAG_STRING_CALC_TYPE = "计算方法";
var ID_RES_PROP_TAG_STRING_CALC_SUM = "合计";
var ID_RES_PROP_TAG_STRING_CALC_AVG = "平均";
var ID_RES_PROP_TAG_STRING_CALC_MUL = "乘积";
var ID_RES_PROP_TAG_STRING_CALC_RESULT = "计算结果";
var ID_RES_PROP_TAG_STRING_SPLIT_ROW_COL = "分离列/格";			//400

var ID_RES_PROP_TEMPLETE_STRING_FORM_SUBJECT = "样式标题";
var ID_RES_PROP_TEMPLETE_STRING_SUBJECT = "标题";
var ID_RES_PROP_TEMPLETE_STRING_SIZE_ITEM_SET = "设定大小/项目";
var ID_RES_PROP_TEMPLETE_STRING_AUTO = "自动";
var ID_RES_PROP_ALERT_ONLY_NUMBER_CALC = "只可以计算数字。";

var ID_RES_DIALOG_SHORTCUTS_TITLE = "快捷键";
var ID_RES_DIALOG_SHORTCUTS_MENU_PATH = "菜单途径";
var ID_RES_DIALOG_SHORTCUTS_FUNCTION = "功能";
var ID_RES_DIALOG_SHORTCUTS_BASIC = "标准快捷键";
var ID_RES_DIALOG_SHORTCUTS_SPACE = "插入空格";					//410
var ID_RES_DIALOG_SHORTCUTS_ENTER = "分离文段";
var ID_RES_DIALOG_SHORTCUTS_LEFT = "向左移动一个字段";
var ID_RES_DIALOG_SHORTCUTS_RIGHT = "向右移动一个字段";
var ID_RES_DIALOG_SHORTCUTS_DOWN = "向下挪一行";
var ID_RES_DIALOG_SHORTCUTS_UP = "向上挪一行";
var ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD = "向右移动一个单词";
var ID_RES_DIALOG_SHORTCUTS_LEFT_WORD = "向左移动一个单词";
var ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH = "向下挪一个文段";
var ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH = "向上挪一个文段";
var ID_RES_DIALOG_SHORTCUTS_HOME = "移动到列前";					//420
var ID_RES_DIALOG_SHORTCUTS_END = "移动到列端";
var ID_RES_DIALOG_SHORTCUTS_HOME_PAGE = "转到首页";
var ID_RES_DIALOG_SHORTCUTS_END_PAGE = "转到末页";
var ID_RES_DIALOG_SHORTCUTS_DELETE = "删除后字";
var ID_RES_DIALOG_SHORTCUTS_BACKSPACE = "删除前字";
var ID_RES_DIALOG_SHORTCUTS_DELETE_WORD = "删除一个单词";
var ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD = "删除前一个单词";

var ID_RES_DIALOG_SHORTCUTS_FILE = "文件菜单";
var ID_RES_DIALOG_SHORTCUTS_EDIT = "编辑菜单";
var ID_RES_DIALOG_SHORTCUTS_INSERT = "插入菜单";					//430
var ID_RES_DIALOG_SHORTCUTS_STYLE = "格式菜单";
var ID_RES_DIALOG_SHORTCUTS_TABLE = "表格菜单";

var ID_RES_CONST_STRING_CLEAR = "发布";

var ID_RES_CONST_STRING_INCREASE_LETTERSPACING = "放大字间距离";
var ID_RES_CONST_STRING_DECREASE_LETTERSPACING = "缩小字间距离";

var ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT = "放大左白边";
var ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT = "缩小左白边";
var ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT = "放大右白边";
var ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT = "缩小右白边";

var ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT = "多处一行";	//440
var ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT = "缩进一行";

var ID_RES_CONST_STRING_INCREASE_LINEHEIGHT = "放大列间隔";
var ID_RES_CONST_STRING_DECREASE_LINEHEIGHT = "缩小列间隔";

var ID_RES_CONST_STRING_SELECT_CURRENT_CELL = "选择当前单元格";
var ID_RES_CONST_STRING_MOVE_CELL_UNIT = "以单元格单位移动光标";
var ID_RES_CONST_STRING_MOVE_NEXT_CELL = "在表格中向其他单元格移动(正方向)";
var ID_RES_CONST_STRING_MOVE_PREV_CELL = "在表格中向其他单元格移动(逆方向)";

var ID_RES_CONST_STRING_BLOCK_ALL_COL = "格所有模块";
var ID_RES_CONST_STRING_BLOCK_ALL_ROW = "列所有模块";
var ID_RES_CONST_STRING_MULTI_CELL_SELECT = "选择多个单元格时";		//450
var ID_RES_CONST_STRING_ARROW_KEY = "方向键";

var ID_RES_CONST_STRING_STANDARD = "标准";
var ID_RES_CONST_STRING_USER_DEFINE = "习惯";
var ID_RES_CONST_STRING_USER_SET = "习惯";
var ID_RES_CONST_STRING_REPLACE_CASE_CAPITAL = "都转化为大写";
var ID_RES_CONST_STRING_REPLACE_CASE_SMALL = "都转换为小写";
var ID_RES_CONST_STRING_REPLACE_CASE_REVERSE = "替换大写和小写";
var ID_RES_CONST_STRING_REPLACE_CASE_LETTER = "首字母转换为大写";
var ID_RES_CONST_STRING_REPLACE_CASE_SENTENCE = "文章第一个字替换为大写";
var ID_RES_CONST_STRING_REPLACE_CASE_PARAGRAPH = " 文段第一个字替换为大写";	//460
var ID_RES_CONST_BTN_DELETE = "删除";
var ID_RES_CONST_INSERT_IMAGE_PARAGRAPH_ALIGN = "整列本文";

var ID_RES_CONST_STRING_NEW_COLOR = "新的颜色";
var ID_RES_CONST_STRING_CURRENT_COLOR = "当前颜色";
var ID_RES_CONST_STRING_OTHER_COLOR = "其他颜色";
var ID_RES_CONST_STRING_RECENT_COLOR = "最近使用的颜色";
var ID_RES_CONST_STRING_ADD_USER_COLOR = "添加到用户指定的颜色中";
var ID_RES_CONST_STRING_RED = "红色";
var ID_RES_CONST_STRING_GREEN = "绿色";
var ID_RES_CONST_STRING_BLUE = "蓝色";								//470
var ID_RES_CONST_STRING_HUE = "颜色";
var ID_RES_CONST_STRING_SATURATION = "彩度";
var ID_RES_CONST_STRING_LIGHTNESS = "明度";

var ID_RES_CONST_MSG_ALERT_NO_RECENT_COLOR = "没有最近使用的颜色。";
var ID_RES_CONST_MSG_ALERT_DELETE_RECENT_COLOR = "要删除最近使用的所有颜色吗？";

var ID_RED_CONST_STRING_ALIGN_LEFT_TOP		= "左上";
var ID_RED_CONST_STRING_ALIGN_LEFT_MIDDLE	= "左中";
var ID_RED_CONST_STRING_ALIGN_LEFT_BOTTOM	= "左下";
var ID_RED_CONST_STRING_ALIGN_CENTER_TOP	= "上中";
var ID_RED_CONST_STRING_ALIGN_CENTER_MIDDLE = "正中";				//480
var ID_RED_CONST_STRING_ALIGN_CENTER_BOTTOM = "下中";
var ID_RED_CONST_STRING_ALIGN_RIGHT_TOP		= "右上";
var ID_RED_CONST_STRING_ALIGN_RIGHT_MIDDLE	= "右中";
var ID_RED_CONST_STRING_ALIGN_RIGHT_BOTTOM	= "右下";
var ID_RED_CONST_STRING_TABLE_CELL_BACKCOLOR	= "单元格背景颜色";

var ID_RES_CONST_STRING_COLOR_STANDARD = "标准颜色";
var ID_RES_CONST_STRING_COLOR_THEME = "主体颜色";

var ID_RES_CONST_STRING_EMOTICONS_FEEL = "感情";
var ID_RES_CONST_STRING_EMOTICONS_ACTION = "行动";
var ID_RES_CONST_STRING_EMOTICONS_ETC = "其他";						//490
var ID_RES_DIALOG_STRING_CATEGORY_AREA = "分类";
var ID_RES_DIALOG_STRING_EMOTICON_SELECT = "选择表情符号";
var ID_RES_DIALOG_STRING_RECECT_USE_EMOTICONS = "最近使用的表情符号";

var ID_RES_UI_TOGGLE_STRING_RIBBON = "自定义菜单样式";
var ID_RES_UI_TOGGLE_STRING_TOOLBAR = "工具栏菜单样式";
var ID_RES_CONST_STRING_PRINT_PAGE_BREAK = "划分打印页面";
var ID_RES_CONST_STRING_VIEW_RULERBAR = "显示标尺";
var ID_RES_DIALOG_STRING_CASCADE_ORDERLIST = "分步目录";
var ID_RES_CONST_STRING_COPY_EXT_STYLE = "复制样式";

var ID_RES_CONST_STRING_BORDER_TYPE = "边线种类";					//500
var ID_RES_CONST_STRING_BORDER_THICKNESS = "边线厚度";
var ID_RES_CONST_STRING_BORDER_COLOR = "边线颜色";
var ID_RES_CONST_STRING_RESET_PICTURE = "按原图";

var ID_RES_CONST_STRING_NO_LINE = "除线";
var ID_RES_CONST_STRING_SOLID_LINE = "实线";
var ID_RES_CONST_STRING_DASHED_LINE = "波线";
var ID_RES_CONST_STRING_DOTTED_LINE = "虚线";
var ID_RES_CONST_STRING_DOUBLE_LINE = "双重线";

var ID_RES_CONST_STRING_TABLE_SELECT_CELL = "选择单元格";
var ID_RES_CONST_STRING_TABLE_SELECT_COL = "选择列";				//510
var ID_RES_CONST_STRING_TABLE_SELECT_ROW = "选择行";
var ID_RES_CONST_STRING_TABLE_SELECT_TABLE = "选择表格";

var ID_RES_CONST_STRING_IMAGE_TO_TABLE = "FORMBOT";
var ID_RES_DIALOG_ALERT_SELECT_TABLE_STYLE = "请选择样式。";

var ID_RES_CONST_STRING_TEXTBOX = "文本框";

var ID_RES_CONST_TAB_COLOR_AND_BORDER = "颜色和线条";
var	ID_RES_DIALOG_BTN_MODIFY = "调整";
var ID_RES_CONST_TEXTATT = "字体";
var ID_RES_CONST_TEXTATT_STYLE = "字体样式";
var ID_RES_CONST_VERTICAL_ALIGN = "纵向对齐";

var ID_RES_CONST_STRING_INNER_MARGIN = "内边距";
var ID_RES_CONST_STRING_OUTER_MARGIN = "外边距";
var ID_RES_CONST_STRING_LINE = "线条";
var ID_RES_CONST_STRING_LINE_WIDTH = "粗细";
var ID_RES_CONST_STRING_LINE_STYLE = "种类";

var ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO = "请插入正常的视频。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO_EMPTY = "업로드할 동영상을 선택해주세요.";
var ID_RES_CONST_STRING_WEB_SEARCH = "网络搜索";
var ID_RES_CONST_STRING_NO_SEARCH_RESULT = "未找到结果。";
var ID_RES_CONST_STRING_INPUT_SEARCH_KEYWORD = "请输入关键词。";
var ID_RES_CONST_STRING_CONV_KOREAN = "韩英转换";
var ID_RED_CONST_STRING_ENCYCLOPEDIA = "百科全书";
var ID_RED_CONST_STRING_IMAGE = "图片";
var ID_RED_CONST_STRING_NEWS = "新闻";
var ID_RED_CONST_STRING_VIEW_MORE = "查看更多";
var ID_RED_CONST_STRING_SEARCHING = "正在搜索";
var ID_RES_CONST_STRING_HIGHLIGHTER = "荧光笔";
var ID_RES_CONST_ALERT_HIGHLIGHTER_MODE = "按ESC键即可取消荧光笔模式。";
var ID_RES_CONST_TABLE_CELL_PASTE = "粘贴复制的单元格";
var ID_RES_CONST_ALERTTABLE_CELL_PASTE_MODE = "按ESC键即可取消粘贴复制的单元格。";

var ID_RES_PROP_INSERT_VIDEO = "视频属性";
var ID_RES_PROP_TEXTBOX_CONTENTS = "内容";
var ID_RES_CONST_STRING_SAVEAS_REMOTE = "建立副本";
var ID_RES_CONST_STRING_SAVE_REMOTE = "保存";

var ID_RES_CONST_STRING_NEW_DOCUMENT = "新建文档";
var ID_RES_CONST_STRING_NEW_FOLDER = "新建文件夹";
var ID_RES_CONST_STRING_OPEN_DOCUMENT = "打开";
var ID_RES_CONST_STRING_SET_FAVORITE_ON = "重要标签";
var ID_RES_CONST_STRING_SET_FAVORITE_OFF = "重要标签取消";
var ID_RES_CONST_STRING_RENAME = "重命名";
var ID_RES_CONST_STRING_COPY = "复制";
var ID_RES_CONST_STRING_SET_READONLY_ON = "设置只读";
var ID_RES_CONST_STRING_SET_READONLY_OFF = "取消只读";
var ID_RES_CONST_STRING_CLEAR_TRASHBOX = "清空回收站";
var ID_RES_CONST_STRING_RESTORE = "还原";
var ID_RES_CONST_STRING_DELETE_COMPLETE = "永久删除";
var ID_RES_CONST_STRING_SHARE_DOCUMENT = "共享";
var ID_RES_CONST_STRING_UNSHARE_DOCUMENT = "取消共享";

var ID_RES_CONST_STRING_PLEASE_INPUT_FOLDER_NAME = "请输入文件夹名称。";
var ID_RES_CONST_STRING_PLEASE_INPUT_RENAME = "请输入想要变更的名称。";
var ID_RES_CONST_STRING_CONFIRM_DELETE_DOCUMENT = "您确定要删除{0}' 文件吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_FOLDER = "如果删除文件夹， 内部文件也将全部被删除。<br/>您确定要删除吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_SELECTED_DOCUMENT = "您确定要删除{0}个文件吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_SELECTED_FOLDER_FILE = "如果删除文件夹， 内部文件也将全部被删除。<br/>您确定要删除所选选项吗？";
var ID_RES_CONST_STRING_NOTI_DELETED_DOCUMENT = "已删除{0}个文件。";
var ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT = "此文件已被删除或权限已被变更。";
var ID_RES_CONST_STRING_WARNING_FILE_DUPLICATE = "存在使用相同名称的文件夹/文件。请输入其他名称。";
var ID_RES_CONST_STRING_WARNING_CANNOT_MOVE_SELECTED_FOLDER = "无法移动至选中的文件夹。";

var ID_RES_CONST_STRING_PRINT_MARGIN_SETTING = "设置页边距";
var ID_RES_CONST_STRING_PRINT_MARGIN_NARROW = "窄";
var ID_RES_CONST_STRING_PRINT_MARGIN_NORMAL = "正常";
var ID_RES_CONST_STRING_PRINT_MARGIN_WIDE = "宽";

var ID_RES_CONST_STRING_BROWSER_MY = "我的文档";
var ID_RES_CONST_STRING_BROWSER_RECENT = "ONEFFICE HOME";
var ID_RES_CONST_STRING_BROWSER_SHARE = "共享文档";
var ID_RES_CONST_STRING_BROWSER_FAVORITE = "重要文档";
var ID_RES_CONST_STRING_BROWSER_TRASHBOX = "垃圾箱";
var ID_RES_CONST_STRING_BROWSER_SEARCH_RESULT = "总共{0} 个搜索结果";

var ID_RES_CONST_STRING_PAPER = "纸张";
var ID_RES_CONST_STRING_PAGE_SETUP = "页面设置";
var ID_RES_CONST_STRING_PAPER_ORIENTATION_SERO = "纵向";
var ID_RES_CONST_STRING_PAPER_ORIENTATION_GARO = "横向";

var ID_RES_CONST_STRING_NOTI_COPIED_DOCUMENT = "此文件已复制到{0}。";
var ID_RES_CONST_STRING_NOTI_MOVED_DOCUMENT = "{0}文件已移至{1}。";
var ID_RES_CONST_STRING_NOTI_MOVED_DOCUMENT_LIST = "已移动{0}个文件。";
var ID_RES_CONST_STRING_NOTI_SHARE_DOCUMENT = "{0}文件已共享。";
var ID_RES_CONST_STRING_NOTI_UNSHARE_DOCUMENT = "已取消{0}文件的共享。";
var ID_RES_CONST_STRING_NOTI_UNSHARE_MULTI_DOCUMENT = "已取消{0}个文件的共享。";

var ID_RES_CONST_STRING_TEXTBOX_FILL_COLOR = "填充颜色";
var ID_RES_CONST_STRING_TEXTBOX_BORDER_COLOR = "边框颜色";

var ID_RES_CONST_STRING_INSERT_CHART = "图表";
var ID_RES_CONST_STRING_NOTI_DELETE_CONFIRM = "您确定要删除吗？";
var ID_RES_CONST_STRING_COMPLETE_DELETE_CONFIRM = "Files deleted during permanent deletion cannot be recovered.<br>Do you want to permanently delete?";			//590

var ID_RES_CONST_STRING_PAGE_DELETE_CONFIRM = "The content of the page is also deleted.<br>Are you sure you want to delete the page?";			//590

var ID_RES_CONST_STRING_GROUP_CHART = "组织图";
var ID_RES_CONST_STRING_PAGE_SETTING = "页面设置";
var ID_RES_CONST_STRING_PASTE_CELL = "单元格粘贴选项";
var ID_RES_CONST_STRING_PASTE_CELL_INSERT = "插入一个新行";
var ID_RES_CONST_STRING_PASTE_CELL_OVER_ALL = "覆盖单元格";
var ID_RES_CONST_STRING_PASTE_CELL_OVER_CONTENT = "粘贴内容";

var ID_RES_CONST_STRING_SHARE_LINK_COPY = "复制链接";
var ID_RES_CONST_STRING_CONVERT_ELE_TO_IMG = "画布";

var ID_RES_CONST_STRING_BROWSER_MY_SHARE_LIST = "共享文件";
var ID_RES_CONST_STRING_BROWSER_SHARED_BY_LIST = "接收的共享文件";

var ID_RES_CONST_STRING_SHARE_PERMISSION_VIEW = "所有拥有链接的用户均可查看";
var ID_RES_CONST_STRING_SHARE_PERMISSION_EDIT = "所有拥有链接的用户均可编辑";

var ID_RES_UI_TOGGLE_STRING_MENUSTYLE = "菜单样式";
var ID_RES_CONST_STRING_WARNING_INVALID_DOCUMENT_CALL = "此文件链接错误。";

var ID_RES_CONST_STRING_NOTI_MOVED_LIST_FAIL = "{0}个文件移动失败。";
var ID_RES_CONST_STRING_NOTI_COPIED_LIST_FAIL = "文件复制失败。";
var ID_RES_CONST_STRING_NOTI_DELETE_FAIL_DOCUMENT_LIST = "{0}个文件删除失败。";

var ID_RES_CONST_STRING_CONFIRM_DELETE_SHARE_DOCUMENT = "此文件是共享文件。\n您确定要删除{0}个文件吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_SHARE_DOCUMENT = "已包括共享文件。\n您确定要删除{0}个文件吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_IMPORTANT_DOCUMENT = "此文件是重要文件。\n您确定要删除{0}个文件吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_IMPORTANT_DOCUMENT = "包含重要文件。\n您确定要删除{0}个文件吗？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_SHARE_IMPORTANT_DOCUMENT = "包含有重要文件和共享文件。\n您确定要删除{0}个文件吗？";

var ID_RES_CONST_STRING_GO_TO_MOVILE_VIEWER = "移动至手机版。";
var ID_RES_CONST_STRING_INVALID_CALL = "呼叫错误。";
var ID_RES_CONST_STRING_SAVED = "已保存。";
var ID_RES_CONST_STRING_AUTO_SAVED = "已自动保存。";
var ID_RES_CONST_STRING_MOVE_TO_PARENT_FOLDER = "移动至上级文件夹";
var ID_RES_CONST_STRING_DISABLE_POPUP_BLOCKER = "请关闭弹出窗口阻止程序。";
var ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT = "没有权限或文件不存在。";
var ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT_2 = "没有权限或<br />文件不存在。";
var ID_RES_CONST_STRING_DELETE_CONTAINS_IMPORTANT_DOCUMENT = "已删除的文件无法浏览。";
var ID_RES_CONST_STRING_DELETE_CONTAINS_IMPORTANT_FOLDER = "已删除的文件夹无法浏览。";

var ID_RES_CONST_STRING_RECENT_NO_SHARE_DOCUMENT = "共享权限已被取消，无法浏览。";

var ID_RES_CONST_STRING_READ_ONLY = "只读";
var ID_RES_CONST_STRING_OPENED_READ_ONLY = "以只读方式打开。";
var ID_RES_CONST_STRING_OPENED_READ_ONLY_DOCUMENT = "以只读方式打开的文件。";
var ID_RES_CONST_STRING_SET_READ_ONLY = "已设置为只读。";
var ID_RES_CONST_STRING_SET_EDITABLE = "已取消只读。";
var ID_RES_CONST_STRING_CHANGED_TO_READ_ONLY = "已更改为只读。";

var ID_RES_CONST_STRING_ENTER_SUBJECT = "请输入题目";

var ID_RES_CONST_STRING_RECOVERED = "已还原。";
var ID_RES_CONST_STRING_RECOVERED_ALL = "已全部还原。";
var ID_RES_CONST_STRING_RECOVERY_FAILED = "还原失败。";
var ID_RES_CONST_STRING_FULL_RECOVERY_FAILED = "全部还原失败。";
var ID_RES_CONST_STRING_SOME_RECOVERY_FAILED = "部分还原失败。";

var ID_RES_CONST_STRING_DELETED = "已删除。";
var ID_RES_CONST_STRING_DELETED_ALL = "已全部删除。";
var ID_RES_CONST_STRING_DELETE_ALL_FAIL = "全部删除失败。";
var ID_RES_CONST_STRING_DELETE_SOME_FAIL = "部分删除失败。";
var ID_RES_CONST_STRING_TRASH_IS_EMPTY = "回收站已清空。";
var ID_RES_CONST_STRING_SAVING_DATA = "正在保存数据。";

var ID_RES_CONST_STRING_SELECT_IS_EMPTY = "最近查询的文件不存在。";
var ID_RES_CONST_STRING_SELECT_IS_EMPTY_NEWDOC = "+ 新建";
var ID_RES_CONST_STRING_SELECT_IS_EMPTY_TEMPLATE_MSG = "或用模板创建文件。";

var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_SET_UP = "已设置为重要文件。";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_NOT_SET_UP = "重要文件已取消。";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_SET = "重要文件（已设置）";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_NOT_SET = "重要文件（已取消）";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_CAN_SET_BY_OWNER = "重要文件设置只能由文件所有者进行。";

var ID_RES_CONST_STRING_ENTENR_ID = "请输入用户名！";
var ID_RES_CONST_STRING_LOGIN_FAIL_ENTER_CORRETLY = "登录失败。请正确输入！";
var ID_RES_CONST_STRING_LAST_MODIFIED_DATE = "最新修改日期";
var ID_RES_CONST_STRING_LAST_READ_DATE = "最新查询日期";
var ID_RES_CONST_STRING_SHAREBY_DATE = "接收共享日期";
var ID_RES_CONST_STRING_SHARETO_DATE = "共享日期";
var ID_RES_CONST_STRING_SHARE_DATE = "共享日期";
var ID_RES_CONST_STRING_FILE_SIZE = "文件大小";
var ID_RES_CONST_STRING_OWNER = "所有者";
var ID_RES_CONST_STRING_DELETED_DOCUMENT = "已删除的文件";
var ID_RES_CONST_STRING_COMMING_SOON = "正在准备。";
var ID_RES_CONST_STRING_USAGE = "使用量";
var ID_RES_CONST_STRING_SHARED_DOCUMENT = "共享文件";
var ID_RES_CONST_STRING_COPIED = "已复制。";
var ID_RES_CONST_STRING_FOLDER_LOCATION = "文件夹位置";
var ID_RES_CONST_STRING_CUSTOM_SHARE = "自定义共享";
var ID_RES_CONST_STRING_CLOSE_CUSTOM_SHARE = "关闭自定义共享";
var ID_RES_CONST_STRING_USER_SELECTION = "自定义选择";
var ID_RES_CONST_STRING_ADD_MESSAGE = "添加信息";
var ID_RES_CONST_STRING_VIEWABLE = "可查看";
var ID_RES_CONST_STRING_EDITABLE = "可编辑";
var ID_RES_CONST_STRING_NOT_MODIFIED = "更改记录不存在。";
var ID_RES_CONST_STRING_NO_CELL_COPIED = "没有复制的单元格。";
var ID_RES_CONST_STRING_DOCUMENT_TITLE = "文件标题";
var ID_RES_CONST_STRING_SAVE_PATH = "保存路径";

var ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE = "此文件无法上传。\n* 可用文件：";
var ID_RES_CONST_STRING_ALIGN = "对齐";
var ID_RES_CONST_STRING_HORIZONTAL_WIDTH = "横向宽度";
var ID_RES_CONST_STRING_VERTICAL_HEIGHT = "纵向高度";

var ID_RES_CONST_STRING_KEEP_ORG_HEIGHT = "保持原件高度";
var ID_RES_CONST_STRING_NEW_BLOCK_REFERENCE_HEIGHT = "新BLOCK设置为<br/>标准高度";
var ID_RES_CONST_STRING_PAPER_ORIENTATION = "纸张方向";
var ID_RES_CONST_STRING_PAPER_COLOR = "背景颜色";

var ID_RES_CONST_STRING_PAGE = "页面";
var ID_RES_CONST_STRING_FIRST_PAGE = "此页是首页。";
var ID_RES_CONST_STRING_LAST_PAGE = "此页是最后一页。";
var ID_RES_CONST_STRING_NEXT = "下一页";
var ID_RES_CONST_STRING_PREV = "上一页";
var ID_RES_CONST_STRING_VIEW_SHOW = "播放幻灯片";

var ID_RES_CONST_STRING_CELL_CONTENTS_COPIED = "单元格内容已复制。";
var ID_RES_CONST_STRING_CANNOT_INSERT_CELL_SHAPE_DIFFERENT = "复制单元格和粘贴单元格形状不同，无法插入。";
var ID_RES_CONST_STRING_CLICK_INSERT_POSITION = "请点击要插入的位置！";
var ID_RES_CONST_STRING_CANCLED_INSERT_CHART = "图表插入已取消。";
var ID_RES_CONST_STRING_CHART_TYPE = "图表类型";
var ID_RES_CONST_STRING_AXIS_TRANSFORMATION = "转换坐标轴";
var ID_RES_CONST_STRING_TRANSFORMATION = "转换";

var ID_RES_CONST_STRING_SLIDE_SHOW = "幻灯片放映";
var ID_RES_CONST_STRING_ZOOM_OUT = "缩小查看";
var ID_RES_CONST_STRING_ZOOM_IN = "原始大小";
var ID_RES_CONST_STRING_SLIDE_SHOW_EXIT = "结束放映幻灯片";
var ID_RES_CONST_STRING_BACKGROUND_COLOR = "背景色";
var ID_RES_CONST_STRING_CANNOT_READ_DOCUMENT_FORMAT = "无法表达格式文件的格式";
var ID_RES_CONST_STRING_LOSE_ALL_CONTINUE = "现有内容将初始化。<br/>您确定要继续进行吗？";
var ID_RES_CONST_STRING_READ_ONLY_DOCUMENT = "只读文件";

var ID_RES_CONST_STRING_ENTER_DETAIL = "请输入内容。";

var ID_RES_CONST_STRING_DOCUMENT_SECURITY = "文件安全";
var ID_RES_CONST_STRING_SECURITY_DOCUMENTS = "安全文件";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_SETTING = "设置文件安全";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_RESET = "取消更改文件安全";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_SETTING_NOTE = "注意：\n如果忘记密码，将无法还原此文件。\n密码区分大小写，可输入4到20个字符。";
var ID_RES_CONST_STRING_DOCUMENT_PASSWORD = "文件密码";
var ID_RES_CONST_STRING_DOCUMENT_NEW_PASSWORD = "新密码";
var ID_RES_CONST_STRING_PASSWORD_CONFIRMATION = "确认密码";
var ID_RES_CONST_STRING_NOTI_CONFIRMATION_PASSWORD_ERROR = "确认密码不一致。";
var ID_RES_CONST_STRING_NOTI_CHECK_PASSWORD_ERROR = "当前密码与已设置的密码不一致。";
var ID_RES_CONST_STRING_NOTI_DUPLICATE_PASSWORD_ERROR = "新密码与当前密码相同。";
var ID_RES_CONST_STRING_NOTI_PASSWORD_LENGTH_ERROR = "密码可输入4到10个字符。请重新输入。";
var ID_RES_CONST_STRING_NOTI_WRONG_PASSWORD_ERROR = "密码错误。\Caps";
var ID_RES_CONST_STRING_INPUT_PASSWORD = "请输入密码。";
var ID_RES_CONST_STRING_CHANGE_PASSWORD = "更改密码";
var ID_RES_CONST_STRING_UNSET_PASSWORD = "取消密码";

var ID_RES_CONST_STRING_IMAGE_REPLACE = "更改图片";
var ID_RES_CONST_STRING_IMAGE_SAVEAS = "另存为图片";
var ID_RES_CONST_STRING_ONEFFICE_CONNECT = "ONEFFICE CONNECT";
var ID_RES_CONST_STRING_DOC_OPEN = "获取";
var ID_RES_CONST_STRING_IMAGE_CROPPER = "裁剪图片";

var ID_RES_CONST_STRING_SET_COMPLETE_PASSWORD = "密码已设置 。";
var ID_RES_CONST_STRING_CHANGE_COMPLETE_PASSWORD = "密码已更改。";
var ID_RES_CONST_STRING_UNSET_COMPLETE_PASSWORD = "密码已取消。";
var ID_RES_CONST_STRING_DOWNLOAD_PDF = "下载PDF";

var ID_RES_CONST_STRING_SHARE_PERMISSION_OFF = "关闭（仅共享给指定用户）";
var ID_RES_CONST_STRING_MAIL_SHARE = "共享电子邮件";
var ID_RES_CONST_STRING_NOTE_SHARE = "共享字条";
var ID_RES_CONST_STRING_CHAT_SHARE = "共享聊天室";
var ID_RES_CONST_STRING_SHARE_PERMISSION_LINK = "所有拥有链接的用户";
var ID_RES_CONST_STRING_PERMISSION_ALLOW_USER = "所有拥有权限的用户";

var ID_RES_CONST_STRING_NOTI_SHARE_MULTI_DOCUMENT = "{0}个文件已共享。";
var ID_RES_CONST_STRING_DOC_ZOOM = "放大/缩小";
var ID_RES_CONST_STRING_DOC_ZOOM_FIT_WIDTH = "调整页边距";
var ID_RES_CONST_STRING_DOC_ZOOM_FIT_PAGE = "调整纸张大小";
var ID_RES_CONST_STRING_NOTI_DO_NOT_DELETE = "此页面无法删除。";
var ID_RES_CONST_STRING_GET_REMOTE_SITE_CONTENT = "网络&nbsp格式";
var ID_RES_CONST_STRING_SUPPORT_ONLY_ENTIRE_ROW_COL = "只可以剪切所有行或所有列。";

var ID_RES_CONST_STRING_SELECTED_MULTI_DOCUMENT = "已选中{0}个文件。";
var ID_RES_CONST_STRING_SHARED_OK = "已共享";
var ID_RES_CONST_STRING_SHARED_NO = "未共享";

var ID_RES_CONST_STRING_SHARE_STATUS_CHANGED = "更改的共享内容已反映。";
var ID_RES_CONST_STRING_SHARE_STATUS_NOT_CHANGED = "更改的共享内容不存在。";
var ID_RES_CONST_STRING_WE_NOT_SUPPORTED = "不支持。";
var ID_RES_CONST_STRING_IE_NOT_SUPPORT_LANDSCAPE_PRINT = "IE不支持横向打印。";

var ID_RES_CONST_STRING_SHARE_FAX = "共享传真";
var ID_RES_CONST_STRING_DOC_SECURE_GRADE = "插入文件安全等级";
var ID_RES_CONST_STRING_ALERT_CHOICE_DOC_SECURE_GRADE = "请选择文件安全等级。";
var IE_RES_CONST_STRING_THUMBNAIL_VIEW = "查看缩略图";

var ID_RES_CONST_STRING_INVITE_YOU_SHARE_DOCUMENT = "{0}邀请您{1}下一个文件。";
var ID_RES_CONST_STRING_DOCUMENT_OPEN = "打开文件";
var ID_RES_CONST_STRING_DOCUMENT_SHARE = "共享文件";
var ID_RES_CONST_STRING_SHOW = "查看";
var ID_RES_CONST_STRING_POINTER_OPTION = "指针选项";

var ID_RES_CONST_STRING_NOTI_EXIST_TEMP_DOCUMENT = "存在未指定标题的文件 。";
var ID_RES_CONST_STRING_NOTI_DENY_UNSHARE_DEPARTSHARE_DOCUMENT = "部门共享的文件将限制取消共享。";
var ID_RES_CONST_STRING_TABLE_LOCK_EDIT_CELL = "限制编辑单元格";
var ID_RES_CONST_STRING_NOT_EDITABLE_AREA = "该区域限制编辑。";

var ID_RES_CONST_STRING_SAVE_DOCUMENT_FIRST = "请先保存文件。";

var ID_RES_CONST_STRING_PROTECT_PRIVACY = "个人信息保护";
var ID_RES_CONST_STRING_SELECT_PRIVACY = "选择个人信息";
var ID_RES_CONST_STRING_SELECT_PROTECT_CHAR = "选择保护字符";
var ID_RES_CONST_STRING_PROTECT = "保护";
var ID_RES_CONST_STRING_PROTECT_ALL = "所有保护";
var ID_RES_CONST_STRING_PHONE_NUMBER = "电话号码";
var ID_RES_CONST_STRING_E_MAIL = "电子邮件";
var ID_RES_CONST_STRING_RESIDENT_REGISTRATION_NUMBER = "身份证号码";
var ID_RES_CONST_STRING_ALERT_SELECT_PRIVACY = "请选择个人信息。";
var ID_RES_CONST_STRING_NOTI_MARKING_PRIVACY_COUNT = "已完成{0}次保护个人信息。";
var ID_RES_CONST_STRING_DOCUMENT_BACKUP = "文件备份与还原";

var ID_RES_CONST_STRING_PRIVACY_PASSWORD = "个人信息密码";
var ID_RES_CONST_STRING_DISABLE_PRIVACY = "取消个人信息保护";
var ID_RES_CONST_STRING_DISABLE_PRIVACY_FAIL = "取消个人信息保护失败。";
var ID_RES_CONST_STRING_DISABLE_PRIVACY_DONE = "个人信息保护已取消。";
var ID_RES_CONST_STRING_WEBSEARCH_SUPPLY = "提供搜索结果";

var ID_RES_CONST_STRING_HEADER = "页眉";
var ID_RES_CONST_STRING_FOOTER = "页脚";
var ID_RES_CONST_STRING_HEADER_FOOTER = "页眉/页脚";

var ID_RES_CONST_STRING_FIRST_HEADER = "首页页眉";
var ID_RES_CONST_STRING_FIRST_FOOTER = "首页页脚";
var ID_RES_CONST_STRING_EVEN_HEADER = "偶数页页眉";
var ID_RES_CONST_STRING_EVEN_FOOTER = "偶数页页脚";
var ID_RES_CONST_STRING_ODD_HEADER = "奇数页页眉";
var ID_RES_CONST_STRING_ODD_FOOTER = "奇数页页脚";

var ID_RES_CONST_STRING_EDIT_HEADER = "编辑页眉";
var ID_RES_CONST_STRING_EDIT_FOOTER = "编辑页脚";
var ID_RES_CONST_STRING_CLOSE_HEADER_FOOTER = "关闭页眉/页脚";
var ID_RES_CONST_STRING_REMOVE_HEADER = "删除页眉";
var ID_RES_CONST_STRING_REMOVE_FOOTER = "删除页脚";

var ID_RES_CONST_STRING_GO_TO_HEADER = "转至页眉";
var ID_RES_CONST_STRING_GO_TO_FOOTER = "转至页脚";

var ID_RES_CONST_STRING_HEADER_MARGIN_FROM_TOP = "页眉（上方）";
var ID_RES_CONST_STRING_FOOTER_MARGIN_FROM_BOTTOM = "页脚（下方）";

var ID_RES_CONST_STRING_OPTIONS = "选项";
var ID_RES_CONST_STRING_DIFFERENT_FIRST_PAGE = "首页不同";
var ID_RES_CONST_STRING_DIFFERENT_ODD_EVEN_PAGES = "奇偶页不同";
var ID_RES_CONST_STRING_SHOW_DOCUMENT_TEXT = "显示文件文本";
var ID_RES_CONST_STRING_SHOW_RIBBON_TOOLBARS_ALWAYS = "固定功能区";
var ID_RES_CONST_STRING_HIDE_RIBBON_TOOLBARS = "折叠功能区";

var ID_RES_CONST_STRING_DELETE_IMAGE = "删除图片";
var ID_RES_CONST_STRING_DELETE_VIDEO = "删除视频";

var ID_RES_DIALOG_STRING_ALIGN_MIDDLE = "中部";
var ID_RES_DIALOG_STRING_ALIGN_TOP = "顶端";
var ID_RES_TOOL_STRING_MENU_HOME = "开始";
var ID_RES_TOOL_STRING_MENU_LAYOUT = "布局";
var ID_RES_CONST_STRING_HELP_ONLINE = "在线手册";

var ID_RES_DIALOG_STRING_NO_SELECT = "不选中";
var ID_RES_DIALOG_STRING_AUTO_PLAY = "自动创建";
var ID_RES_CONST_STRING_VIEWING = "浏览";
var ID_RES_CONST_STRING_CHART_DATA_SORT = "数据顺序";
var ID_RES_CONST_STRING_CHART_DATA_SORT_REVERSE = "逆向";

var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ALL = "整个期间";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_DAY = "1日";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_WEEK = "1周";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_MONTH = "1个月";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_SIX_MONTH = "6个月";
var ID_RES_CONST_STRING_SEARCH_SEARCH_PERIOD_OPTION_ONE_YEAR = "1年";

var ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT = "题目";
var ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_OWNER = "所有者";
var ID_RES_CONST_STRING_BROWSER_UNIFIED_SEARCH_RESULT = "在\{0}\"";
var ID_RES_CONST_STRING_ALL_SEARCH_RESULT = "全部搜索结果";
var ID_RES_CONST_STRING_SEND_BIZBOX_REPORT = "发送业务报告";
var ID_RES_CONST_STRING_UPDATE_BIZBOX_REPORT = "更新业务报告";

var ID_RES_CONST_STRING_DOCUMENT_HISTORY = "文件记录";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_VIEW_LARGER = "放大查看";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_ACTION_TYPE = "类别";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_SHARE_INFO = "共享信息";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_DEVIDE_INFO = "设备信息";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_ACCESS = "访问";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_SHARE_ALL = "全部共享";

var ID_RES_CONST_STRING_ADD = "添加";
var ID_RES_CONST_STRING_DELETE = "删除";

var ID_RES_CONST_STRING_ADD_SCHEDULE = "添加日程";
var ID_RES_CONST_STRING_DELETE_SCHEDULE = "删除日程";
var ID_RES_CONST_STRING_ADD_TASK = "添加业务";
var ID_RES_CONST_STRING_DELETE_TASK = "删除业务";
var ID_RES_CONST_STRING_ALERT_NOT_AVAILABLE_IN_ONEPAGE_MODE = "在单页模式下无法使用。";
var ID_RES_CONST_STRING_ONEPAGE_MODE = "分离页面";
var ID_RES_CONST_STRING_ONEPAGE_MODE_ON = "单页";
var ID_RES_CONST_STRING_ONEPAGE_MODE_OFF = "多页";
var ID_RES_CONST_STRING_PAPER_SIZE = "纸张大小";
var ID_RES_CONST_STRING_NOTI_HYPERLINK_GUIDE = "跟踪超链接时需按住<Ctrl>键单击。";

var ID_RES_CONST_STRING_SHAPES = "形状";
var ID_RES_CONST_STRING_SHAPES_FORMAT = "形状格式";
var ID_RES_CONST_STRING_SHAPES_CHANGE = "更改形状格式";
var ID_RES_CONST_STRING_SHAPES_STYLE = "形状样式";
var ID_RES_CONST_STRING_SHAPES_FILL = "形状填充";
var ID_RES_CONST_STRING_SHAPES_BORDER = "形状轮廓";
var ID_RES_CONST_STRING_SHAPES_TEXT_ALIGN = "对齐文本";
var ID_RES_CONST_STRING_SHAPES_LAYOUT = "自动换行";
var ID_RES_CONST_STRING_SHAPES_MOVE_FRONT = "浮于文字上方";
var ID_RES_CONST_STRING_SHAPES_MOVE_FRONT_EDGE = "置于顶层";
var ID_RES_CONST_STRING_SHAPES_MOVE_BACK = "衬于文字下方";
var ID_RES_CONST_STRING_SHAPES_MOVE_BACK_EDGE = "置于底层";
var ID_RES_CONST_STRING_SHAPES_ALIGN = "对齐";
var ID_RES_CONST_STRING_SHAPES_ROTATE = "旋转";
var ID_RES_CONST_STRING_SHAPES_TRANSPARENT = "透明度";
var ID_RES_CONST_STRING_SHAPES_FILL_NONE = "无填充";
var ID_RES_CONST_STRING_SHAPES_FILL_SOLID = "纯色填充";
var ID_RES_CONST_STRING_SHAPES_STYLE_TEMPLATE = "基本形状";
var ID_RES_CONST_STRING_SHAPES_TEXT_ALIGN_MIDDLE = "中间";

var ID_RES_CONST_STRING_SHAPES_SQUARE_RIGHT_ANGLE = "矩形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_ROUNDED = "矩形：圆角";
var ID_RES_CONST_STRING_SHAPES_SQUARE_TRAPEZOID = "梯形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_PARALLELOGRAM = "平行四边形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_DIAMOND = "菱形";

var ID_RES_CONST_STRING_SHAPES_TRIANGLE_ISOSCELES_TOP = "上方等腰三角形";
var ID_RES_CONST_STRING_SHAPES_TRIANGLE_ISOSCELES_RIGHT = "右侧等腰三角形";
var ID_RES_CONST_STRING_SHAPES_TRIANGLE_RIGHT_ANGLE = "直角三角形";

var ID_RES_CONST_STRING_SHAPES_CIRCLE = "饼图";
var ID_RES_CONST_STRING_SHAPES_ELLIPSE = "椭圆";

var ID_RES_CONST_STRING_SHAPES_ARROW_RIGHT = "箭头：右";
var ID_RES_CONST_STRING_SHAPES_ARROW_TOP = "箭头：上";
var ID_RES_CONST_STRING_SHAPES_ARROW_LEFT_RIGHT = "箭头：左右";
var ID_RES_CONST_STRING_SHAPES_ARROW_TOP_BOTTOM = "箭头：上下";

var ID_RES_CONST_STRING_SHAPES_LINE_NORMAL = "线条";
var ID_RES_CONST_STRING_SHAPES_LINE_ARROW_UNI_DIRECTION = "箭头：单向";
var ID_RES_CONST_STRING_SHAPES_LINE_ARROW_BI_DIRECTION = "箭头：双向";

var ID_RES_CONST_STRING_LIST_NO_START = "从下一个编号开始";

var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_TOP = "顶端";
var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_MIDDLE = "中部";
var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_BOTTOM = "底端";
var ID_RES_CONST_STRING_OBJ_ALIGN_TOP = "顶端对齐";
var ID_RES_CONST_STRING_OBJ_ALIGN_MIDDLE = "中部对齐";
var ID_RES_CONST_STRING_OBJ_ALIGN_BOTTOM = "底端对齐";

var ID_RES_CONST_STRING_OBJ_ROTATE_RIGHT_90 = "向右旋转90°";
var ID_RES_CONST_STRING_OBJ_ROTATE_LEFT_90 = "向左旋转90°";
var ID_RES_CONST_STRING_OBJ_ROTATE_FLIP_VERTICAL = "垂直翻转";
var ID_RES_CONST_STRING_OBJ_ROTATE_FLIP_HORIZONTAL = "水平翻转";
var ID_RES_CONST_STRING_OBJ_ROTATE_OTHERS = "其他旋转选项";

var ID_RES_CONST_STRING_TXTLAYOUT_IN_LINE_WIDTH_TEXT = "嵌入型";
var ID_RES_CONST_STRING_TXTLAYOUT_SQUARE = "正方形";
var ID_RES_CONST_STRING_TXTLAYOUT_TIGHT = "紧密型环绕";
var ID_RES_CONST_STRING_TXTLAYOUT_THROUGH = "穿越型环绕";
var ID_RES_CONST_STRING_TXTLAYOUT_TOPANDBOTTOM = "上下型环绕";
var ID_RES_CONST_STRING_TXTLAYOUT_BEHIND_TEXT = "衬于文字下方";
var ID_RES_CONST_STRING_TXTLAYOUT_IN_FRONT_OF_TEXT = "浮于文字上方";
var ID_RES_CONST_STRING_TXTLAYOUT_LEFT_TEXT = "文字左侧";
var ID_RES_CONST_STRING_TXTLAYOUT_RIGHT_TEXT = "文字右侧";
var ID_RES_CONST_STRING_TXTLAYOUT_OTHERS = "其他布局选项";
var ID_RES_CONST_STRING_LINE_NOCOLOR = "无轮廓";
var ID_RES_CONST_STRING_LINE_OTHER_COLOR = "其他轮廓颜色";

var ID_RES_CONST_STRING_COUNT = "个";
var ID_RES_CONST_STRING_ARROW = "箭头";
var ID_RES_CONST_STRING_ARROW_NONE = "无箭头";
var ID_RES_CONST_STRING_ARROW1 = "箭头1";
var ID_RES_CONST_STRING_ARROW2 = "箭头2";
var ID_RES_CONST_STRING_ARROW3 = "箭头3";
var ID_RES_CONST_STRING_ARROW4 = "箭头4";
var ID_RES_CONST_STRING_ARROW5 = "箭头5";
var ID_RES_CONST_STRING_ARROW6 = "箭头6";
var ID_RES_CONST_STRING_ARROW7 = "箭头7";
var ID_RES_CONST_STRING_ARROW8 = "箭头8";
var ID_RES_CONST_STRING_ARROW9 = "箭头9";
var ID_RES_CONST_STRING_ARROW10 = "箭头10";

var ID_RES_CONST_STRING_GET_BIZBOX_REPORT_LIST = "获取业务报告";

var ID_RES_CONST_STRING_SHAPES_PLACING = "环绕文字";
var ID_RES_CONST_STRING_SHAPES_DISTANCE_WITH_TEXT = "距正文";
var ID_RES_CONST_STRING_SHAPES_RATIO = "纵横比";
var ID_RES_CONST_STRING_SHAPES_FIXED_RATIO = "锁定纵横比";
var ID_RES_CONST_STRING_SHAPES_ADD_TEXT = "添加文本";

var ID_RES_CONST_STRING_OPEN_LINK = "OPENLINK";
var ID_RES_CONST_STRING_SHARED_USER = "共享中的用户";
var ID_RES_CONST_STRING_PEOPLE_COUNT = "名";
var ID_RES_CONST_STRING_USER_SHARING = "自定义共享";
var ID_RES_CONST_STRING_STATUS_ON = "打开";
var ID_RES_CONST_STRING_STATUS_OFF = "关闭";
var ID_RES_CONST_STRING_LINK_OFF = "关闭链接";
var ID_RES_CONST_STRING_SHARE_NOTI_TYPE = "发送方式";
var ID_RES_CONST_STRING_MAIL = "发送邮件";
var ID_RES_CONST_STRING_NOTE = "发送纸条";
var ID_RES_CONST_STRING_ONEFFICE = "ONEFFICE";
var ID_RES_CONST_STRING_SHARE_COUNT_STATUS = "共享中({0})";

var ID_RES_CONST_STRING_FIXED_RATIO = "锁定纵横比";
var ID_RES_CONST_STRING_CHANGE_PROTECT_PASSWORD = "更改保护密码";
var ID_RES_CONST_STRING_FOREIGNER_NUMBER = "外国人登录证号";
var ID_RES_CONST_STRING_CREDITCARD_NUMBER = "信用卡号码";
var ID_RES_CONST_STRING_IP_ADDRESS = "连接IP";
var ID_RES_CONST_STRING_BIRTHDAY = "出生日期";
var ID_RES_CONST_STRING_USER_DEFINE_SETTING = "自定义设置";
var ID_RES_CONST_STRING_DISPLAY_FORM_SETTING = "设置显示格式";

var ID_RES_CONST_STRING_CHART_DATA_CONVERT = "切换数据";
var ID_RES_CONST_STRING_CHART_DATA_XY_CONVERT = "切换行/列";
var ID_RES_CONST_STRING_CHART_DATA_ORDER_CONVERT = "切换顺序";
var ID_RES_CONST_STRING_CHART_TYPE_BAR = "柱形图";
var ID_RES_CONST_STRING_CHART_TYPE_HBAR = "条形图";
var ID_RES_CONST_STRING_CHART_TYPE_LINE = "折线图";
var ID_RES_CONST_STRING_CHART_TYPE_LINE_CUBIC = "曲线图";
var ID_RES_CONST_STRING_CHART_TYPE_PIE = "饼图";
var ID_RES_CONST_STRING_CHART_TYPE_DOUGHNUT = "旭日图";
var ID_RES_CONST_STRING_CHART_TYPE_RADAR = "雷达图";
var ID_RES_CONST_STRING_CHART_TYPE_POLARAREA = "扇形图";
var ID_RES_CONST_STRING_CHART_TITLE = "图表标题";
var ID_RES_CONST_STRING_CHART_DATA_TITLE = "图表数据";
var ID_RES_CONST_STRING_MODIFY_CHART_DATA = "编辑图表数据";
var ID_RES_CONST_STRING_MODIFY_CHART_TYPE = "更改图表类型";
var ID_RES_CONST_STRING_CHART_LEGEND_VIEW = "显示图例";
var ID_RES_CONST_STRING_CHART_DATA_VIEW = "显示数据";
var ID_RES_CONST_STRING_CHART_DATA_VIEW_OK = "显示";
var ID_RES_CONST_STRING_CHART_DATA_LABEL = "数据标签";
var ID_RES_CONST_STRING_CHART_TITLE_PADDING = "距正文";

var ID_RES_CONST_STRING_PAGE_CONTENTS = "页面内容";
var ID_RES_CONST_STRING_PAGE_CONTENTS_OVERFLOW_ON = "取消自动调整";
var ID_RES_CONST_STRING_PAGE_CONTENTS_OVERFLOW_OFF = "自动调整";

var ID_RES_CONST_BTN_MERGE_DOCUMENT = "合并文件";

var ID_RES_CONST_STRING_TABLE_COLLAPSE = "单元格和单元格之间用1条线条表现";

var ID_RES_CONST_STRING_INSERT_NEW_PAGE = "新页面";
var ID_RES_CONST_STRING_PAGE_MANAGEMENT = "页面管理";
var ID_RES_CONST_STRING_INSERT_EMPTY_PAGE = "插入空白页";
var ID_RES_CONST_STRING_COPY_PAGE = "复制页面";
var ID_RES_CONST_STRING_PASTE_PAGE = "粘贴页面";
var ID_RES_CONST_STRING_DELETE_PAGE = "删除页面";
var ID_RES_CONST_STRING_ABOVE_PAGE = "页面顶端";
var ID_RES_CONST_STRING_BELOW_PAGE = "页面底端";
var ID_RES_CONST_STRING_INSERT_TABLE_WITH_CHART = "插入图表时同时插入数据表";

var ID_RES_CONST_STRING_KEEP_TEXT_ONLY = "仅保留文本";
var ID_RES_CONST_STRING_INSERT_AS_NESTED_TABLE = "表格嵌套";

var ID_RES_CONST_STRING_RECEIVED_REPORT = "收到的报告";
var ID_RES_CONST_STRING_SENT_REPORT = "发送的报告";
var ID_RES_CONST_STRING_REFERENCE_REPORT = "参考的报告";
var ID_RES_CONST_STRING_PUBLIC_REPORT = "公开的报告";

var ID_RES_CONST_STRING_BROWSER_SECURITY = "安全文档";

var ID_RES_CONST_STRING_SHARED_DATE = "共享日期";

var ID_RES_CONST_STRING_EXTEND_FUNC = "放大功能";
var ID_RES_SEND_MAIL_FAIL = "邮件发送失败。";
var ID_RES_CONST_STRING_ALREADY_IN_USER = "此用户已包括在内。";
var ID_RES_CONST_STRING_IMPORTANT = "重要";
var ID_RES_CONST_STRING_FILE_TYPE = "文件类型";

var ID_RES_CONST_STRING_CREATE_FOLDER = "新建文件夹";
var ID_RES_CONST_STRING_CREATE_FILE = "新建文档";
var ID_RES_CONST_STRING_CHANGES_NOT_SAVED = "变更事项可能无法保存。";

var ID_RES_CONST_STRING_DIRECT_GO = "快捷键";
var ID_RES_CONST_STRING_LOGIN_GUIDE_TITLE = "登录指南";
var ID_RES_CONST_STRING_LOGIN_GUIDE_CONTENT = "会话已过期， 需要重新登录 。<br />请在新窗口登录后重新尝试。<br />您确定要在新窗口打开登录页面吗？";
var ID_RES_CONST_STRING_SERVER_ERROR_TITLE = "网络错误指南";
var ID_RES_CONST_STRING_SERVER_ERROR_CONTENT = "发生了网络错误。<br />请稍后再试。";
var ID_RES_CONST_STRING_INSERT_QRCODE = "二维码";

var ID_RES_CONST_PANEL_TITLE_DOC_INFO = "文件详细信息";
var ID_RES_CONST_PANEL_TITLE_DOC_ACCESS = "文件访问管理";
var ID_RES_CONST_PANEL_TITLE_DOC_COMMENT = "文件回复";
var ID_RES_CONST_PANEL_TITLE_DOC_CHART = "图表格式";
var ID_RES_CONST_TOAST_EDIT_AUTH_REQUEST_CANCEL = "编辑权限请求已取消。";
var ID_RES_CONST_TOAST_EDIT_AUTH_PASS_SUCCESS = "编辑权限已移交。";
var ID_RES_CONST_TOAST_REJECT_EDIT_REQUEST = "编辑权限请求已被拒绝。";
var ID_RES_CONST_TOAST_OTHER_USED_REQUEST = "其他用户正在请求编辑权限。";
var ID_RES_CONST_TOAST_ACCESS_MANAGER_TITLE = "请求权限";
var ID_RES_CONST_STRING_DELETE_DIV = "删除虚线框";

var ID_RES_CONST_STRING_QRCODE_FITST_INFO = "首页右上角";
var ID_RES_CONST_STRING_QRCODE_LAST_INFO = "最后一页底部";

var ID_RES_CONST_STRING_SORT_TITE = "文件标题";
var ID_RES_CONST_STRING_SORT_RECENTDATE = "最新修改日期";
var ID_RES_CONST_STRING_SORT_READDATE = "最新查询日期";
var ID_RES_CONST_STRING_SORT_SHEREBYDATE = "接收共享日期";
var ID_RES_CONST_STRING_SORT_FILESIZE = "文件大小";
var ID_RES_CONST_STRING_SORT_SHEREDATE = "共享日期";
var ID_RES_CONST_STRING_SORT_OWNER = "所有者";

var ID_RES_CONST_STRING_FILTER_ALL = "所有文件";
var ID_RES_CONST_STRING_FILTER_MY = "我的文件";
var ID_RES_CONST_STRING_FILTER_BY = "接收的共享文件";

var ID_RES_CONST_STRING_CREATE_DATE = "创建日期";
var ID_RES_CONST_STRING_MODIFY_DATE = "修改日期";
var ID_RES_CONST_STRING_NO_PERMMISION = "没有浏览权限。";
var ID_RES_CONST_STRING_NO_PERMMISION_INFO = "请向所有者请求权限。";
var ID_RES_CONST_STRING_REQUEST_PERMMISION = "请求权限";
var ID_RES_CONST_STRING_REQUEST_CONFIRM = "已请求权限。";
var ID_RES_CONST_STRING_REQUEST_ALLOW = "权限已经允许。";
var ID_RES_CONST_STRING_REQUEST_NOT_ALLOW = "权限未经允许。";
var ID_RES_CONST_STRING_SOMEONE_PERM = "为了让{0}可以{1}文件";
var ID_RES_CONST_STRING_ALLOW_PERMISSION = "您确定要允许权限吗？";
var ID_RES_CONST_STRING_ALLOW = "允许";
var ID_RES_CONST_STRING_DENY = "拒绝";
var ID_RES_CONST_STRING_ALREADY_ALLOW_DOCUMENT = "此文件已允许权限。";

var ID_RES_CONST_PANEL_FILE_SELECT_NONE = "请选择文件或文档。";
var ID_RES_CONST_PANEL_MENU_DETAIL_INFO = "查看更多";
var ID_RES_CONST_PANEL_EDITING_USER = "正在编辑的用户";
var ID_RES_CONST_PANEL_VIEWING_USER = "正在浏览的用户";
var ID_RES_CONST_PANEL_REQUEST_WRITE_AUTH = "请求权限";
var ID_RES_CONST_PANEL_PASS_WRITE_AUTH = "移交权限";
var ID_RES_CONST_PANEL_CANCEL_REQUEST_WRITE_AUTH = "取消请求";
var ID_RES_CONST_PANEL_CREATE_NEW_DOC = "创建新文件";
var ID_RES_CONST_STRING_YEAR = "年";
var ID_RES_CONST_STRING_MONTH = "月";
var ID_RES_CONST_STRING_DAY = "日";
var ID_RES_CONST_STRING_AM = "上午";
var ID_RES_CONST_STRING_PM = "下午";
var ID_RES_CONST_PANEL_MSG_REQUEST_WRITE_AUTH_FROM = "下一位用户已请求编辑权限 。";
var ID_RES_CONST_PANEL_MSG_CONFIRM_WRITE_AUTH = "您确定要{0}编辑权限吗？";
var ID_RES_CONST_PANEL_MSG_REJECT_WRITE_AUTH = "编辑权限请求已{0}。";
var ID_RES_CONST_PANEL_MSG_DUPLICATED_REQUEST = "其他用户拥有{0}编辑权限。";
var ID_RES_CONST_PANEL_REQUEST = "请求";
var ID_RES_CONST_PANEL_PASS_TO = "移交";
var ID_RES_CONST_PANEL_REJECT = "拒绝";
var ID_RES_CONST_PANEL_REQUESTING = "正在请求";
var ID_RES_CONST_PANEL_REQUEST_WRITE_SUCCESS = "已获得编辑权限。";
var ID_RES_CONST_PANEL_AM_EDITOR_OUT = "编辑者已关闭文件后退出。";

var ID_RES_CONST_STRING_WRAP_TEXT = "自动换行";

var ID_RES_CONST_STRING_DEFAULT_FILE_NAME = "无标题的文件";
var ID_RES_CONST_STRING_DEFAULT_FOLDER_NAME = "无标题的文件夹";

var ID_RES_CONST_STRING_PAGE_MOVE = "移动页面";
var ID_RES_CONST_STRING_SLIDE_SHOW_CONFIRM = "因浏览器政策确认时<br />进入全部幻灯片放映模式。";
var ID_RES_CONST_STRING_NEXT_SLIDE = "下一张幻灯片";
var ID_RES_CONST_STRING_PREV_SLIDE = "上一张幻灯片";
var ID_RES_CONST_STRING_MOVE_SLIDE = "移动幻灯片";
var ID_RES_CONST_STRING_ZOOM_INOUT = "放大/缩小";

var ID_RES_CONST_SLIDESHOW_ZOOM_HEIGHT = "调整上下页边距";
var ID_RES_CONST_SLIDESHOW_ZOOM_WIDTH = "调整左右页边距";
var ID_RES_CONST_SLIDESHOW_ZOOM_125 = "125%";
var ID_RES_CONST_SLIDESHOW_ZOOM_150 = "150%";
var ID_RES_CONST_SLIDESHOW_ZOOM_175 = "175%";

var ID_RES_CONST_STRING_CURRENT_SLIDE_SHOW = "从当前幻灯片开始放映";
var ID_RES_CONST_STRING_TOOLBAR_100 = "100%对齐";

var ID_RES_CONST_STRING_PGNUM = "页码";
var ID_RES_CONST_STRING_PGNUM_FORMAT = "页码格式";
var ID_RES_CONST_STRING_PGNUM_REMOVE = "删除页码";

var ID_RES_CONST_STRING_FORMAT_STYLE = "格式样式";
var ID_RES_CONST_STRING_NUM_FORMAT = "编号格式";
var ID_RES_CONST_STRING_NUM_POS = "编号位置";

var ID_RES_CONST_STRING_TEXT_STYLE = "文本样式";

var ID_RES_CONST_STRING_PGNUMERING = "设置页码";
var ID_RES_CONST_STRING_PGNUM_START = "指定起始页";

var ID_RES_CONST_STRING_PGNUM_NO = "无编号";

var ID_RED_CONST_STRING_TOP_LEFT = "左上角";
var ID_RED_CONST_STRING_TOP_CENTER = "顶端居中";
var ID_RED_CONST_STRING_TOP_RIGHT = "右上角";
var ID_RED_CONST_STRING_BOTTOM_LEFT = "左下角";
var ID_RED_CONST_STRING_BOTTOM_CENTER = "底端居中";
var ID_RED_CONST_STRING_BOTTOM_RIGHT = "右下角";

var ID_RES_CONST_STRING_FONT_STYLE = "字体样式";
var ID_RES_CONST_STRING_DOCUMENT_CONTINUE_WRITE = "文件连续写入。";
var ID_RES_CONST_STRING_DOCUMENT_RELOAD = "重新载入文件。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_LOADED = "正在浏览临时保存在{0}中的文件。";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_OPEN = "临时保存在{0}中的文件，可以[只读]进行浏览。您确定要确认临时保存的文件吗？";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_DELETE = "您确定要删除临时保存的文件吗？<br />已删除的文件无法还原。";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_ALL_DOCUMENT_DELETE = "您确定要删除全部临时保存的文件吗？<br />已删除的文件无法还原。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_DELETED_COMPLETE = "已删除。";
var ID_RES_CONST_STRING_TEMP_SAVED_ALL_DOCUMENT_DELETED_COMPLETE = "全部文件已删除。";

var ID_RES_CONST_STRING_TEMP_SAVED_DOC_BOX = "临时保存文档";
var ID_RES_CONST_STRING_TEMP_SAVE = "临时保存";
var ID_RES_CONST_STRING_OVERWRITE_ORG_DOC = "覆盖原文";
var ID_RES_CONST_STRING_DELETE_DOC = "删除文件";
var ID_RES_CONST_STRING_ORG_DOCUMENT_INFO = "原始文件信息";
var ID_RES_CONST_STRING_DOCUMENT_LAST_UPDATE = "最后保存日期";
var ID_RES_CONST_STRING_DOCUMENT_WRITER = "作者";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_OVERWRITE = "您确定要将临时保存的文件覆盖在原始文件上吗？<br />覆盖的原文内容无法还原。";
var ID_RES_CONST_STRING_OVERWRITE_ORG_DOC_COMPLETE = "已覆盖。";
var ID_RES_CONST_STRING_ALERT_OVERWRITE_FAIL_READONLY_ATTR_DOCUMENT = "原始文件为只读文件，无法覆盖。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_NUM_STRING = "总共{0}个临时保存文件";
var ID_RES_CONST_STRING_DELETE_ALL_DOC = "全部删除";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENTS = "临时保存的文档";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_LIST_OPEN = "存在临时保存的文件。<br />您要确认吗？";
var ID_RES_CONST_STRING_CLOSE_WINDOW = "您确定要关闭窗口吗？";

var ID_RES_STRING_CONTROL_HEIGHT = "调整高度";
var ID_RES_STRING_CONTROL_WIDTH = "调整宽度";

var ID_RES_STRING_PAGE_BREAK_GUIDE = "――― 分页符 ―――";
var ID_RES_STRING_PASTE_CELL_INSERT_AS_TABLE = "表格嵌套";

var ID_RES_CONST_STRING_REGIST_SCHEDULE = "登记日程";

var ID_RES_STRING_CHG_OWN = "移交文件所有权";
var ID_RES_STRING_CHG_OWN_ING = "正在移交所有权";
var ID_RES_STRING_CHG_OWN_CANCEL = "取消移交所有权";
var ID_RES_STRING_CHG_OWN_TARGET = "移交对象";

var ID_RES_STRING_CHG_OWN_PLACEHOLDER = "移交对象可以选择1名";
var ID_RES_STRING_CHG_OWN_SEL_ERR0 = "请选择移交对象。";
var ID_RES_STRING_CHG_OWN_SEL_ERR1 = "请仅选择1名移交对象。";
var ID_RES_STRING_CHG_OWN_SEL_ERR2 = "无法将所有权移交给自己。";
var ID_RES_STRING_CHG_OWN_SEL_ERR3 = "无法将所有权移交给部门。";

var ID_RES_STRING_CHG_OWN_POP_REQ = "您确定要向此用户请求转交文件所有权吗？\n（经移交对象确认后即可最终转移。）";
var ID_RES_STRING_CHG_OWN_POP_CANCEL = "您确定要\n取消此文件所有权的移交请求吗？";
var ID_RES_STRING_CHG_OWN_POP_ACCEPT = "您确定要接受\n{0}的文件所有权移交请求吗？";

var ID_RES_STRING_CHG_OWN_TOAST = "所有权移交请求已提交。";
var ID_RES_STRING_CHG_OWN_TOAST1 = "已移交所有权。";
var ID_RES_STRING_CHG_OWN_TOAST2 = "已拒绝所有权移交请求。";
var ID_RES_STRING_CHG_OWN_TOAST3 = "所有权移交请求已取消。";
var ID_RES_STRING_CHG_OWN_TOAST4 = "您请求的{0}已{1}。";
var ID_RES_STRING_CHG_OWN_TOAST5 = "{0}已请求移交文件所有权。{1}";
var ID_RES_STRING_CHG_OWN_TOAST6 = "不存在移交文件。";

var ID_RES_STRING_CHG_OWN_SEL_FOLDER = "保存所有权移交文件";

var ID_RES_CONST_STRING_ACCEPT = "批准";
var ID_RES_CONST_STRING_REJECT = "拒绝";
var ID_RES_CONST_STRING_END = "结束";

var ID_RES_STRING_CHG_OWN_NOTE_MSG = "[文件所有权移交请求通知]\r\n\r\n{0}已请求移交文件所有权。\r\n\r\n[转至接受请求]\r\n{1}";

var ID_RES_STRING_EDIT_WATERMARK = "水印";

var ID_RES_STRING_SEND_EXTERNAL = "发送到外部";
var ID_RES_STRING_SEND_EXTERNAL_NOTI = "确认时ONEFFICE文件将转换为PDF后自动附加到电子邮件中";

var ID_RES_STRING_TRANSFER_MOBILE_EDITOR_FAIL = "{0}正在手机上进行编辑。<br>手机版不支持权限请求功能。";

var ID_RES_CONST_DOC_COMMENT_NOTI = "ONEFFICE文件上注册了新留言。";

var ID_RES_STRING_TOTAL_SEARCH = "ONEFFICE综合搜索";

var ID_RES_STRING_NEW_TEMPLATE = "新建文档";
var ID_RES_STRING_TITLE_TEMPLATE = "新文件模板";

var ID_RES_STRING_RECENT_TEMPATE = "最近使用的模板";
var ID_RES_STRING_MY_FAVOR_TITLE_TEMPLATE = "我的模板";
var ID_RES_STRING_BUSS_REOPORT_TITLE_TEMPLATE = "业务报告";
var ID_RES_STRING_REOPORT_TITLE_TEMPLATE = "报告";
var ID_RES_STRING_MEETING_TITLE_TEMPLATE = "会议记录";

var ID_RES_CONST_STRING_DEST_SHARE_USER = "请输入共享对象。";

var ID_RES_STRING_CHART_COLUMN = "系列";
var ID_RES_STRING_CHART_ITEM = "项目";

var ID_RES_STRING_CHART_LABEL = "显示";

var ID_RES_STRING_DAY_REPORT_TEMPLATE = "每日报告";
var ID_RES_STRING_DAY_REPORT_CORONA = "居家办公每日报告";
var ID_RES_STRING_TIME_REPORT_TEMPLATE = "随时报告";
var ID_RES_STRING_MEETING_REPORT_TEMPLATE = "会议记录";
var ID_RES_STRING_MEETING_REPORT_2_TEMPLATE = "会议记录2";
var ID_RES_STRING_MEETING_REPORT_3_TEMPLATE = "会议记录3";
var ID_RES_STRING_MEETING_REPORT_4_TEMPLATE = "会议记录4";
var ID_RES_STRING_MEETING_REPORT_5_TEMPLATE = "会议记录5";

var ID_RES_STRING_DEV_REPORT_TEMPLATE = "开发报告";
var ID_RES_STRING_BUS_REPORT_TEMPLATE = "事业计划报告";
var ID_RES_STRING_WEEK_REPORT_TEMPLATE = "每周报告";
var ID_RES_STRING_BASIC_REPORT_TEMPLATE = "基本报告";
var ID_RES_STRING_ANALYZE_TEMPLATE = "分析报告";

var ID_RES_STRING_GENERAL_FORM_TEMPLATE = "普通报告";
var ID_RES_STRING_GENERAL_FORM_2_TEMPLATE = "普通报告2";
var ID_RES_STRING_GENERAL_FORM_3_TEMPLATE = "普通报告3";
var ID_RES_STRING_PROJECT_FORM_1_TEMPLATE = "项目报告1";
var ID_RES_STRING_PROJECT_FORM_2_TEMPLATE = "项目报告2";

var ID_RES_STRING_PRODUCT_REPORT_TEMPLATE = "产品报告";

var ID_RES_STRING_SERVICE_FORM_TEMPLATE = "服务引进报告";
var ID_RES_STRING_ADJUST_METHOD_TEMPLATE = "调整方案研究报告";
var ID_RES_STRING_EVENT_PLAN_TEMPLATE = "活动推广计划";

var ID_RES_STRING_IMPROVE_FORM_TEMPLATE = "改善报告";
var ID_RES_STRING_ISSUE_FORM_TEMPLATE = "问题报告";
var ID_RES_STRING_CURRENT_FORM_TEMPLATE = "现状报告";

var ID_RES_STRING_TAX_NOTICE_TEMPLATE = "税务提醒";
var ID_RES_STRING_TAX_NET_TEMPLATE = "TAXNET";

var ID_RES_STRING_TAX_LIST_TEMPLATE = "事业分析报告";
var ID_RES_STRING_TAX_SAVING_TEMPLATE = "节税指南";

var ID_RES_STRING_FORM_GROUP_BUSS = "业务报告";
var ID_RES_STRING_FORM_GROUP_MEETING = "会议记录";
var ID_RES_STRING_FORM_GROUP_REPORT = "报告";
var ID_RES_STRING_FORM_GROUP_NORMAL = "常规格式";
var ID_RES_STRING_FORM_GROUP_TAX = "税务格式";
var ID_RES_STRING_FORM_GROUP_ARTICLE = "报道格式";

var ID_RES_STRING_VIDEO_LEARN_ONEFFICE = "通过视频来学习的\nONEFFICE";
var ID_RES_STRING_BUSS_ONEFFICE_WRITE = "使用ONEFFICE写的\n业务报告与众不同！";

var ID_RES_STRING_INSERT_PAGE_BREAK = "分页符";

var ID_RES_STRING_TOP_BOTTOM_POSITION = "上下";
var ID_RES_STRING_LEFT_RIGHT_POSITION = "左右";

var ID_RES_STRING_SELECTED_REPORT = "选中的报告";
var ID_RES_STRING_SELECTED_DOC = "选中的文件";

var ID_RES_STRING_MERGE_SAME_ITEM = "合并同类项目";
var ID_RES_STRING_MERGE_IN_ORDER = "按顺序粘贴";

var ID_RES_STRING_MERGE_REPORT_WARNING = "※ 仅搜索使用ONEFFICE编写的报告。<br />&nbsp&nbsp&nbsp请单击所需的项目<span style='color:#ED7D31'><u>后</u></span>进行选择。";
var ID_RES_STRING_REPORT_SEARCH_DATE = "日期";
var ID_RES_STRING_REPORT_SEARCH_TITLE = "标题";

var ID_RES_STRING_TODAY = "今天";
var ID_RES_STRING_LAST_WEEK = "最近1周";

var ID_RES_STRING_MY_TEMPLATE_1 = "我的模板1";
var ID_RES_STRING_MY_TEMPLATE_2 = "我的模板2";
var ID_RES_STRING_MY_TEMPLATE_3 = "我的模板3";
var ID_RES_STRING_MY_TEMPLATE_4 = "我的模板4";
var ID_RES_STRING_MY_TEMPLATE_5 = "我的模板5";

//파일 이동이나 복사 시 텍스트 추가.
var ID_RES_STRING_COPY_SUBJECT_TEXT = "（副本）";

var ID_RES_STRING_HIDDEN_LINE = "隐藏线条";

var ID_RES_STRING_LAYOUT_TABLE = "创建布局格式";

var ID_RES_STRING_SUBTITLE = "副标题";
var ID_RES_STRING_BODY = "正文";
var ID_RES_STRING_VIDEO = "视频";
var ID_RES_STRING_DATE = "日期";

var ID_RES_STRING_ENTER_TITLE = "请输入标题。";
var ID_RES_STRING_ENTER_SUBTITLE = "请输入副标题。";
var ID_RES_STRING_ENTER_CONTENT = "请输入内容。";

var ID_RES_STRING_INSERT_IMG_AFTER_CLICK = "双击插入图片";
var ID_RES_STRING_INSERT_VIDEO_AFTER_CLICK = "双击插入视频";

var ID_RES_STRING_LIMT_CHAR_COUNT = "字数限制";

var ID_RES_STRING_EDIT_TIMER_ALERT = "长时间不动，已切换为只读模式。<br/>若要继续编辑，请单击确认键。";
var ID_RES_STRING_EDIT_TIMER_ALERT_READ = "长时间不动，已切换为只读模式。<br/>若要重新编辑，请刷新。";
var ID_RES_STRING_EDIT_TIMER_ALERT_READ2 = "长时间不动，已切换为只读模式。";
var ID_RES_STRING_EDIT_USER_CHECK = "不存在正在编辑的用户。<br/>点击确认，即可切换为编辑模式。";

var ID_RES_CONST_STRING_SECURITY = "安全";

var ID_RES_CONST_STRING_SET_PASSWORD = "设置密码";

var ID_RES_CONST_STRING_NOTI_DELETED_FOLDER = "已删除{0}个文件夹。";
var ID_RES_CONST_STRING_NOTI_DELETED_FOLDER_FILE = "已删除{0}个文件夹和文件。";

var ID_RES_CONST_STRING_INVALID_IMG_URL = "是无效的图片URL。\n*可用文件：";

var ID_RES_STRING_DOCUMENT_NAME = "文件标题";
var ID_RES_STRING_GO_TO_HOME = "移动至ONEFFICE 主页";

var ID_RES_STRING_DOCUMENT_RENAMED = "文件标题已更改。";
var ID_RES_STRING_DOCUMENT_RENAMED_FAIL = "文件标题更改失败。";

var ID_RES_STRING_SETTING = "设置";
var ID_RES_STRING_MINUTES = "分钟";
var ID_RES_STRING_NOT_USED = "不使用";
var ID_RES_STRING_RIBBON_MENU = "RIBBON菜单";
var ID_RES_STRING_TOOLBAR_MENU = "TOOLBAR菜单";

var ID_RES_STRING_GET_NEWS_LIST = "获取报道链接";
var ID_RES_STRING_POST_NEWS = "报道登记";
var ID_RES_STRING_GET_CLOUD_IMAGE = "图片云";
var ID_RES_STRING_POST_IMAGE = "图片注册";
var ID_RES_STRING_SET_IMAGE_INFO = "设置图片信息";
var ID_RES_CONST_STRING_DEFAULT_ARTICLE_NAME = "新报道";

var ID_RES_STRING_PLACEHOLDER_NEWS_TITLE = "请输入报道的标题。（100字）";
var ID_RES_STRING_PLACEHOLDER_NEWS_SUBTITLE = "请输入报道的副标题。（150字）";

var ID_RES_STRING_VOC = "客户咨询";
var ID_RES_STRING_SEND = "发送";
var ID_RES_STRING_VOC_PLACEHOLDER = "请填写要咨询的内容。";
var ID_RES_STRING_VOC_SEND_COMPLETE = "咨询已受理。";

var ID_RES_STRING_INSERT_TAB = "制表键输入";

var ID_RES_STRING_DEFAULT = "基本";
var ID_RES_STRING_EMPHASIS1 = "强调1";
var ID_RES_STRING_EMPHASIS2 = "强调2";
var ID_RES_STRING_EMPHASIS3 = "强调3";
var ID_RES_STRING_BOX1 = "框1";
var ID_RES_STRING_BOX2 = "框2";
var ID_RES_STRING_BOX3 = "框3";
var ID_RES_STRING_QUOTATION = "引用句";
var ID_RES_STRING_FIRST_LETTER_BIG = "首字符放大";
var ID_RES_STRING_REMOVE_FORMAT = "清除格式";
var ID_RES_STRING_SUBTITLE1 = "小标题1";
var ID_RES_STRING_SUBTITLE2 = "小标题2";

var ID_RES_STRING_NO_MYINFO = "因没有权限使用受到限制。\r\n单击“确认”即可关闭窗口。";

var ID_RES_STRING_INSERT_FORM_CONTROL = "Control插入";
var ID_RES_STRING_FORM_TAG_RADIO = "音频";

var ID_RES_STRING_CHECK_ALL_CORONA = "请填写所有居家办公确认列表。";

var ID_RES_STRING_CORONA_PC_CONFIG = "居家办公PC环境设置指南";
var ID_RES_STRING_CORONA_SOFTWARE = "居家办公解决方案应用指南";
var ID_RES_STRING_CORONA_WORK_PROCESS = "居家办公流程指南";
var ID_RES_STRING_CORONA_SECURITY = "居家办公安全检查指南";

var ID_RES_STRING_ALL = "全部";
var ID_RES_STRING_OUTER = "外侧";
var ID_RES_STRING_INNER = "内侧";

var ID_RES_STRING_FIND_END = "无匹配项。";

var ID_RES_STRING_TEMP_SAVED = "已临时保存。";
var ID_RES_STRING_MOD_SAVED = "修改内容已保存。";

var ID_RES_STRING_SAVED_GO_REPORT = "内容已更新。\n将移至业务报告页面。";
var ID_RES_STRING_FAIL_SAVE_REPORT = "报告保存失败。";
var ID_RES_STRING_FAIL_GET_REPORT = "报告查询失败。";
var ID_RES_STRING_FAIL_GET_REPORT_LIST = "报告列表查询失败。";
var ID_RES_STRING_FAIL_SAVE_FOR_NO_REPORT = "目标报告信息不存在，无法保存。";
var ID_RES_STRING_TRY_AGAIN_AFTER_CLOSE_WIN = "请关闭当前窗口后重试。";

var ID_RES_STRING_SHOW_CONTENT = "查看原文";
var ID_RES_STRING_SHOW_CONTENT_AT_NEW_WIN = "在新窗口中查看原始报告";

var ID_RES_STRING_SELECT_REPORT = "请选择报告。";
var ID_RES_STRING_MERGE_END = "已合并。";

var ID_RES_STRING_TITLE_EDIT_HEADER = "双击编辑页眉";
var ID_RES_STRING_TITLE_EDIT_FOOTER = "双击编辑页脚";

var ID_RES_STRING_RECENT_DELETE = "Recent Delete";
var ID_RES_STRING_RECENT_DELETE_FAIL = "Failed to remove the list of recent items.";

var ID_RES_CONST_STRING_FILELIST_NO_SEARCH = "搜索结果不存在。";
var ID_RES_STRING_SELECTED_REPORT_NODATA = "No Report Selected";
var ID_RES_STRING_SELECTED_DOC_NODATA = "没有选定文件。";

var ID_RES_STRING_SECURITY_DOC_CANNOT_SEND_REPORT = "安全文件无法作为业务报告发送。";

var ID_RES_STRING_NO_BACKUP_AND_RECOVER = "Backup and restore functions are not supported in read mode.";

var ID_RES_CONST_STRING_SHOW_NUMPAGES = "整页显示";
var ID_RES_CONST_STRING_NUMPAGES = "整页";

var ID_RES_CONST_STRING_ADD_TASK_SCHEDULE = "添加主要日程/主要业务";
var ID_RES_CONST_STRING_DELETE_TASK_SCHEDULE = "删除主要日程/主要业务";

var ID_RES_STRING_AUTO_SAVE_CYCLE = "自动存储周期";

var ID_RES_CONST_STRING_HOUR = "hour";
var ID_RES_CONST_STRING_MINUTE = "minute";
var ID_RES_CONST_LEGEND = "Legend";

var ID_RES_STRING_ALERT_CHANGE_LANGUAGE = "ONEFFICE显示语言已更改为{0}。";
var ID_RES_STRING_LANGUAGE_KO = "日语";
var ID_RES_STRING_LANGUAGE_EN = "英语";
var ID_RES_STRING_LANGUAGE_JA = "日语";
var ID_RES_STRING_LANGUAGE_CN = "中文";

var ID_RES_STRING_MY_GROUP = "我的组";

var ID_RES_CONST_STRING_PAGE_NUMBER_BOX_MSG = "Please enter the page number";

var ID_RES_CONST_STRING_TABLE_INSERT = "创建表";
var ID_RES_STRING_LETTER = "信件";

var ID_RES_STRING_INSERT_IMG = "插入图片";
var ID_RES_STRING_INSERT_VIDEO = "插入影片";

/* WE000028862 */ var ID_RES_STRING_LAYOUT_TABLE_LIMIT_ROW = "布局表格不能超过一页";

/* WE000028863 */ var ID_RES_STRING_SELECT_MULTI_ROW = "请选择多行";
/* WE000028864 */ var ID_RES_STRING_SELECT_MULTI_COL = "请选择多列";

var ID_RES_CONST_STRING_RETURN_TO_ORIGIN_DOC = "Original document";
var ID_RES_CONST_STRING_EXTERNAL_BOX = "External box";

var ID_RES_STRING_CURRENT_LIST_STYLE = "Current List";
//NewsEditor
var ID_RES_CONST_STRING_INSERT_IMAGE2 = "图像"; 
var ID_RES_PROP_INSERT_IMAGE2 = "图像属性"; 
var ID_RES_PROP_TAG_STRING_IMAGE2 = "图像";
var ID_RES_PROP_TAG_STRING_USER_IMAGE2 = "使用图片";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE2 = "图像文件";
var ID_RES_CONST_STRING_IMAGE_REPLACE2 = "替换图像";
var ID_RES_CONST_STRING_IMAGE_SAVEAS2 = "另存为图像";
var ID_RES_CONST_STRING_DELETE_IMAGE2 = "删除图像";

var ID_RES_DIALOG_STRING_URL_INPUT_YOUTUBE = "YouTube";
var ID_RES_DIALOG_STRING_URL_INPUT_NAVERTV = "NaverTV";
var ID_RES_DIALOG_STRING_URL_INPUT_KAKAOTV = "KakaoTV";

var ID_RES_STRING_SET_LIST_START_NEW = "List Start New";
var ID_RES_STRING_SET_LIST_START_CONTINUE = "List Start Continue";

var ID_RES_CONST_STRING_BROWSER_NEWSROOM = "Article Room";
var ID_RES_CONST_STRING_BROWSER_MYNEWS_LIST = "My Article";
var ID_RES_CONST_STRING_BROWSER_SEND_MYNEWS_LIST = "Registred Article";//
var ID_RES_CONST_STRING_POST_MYNEWS = "Registred";//

var ID_RES_STRING_NEWS_IMAGE_INFO = "Article Image Infomation";
var ID_RES_STRING_CAPTION = "Caption";
var ID_RES_STRING_REPLACE_TEXT = "Replace Text";
var ID_RES_STRING_LINK_URL = "URL";
var ID_RES_STRING_SET_MAIN_IMAGE = "Main Image";

var ID_RES_STRING_NEWS_SEND_INFO = "Post Setting";
var ID_RES_CONST_STRING_NEWS_JOURNALIST_INFO = "Journalist";
var ID_RES_CONST_STRING_NEWS_CLASSIFY_INFO = "Article Category";
var ID_RES_CONST_STRING_NEWS_GRADE_INFO = "Article Grade";
var ID_RES_CONST_STRING_NEWS_JOURNALIST_SEND_INFO = "Registred Jounralist";
var ID_RES_CONST_STRING_NEWS_TITLE_INFO = "Subject / SubTitle";
var ID_RES_CONST_STRING_NEWS_TAG_INFO = "Tag";
var ID_RES_CONST_STRING_NEWS_NAVER_CATEGORY_INFO = "Naver Category";

var ID_RES_STRING_ETC_MEMO = "Memo";
var ID_RES_STRING_ETC_TODO = "Todo";

var ID_RES_STRING_ETC_MEMO_INPUT_PLEASE = "Input Memo";
var ID_RES_STRING_ETC_TODO_INPUT_PLEASE = "Input Todo";

var ID_RES_STRING_WEBSEARCH_IMG_DBCLICK = "Double click on the image to insert it into the body.";

var ID_RES_CONST_STRING_NO_DATA_MEMO = "No Memo";
var ID_RES_CONST_STRING_NO_DATA_TODO = "No Todo";
var ID_RES_STRING_UPDATE_POSTED_NEWS = "Article Update";