/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// resource.js -	다국어 지원용 resource 모음(JAPAN)
//					
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// 전체 적용되는 리소스 선언
var ID_RES_GLOBAL_DEFAULT_FONT_FAMILY = "Arial";
var ID_RES_GLOBAL_FONT_FAMILY_TYPE_1 = "Arial";

// ComboBox Size Layer(comboboxwin) 리소스 선언
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_8 = "あいうえ ABCD";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_24 = "あいう ABC";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_36 = "あい AB";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_MAX = "あい";
var ID_RES_COOMBOBOX_FONT_NAME_0 = "arial";
var ID_RES_COOMBOBOX_FONT_NAME_1 = "tahoma";
var ID_RES_COOMBOBOX_FONT_NAME_2 = "times new roman";
var ID_RES_COOMBOBOX_FONT_NAME_3 = "verdana";			//10
var ID_RES_COOMBOBOX_FONT_NAME_4 = "comic sans ms";
var ID_RES_COOMBOBOX_FONT_NAME_5 = "courier new";
var ID_RES_COOMBOBOX_FONT_NAME_6 = "";
var ID_RES_COOMBOBOX_FONT_NAME_7 = "";
var ID_RES_COOMBOBOX_FONT_NAME_8 = "";
var ID_RES_COOMBOBOX_FONT_NAME_9 = "";
var ID_RES_COOMBOBOX_FONT_NAME_10 = "";

// 글관련 서식 제거 문구 선언
var ID_RES_COMBOBOX_REMOVE_FONT_FAMILY = "基本";
var ID_RES_COMBOBOX_REMOVE_FONT_SIZE = "基本";
var ID_RES_COMBOBOX_REMOVE_LETTER_SPACING = "基本";		//20
var ID_RES_COMBOBOX_REMOVE_LINE_HEIGHT = "基本";

// 에디터 문자상수(initconst) 리소스 선언
var ID_RES_CONST_STRING_BOLD = "太字";
var ID_RES_CONST_STRING_ITALIC = "斜体";
var ID_RES_CONST_STRING_UNDERLINE = "下線";
var ID_RES_CONST_STRING_JUSTIFYLEFT = "左揃え";
var ID_RES_CONST_STRING_JUSTIFYCENTER = "中央揃え";
var ID_RES_CONST_STRING_JUSTIFYRIGHT = "右揃え";
var ID_RES_CONST_STRING_JUSTIFYJUSTIFY = "両側揃え";
var ID_RES_CONST_STRING_ORDERLIST = "番号付きリスト";
var ID_RES_CONST_STRING_UNORDERLIST = "記号付きリスト";	//30
var ID_RES_CONST_STRING_STRIKE = "取り消し線";
var ID_RES_CONST_STRING_SUBSCRIPT = "下付き文字";
var ID_RES_CONST_STRING_SUPERSCRIPT = "上付き文字";
var ID_RES_CONST_STRING_OUTDENT = "アウトデント";
var ID_RES_CONST_STRING_INDENT = "インデント";
var ID_RES_CONST_STRING_UNDO = "取り消し";
var ID_RES_CONST_STRING_REDO = "やり直し";
var ID_RES_CONST_STRING_FONT_NAME = "フォント";
var ID_RES_CONST_STRING_FONT_SIZE = "サイズ";
var ID_RES_CONST_STRING_FORE_COLOR = "前景色";			//40
var ID_RES_CONST_STRING_BACK_COLOR = "背景色";
var ID_RES_CONST_STRING_TABLE_CREATE = "表の生成";
var ID_RES_CONST_STRING_TABLE_ADD_ROW = "行の追加(Up)";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_DOWN = "行の追加(Down)";
var ID_RES_CONST_STRING_TABLE_COPY_ROW_DOWN = "行の追加(Copy)";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW = "行の削除";
var ID_RES_CONST_STRING_TABLE_ADD_COL = "列の追加(Left)";
var ID_RES_CONST_STRING_TABLE_ADD_COL_RIGHT = "列の追加(Right)";
var ID_RES_CONST_STRING_TABLE_DELETE_COL = "列の削除";
var ID_RES_CONST_STRING_TABLE_MERGE_CELL = "セルの結合";	//50
var ID_RES_CONST_STRING_TABLE_SPLIT_ROW = "行の分割";
var ID_RES_CONST_STRING_TABLE_SPLIT_COL = "列の分割";
var ID_RES_CONST_STRING_TABLE_SELECT = "選択";

var ID_RES_CONST_STRING_IMAGE_INSERT = "イメージ挿入/属性";
var ID_RES_CONST_STRING_FLASH_INSERT = "フラッシュ挿入/属性";
var ID_RES_CONST_STRING_MEDIA_INSERT = "動画挿入/属性";
var ID_RES_CONST_STRING_FULLSCREEN = "全画面";
var ID_RES_CONST_STRING_TABLE_CELL_PROPERTY = "セル属性";
var ID_RES_CONST_STRING_TABLE_PROPERTY = "テーブル属性";
var ID_RES_CONST_STRING_MARK_INSERT = "特殊文字挿入";						//60
var ID_RES_CONST_STRING_TABLE_TEMPLETE_INSERT = "表の生成（テンプレート)";


var ID_RES_CONST_STRING_ADJUST_HWP_BASIC = "HWP調整";
var ID_RES_CONST_STRING_ADJUST_DOC_BASIC = "Ｗord調整";
var ID_RES_CONST_STRING_HORIZONTAL_RULE = "水平線挿入";
var ID_RES_CONST_STRING_LETTER_SPACING = "文字間隔";
var ID_RES_CONST_STRING_LINE_HEIGHT = "行間隔";
var ID_RES_CONST_STRING_BODY_BG_COLOR = "文書の背景色";
var ID_RES_CONST_STRING_BODY_BG_IMAGE = "文書の背景イメージ";
var ID_RES_CONST_STRING_DOC_TEMPLETE = "編集ブロック挿入";
var ID_RES_CONST_STRING_PREVIEW = "プレビュー";								//70
var ID_RES_CONST_STRING_HIDE_MINIBAR = "ミニバー隠す";
var ID_RES_CONST_STRING_WRITE_AREA_SET = "編集領域の設定";
var ID_RES_CONST_STRING_SHOW_EDITABLE_AREA = "編集領域の表示";
var ID_RES_CONST_STRING_SAVEAS = "Download";
var ID_RES_CONST_STRING_PRINT = "出力";
var ID_RES_CONST_STRING_Z_INDEX_SETTING = "z-Indexの設定";
var ID_RES_CONST_STRING_TEXT_BOX = "テキストボックス";
var ID_RES_CONST_STRING_OBJECT_POSITION = "オブジェクトPosition設定";
var ID_RES_CONST_STRING_RESPONSIVE_WIDTH = "反応型の大きさ確認";
var ID_RES_CONST_STRING_DOC_LAYOUT = "レイアウト設定";							//80
var ID_RES_CONST_STRING_HEADING_SIZE = "スタイル";
var ID_RES_CONST_STRING_RESPONSIVE_SET = "反応型一括設定";
var ID_RES_CONST_STRING_FORM_TABLE = "表の編集ブロック";
var ID_RES_CONST_STRING_DRAW_TABLE = "表の作成";


//파일 메뉴 
var ID_RES_CONST_STRING_FILE_NEW				= "新規作成";
var ID_RES_CONST_STRING_FILE_OPEN				= "ファイルを開く";
var ID_RES_CONST_STRING_FILE_DOCFORM			= "書式様式";
var ID_RES_CONST_STRING_FILE_LAYOUT				= "レイアウト";

//편집 메뉴 
var ID_RES_CONST_STRING_CUT						= "カット";
var ID_RES_CONST_STRING_COPY					= "コピー";					//90
var ID_RES_CONST_STRING_PASTE					= "ペースト";
var ID_RES_CONST_STRING_EDIT_PASTESPECIAL		= "選んでつける";
var ID_RES_CONST_STRING_SELECT_ALL				= "すべて選択";
var ID_RES_CONST_STRING_EDIT_SEARCH				= "検索";
var ID_RES_CONST_STRING_EDIT_REPLACE			= "変換";
var ID_RES_CONST_STRING_REPLACE_CASE			= "大文字/小文字 を変更する";

//보기 메뉴 
var ID_RES_CONST_STRING_VIEW_EDIT				= "編集窓";
var ID_RES_CONST_STRING_VIEW_HTML				= "ソース窓";

//삽입 메뉴 
var ID_RES_CONST_STRING_INSERT_IMAGE			= "イメージ";				//100
var ID_RES_CONST_STRING_INSERT_OBJECT			= "エンティティ";
var ID_RES_CONST_STRING_INSERT_SPECIALCHARS		= "特殊文字挿入";
var ID_RES_CONST_STRING_INSERT_BOOKMARK			= "ブックマーク";
var ID_RES_CONST_STRING_INSERT_EMOTICONS		= "絵文字";
var ID_RES_CONST_STRING_HYPERLINK_INSERT		= "ハイパーリンク";
var ID_RES_CONST_STRING_HYPERLINK_MODIFY		= "ハイパーリンクの設定";
var ID_RES_CONST_STRING_HYPERLINK_REMOVE		= "ハイパーリンクの削除";

//서식 메뉴 
var ID_RES_CONST_STRING_STYLE_FONT				= "文字スタイル";
var ID_RES_CONST_STRING_STYLE_PARAGRAPH			= "段落スタイル";
var ID_RES_CONST_STRING_STYLE_STYLE				= "スタイル";					//110
var ID_RES_CONST_STRING_STYLE_UNORDEREDLIST		= "記号付きリスト";
var ID_RES_CONST_STRING_STYLE_ORDEREDLIST		= "番号付きリスト";
var ID_RES_CONST_STRING_STYLE_INCREASEORDER		= "レベル上げる";
var ID_RES_CONST_STRING_STYLE_DECREASEORDER		= "レベル下げる";

//표 메뉴 
var ID_RES_CONST_STRING_TABLE_CELL_STYLE		= "セルの枠 & 背景";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_COL		= "行/間追加";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL	= "行/間削除";
var ID_RES_CONST_STRING_TABLE_SPLIT_CELL		= "セル分割";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT	= "セルの高さを同じに";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH	= "セルの幅を同じに";				//120
var ID_RES_CONST_STRING_TABLE_CELL_ALIGN		= "セル整列";
var ID_RES_CONST_STRING_TABLE_MADANG			= "表庭";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "計算式";
var ID_RES_CONST_STRING_TABLE_NUMBER_FORMAT		= "1,000単位の区分読点";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICALALIGN	= "セル縦整列";

var ID_RES_CONST_STRING_TABLE_BLOCK_FORMULA		= "ブロック計算式";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "計算式";
var ID_RES_CONST_STRING_TABLE_SELECT_FORMULA	= "選択計算式";
var ID_RES_CONST_STRING_TABLE_EASY_FORMULA	= "簡単な計算式";

//도움말
var ID_RES_CONST_STRING_HELP_SHORTCUTS = "ショートカット";					//130
var ID_RES_CONST_STRING_HELP = "ヘルプ";
var ID_RES_CONST_STRING_PRODUCT_INFO = "バージョン情報";


//2depth 메뉴
var ID_RES_CONST_STRING_INSERT_OBJECT_MOVIE = "動画挿入";
var ID_RES_CONST_STRING_INSERT_OBJECT_FILE = "ファイル";
var ID_RES_CONST_STRING_INSERT_OBJECT_HR = "水平線挿入";

var ID_RES_CONST_STRING_STYLE_STYLE_BASIC = "基本";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT1 = "タイトル1";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT2 = "タイトル2";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT3 = "タイトル3";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT4 = "タイトル4";						//140
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT5 = "タイトル5";

var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_TOP = "上揃え";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_MIDDLE = "中央揃え";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_BOTTOM = "下に揃え";

var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTALALIGN	= "セルの横整列";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_LEFT = "左揃え";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_CENTER = "中央揃え";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_RIGHT = "右揃え";

var ID_RES_CONST_STRING_TABLE_BLOCK_SUM = "ブロック合計";
var ID_RES_CONST_STRING_TABLE_BLOCK_AVG = "ブロックの平均";							//150
var ID_RES_CONST_STRING_TABLE_BLOCK_MUL = "ブロック掛け";

var ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM = "横合計";
var ID_RES_CONST_STRING_TABLE_VERTICAL_SUM = "縦合計";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE = "横平均";
var ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE = "縦平均";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY = "横掛け";
var ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY = "縦掛け";

var ID_RES_CONST_STRING_TABLE_ADD_NUMBER_FORMAT = "定位点挿入";
var ID_RES_CONST_STRING_TABLE_REMOVE_NUMBER_FORMAT = "定位点削除";


//-- 툴바에만 존재하는 버튼
var ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE = "フォントサイズ大きく";				//160
var ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE = "フォントサイズ小さく";

// 폼태그 버튼
var ID_RES_CONST_STRING_FORM_TAG_SWITCH = "フォームコントロールの選択転換";
var ID_RES_CONST_STRING_FORM_TAG_CHECKBOX = "選択ボックス";
var ID_RES_CONST_STRING_FORM_TAG_SELECT = "リストボックス";

// 양식 템플릿
var ID_RES_CONST_STRING_TEMPLETE_FORM = "様式テンプレート";

// 빈문단삽입
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_STARTPOINT = "スタートラインに文壇挿入";
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_ENDPOINT = "最後のところに文壇挿入";

// 표 삭제
var ID_RES_CONST_STRING_TABLE_DELETE_TABLE = "テーブル 消す";

// 삽입 - 문단
var ID_RES_CONST_STRING_INSERT_PARAGRAPH = "文段";

// 서식 - 글자모양 - 보통모양 버튼 텍스트
var ID_RES_CONST_STRING_NORMAL = "普通の形";									//170

//표 - 표 텍스트로 변환
var ID_RES_CONST_STRING_TABLE_CONVERT_TEXT = "表をテキストに変換";

// 테이블생성 Layer(tablesize) 리소스 선언
var ID_RES_TABLE_SIZE_SELECT = "選択";
var ID_RES_TABLE_SIZE_CANCEL = "取り消し";

// 툴빌더(toolbuilder) 리소스 선언
var ID_RES_TOOL_STRING_MENU_FILE = "ファイル";
var ID_RES_TOOL_STRING_MENU_EDIT = "編集";
var ID_RES_TOOL_STRING_MENU_VIEW = "表示";
var ID_RES_TOOL_STRING_MENU_INSERT = "挿入";
var ID_RES_TOOL_STRING_MENU_BASIC = "書式";
var ID_RES_TOOL_STRING_MENU_TABLE = "表";
var ID_RES_TOOL_STRING_MENU_HELP = "ヘルプ";								//180
var ID_RES_TOOL_STRING_TAB_PREVIEW = "プレビュー";
var ID_RES_TOOL_STRING_TAB_EDIT = "編集窓";
var ID_RES_TOOL_STRING_TAB_SOURCE = "ソース窓";

// 사용자메세지(usermsg) 리소스 선언
var ID_RES_USER_MSG_STRING_ALERT_CUT = "ブラウザのセキュリティ設定では実行できません\nCtrl+X を押すと実行できます";
var ID_RES_USER_MSG_STRING_ALERT_COPY = "ブラウザのセキュリティ設定では実行できません\nCtrl+C を押すと実行できます";
var ID_RES_USER_MSG_STRING_ALERT_PASTE = "ブラウザのセキュリティ設定では実行できません\nCtrl+V を押すと実行できます";
var ID_RES_USER_MSG_STRING_WARNING_SCRIPT = "ソースコード上にスクリプトは含めません\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_MEDIA = "動画像挿入はIE6,7,8のみ支援されます\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_IFRAME = "ソースコード上にiframeタグは含められません\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_SOURCE_EDIT = "フォームのユーザーモードではソースウィンドウは使用できません\n";	//190
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_2 = "firefox は3バージョン以上から支援されます\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_EDIT = "firefox 編集モードの設定上,支援されません\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_SUPPORT_FORM_MODE = "コード検査は様式管理者又は使用者モードでは支援されません\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_ATTIRIBUTE_CHARACTER = "属性値で＜,＞,＆,\',\"などは使用できません\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_COLOR_CODE = "유효한 색상코드를 입력하셔야 합니다.\n 예) #0099ff\n";
//var ID_RES_USER_MSG_STRING_WARNING_IN_CONTROL_KEY_NO_SOURCE_EDIT = "키보드 제어용에서는 소스창을 사용할 수 없습니다";

// 문서보정(leftviewui) 리소스 선언
var ID_RES_ADJUST_VIEW_CLOSE = "閉じる";

// 편집창 Title 리소스 선언
var ID_RES_EDIT_TITLE_STRING = "文章入力部分";

var ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY = "適用";

// 양식 저작(Form Table) 리소스 선언
var ID_RES_PROP_FORM_WIN_TITLE = "様式レイアウト";
var ID_RES_PROP_TAG_SELECT_WIN_TITLE = "リストボックス";
var ID_RES_PROP_MAPPING_CODE_WIN_TITLE = "様式コード";
var ID_RES_PROP_MAPPING_CSS_WIN_TITLE = "様式CSS設定";
var ID_RES_PROP_TEMPLETE_FORM_WIN_TITLE = "様式テンプレート";

// 컨텍스트 메뉴
var ID_RES_PROP_INSERT_IMAGE = "イメージ 属性";
var ID_RES_PROP_INSERT_FILE = "ファイル付け属性";

var ID_RES_DIALOG_BTN_OK = "確認";
var ID_RES_DIALOG_BTN_CANCEL = "取消";
var ID_RES_DIALOG_BTN_NOCOLOR = "色ない";										//210
var ID_RES_DIALOG_TAB_GENERAL = "一般";
var ID_RES_DIALOG_TAB_BORDER = "枠";
var ID_RES_DIALOG_TAB_BACKGROUND = "背景";
var ID_RES_DIALOG_FORM_LIST1 = "サンプル項目1";
var ID_RES_DIALOG_FORM_LIST2 = "サンプル項目2";
var ID_RES_DIALOG_FORM_LIST3 = "サンプル項目3";
var ID_RES_DIALOG_MAPPINGCODE_TAB1 = "電子決裁様式";
var ID_RES_DIALOG_MAPPINGCODE_TAB2 = "公文書様式";
var ID_RES_DIALOG_CONFIRM_SAVE = "<p>作成中の内容があります。</p><p>保存しますか?</p>";
var ID_RES_DIALOG_CONFIRM_YES = "はい";										//220
var ID_RES_DIALOG_CONFIRM_NO = "いいえ";
var ID_RES_DIALOG_CONFIRM_EMPTY_DOC = "文書が空いています。 ご確認ください。";
var ID_RES_DIALOG_ALERT_SELECTFILE = "ファイルを選択してください。";
var ID_RES_DIALOG_CONFIRM_FILE_DELETE_CONTENT = "ファイルを呼び込むと、作成中の内容が削除されます。\nファイルを呼び込みますか?";
var ID_RES_DIALOG_ALERT_ALLOWFILES = "ファイルはアップロードできません。\nアップロード可能ファイル";
var ID_RES_DIALOG_ALERT_SELECTIMAGE = "イメージファイルを選択した後、アップロードボタンをクリックしてください。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_IMAGE = "正常なイメージを挿入してください。";
var ID_RES_DIALOG_ALERT_FIND_INPUT_TEXT = "探す内容を入力してください。";
var ID_RES_DIALOG_ALERT_FIND_ERROR = "検索中にエラーが発生しました。";
var ID_RES_DIALOG_ALERT_FIND_NOTHING = "該当内容を見つけられませんでした。";					//230
var ID_RES_DIALOG_CONFIRM_FIND_END = "文書の最後まで見つけました。\n文書を最初からずっと検索しますか。";
var ID_RES_DIALOG_CONFIRM_FIND_FIRST = "文書の最初まで見つけました。\n文書の最後までずっと検索しますか。";
var ID_RES_DIALOG_ALERT_REPLACE_INPUT_TEXT = "変更する内容を入力してください。";
var ID_RES_DIALOG_ALERT_REPLACE_ERROR = "変更進行中エラーが発生しました。";
var ID_RES_DIALOG_ALERT_REPLACEALL_COMPLETE = "すべて変更が完了しました。";
var ID_RES_DIALOG_ALERT_REPLACE_N = "個の項目が変更されました。";
var ID_RES_DIALOG_TITLE_FIND_REPLACE = "検索/変換";
var ID_RES_DIALOG_BTN_REPLACEALL = "全て変換";
var ID_RES_DIALOG_BTN_FIND_NEXT = "検索";
var ID_RES_DIALOG_TITLE_EXT_MOVIE = "外部動画";								//240
var ID_RES_DIALOG_TITLE_FILE_INSERT = "ファイル";
var ID_RES_DIALOG_BTN_INSERT = "挿入";
var ID_RES_DIALOG_TITLE_WEBEDITOR_INFO = "DOUZONE ONEFFICE 情報";

var ID_RES_DIALOG_LIST_TITLE_FORM_AREA = "様式領域";
var ID_RES_DIALOG_LIST_TITLE_FORM_SELECT = "様式の選択";
var ID_RES_DIALOG_ALERT_SELECT_DOCFORM = "書式の様式を選択してください。";
var ID_RES_DIALOG_CONFIRM_DOCFORM_DELETE_CONTENT = "書式様式を挿入すると、編集中の文書の内容が削除されます。\n挿入しますか。";
var ID_RES_DIALOG_ALERT_SELECT_LAYOUT_DESIGN = "レイアウトデザインを選択してください。";
var ID_RES_DIALOG_CONFIRM_LAYOUT_DELETE_CONTENT = "レアアウトを挿入すると、編集中の文書の内容が削除されます。\n挿入しますか。";

var ID_RES_DIALOG_STRING_FILE_PATH = "ファイルパス";						//250
var ID_RES_DIALOG_STRING_URL_INPUT = "挿入URL";	
var ID_RES_DIALOG_STRING_UPLOAD = "アップロード";
var ID_RES_DIALOG_STRING_SIZE = "サイズ";
var ID_RES_DIALOG_STRING_WIDTH = "幅";
var ID_RES_DIALOG_STRING_HEIGHT = "高さ";
var ID_RES_DIALOG_STRING_KEEP_RATIO = "比率維持";
var ID_RES_DIALOG_STRING_SET_ORG = "元のサイズを維持";
var ID_RES_DIALOG_STRING_MARGIN = "余白";
var ID_RES_DIALOG_STRING_MARGIN_LEFT = "左余白";
var ID_RES_DIALOG_STRING_MARGIN_TOP = "上余白";								//260
var ID_RES_DIALOG_STRING_MARGIN_RIGHT = "右余白";
var ID_RES_DIALOG_STRING_MARGIN_BOTTOM = "下余白";
var ID_RES_DIALOG_STRING_ALIGN_BASIC = "既定";
var ID_RES_DIALOG_STRING_ALIGN_LEFT = "左揃え";
var ID_RES_DIALOG_STRING_ALIGN_CENTER = "中央揃え";
var ID_RES_DIALOG_STRING_ALIGN_RIGHT = "右揃え";
var ID_RES_DIALOG_ALERT_MAX_VALUE = "最大値から外れました。\n最大値 : ";
var ID_RES_DIALOG_ALERT_MIN_VALUE = "最小値から外れました。\n最小値 : ";
var ID_RES_DIALOG_ALERT_NUMBER_ONLY = "数字のみ入力できます。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_URL = "イメージURLをもう一度確認してください!";	//270
var ID_RES_DIALOG_ALERT_UPLOAD_ERROR = "アップロードしているうちにエラーが発生しました。 もう一度試してください。";
var ID_RES_DIALOG_ALERT_INSERT_IMAGE = "イメージを先に登録してください。";
var ID_RES_DIALOG_STRING_NO_STYLE_TEXT = "書式のないテキスト";
var ID_RES_DIALOG_STRING_HTML_STYLE_TEXT = "HTML 形式";
var ID_RES_DIALOG_STRING_FIND_TEXT = "探す内容";
var ID_RES_DIALOG_STRING_REPLACE_TEXT = "変換内容";
var ID_RES_DIALOG_STRING_FIND_OPTION = "検索オップション";
var ID_RES_DIALOG_STRING_CASESENSITIVE = "大/小文字区分";
var ID_RES_DIALOG_STRING_COMPLETEWORD = "単語単位で";
var ID_RES_DIALOG_STRING_IGNORESPACE = "分かち書き無視";							//280
var ID_RES_DIALOG_STRING_FIND_DERECTION = "検索方向";
var ID_RES_DIALOG_STRING_FIND_DOWN = "下で";
var ID_RES_DIALOG_STRING_FIND_UP = "上に";
var ID_RES_DIALOG_STRING_INPUT_SOURCE = "ソース入力";
var ID_RES_DIALOG_STRING_MOVIE_INPUT_GUIDE = "objectまたはiframeソースコード入力してください。";
var ID_RES_DIALOG_STRING_INPUT_MOVIE_SOURCE = "動画ソースを入力してください。";
var ID_RES_DIALOG_STRING_VIEW_TEXT = "表示するテキスト";
var ID_RES_DIALOG_ALERT_ALLOW_FORMAT = "フォーマットのみ提供します。";
var ID_RES_DIALOG_STRING_CHARACTER_AREA = "文字領域";
var ID_RES_DIALOG_STRING_CHARACTER_SELECT = "文字選択";						//290
var ID_RES_DIALOG_STRING_RECECT_USE_CHARACTER = "最近に使用した文字";

var ID_RES_DIALOG_ALERT_SELECT_CHARACTER = "文字を選択してください。";
var ID_RES_CONST_STRING_CHARACTER_GENERAL = "一般/記号";
var ID_RES_CONST_STRING_CHARACTER_ENG_NUMBER = "英語/数字";
var ID_RES_CONST_STRING_CHARACTER_GREEK = "ギリシャ語";
var ID_RES_CONST_STRING_CHARACTER_LINE = "線文字";
var ID_RES_CONST_STRING_CHARACTER_UNIT = "単位記号";
var ID_RES_CONST_STRING_CHARACTER_CIRCLE = "円文字";
var ID_RES_CONST_STRING_CHARACTER_BRAKETCHAR = "括弧文字";
var ID_RES_CONST_STRING_CHARACTER_FRACTION_SCRIPT = "分数/添字";				//300
var ID_RES_CONST_STRING_CHARACTER_ARROW = "矢印";
var ID_RES_CONST_STRING_CHARACTER_BRAKET = "括弧";
var ID_RES_CONST_STRING_CHARACTER_MATH = "数学演算";
var ID_RES_CONST_STRING_CHARACTER_PUNCTUATION_MARKS = "文章符号";
var ID_RES_CONST_STRING_CHARACTER_CURRENCY = "通貨記号";

var ID_RES_DIALOG_STRING_BOOKMARK_NAME = "ブックマーク名";
var ID_RES_DIALOG_STRING_BOOKMARK_LIST = "ブックマークリスト";
var ID_RES_DIALOG_STRING_MOVE = "移動";
var ID_RES_DIALOG_STRING_BOOKMARK_SORT_STANDARD = "ブックマーク整列基準";
var ID_RES_DIALOG_STRING_NAME = "名前";										//310
var ID_RES_DIALOG_STRING_POSITION = "位置";
var ID_RES_DIALOG_ALERT_INPUT_BOOKMARK_NAME = "しおりの名前を入力してください";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_DELTE_BOOKMARK_ITEM = "ブックマークリストから削除する項目を選択してください";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_MOVE_BOOKMARK_ITEM = "ブックマークリストで移動する項目を選択してください";

var ID_RES_DIALOG_STRING_LINK_TYPE = "リンク種類";
var ID_RES_DIALOG_STRING_WEB_ADDR = "ウェブアドレス";
var ID_RES_DIALOG_STRING_LINK_TARGET = "連結文書を開く";
var ID_RES_DIALOG_STRING_LINK_CURRENT_WINDOW = "同じウインドー";
var ID_RES_DIALOG_STRING_LINK_NEW_WINDOW = "新しいウィンドウに";
var ID_RES_DIALOG_STRING_LINK_NO_CONNECT = "連結しない";							//320
var ID_RES_DIALOG_STRING_LIST_SELECT = "選択";
var ID_RES_DIALOG_ALERT_SELECT_BOOKMARK = "ブックマークを選択してください";
var ID_RES_DIALOG_ALERT_INPUT_WEB_ADDR = "ウェブアドレスを入力してください";

var ID_RES_DIALOG_STRING_LETTERSPACING = "子癇";
var ID_RES_DIALOG_STRING_BASIC = "基本";
var ID_RES_DIALOG_STRING_PROPERTY = "属性";
var ID_RES_DIALOG_STRING_FONT_STYLE_PREVIEW = "あいうABCabc123※○";

var ID_RES_DIALOG_STRING_ALIGN_TYPE = "整列方式";
var ID_RES_DIALOG_STRING_NORMAL = "普通";
var ID_RES_DIALOG_STRING_SPACING = "間隔";									//330
var ID_RES_DIALOG_STRING_LINEHEIGHT = "行間隔";
var ID_RES_DIALOG_STRING_PARAGRAPH_TOP = "文壇の上";
var ID_RES_DIALOG_STRING_PARAGRAPH_BOTTOM = "文壇の下";
var ID_RES_DIALOG_STRING_FIRST_PARAGRAPH = "最初の行";

var ID_RES_DIALOG_STRING_NONE = "なし";
var ID_RES_DIALOG_STRING_VERSION = "バージョン";


var ID_RES_DIALOG_STRING_FORM_BASE_SIZE = "基準の大きさと高さ";
var ID_RES_DIALOG_STRING_FORM_HEIGHT_MSG = "高さ設定は<br/>様式生成際に反映される";
var ID_RES_DIALOG_STRING_FORM_OUTLINE = "外角線";
var ID_RES_DIALOG_STRING_FORM_TYPE = "タイプ";									//340
var ID_RES_DIALOG_STRING_FORM_COLOR = "色";
var ID_RES_DIALOG_STRING_FORM_MULTI_SELECT = "多重選択:<br/>&nbsp;&nbsp;Ctrlキー+オブジェクト選択";
var ID_RES_DIALOG_STRING_FORM_MULTI_OTHER_SELECT = "多重選択:<br/>&nbsp;&nbsp;オブジェクトの選択->shiftキー-><br/>&nbsp;&nbsp;他のオブジェクト選択";
var ID_RES_DIALOG_STRING_FORM_COPY_PASTE = "コピペ:<br/>&nbsp;&nbsp;オブジェクトを選択した後、Ctrlキー+V";
var ID_RES_DIALOG_STRING_FORM_COPY_MOVE = "移動:<br/>&nbsp;&nbsp;、上下左右の矢印キー";
var ID_RES_DIALOG_STRING_FORM_RESIZE = "大きさの調整:<br/>&nbsp;&nbsp;Ctrlキー+矢印キー";
var ID_RES_DIALOG_STRING_FORM_PRE_APPLY = "先に適用";
var ID_RES_DIALOG_ALERT_FORM_SIZE = "大きさ(width)単位が%である場合のみを提供しています。";

var ID_RES_PROP_TAG_STRING_ROW_NUM = "行数";
var ID_RES_PROP_TAG_STRING_COL_NUM = "列数";									//350
var ID_RES_PROP_TAG_STRING_ROW_COL = "行/セル";
var ID_RES_PROP_TAG_STRING_SIZE_DEFINE = "大きさ指定";
var ID_RES_PROP_TAG_STRING_WIDTH_UNIT = "幅単位";
var ID_RES_PROP_TAG_STRING_ALL_CELL_INNER_MARGIN = "すべてのセルの奥の余白";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN = "整列";

var ID_RES_PROP_TAG_STRING_FILL = "満たす";									//360
var ID_RES_PROP_TAG_STRING_NO_COLOR_FILL = "色を満たすなし";
var ID_RES_PROP_TAG_STRING_COLOR = "色";
var ID_RES_PROP_TAG_STRING_FACE_COLOR = "面色";

var ID_RES_PROP_TAG_STRING_IMAGE = "イメージ";
var ID_RES_PROP_TAG_STRING_USER_IMAGE = "イメージ使用";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE = "イメージファイル";
var ID_RES_PROP_TAG_STRING_FILL_TYPE = "満たすスタイル";
var ID_RES_PROP_TAG_STRING_REPEAT = "繰り返し";
var ID_RES_PROP_TAG_STRING_REPEAT_HOR = "横繰り返し";
var ID_RES_PROP_TAG_STRING_REPEAT_VER = "縦繰り返し";						//370
var ID_RES_PROP_TAG_STRING_REPEAT_NO = "繰り返しなし";

var ID_RES_PROP_TAG_LIST_NUM = "リスト数";
var ID_RES_PROP_TAG_LIST_CONTENT = "リスト内容";

var ID_RES_PROP_TAG_ADD_ROW = "行追加";
var ID_RES_PROP_TAG_UP = "アップ";
var ID_RES_PROP_TAG_DOWN = "ダウン";
var ID_RES_PROP_TAG_ADD_COL = "列の追加";

var ID_RES_PROP_TAG_SET_INNER_MARGIN = "奥の余白指定";

var ID_RES_PROP_TAG_STRING_LEFT = "左揃え";
var ID_RES_PROP_TAG_STRING_TOP = "アップ";									//380
var ID_RES_PROP_TAG_STRING_RIGHT = "右揃え";
var ID_RES_PROP_TAG_STRING_BOTTOM = "ダウン";
var ID_RES_PROP_TAG_STRING_CENTER = "中";

var ID_RES_PROP_TAG_STRING_ALIGN_HOR = "水平揃え";
var ID_RES_PROP_TAG_STRING_ALIGN_VER = "高さ 指定";
var ID_RES_PROP_TAG_STRING_ALIGN_TOP = "上揃え";
var ID_RES_PROP_TAG_STRING_ALIGN_MIDDLE = "中央揃え";
var ID_RES_PROP_TAG_STRING_ALIGN_BOTTOM = "下に揃え";

var ID_RES_PROP_TAG_STRING_APPLY_RANGE= "適用範囲";
var ID_RES_PROP_TAG_STRING_SELECTED_CELL = "選択されたセル";
var ID_RES_PROP_TAG_STRING_ALL_CELL = "すべてのセル";								//390

var ID_RES_PROP_TAG_STRING_SELECT_CELL_EDITOR = "適用するセルを編集画面で選択してください。";
var ID_RES_PROP_TAG_STRING_NO_CALC_SELECTED_CELL = "計算不可能な項目が選択されました。";
var ID_RES_PROP_TAG_STRING_SELECT_CELL = "セル選択";
var ID_RES_PROP_TAG_STRING_CALC_TYPE = "計算方法";
var ID_RES_PROP_TAG_STRING_CALC_SUM = "合計";
var ID_RES_PROP_TAG_STRING_CALC_AVG = "平均";
var ID_RES_PROP_TAG_STRING_CALC_MUL = "掛け";
var ID_RES_PROP_TAG_STRING_CALC_RESULT = "計算結果";
var ID_RES_PROP_TAG_STRING_SPLIT_ROW_COL = "行/間区分";						//400

var ID_RES_PROP_TEMPLETE_STRING_FORM_SUBJECT = "様式のタイトル";
var ID_RES_PROP_TEMPLETE_STRING_SUBJECT = "タイトル";
var ID_RES_PROP_TEMPLETE_STRING_SIZE_ITEM_SET = "大きさ/項目の設定";
var ID_RES_PROP_TEMPLETE_STRING_AUTO = "自動";
var ID_RES_PROP_ALERT_ONLY_NUMBER_CALC = "数字のみ計算が可能です。";

var ID_RES_DIALOG_SHORTCUTS_TITLE = "ショートカット";
var ID_RES_DIALOG_SHORTCUTS_MENU_PATH = "メニュー経路";
var ID_RES_DIALOG_SHORTCUTS_FUNCTION = "機能";
var ID_RES_DIALOG_SHORTCUTS_BASIC = "基本ホットキー";
var ID_RES_DIALOG_SHORTCUTS_SPACE = "空欄挿入";								//410
var ID_RES_DIALOG_SHORTCUTS_ENTER = "文壇の分け合い";
var ID_RES_DIALOG_SHORTCUTS_LEFT = "一字左に";
var ID_RES_DIALOG_SHORTCUTS_RIGHT = "一字右に";
var ID_RES_DIALOG_SHORTCUTS_DOWN = "一行下に";
var ID_RES_DIALOG_SHORTCUTS_UP = "一行の上に";
var ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD = "一単語の右に";
var ID_RES_DIALOG_SHORTCUTS_LEFT_WORD = "一単語の左に";
var ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH = "一段落の下に";
var ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH = "一段落の上に";
var ID_RES_DIALOG_SHORTCUTS_HOME = "最初の行に";								//420
var ID_RES_DIALOG_SHORTCUTS_END = "最後の行に";
var ID_RES_DIALOG_SHORTCUTS_HOME_PAGE = "最初の画面に";
var ID_RES_DIALOG_SHORTCUTS_END_PAGE = "最後の画面に";
var ID_RES_DIALOG_SHORTCUTS_DELETE = "最後の文字を削除";
var ID_RES_DIALOG_SHORTCUTS_BACKSPACE = "頭文字を削除";
var ID_RES_DIALOG_SHORTCUTS_DELETE_WORD = "一単語を削除";
var ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD = "前の単語を削除";

var ID_RES_DIALOG_SHORTCUTS_FILE = "ファイルメニュー";
var ID_RES_DIALOG_SHORTCUTS_EDIT = "編集メニュー";
var ID_RES_DIALOG_SHORTCUTS_INSERT = "挿入メニュー";								//430
var ID_RES_DIALOG_SHORTCUTS_STYLE = "書式メニュー";
var ID_RES_DIALOG_SHORTCUTS_TABLE = "表メニュー";

var ID_RES_CONST_STRING_CLEAR = "オフ";

var ID_RES_CONST_STRING_INCREASE_LETTERSPACING = "子癇広く";
var ID_RES_CONST_STRING_DECREASE_LETTERSPACING = "子癇狭く";

var ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT = "左側の余白増やす";
var ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT = "左側の余白減らす";
var ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT = "右側の余白増やす";
var ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT = "右側の余白減らす";

var ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT = "最初の行アウトデント";				//440
var ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT = "最初の行インデント";

var ID_RES_CONST_STRING_INCREASE_LINEHEIGHT = "行間隔広く";
var ID_RES_CONST_STRING_DECREASE_LINEHEIGHT = "行間隔狭く";

var ID_RES_CONST_STRING_SELECT_CURRENT_CELL = "現在セル選択";
var ID_RES_CONST_STRING_MOVE_CELL_UNIT = "セル単位にカーソル移動";
var ID_RES_CONST_STRING_MOVE_NEXT_CELL = "表中で他のセルに移動(前進)";
var ID_RES_CONST_STRING_MOVE_PREV_CELL = "表中で他のセルに移動(逆方向)";

var ID_RES_CONST_STRING_BLOCK_ALL_COL = "間全体ブロック";
var ID_RES_CONST_STRING_BLOCK_ALL_ROW = "行全体ブロック";
var ID_RES_CONST_STRING_MULTI_CELL_SELECT = "多重セル選択時";					//450
var ID_RES_CONST_STRING_ARROW_KEY = "カーソルキー";

var ID_RES_CONST_STRING_STANDARD = "標準";
var ID_RES_CONST_STRING_USER_DEFINE = "カスタム";
var ID_RES_CONST_STRING_USER_SET = "カスタム";
var ID_RES_CONST_STRING_REPLACE_CASE_CAPITAL = "すべて大文字に変更する";
var ID_RES_CONST_STRING_REPLACE_CASE_SMALL = "すべて小文字に変更";
var ID_RES_CONST_STRING_REPLACE_CASE_REVERSE = "大文字・小文字変換";
var ID_RES_CONST_STRING_REPLACE_CASE_LETTER = "単語の先頭文字を大文字に";
var ID_RES_CONST_STRING_REPLACE_CASE_SENTENCE = "文章の最初の文字を大文字に";
var ID_RES_CONST_STRING_REPLACE_CASE_PARAGRAPH = "文壇の最初の文字を大文字に";			//460
var ID_RES_CONST_BTN_DELETE = "削除します";
var ID_RES_CONST_INSERT_IMAGE_PARAGRAPH_ALIGN = "本文整列";

var ID_RES_CONST_STRING_NEW_COLOR = "新しい色";
var ID_RES_CONST_STRING_CURRENT_COLOR = "現在色";
var ID_RES_CONST_STRING_OTHER_COLOR = "他の色";
var ID_RES_CONST_STRING_RECENT_COLOR = "最近使用した色";
var ID_RES_CONST_STRING_ADD_USER_COLOR = "ユーザーが指定した色に追加";
var ID_RES_CONST_STRING_RED = "赤";
var ID_RES_CONST_STRING_GREEN = "緑";
var ID_RES_CONST_STRING_BLUE = "青色";										//470
var ID_RES_CONST_STRING_HUE = "色";
var ID_RES_CONST_STRING_SATURATION = "彩度";
var ID_RES_CONST_STRING_LIGHTNESS = "明度";

var ID_RES_CONST_MSG_ALERT_NO_RECENT_COLOR = "最近使用した色がありません。";
var ID_RES_CONST_MSG_ALERT_DELETE_RECENT_COLOR = "最近使用した色をすべて削除しますか。";

var ID_RED_CONST_STRING_ALIGN_LEFT_TOP		= "左上";
var ID_RED_CONST_STRING_ALIGN_LEFT_MIDDLE	= "左の中間";
var ID_RED_CONST_STRING_ALIGN_LEFT_BOTTOM	= "左下";
var ID_RED_CONST_STRING_ALIGN_CENTER_TOP	= "上側の中央";
var ID_RED_CONST_STRING_ALIGN_CENTER_MIDDLE = "真ん中";						//480
var ID_RED_CONST_STRING_ALIGN_CENTER_BOTTOM = "下方の中央";
var ID_RED_CONST_STRING_ALIGN_RIGHT_TOP		= "右上";
var ID_RED_CONST_STRING_ALIGN_RIGHT_MIDDLE	= "右の中間";
var ID_RED_CONST_STRING_ALIGN_RIGHT_BOTTOM	= "右下";
var ID_RED_CONST_STRING_TABLE_CELL_BACKCOLOR	= "セル背景色";

var ID_RES_CONST_STRING_COLOR_STANDARD = "標準色";
var ID_RES_CONST_STRING_COLOR_THEME = "テーマ色";

var ID_RES_CONST_STRING_EMOTICONS_FEEL = "感情";
var ID_RES_CONST_STRING_EMOTICONS_ACTION = "行動";
var ID_RES_CONST_STRING_EMOTICONS_ETC = "その他の";								//490
var ID_RES_DIALOG_STRING_CATEGORY_AREA = "分類";
var ID_RES_DIALOG_STRING_EMOTICON_SELECT = "顔文字選択";
var ID_RES_DIALOG_STRING_RECECT_USE_EMOTICONS = "最近に使用した顔文字";

var ID_RES_UI_TOGGLE_STRING_RIBBON = "リボンメニュースタイル";
var ID_RES_UI_TOGGLE_STRING_TOOLBAR = "ツールバーのメニュースタイル";
var ID_RES_CONST_STRING_PRINT_PAGE_BREAK = "印刷ページの分割";
var ID_RES_CONST_STRING_VIEW_RULERBAR = "ルーラー表示";
var ID_RES_DIALOG_STRING_CASCADE_ORDERLIST = "多段階リスト";
var ID_RES_CONST_STRING_COPY_EXT_STYLE = "書式コピー";

var ID_RES_CONST_STRING_BORDER_TYPE = "枠タイプ";					//500
var ID_RES_CONST_STRING_BORDER_THICKNESS = "枠の厚さ";
var ID_RES_CONST_STRING_BORDER_COLOR = "枠の色";
var ID_RES_CONST_STRING_RESET_PICTURE = "イメージを元に戻す";

var ID_RES_CONST_STRING_NO_LINE = "線無し";
var ID_RES_CONST_STRING_SOLID_LINE = "実線";
var ID_RES_CONST_STRING_DASHED_LINE = "波線";
var ID_RES_CONST_STRING_DOTTED_LINE = "点線";
var ID_RES_CONST_STRING_DOUBLE_LINE = "二重線";

var ID_RES_CONST_STRING_TABLE_SELECT_CELL = "セル選択";
var ID_RES_CONST_STRING_TABLE_SELECT_COL = "列選択";				//510
var ID_RES_CONST_STRING_TABLE_SELECT_ROW = "行選択";
var ID_RES_CONST_STRING_TABLE_SELECT_TABLE = "表選択";

var ID_RES_CONST_STRING_IMAGE_TO_TABLE = "フォームボット";
var ID_RES_DIALOG_ALERT_SELECT_TABLE_STYLE = "スタイルを選択してください。";

var ID_RES_CONST_STRING_TEXTBOX = "テキストボックス";

var ID_RES_CONST_TAB_COLOR_AND_BORDER = "色と線";
var ID_RES_DIALOG_BTN_MODIFY = "修正";
var ID_RES_CONST_TEXTATT = "フォント";
var ID_RES_CONST_TEXTATT_STYLE = "フォントスタイル";
var ID_RES_CONST_VERTICAL_ALIGN = "縦整列";

var ID_RES_CONST_STRING_INNER_MARGIN = "内側の余白";
var ID_RES_CONST_STRING_OUTER_MARGIN = "外側の余白";
var ID_RES_CONST_STRING_LINE = "線";
var ID_RES_CONST_STRING_LINE_WIDTH = "厚さ";
var ID_RES_CONST_STRING_LINE_STYLE = "種類";

var ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO = "正常な動画を挿入してください。";
var ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO_EMPTY = "업로드할 동영상을 선택해주세요.";
var ID_RES_CONST_STRING_WEB_SEARCH = "ウェブ検索";
var ID_RES_CONST_STRING_NO_SEARCH_RESULT = "検索結果がありません。";
var ID_RES_CONST_STRING_INPUT_SEARCH_KEYWORD = "検索キーワードを入力してください。";
var ID_RES_CONST_STRING_CONV_KOREAN = "日英変換";
var ID_RED_CONST_STRING_ENCYCLOPEDIA = "百科事典";
var ID_RED_CONST_STRING_IMAGE = "画像";
var ID_RED_CONST_STRING_NEWS = "ニュース";
var ID_RED_CONST_STRING_VIEW_MORE = "もっと見る";
var ID_RED_CONST_STRING_SEARCHING = "検索中";
var ID_RES_CONST_STRING_HIGHLIGHTER = "蛍光ペン";
var ID_RES_CONST_ALERT_HIGHLIGHTER_MODE = "ESCキーを押すと、蛍光ペンモードが解除されます。";
var ID_RES_CONST_TABLE_CELL_PASTE = "コピーしたセルを貼り付け";
var ID_RES_CONST_ALERTTABLE_CELL_PASTE_MODE = "ESCキーを押すと、コピーしたセルの貼り付けが解除されます。";

var ID_RES_PROP_INSERT_VIDEO = "ビデオのプロパティ";
var ID_RES_PROP_TEXTBOX_CONTENTS = "内容";
var ID_RES_CONST_STRING_SAVEAS_REMOTE = "コピーを作成";
var ID_RES_CONST_STRING_SAVE_REMOTE = "保存する";

var ID_RES_CONST_STRING_NEW_DOCUMENT = "新しいドキュメント";
var ID_RES_CONST_STRING_NEW_FOLDER = "新しいフォルダ";
var ID_RES_CONST_STRING_OPEN_DOCUMENT = "開く";
var ID_RES_CONST_STRING_SET_FAVORITE_ON = "重要表示";
var ID_RES_CONST_STRING_SET_FAVORITE_OFF = "重要マークを解除";
var ID_RES_CONST_STRING_RENAME = "名前の変更";
var ID_RES_CONST_STRING_COPY = "コピー";
var ID_RES_CONST_STRING_SET_READONLY_ON = "読み取り専用に設定";
var ID_RES_CONST_STRING_SET_READONLY_OFF = "読み取り専用を解除";
var ID_RES_CONST_STRING_CLEAR_TRASHBOX = "ゴミ箱を空にする";
var ID_RES_CONST_STRING_RESTORE = "復元";
var ID_RES_CONST_STRING_DELETE_COMPLETE = "完全に削除";
var ID_RES_CONST_STRING_SHARE_DOCUMENT = "共有";
var ID_RES_CONST_STRING_UNSHARE_DOCUMENT = "共有解除";

var ID_RES_CONST_STRING_PLEASE_INPUT_FOLDER_NAME = "フォルダ名を入力してください。";
var ID_RES_CONST_STRING_PLEASE_INPUT_RENAME = "変更する名前を入力してください。";
var ID_RES_CONST_STRING_CONFIRM_DELETE_DOCUMENT = "{0}'文書を削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_FOLDER = "フォルダを削除すると、内部のファイルもすべて削除されます。<br/>削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_SELECTED_DOCUMENT = "{0}個の文書を削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_SELECTED_FOLDER_FILE = "フォルダを削除すると、内部の文書もすべて削除されます。<br/>選択された項目を削除しますか？";
var ID_RES_CONST_STRING_NOTI_DELETED_DOCUMENT = "{0}個の文書を削除しました。";
var ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT = "削除されたか、権限が変更された文書です。";
var ID_RES_CONST_STRING_WARNING_FILE_DUPLICATE = "同じ名前のフォルダ/文書が存在します。別の名前を入力してください。";
var ID_RES_CONST_STRING_WARNING_CANNOT_MOVE_SELECTED_FOLDER = "選択されたフォルダに移動できません。";

var ID_RES_CONST_STRING_PRINT_MARGIN_SETTING = "ページの余白設定";
var ID_RES_CONST_STRING_PRINT_MARGIN_NARROW = "狭く";
var ID_RES_CONST_STRING_PRINT_MARGIN_NORMAL = "普通";
var ID_RES_CONST_STRING_PRINT_MARGIN_WIDE = "広く";

var ID_RES_CONST_STRING_BROWSER_MY = "マイドキュメント";
var ID_RES_CONST_STRING_BROWSER_RECENT = "ONEFFICE HOME";
var ID_RES_CONST_STRING_BROWSER_SHARE = "共有文書ボックス";
var ID_RES_CONST_STRING_BROWSER_FAVORITE = "重要文書ボックス";
var ID_RES_CONST_STRING_BROWSER_TRASHBOX = "ゴミ箱";
var ID_RES_CONST_STRING_BROWSER_SEARCH_RESULT = "計{0}個の検索結果";

var ID_RES_CONST_STRING_PAPER = "用紙";
var ID_RES_CONST_STRING_PAGE_SETUP = "ページ設定";
var ID_RES_CONST_STRING_PAPER_ORIENTATION_SERO = "縦";
var ID_RES_CONST_STRING_PAPER_ORIENTATION_GARO = "横";

var ID_RES_CONST_STRING_NOTI_COPIED_DOCUMENT = "文書を{0}にコピーしました。";
var ID_RES_CONST_STRING_NOTI_MOVED_DOCUMENT = "{0}文書を{1}に移動しました。";
var ID_RES_CONST_STRING_NOTI_MOVED_DOCUMENT_LIST = "{0}個の文書を移動しました。";
var ID_RES_CONST_STRING_NOTI_SHARE_DOCUMENT = "{0}文書が共有されました。";
var ID_RES_CONST_STRING_NOTI_UNSHARE_DOCUMENT = "{0}文書の共有が解除されました。";
var ID_RES_CONST_STRING_NOTI_UNSHARE_MULTI_DOCUMENT = "{0}個の文書の共有が解除されました。";

var ID_RES_CONST_STRING_TEXTBOX_FILL_COLOR = "塗りつぶし色";
var ID_RES_CONST_STRING_TEXTBOX_BORDER_COLOR = "枠の色";

var ID_RES_CONST_STRING_INSERT_CHART = "チャート";
var ID_RES_CONST_STRING_NOTI_DELETE_CONFIRM = "本当に削除しますか？";
var ID_RES_CONST_STRING_COMPLETE_DELETE_CONFIRM = "永久削除時に削除されたファイルは復元することはできません。<br>完全に削除しますか？";

var ID_RES_CONST_STRING_PAGE_DELETE_CONFIRM = "ページの内容も削除されます。<br>ページを削除しますか？";

var ID_RES_CONST_STRING_GROUP_CHART = "組織図";
var ID_RES_CONST_STRING_PAGE_SETTING = "ページ設定";
var ID_RES_CONST_STRING_PASTE_CELL = "セルの貼り付けオプション";
var ID_RES_CONST_STRING_PASTE_CELL_INSERT = "新しい行に挿入";
var ID_RES_CONST_STRING_PASTE_CELL_OVER_ALL = "セルの上書き";
var ID_RES_CONST_STRING_PASTE_CELL_OVER_CONTENT = "内容の貼り付け";

var ID_RES_CONST_STRING_SHARE_LINK_COPY = "リンクをコピー";
var ID_RES_CONST_STRING_CONVERT_ELE_TO_IMG = "キャンバス";

var ID_RES_CONST_STRING_BROWSER_MY_SHARE_LIST = "共有した文書";
var ID_RES_CONST_STRING_BROWSER_SHARED_BY_LIST = "共有された文書";

var ID_RES_CONST_STRING_SHARE_PERMISSION_VIEW = "リンクのあるすべてのユーザーは閲覧可能";
var ID_RES_CONST_STRING_SHARE_PERMISSION_EDIT = "リンクのあるすべてのユーザーは編集可能";

var ID_RES_UI_TOGGLE_STRING_MENUSTYLE = "メニューのタイプ";
var ID_RES_CONST_STRING_WARNING_INVALID_DOCUMENT_CALL = "不適切な文書のリンクです。";

var ID_RES_CONST_STRING_NOTI_MOVED_LIST_FAIL = "{0}個の文書の移動に失敗しました。";
var ID_RES_CONST_STRING_NOTI_COPIED_LIST_FAIL = "文書のコピーに失敗しました。";
var ID_RES_CONST_STRING_NOTI_DELETE_FAIL_DOCUMENT_LIST = "{0}個の文書の削除に失敗しました。";

var ID_RES_CONST_STRING_CONFIRM_DELETE_SHARE_DOCUMENT = "共有文書です。\n{0}個の文書を削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_SHARE_DOCUMENT = "共有文書が含まれています。\n{0}個の文書を削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_IMPORTANT_DOCUMENT = "重要文書です。\n{0}個の文書を削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_IMPORTANT_DOCUMENT = "重要文書が含まれています。\n{0}個の文書を削除しますか？";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_SHARE_IMPORTANT_DOCUMENT = "重要文書と共有文書が含まれています。\n{0}個の文書を削除しますか？";

var ID_RES_CONST_STRING_GO_TO_MOVILE_VIEWER = "モバイルビューアに移動します。";
var ID_RES_CONST_STRING_INVALID_CALL = "不適切な呼び出しです。";
var ID_RES_CONST_STRING_SAVED = "保存されました。";
var ID_RES_CONST_STRING_AUTO_SAVED = "自動保存されました。";
var ID_RES_CONST_STRING_MOVE_TO_PARENT_FOLDER = "上位フォルダへ移動";
var ID_RES_CONST_STRING_DISABLE_POPUP_BLOCKER = "ポップアップブロックを解除してください。";
var ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT = "権限がないか、存在しない文書です。";
var ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT_2 = "権限がないか<br/>存在しない文書です。";
var ID_RES_CONST_STRING_DELETE_CONTAINS_IMPORTANT_DOCUMENT = "削除された文書は閲覧できません。";
var ID_RES_CONST_STRING_DELETE_CONTAINS_IMPORTANT_FOLDER = "削除されたフォルダは閲覧できません。";

var ID_RES_CONST_STRING_RECENT_NO_SHARE_DOCUMENT = "共有権限が解除されたため、閲覧できません。";

var ID_RES_CONST_STRING_READ_ONLY = "読み取り専用";
var ID_RES_CONST_STRING_OPENED_READ_ONLY = "読み取り専用で開きました。";
var ID_RES_CONST_STRING_OPENED_READ_ONLY_DOCUMENT = "読み取り専用で開いた文書です。";
var ID_RES_CONST_STRING_SET_READ_ONLY = "読み取り専用に設定されました。";
var ID_RES_CONST_STRING_SET_EDITABLE = "読み取り専用が解除されました。";
var ID_RES_CONST_STRING_CHANGED_TO_READ_ONLY = "読み取り専用に変更されました。";

var ID_RES_CONST_STRING_ENTER_SUBJECT = "タイトルを入力してください。";

var ID_RES_CONST_STRING_RECOVERED = "復旧されました。";
var ID_RES_CONST_STRING_RECOVERED_ALL = "すべて復旧されました。";
var ID_RES_CONST_STRING_RECOVERY_FAILED = "復旧に失敗しました。";
var ID_RES_CONST_STRING_FULL_RECOVERY_FAILED = "全体復旧に失敗しました。";
var ID_RES_CONST_STRING_SOME_RECOVERY_FAILED = "一部復旧に失敗しました。";

var ID_RES_CONST_STRING_DELETED = "削除されました。";
var ID_RES_CONST_STRING_DELETED_ALL = "すべて削除されました。";
var ID_RES_CONST_STRING_DELETE_ALL_FAIL = "全体削除に失敗しました。";
var ID_RES_CONST_STRING_DELETE_SOME_FAIL = "一部削除に失敗しました。";
var ID_RES_CONST_STRING_TRASH_IS_EMPTY = "ごみ箱を空にしました。";
var ID_RES_CONST_STRING_SAVING_DATA = "データを保存しています。";

var ID_RES_CONST_STRING_SELECT_IS_EMPTY = "最近表示した文書がありません。";
var ID_RES_CONST_STRING_SELECT_IS_EMPTY_NEWDOC = "+新規作成";
var ID_RES_CONST_STRING_SELECT_IS_EMPTY_TEMPLATE_MSG = "またはテンプレートで文書を作成してください。";

var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_SET_UP = "重要文書に設定されました。";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_NOT_SET_UP = "重要文書から解除されました。";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_SET = "重要文書（設定済み）";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_NOT_SET = "重要文書（解除済み）";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_CAN_SET_BY_OWNER = "重要文書の設定は、文書の所有者のみ可能です。";

var ID_RES_CONST_STRING_ENTENR_ID = "IDを入力してください！";
var ID_RES_CONST_STRING_LOGIN_FAIL_ENTER_CORRETLY = "ログインに失敗しました。正確に入力してください！";
var ID_RES_CONST_STRING_LAST_MODIFIED_DATE = "最終更新日";
var ID_RES_CONST_STRING_LAST_READ_DATE = "最終アクセス日";
var ID_RES_CONST_STRING_SHAREBY_DATE = "共有された日";
var ID_RES_CONST_STRING_SHARETO_DATE = "共有した日";
var ID_RES_CONST_STRING_SHARE_DATE = "共有日";
var ID_RES_CONST_STRING_FILE_SIZE = "ファイルサイズ";
var ID_RES_CONST_STRING_OWNER = "所有者";
var ID_RES_CONST_STRING_DELETED_DOCUMENT = "削除された文書";
var ID_RES_CONST_STRING_COMMING_SOON = "準備中です。";
var ID_RES_CONST_STRING_USAGE = "使用量";
var ID_RES_CONST_STRING_SHARED_DOCUMENT = "共有文書";
var ID_RES_CONST_STRING_COPIED = "コピーされました。";
var ID_RES_CONST_STRING_FOLDER_LOCATION = "フォルダの場所";
var ID_RES_CONST_STRING_CUSTOM_SHARE = "カスタム共有";
var ID_RES_CONST_STRING_CLOSE_CUSTOM_SHARE = "カスタム共有を閉じる";
var ID_RES_CONST_STRING_USER_SELECTION = "ユーザー選択";
var ID_RES_CONST_STRING_ADD_MESSAGE = "メッセージを追加";
var ID_RES_CONST_STRING_VIEWABLE = "表示可能";
var ID_RES_CONST_STRING_EDITABLE = "編集可能";
var ID_RES_CONST_STRING_NOT_MODIFIED = "更新された内容がありません。";
var ID_RES_CONST_STRING_NO_CELL_COPIED = "コピーしたセルがありません。";
var ID_RES_CONST_STRING_DOCUMENT_TITLE = "文書タイトル";
var ID_RES_CONST_STRING_SAVE_PATH = "保存パス";

var ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE = "ファイルはアップロードできないファイルです。\n*使用可能なファイル:";
var ID_RES_CONST_STRING_ALIGN = "カスタム";
var ID_RES_CONST_STRING_HORIZONTAL_WIDTH = "横幅";
var ID_RES_CONST_STRING_VERTICAL_HEIGHT = "縦の高さ";

var ID_RES_CONST_STRING_KEEP_ORG_HEIGHT = "原本の高さを維持";
var ID_RES_CONST_STRING_NEW_BLOCK_REFERENCE_HEIGHT = "新規ブロックは<br />基準の高さに設定";
var ID_RES_CONST_STRING_PAPER_ORIENTATION = "用紙の向き";
var ID_RES_CONST_STRING_PAPER_COLOR = "背景色";

var ID_RES_CONST_STRING_PAGE = "ページ";
var ID_RES_CONST_STRING_FIRST_PAGE = "最初のページです。";
var ID_RES_CONST_STRING_LAST_PAGE = "最後のページです。";
var ID_RES_CONST_STRING_NEXT = "次";
var ID_RES_CONST_STRING_PREV = "前";
var ID_RES_CONST_STRING_VIEW_SHOW = "ショーを見る";

var ID_RES_CONST_STRING_CELL_CONTENTS_COPIED = "セルの内容がコピーされました。";
var ID_RES_CONST_STRING_CANNOT_INSERT_CELL_SHAPE_DIFFERENT = "コピーしたセルと対象セルの形が違うため、挿入できません。";
var ID_RES_CONST_STRING_CLICK_INSERT_POSITION = "挿入する場所をクリックしてください！";
var ID_RES_CONST_STRING_CANCLED_INSERT_CHART = "チャート挿入がキャンセルされました。";
var ID_RES_CONST_STRING_CHART_TYPE = "チャートタイプ";
var ID_RES_CONST_STRING_AXIS_TRANSFORMATION = "軸変換";
var ID_RES_CONST_STRING_TRANSFORMATION = "変換";

var ID_RES_CONST_STRING_SLIDE_SHOW = "スライドショー";
var ID_RES_CONST_STRING_ZOOM_OUT = "縮小";
var ID_RES_CONST_STRING_ZOOM_IN = "元に戻す";
var ID_RES_CONST_STRING_SLIDE_SHOW_EXIT = "ショー終了";
var ID_RES_CONST_STRING_BACKGROUND_COLOR = "背景色";
var ID_RES_CONST_STRING_CANNOT_READ_DOCUMENT_FORMAT = "フォーム文書のフォーマットを表現できません。";
var ID_RES_CONST_STRING_LOSE_ALL_CONTINUE = "作成済みの内容は初期化されます。<br/>続行しますか？";
var ID_RES_CONST_STRING_READ_ONLY_DOCUMENT = "読み込み専用文書";

var ID_RES_CONST_STRING_ENTER_DETAIL = "内容を入力してください。";

var ID_RES_CONST_STRING_DOCUMENT_SECURITY = "ドキュメントセキュリティ";
var ID_RES_CONST_STRING_SECURITY_DOCUMENTS = "セキュリティ文書";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_SETTING = "文書のセキュリティ設定";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_RESET = "文書のセキュリティの変更解除";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_SETTING_NOTE = "注意:\nパスワードを忘れると文書を復旧できません。\nパスワードは大文字と小文字を区別し、4文字以上20文字以下で入力可能です。";
var ID_RES_CONST_STRING_DOCUMENT_PASSWORD = "文書のパスワード";
var ID_RES_CONST_STRING_DOCUMENT_NEW_PASSWORD = "新しいパスワード";
var ID_RES_CONST_STRING_PASSWORD_CONFIRMATION = "パスワードの確認";
var ID_RES_CONST_STRING_NOTI_CONFIRMATION_PASSWORD_ERROR = "確認パスワードが一致しません。";
var ID_RES_CONST_STRING_NOTI_CHECK_PASSWORD_ERROR = "現在のパスワードが設定されたパスワードと一致しません。";
var ID_RES_CONST_STRING_NOTI_DUPLICATE_PASSWORD_ERROR = "新しいパスワードが現在のパスワードと同じです。";
var ID_RES_CONST_STRING_NOTI_PASSWORD_LENGTH_ERROR = "パスワードは4文字以上10文字以下で入力できます。 もう一度入力してください。";
var ID_RES_CONST_STRING_NOTI_WRONG_PASSWORD_ERROR = "パスワードが正しくありません。\Caps";
var ID_RES_CONST_STRING_INPUT_PASSWORD = "パスワードを入力してください。";
var ID_RES_CONST_STRING_CHANGE_PASSWORD = "パスワード変更";
var ID_RES_CONST_STRING_UNSET_PASSWORD = "パスワード解除";

var ID_RES_CONST_STRING_IMAGE_REPLACE = "画像の変更";
var ID_RES_CONST_STRING_IMAGE_SAVEAS = "画像で保存";
var ID_RES_CONST_STRING_ONEFFICE_CONNECT = "ワンピースコネクト";
var ID_RES_CONST_STRING_DOC_OPEN = "読み込み";
var ID_RES_CONST_STRING_IMAGE_CROPPER = "画像のトリミング";

var ID_RES_CONST_STRING_SET_COMPLETE_PASSWORD = "パスワードが設定されました。";
var ID_RES_CONST_STRING_CHANGE_COMPLETE_PASSWORD = "パスワードが変更されました。";
var ID_RES_CONST_STRING_UNSET_COMPLETE_PASSWORD = "パスワードが解除されました。";
var ID_RES_CONST_STRING_DOWNLOAD_PDF = "PDFダウンロード";

var ID_RES_CONST_STRING_SHARE_PERMISSION_OFF = "オフ(特定ユーザーのみ共有)";
var ID_RES_CONST_STRING_MAIL_SHARE = "メール共有";
var ID_RES_CONST_STRING_NOTE_SHARE = "メッセージ共有";
var ID_RES_CONST_STRING_CHAT_SHARE = "チャットルーム共有";
var ID_RES_CONST_STRING_SHARE_PERMISSION_LINK = "リンクのあるすべてのユーザー";
var ID_RES_CONST_STRING_PERMISSION_ALLOW_USER = "権限のあるユーザー";

var ID_RES_CONST_STRING_NOTI_SHARE_MULTI_DOCUMENT = "{0}個の文書が共有されました。";
var ID_RES_CONST_STRING_DOC_ZOOM = "拡大/縮小";
var ID_RES_CONST_STRING_DOC_ZOOM_FIT_WIDTH = "ページの幅に合わせる";
var ID_RES_CONST_STRING_DOC_ZOOM_FIT_PAGE = "ページサイズに合わせる";
var ID_RES_CONST_STRING_NOTI_DO_NOT_DELETE = "このページは削除できません。";
var ID_RES_CONST_STRING_GET_REMOTE_SITE_CONTENT = "ウェブ&nbspフォーム";
var ID_RES_CONST_STRING_SUPPORT_ONLY_ENTIRE_ROW_COL = "行全体または列全体のみ切り取りが可能です。";

var ID_RES_CONST_STRING_SELECTED_MULTI_DOCUMENT = "{0}個の文書が選択されました。";
var ID_RES_CONST_STRING_SHARED_OK = "共有完了";
var ID_RES_CONST_STRING_SHARED_NO = "未共有";

var ID_RES_CONST_STRING_SHARE_STATUS_CHANGED = "変更された共有履歴が反映されました。";
var ID_RES_CONST_STRING_SHARE_STATUS_NOT_CHANGED = "変更された共有履歴はありません。";
var ID_RES_CONST_STRING_WE_NOT_SUPPORTED = "サポートしていません。";
var ID_RES_CONST_STRING_IE_NOT_SUPPORT_LANDSCAPE_PRINT = "IEは横向きの印刷をサポートしません。";

var ID_RES_CONST_STRING_SHARE_FAX = "ファックス共有";
var ID_RES_CONST_STRING_DOC_SECURE_GRADE = "文書のセキュリティレベルを挿入";
var ID_RES_CONST_STRING_ALERT_CHOICE_DOC_SECURE_GRADE = "文書のセキュリティ レベルを選択してください。";
var IE_RES_CONST_STRING_THUMBNAIL_VIEW = "サムネイル表示";

var ID_RES_CONST_STRING_INVITE_YOU_SHARE_DOCUMENT = "{0}様が次の文書を{1}するよう招待しました。";
var ID_RES_CONST_STRING_DOCUMENT_OPEN = "文書を開く";
var ID_RES_CONST_STRING_DOCUMENT_SHARE = "文書共有";
var ID_RES_CONST_STRING_SHOW = "表示";
var ID_RES_CONST_STRING_POINTER_OPTION = "ポインターオプション";

var ID_RES_CONST_STRING_NOTI_EXIST_TEMP_DOCUMENT = "タイトルが指定されていない文書が存在します。";
var ID_RES_CONST_STRING_NOTI_DENY_UNSHARE_DEPARTSHARE_DOCUMENT = "部署共有がされている文書は共有解除が制限されます。";
var ID_RES_CONST_STRING_TABLE_LOCK_EDIT_CELL = "セルの編集制限";
var ID_RES_CONST_STRING_NOT_EDITABLE_AREA = "編集が制限された領域です。";

var ID_RES_CONST_STRING_SAVE_DOCUMENT_FIRST = "文書を先に保存してください。";

var ID_RES_CONST_STRING_PROTECT_PRIVACY = "個人情報の保護";
var ID_RES_CONST_STRING_SELECT_PRIVACY = "個人情報の選択";
var ID_RES_CONST_STRING_SELECT_PROTECT_CHAR = "保護文字の選択";
var ID_RES_CONST_STRING_PROTECT = "保護する";
var ID_RES_CONST_STRING_PROTECT_ALL = "すべての保護";
var ID_RES_CONST_STRING_PHONE_NUMBER = "電話番号";
var ID_RES_CONST_STRING_E_MAIL = "電子メール";
var ID_RES_CONST_STRING_RESIDENT_REGISTRATION_NUMBER = "住民登録番号";
var ID_RES_CONST_STRING_ALERT_SELECT_PRIVACY = "個人情報を選択してください。";
var ID_RES_CONST_STRING_NOTI_MARKING_PRIVACY_COUNT = "個人情報の保護を{0}回しました。";
var ID_RES_CONST_STRING_DOCUMENT_BACKUP = "文書バックアップおよび復元";

var ID_RES_CONST_STRING_PRIVACY_PASSWORD = "個人情報のパスワード";
var ID_RES_CONST_STRING_DISABLE_PRIVACY = "個人情報の保護を解除";
var ID_RES_CONST_STRING_DISABLE_PRIVACY_FAIL = "個人情報の保護の解除に失敗しました。";
var ID_RES_CONST_STRING_DISABLE_PRIVACY_DONE = "個人情報保護が解除されました。";
var ID_RES_CONST_STRING_WEBSEARCH_SUPPLY = "検索結果を提供";

var ID_RES_CONST_STRING_HEADER = "ヘッダー";
var ID_RES_CONST_STRING_FOOTER = "フッター";
var ID_RES_CONST_STRING_HEADER_FOOTER = "ヘッダー/フッター";

var ID_RES_CONST_STRING_FIRST_HEADER = "最初のページのヘッダー";
var ID_RES_CONST_STRING_FIRST_FOOTER = "最初のページのフッター";
var ID_RES_CONST_STRING_EVEN_HEADER = "偶数ページのヘッダー";
var ID_RES_CONST_STRING_EVEN_FOOTER = "偶数ページのフッター";
var ID_RES_CONST_STRING_ODD_HEADER = "奇数ページのヘッダー";
var ID_RES_CONST_STRING_ODD_FOOTER = "奇数ページのフッター";

var ID_RES_CONST_STRING_EDIT_HEADER = "ヘッダーを編集";
var ID_RES_CONST_STRING_EDIT_FOOTER = "フッターを編集";
var ID_RES_CONST_STRING_CLOSE_HEADER_FOOTER = "ヘッダー/フッターを閉じる";
var ID_RES_CONST_STRING_REMOVE_HEADER = "ヘッダーを削除";
var ID_RES_CONST_STRING_REMOVE_FOOTER = "フッターを削除";

var ID_RES_CONST_STRING_GO_TO_HEADER = "ヘッダーへ移動";
var ID_RES_CONST_STRING_GO_TO_FOOTER = "フッターへ移動";

var ID_RES_CONST_STRING_HEADER_MARGIN_FROM_TOP = "ヘッダー（上部）";
var ID_RES_CONST_STRING_FOOTER_MARGIN_FROM_BOTTOM = "フッター（下部）";

var ID_RES_CONST_STRING_OPTIONS = "オプション";
var ID_RES_CONST_STRING_DIFFERENT_FIRST_PAGE = "最初のページを別の形で指定";
var ID_RES_CONST_STRING_DIFFERENT_ODD_EVEN_PAGES = "偶数と奇数ページを別の形で指定";
var ID_RES_CONST_STRING_SHOW_DOCUMENT_TEXT = "文書テキストを表示";
var ID_RES_CONST_STRING_SHOW_RIBBON_TOOLBARS_ALWAYS = "リボンツールバーは常に表示";
var ID_RES_CONST_STRING_HIDE_RIBBON_TOOLBARS = "リボンツールバーを非表示";

var ID_RES_CONST_STRING_DELETE_IMAGE = "画像削除";
var ID_RES_CONST_STRING_DELETE_VIDEO = "ビデオ削除";

var ID_RES_DIALOG_STRING_ALIGN_MIDDLE = "中央";
var ID_RES_DIALOG_STRING_ALIGN_TOP = "上";
var ID_RES_TOOL_STRING_MENU_HOME = "ホーム";
var ID_RES_TOOL_STRING_MENU_LAYOUT = "レイアウト";
var ID_RES_CONST_STRING_HELP_ONLINE = "オンラインマニュアル";

var ID_RES_DIALOG_STRING_NO_SELECT = "選択しない";
var ID_RES_DIALOG_STRING_AUTO_PLAY = "自動再生";
var ID_RES_CONST_STRING_VIEWING = "閲覧";
var ID_RES_CONST_STRING_CHART_DATA_SORT = "データの順番";
var ID_RES_CONST_STRING_CHART_DATA_SORT_REVERSE = "逆方向";

var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ALL = "全体期間";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_DAY = "1日";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_WEEK = "1週間";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_MONTH = "1ヶ月";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_SIX_MONTH = "6ヶ月";
var ID_RES_CONST_STRING_SEARCH_SEARCH_PERIOD_OPTION_ONE_YEAR = "1年";

var ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT = "タイトル";
var ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_OWNER = "所有者";
var ID_RES_CONST_STRING_BROWSER_UNIFIED_SEARCH_RESULT = "\{0}\"に";
var ID_RES_CONST_STRING_ALL_SEARCH_RESULT = "全体の検索結果";
var ID_RES_CONST_STRING_SEND_BIZBOX_REPORT = "業務報告を送る";
var ID_RES_CONST_STRING_UPDATE_BIZBOX_REPORT = "業務報告の更新";

var ID_RES_CONST_STRING_DOCUMENT_HISTORY = "文書の履歴";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_VIEW_LARGER = "拡大して見る";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_ACTION_TYPE = "区分";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_SHARE_INFO = "共有情報";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_DEVIDE_INFO = "機器情報";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_ACCESS = "アクセス";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_SHARE_ALL = "全体共有";

var ID_RES_CONST_STRING_ADD = "追加";
var ID_RES_CONST_STRING_DELETE = "削除";

var ID_RES_CONST_STRING_ADD_SCHEDULE = "スケジュール追加";
var ID_RES_CONST_STRING_DELETE_SCHEDULE = "スケジュール削除";
var ID_RES_CONST_STRING_ADD_TASK = "業務追加";
var ID_RES_CONST_STRING_DELETE_TASK = "業務削除";
var ID_RES_CONST_STRING_ALERT_NOT_AVAILABLE_IN_ONEPAGE_MODE = "単一ページモードでは使用できません。";
var ID_RES_CONST_STRING_ONEPAGE_MODE = "ページ分割";
var ID_RES_CONST_STRING_ONEPAGE_MODE_ON = "単一ページ";
var ID_RES_CONST_STRING_ONEPAGE_MODE_OFF = "複数のページ";
var ID_RES_CONST_STRING_PAPER_SIZE = "用紙サイズ";
var ID_RES_CONST_STRING_NOTI_HYPERLINK_GUIDE = "リンク先に移動するには<Ctrl>キーを押しながらクリックします。";

var ID_RES_CONST_STRING_SHAPES = "図形";
var ID_RES_CONST_STRING_SHAPES_FORMAT = "図形書式";
var ID_RES_CONST_STRING_SHAPES_CHANGE = "図形の変更";
var ID_RES_CONST_STRING_SHAPES_STYLE = "スタイル";
var ID_RES_CONST_STRING_SHAPES_FILL = "塗りつぶし";
var ID_RES_CONST_STRING_SHAPES_BORDER = "枠線";
var ID_RES_CONST_STRING_SHAPES_TEXT_ALIGN = "テキストの配置";
var ID_RES_CONST_STRING_SHAPES_LAYOUT = "テキストの行変更";
var ID_RES_CONST_STRING_SHAPES_MOVE_FRONT = "前に移動";
var ID_RES_CONST_STRING_SHAPES_MOVE_FRONT_EDGE = "一番前に持ってくる";
var ID_RES_CONST_STRING_SHAPES_MOVE_BACK = "後ろに送る";
var ID_RES_CONST_STRING_SHAPES_MOVE_BACK_EDGE = "一番後ろに送る";
var ID_RES_CONST_STRING_SHAPES_ALIGN = "カスタム";
var ID_RES_CONST_STRING_SHAPES_ROTATE = "回転";
var ID_RES_CONST_STRING_SHAPES_TRANSPARENT = "透明度";
var ID_RES_CONST_STRING_SHAPES_FILL_NONE = "塗りつぶしなし";
var ID_RES_CONST_STRING_SHAPES_FILL_SOLID = "単色塗り";
var ID_RES_CONST_STRING_SHAPES_STYLE_TEMPLATE = "基本スタイル";
var ID_RES_CONST_STRING_SHAPES_TEXT_ALIGN_MIDDLE = "中間";

var ID_RES_CONST_STRING_SHAPES_SQUARE_RIGHT_ANGLE = "長方形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_ROUNDED = "角の丸い長方形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_TRAPEZOID = "台形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_PARALLELOGRAM = "平行四辺形";
var ID_RES_CONST_STRING_SHAPES_SQUARE_DIAMOND = "菱形";

var ID_RES_CONST_STRING_SHAPES_TRIANGLE_ISOSCELES_TOP = "上部二等辺三角形";
var ID_RES_CONST_STRING_SHAPES_TRIANGLE_ISOSCELES_RIGHT = "右二等辺三角形";
var ID_RES_CONST_STRING_SHAPES_TRIANGLE_RIGHT_ANGLE = "直角三角形";

var ID_RES_CONST_STRING_SHAPES_CIRCLE = "円";
var ID_RES_CONST_STRING_SHAPES_ELLIPSE = "楕円";

var ID_RES_CONST_STRING_SHAPES_ARROW_RIGHT = "右矢印";
var ID_RES_CONST_STRING_SHAPES_ARROW_TOP = "上矢印";
var ID_RES_CONST_STRING_SHAPES_ARROW_LEFT_RIGHT = "左右矢印";
var ID_RES_CONST_STRING_SHAPES_ARROW_TOP_BOTTOM = "上下矢印";

var ID_RES_CONST_STRING_SHAPES_LINE_NORMAL = "線";
var ID_RES_CONST_STRING_SHAPES_LINE_ARROW_UNI_DIRECTION = "一方向矢印";
var ID_RES_CONST_STRING_SHAPES_LINE_ARROW_BI_DIRECTION = "両方向矢印";

var ID_RES_CONST_STRING_LIST_NO_START = "次の番号で開始";

var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_TOP = "上部";
var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_MIDDLE = "中央";
var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_BOTTOM = "下部";
var ID_RES_CONST_STRING_OBJ_ALIGN_TOP = "上揃え";
var ID_RES_CONST_STRING_OBJ_ALIGN_MIDDLE = "中央揃え";
var ID_RES_CONST_STRING_OBJ_ALIGN_BOTTOM = "下揃え";

var ID_RES_CONST_STRING_OBJ_ROTATE_RIGHT_90 = "右に90度回転";
var ID_RES_CONST_STRING_OBJ_ROTATE_LEFT_90 = "左に90度回転";
var ID_RES_CONST_STRING_OBJ_ROTATE_FLIP_VERTICAL = "上下対称";
var ID_RES_CONST_STRING_OBJ_ROTATE_FLIP_HORIZONTAL = "左右対称";
var ID_RES_CONST_STRING_OBJ_ROTATE_OTHERS = "その他の回転オプション";

var ID_RES_CONST_STRING_TXTLAYOUT_IN_LINE_WIDTH_TEXT = "行内";
var ID_RES_CONST_STRING_TXTLAYOUT_SQUARE = "四角";
var ID_RES_CONST_STRING_TXTLAYOUT_TIGHT = "外周";
var ID_RES_CONST_STRING_TXTLAYOUT_THROUGH = "内部";
var ID_RES_CONST_STRING_TXTLAYOUT_TOPANDBOTTOM = "上/下";
var ID_RES_CONST_STRING_TXTLAYOUT_BEHIND_TEXT = "背面";
var ID_RES_CONST_STRING_TXTLAYOUT_IN_FRONT_OF_TEXT = "前面";
var ID_RES_CONST_STRING_TXTLAYOUT_LEFT_TEXT = "テキストの左側";
var ID_RES_CONST_STRING_TXTLAYOUT_RIGHT_TEXT = "テキストの右側";
var ID_RES_CONST_STRING_TXTLAYOUT_OTHERS = "その他のレイアウトオプション";
var ID_RES_CONST_STRING_LINE_NOCOLOR = "輪郭なし";
var ID_RES_CONST_STRING_LINE_OTHER_COLOR = "他の輪郭の色";

var ID_RES_CONST_STRING_COUNT = "件";
var ID_RES_CONST_STRING_ARROW = "矢印";
var ID_RES_CONST_STRING_ARROW_NONE = "矢印なし";
var ID_RES_CONST_STRING_ARROW1 = "矢印1";
var ID_RES_CONST_STRING_ARROW2 = "矢印2";
var ID_RES_CONST_STRING_ARROW3 = "矢印3";
var ID_RES_CONST_STRING_ARROW4 = "矢印4";
var ID_RES_CONST_STRING_ARROW5 = "矢印5";
var ID_RES_CONST_STRING_ARROW6 = "矢印6";
var ID_RES_CONST_STRING_ARROW7 = "矢印7";
var ID_RES_CONST_STRING_ARROW8 = "矢印8";
var ID_RES_CONST_STRING_ARROW9 = "矢印9";
var ID_RES_CONST_STRING_ARROW10 = "矢印10";

var ID_RES_CONST_STRING_GET_BIZBOX_REPORT_LIST = "業務報告をインポートする";

var ID_RES_CONST_STRING_SHAPES_PLACING = "テキスト配置";
var ID_RES_CONST_STRING_SHAPES_DISTANCE_WITH_TEXT = "テキストとの間隔";
var ID_RES_CONST_STRING_SHAPES_RATIO = "倍率";
var ID_RES_CONST_STRING_SHAPES_FIXED_RATIO = "縦横比を固定";
var ID_RES_CONST_STRING_SHAPES_ADD_TEXT = "テキストの追加";

var ID_RES_CONST_STRING_OPEN_LINK = "オープンリンク";
var ID_RES_CONST_STRING_SHARED_USER = "共有中のユーザー";
var ID_RES_CONST_STRING_PEOPLE_COUNT = "人";
var ID_RES_CONST_STRING_USER_SHARING = "ユーザー共有";
var ID_RES_CONST_STRING_STATUS_ON = "オン";
var ID_RES_CONST_STRING_STATUS_OFF = "オフ";
var ID_RES_CONST_STRING_LINK_OFF = "リンクオフ";
var ID_RES_CONST_STRING_SHARE_NOTI_TYPE = "送り方";
var ID_RES_CONST_STRING_MAIL = "メール送信";
var ID_RES_CONST_STRING_NOTE = "メッセージ送信";
var ID_RES_CONST_STRING_ONEFFICE = "ワンピース";
var ID_RES_CONST_STRING_SHARE_COUNT_STATUS = "共有中（{0}）";

var ID_RES_CONST_STRING_FIXED_RATIO = "比率固定";
var ID_RES_CONST_STRING_CHANGE_PROTECT_PASSWORD = "保護パスワードを変更";
var ID_RES_CONST_STRING_FOREIGNER_NUMBER = "外国人登録番号";
var ID_RES_CONST_STRING_CREDITCARD_NUMBER = "クレジットカード番号";
var ID_RES_CONST_STRING_IP_ADDRESS = "アクセスIP";
var ID_RES_CONST_STRING_BIRTHDAY = "生年月日";
var ID_RES_CONST_STRING_USER_DEFINE_SETTING = "カスタム設定";
var ID_RES_CONST_STRING_DISPLAY_FORM_SETTING = "表示形式の設定";

var ID_RES_CONST_STRING_CHART_DATA_CONVERT = "データ変換";
var ID_RES_CONST_STRING_CHART_DATA_XY_CONVERT = "行/列変換";
var ID_RES_CONST_STRING_CHART_DATA_ORDER_CONVERT = "順番変換";
var ID_RES_CONST_STRING_CHART_TYPE_BAR = "縦棒";
var ID_RES_CONST_STRING_CHART_TYPE_HBAR = "横棒";
var ID_RES_CONST_STRING_CHART_TYPE_LINE = "折れ線";
var ID_RES_CONST_STRING_CHART_TYPE_LINE_CUBIC = "曲線";
var ID_RES_CONST_STRING_CHART_TYPE_PIE = "円";
var ID_RES_CONST_STRING_CHART_TYPE_DOUGHNUT = "ドーナツ";
var ID_RES_CONST_STRING_CHART_TYPE_RADAR = "レーダー";
var ID_RES_CONST_STRING_CHART_TYPE_POLARAREA = "扇子";
var ID_RES_CONST_STRING_CHART_TITLE = "グラフタイトル";
var ID_RES_CONST_STRING_CHART_DATA_TITLE = "グラフデータ";
var ID_RES_CONST_STRING_MODIFY_CHART_DATA = "グラフデータを編集";
var ID_RES_CONST_STRING_MODIFY_CHART_TYPE = "グラフの種類を変更";
var ID_RES_CONST_STRING_CHART_LEGEND_VIEW = "凡例表記";
var ID_RES_CONST_STRING_CHART_DATA_VIEW = "データ表記";
var ID_RES_CONST_STRING_CHART_DATA_VIEW_OK = "表記ボックス";
var ID_RES_CONST_STRING_CHART_DATA_LABEL = "データラベル";
var ID_RES_CONST_STRING_CHART_TITLE_PADDING = "グラフとの間隔";

var ID_RES_CONST_STRING_PAGE_CONTENTS = "ページの内容";
var ID_RES_CONST_STRING_PAGE_CONTENTS_OVERFLOW_ON = "自動調整しない";
var ID_RES_CONST_STRING_PAGE_CONTENTS_OVERFLOW_OFF = "自動調整する";

var ID_RES_CONST_BTN_MERGE_DOCUMENT = "文書収集";

var ID_RES_CONST_STRING_TABLE_COLLAPSE = "セルとセルの間の線を1本で表現";

var ID_RES_CONST_STRING_INSERT_NEW_PAGE = "新しいページ";
var ID_RES_CONST_STRING_PAGE_MANAGEMENT = "ページ管理";
var ID_RES_CONST_STRING_INSERT_EMPTY_PAGE = "空のページを挿入";
var ID_RES_CONST_STRING_COPY_PAGE = "ページコピー";
var ID_RES_CONST_STRING_PASTE_PAGE = "ページの貼り付け";
var ID_RES_CONST_STRING_DELETE_PAGE = "ページ削除";
var ID_RES_CONST_STRING_ABOVE_PAGE = "ページの上";
var ID_RES_CONST_STRING_BELOW_PAGE = "ページの下";
var ID_RES_CONST_STRING_INSERT_TABLE_WITH_CHART = "グラフ挿入時にデータテーブルも共に挿入";

var ID_RES_CONST_STRING_KEEP_TEXT_ONLY = "テキストのみ保持";
var ID_RES_CONST_STRING_INSERT_AS_NESTED_TABLE = "テーブルの多重適用";

var ID_RES_CONST_STRING_RECEIVED_REPORT = "受信したレポート";
var ID_RES_CONST_STRING_SENT_REPORT = "送信レポート";
var ID_RES_CONST_STRING_REFERENCE_REPORT = "参照レポート";
var ID_RES_CONST_STRING_PUBLIC_REPORT = "公開レポート";

var ID_RES_CONST_STRING_BROWSER_SECURITY = "セキュリティ文書ボックス";

var ID_RES_CONST_STRING_SHARED_DATE = "共有日";

var ID_RES_CONST_STRING_EXTEND_FUNC = "拡張機能";
var ID_RES_SEND_MAIL_FAIL = "メール送信に失敗しました。";
var ID_RES_CONST_STRING_ALREADY_IN_USER = "すでに含まれているユーザーです。";
var ID_RES_CONST_STRING_IMPORTANT = "重要";
var ID_RES_CONST_STRING_FILE_TYPE = "文書の種類";

var ID_RES_CONST_STRING_CREATE_FOLDER = "新しいフォルダ";
var ID_RES_CONST_STRING_CREATE_FILE = "新しいドキュメント";
var ID_RES_CONST_STRING_CHANGES_NOT_SAVED = "変更事項が保存されないことがあります。";

var ID_RES_CONST_STRING_DIRECT_GO = "今すぐ移動";
var ID_RES_CONST_STRING_LOGIN_GUIDE_TITLE = "ログインのご案内";
var ID_RES_CONST_STRING_LOGIN_GUIDE_CONTENT = "セッションが終了したため再ログインが必要です。<br >新しいページでログインしてからもう一度実行してください。<br >ログインページを新しいページで開きますか？";
var ID_RES_CONST_STRING_SERVER_ERROR_TITLE = "ネットワークエラーのご案内";
var ID_RES_CONST_STRING_SERVER_ERROR_CONTENT = "ネットワークエラーが発生しました。<br />しばらく後にもう一度実行してください。";
var ID_RES_CONST_STRING_INSERT_QRCODE = "QRコード";

var ID_RES_CONST_PANEL_TITLE_DOC_INFO = "文書の詳細情報";
var ID_RES_CONST_PANEL_TITLE_DOC_ACCESS = "文書へのアクセス管理";
var ID_RES_CONST_PANEL_TITLE_DOC_COMMENT = "文書のコメント";
var ID_RES_CONST_PANEL_TITLE_DOC_CHART = "グラフの書式";
var ID_RES_CONST_TOAST_EDIT_AUTH_REQUEST_CANCEL = "編集権限の要請がキャンセルされました。";
var ID_RES_CONST_TOAST_EDIT_AUTH_PASS_SUCCESS = "編集権限を移管しました。";
var ID_RES_CONST_TOAST_REJECT_EDIT_REQUEST = "編集権限の要請が拒否されました。";
var ID_RES_CONST_TOAST_OTHER_USED_REQUEST = "他のユーザーが編集権限を要請中です。";
var ID_RES_CONST_TOAST_ACCESS_MANAGER_TITLE = "権限要請";
var ID_RES_CONST_STRING_DELETE_DIV = "点線の枠を消す";

var ID_RES_CONST_STRING_QRCODE_FITST_INFO = "最初のページ右上";
var ID_RES_CONST_STRING_QRCODE_LAST_INFO = "最後のページの下部";

var ID_RES_CONST_STRING_SORT_TITE = "文書タイトル";
var ID_RES_CONST_STRING_SORT_RECENTDATE = "最終更新日";
var ID_RES_CONST_STRING_SORT_READDATE = "最終アクセス日";
var ID_RES_CONST_STRING_SORT_SHEREBYDATE = "共有された日";
var ID_RES_CONST_STRING_SORT_FILESIZE = "ファイルサイズ";
var ID_RES_CONST_STRING_SORT_SHEREDATE = "共有日";
var ID_RES_CONST_STRING_SORT_OWNER = "所有者";

var ID_RES_CONST_STRING_FILTER_ALL = "すべての文書";
var ID_RES_CONST_STRING_FILTER_MY = "マイドキュメント";
var ID_RES_CONST_STRING_FILTER_BY = "共有された文書";

var ID_RES_CONST_STRING_CREATE_DATE = "作成日";
var ID_RES_CONST_STRING_MODIFY_DATE = "更新日";
var ID_RES_CONST_STRING_NO_PERMMISION = "閲覧の権限がありません。";
var ID_RES_CONST_STRING_NO_PERMMISION_INFO = "所有者に権限を要請してください。";
var ID_RES_CONST_STRING_REQUEST_PERMMISION = "権限要請";
var ID_RES_CONST_STRING_REQUEST_CONFIRM = "権限を要請しました。";
var ID_RES_CONST_STRING_REQUEST_ALLOW = "権限が許可されました。";
var ID_RES_CONST_STRING_REQUEST_NOT_ALLOW = "権限を許可していません。";
var ID_RES_CONST_STRING_SOMEONE_PERM = "{0}様が文書を{1}できるよう";
var ID_RES_CONST_STRING_ALLOW_PERMISSION = "権限を許可しますか？";
var ID_RES_CONST_STRING_ALLOW = "許可";
var ID_RES_CONST_STRING_DENY = "拒否";
var ID_RES_CONST_STRING_ALREADY_ALLOW_DOCUMENT = "権限が許可された文書です。";

var ID_RES_CONST_PANEL_FILE_SELECT_NONE = "ファイルまたは文書を選択してください。";
var ID_RES_CONST_PANEL_MENU_DETAIL_INFO = "詳細を表示";
var ID_RES_CONST_PANEL_EDITING_USER = "編集中のユーザー";
var ID_RES_CONST_PANEL_VIEWING_USER = "閲覧中のユーザー";
var ID_RES_CONST_PANEL_REQUEST_WRITE_AUTH = "権限要請";
var ID_RES_CONST_PANEL_PASS_WRITE_AUTH = "権限を移管";
var ID_RES_CONST_PANEL_CANCEL_REQUEST_WRITE_AUTH = "要請を取り消す";
var ID_RES_CONST_PANEL_CREATE_NEW_DOC = "新しい文書を作成";
var ID_RES_CONST_STRING_YEAR = "年";
var ID_RES_CONST_STRING_MONTH = "月";
var ID_RES_CONST_STRING_DAY = "日";
var ID_RES_CONST_STRING_AM = "午前";
var ID_RES_CONST_STRING_PM = "午後";
var ID_RES_CONST_PANEL_MSG_REQUEST_WRITE_AUTH_FROM = "次のユーザーが編集権限を要請しました。";
var ID_RES_CONST_PANEL_MSG_CONFIRM_WRITE_AUTH = "編集権限を{0}しますか？";
var ID_RES_CONST_PANEL_MSG_REJECT_WRITE_AUTH = "編集権限要請が{0}されました。";
var ID_RES_CONST_PANEL_MSG_DUPLICATED_REQUEST = "他のユーザーが編集権限を{0}です。";
var ID_RES_CONST_PANEL_REQUEST = "要請";
var ID_RES_CONST_PANEL_PASS_TO = "移管";
var ID_RES_CONST_PANEL_REJECT = "拒否";
var ID_RES_CONST_PANEL_REQUESTING = "要請中";
var ID_RES_CONST_PANEL_REQUEST_WRITE_SUCCESS = "編集権限が移管されました。";
var ID_RES_CONST_PANEL_AM_EDITOR_OUT = "編集者が文書を閉じてアウトました。";

var ID_RES_CONST_STRING_WRAP_TEXT = "テキストの行変更";

var ID_RES_CONST_STRING_DEFAULT_FILE_NAME = "無題ドキュメント";
var ID_RES_CONST_STRING_DEFAULT_FOLDER_NAME = "タイトルのないフォルダ";

var ID_RES_CONST_STRING_PAGE_MOVE = "ページ移動";
var ID_RES_CONST_STRING_SLIDE_SHOW_CONFIRM = "ブラウザポリシーにより、確認時には<br />全体スライドショーモードに切り替わります。";
var ID_RES_CONST_STRING_NEXT_SLIDE = "次のスライド";
var ID_RES_CONST_STRING_PREV_SLIDE = "前のスライド";
var ID_RES_CONST_STRING_MOVE_SLIDE = "スライド移動";
var ID_RES_CONST_STRING_ZOOM_INOUT = "拡大/縮小";

var ID_RES_CONST_SLIDESHOW_ZOOM_HEIGHT = "ページの高さを整列";
var ID_RES_CONST_SLIDESHOW_ZOOM_WIDTH = "ページの幅を整列";
var ID_RES_CONST_SLIDESHOW_ZOOM_125 = "125%";
var ID_RES_CONST_SLIDESHOW_ZOOM_150 = "150%";
var ID_RES_CONST_SLIDESHOW_ZOOM_175 = "175%";

var ID_RES_CONST_STRING_CURRENT_SLIDE_SHOW = "現在からショー再生";
var ID_RES_CONST_STRING_TOOLBAR_100 = "100％にする";

var ID_RES_CONST_STRING_PGNUM = "ページ番号";
var ID_RES_CONST_STRING_PGNUM_FORMAT = "ページ番号の書式";

var ID_RES_CONST_STRING_PGNUM_REMOVE = "ページ番号を削除";
var ID_RES_CONST_STRING_FORMAT_STYLE = "書式スタイル";
var ID_RES_CONST_STRING_NUM_FORMAT = "番号の形";

var ID_RES_CONST_STRING_NUM_POS = "番号の位置";

var ID_RES_CONST_STRING_TEXT_STYLE = "テキストスタイル";
var ID_RES_CONST_STRING_PGNUMERING = "ページ番号を挿入";

var ID_RES_CONST_STRING_PGNUM_START = "スタートページの指定";

var ID_RES_CONST_STRING_PGNUM_NO = "番号なし";
var ID_RED_CONST_STRING_TOP_LEFT = "左上";
var ID_RED_CONST_STRING_TOP_CENTER = "中央上";
var ID_RED_CONST_STRING_TOP_RIGHT = "右上";
var ID_RED_CONST_STRING_BOTTOM_LEFT = "左下";
var ID_RED_CONST_STRING_BOTTOM_CENTER = "中下";

var ID_RED_CONST_STRING_BOTTOM_RIGHT = "右下";
var ID_RES_CONST_STRING_FONT_STYLE = "フォントスタイル";
var ID_RES_CONST_STRING_DOCUMENT_CONTINUE_WRITE = "文書を引続き作成します。";
var ID_RES_CONST_STRING_DOCUMENT_RELOAD = "文書を再ロードします。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_LOADED = "{0}に一時保存された文書を閲覧しています。";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_OPEN = "{0}に一時保存された文書があり、[読み取り専用]で閲覧されます。一時保存された文書を確認しますか？";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_DELETE = "一時保存された文書を削除しますか？<br />削除された文書は復旧されません。";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_ALL_DOCUMENT_DELETE = "一時保存された文書をすべて削除しますか？<br />削除された文書は復旧されません。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_DELETED_COMPLETE = "削除が完了しました。";

var ID_RES_CONST_STRING_TEMP_SAVED_ALL_DOCUMENT_DELETED_COMPLETE = "すべての文書が削除されました。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOC_BOX = "一時保存文書ボックス";
var ID_RES_CONST_STRING_TEMP_SAVE = "一時保存";
var ID_RES_CONST_STRING_OVERWRITE_ORG_DOC = "原本上書き";
var ID_RES_CONST_STRING_DELETE_DOC = "文書を削除する";
var ID_RES_CONST_STRING_ORG_DOCUMENT_INFO = "原本文書情報";
var ID_RES_CONST_STRING_DOCUMENT_LAST_UPDATE = "最後の保存日";
var ID_RES_CONST_STRING_DOCUMENT_WRITER = "作成者";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_OVERWRITE = "元の文書に一時保存文書を上書きしますか？ <br />上書きされた原本の内容は復旧されません。";
var ID_RES_CONST_STRING_OVERWRITE_ORG_DOC_COMPLETE = "上書きが完了しました。";
var ID_RES_CONST_STRING_ALERT_OVERWRITE_FAIL_READONLY_ATTR_DOCUMENT = "元の文書が読み取り専用に設定されているため上書きできません。";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_NUM_STRING = "計{0}個の一時保存文書";
var ID_RES_CONST_STRING_DELETE_ALL_DOC = "すべて削除";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENTS = "一時保存された文書";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_LIST_OPEN = "一時保存された文書があります。<br />確認しますか？";
var ID_RES_CONST_STRING_CLOSE_WINDOW = "ウィンドウを閉じますか？";

var ID_RES_STRING_CONTROL_HEIGHT = "高さ調節";
var ID_RES_STRING_CONTROL_WIDTH = "幅の調節";

var ID_RES_STRING_PAGE_BREAK_GUIDE = "――― ページ分割 ―――";
var ID_RES_STRING_PASTE_CELL_INSERT_AS_TABLE = "テーブルの多重適用";

var ID_RES_CONST_STRING_REGIST_SCHEDULE = "スケジュール登録";

var ID_RES_STRING_CHG_OWN = "文書所有権の移転";
var ID_RES_STRING_CHG_OWN_ING = "所有権移転中";
var ID_RES_STRING_CHG_OWN_CANCEL = "所有権の移転取消";
var ID_RES_STRING_CHG_OWN_TARGET = "移転対象者";

var ID_RES_STRING_CHG_OWN_PLACEHOLDER = "移管対象は1人選択可能";
var ID_RES_STRING_CHG_OWN_SEL_ERR0 = "移管対象を選択してください。";
var ID_RES_STRING_CHG_OWN_SEL_ERR1 = "移管対象を1人だけ選択してください。";
var ID_RES_STRING_CHG_OWN_SEL_ERR2 = "本人には所有権を移転できません。";
var ID_RES_STRING_CHG_OWN_SEL_ERR3 = "部署に所有権を移転することはできません。";

var ID_RES_STRING_CHG_OWN_POP_REQ = "該当ユーザーに文書の所有権の移転を要請しますか？\n(移転対象者の承認後、最終的に移転されます。)";
var ID_RES_STRING_CHG_OWN_POP_CANCEL = "該当文書の所有権移転要請を\n取り消しますか？";
var ID_RES_STRING_CHG_OWN_POP_ACCEPT = "{0}様が要請した文書所有権の移転を\n承認しますか？";

var ID_RES_STRING_CHG_OWN_TOAST = "所有権移転が要請されました。";
var ID_RES_STRING_CHG_OWN_TOAST1 = "所有権移転が完了しました。";
var ID_RES_STRING_CHG_OWN_TOAST2 = "所有権移転の要請を拒否しました。";
var ID_RES_STRING_CHG_OWN_TOAST3 = "所有権移転の要請が取り消されました。";
var ID_RES_STRING_CHG_OWN_TOAST4 = "要請の{0}が{1}されました。";
var ID_RES_STRING_CHG_OWN_TOAST5 = "{0}様が文書所有権の移転を要請しました。 {1}";
var ID_RES_STRING_CHG_OWN_TOAST6 = "移管された文書がありません。";

var ID_RES_STRING_CHG_OWN_SEL_FOLDER = "所有権移転の文書を保存";

var ID_RES_CONST_STRING_ACCEPT = "承認";
var ID_RES_CONST_STRING_REJECT = "拒否";
var ID_RES_CONST_STRING_END = "完了";

var ID_RES_STRING_CHG_OWN_NOTE_MSG = "[文書所有権移転要請の通知]\r\n\r\n{0}様が文書所有権の移転を要請しました。\r\n\r\n[要請承認ショートカット]\r\n{1}";

var ID_RES_STRING_EDIT_WATERMARK = "ウォーターマーク";

var ID_RES_STRING_SEND_EXTERNAL = "外部送信";
var ID_RES_STRING_SEND_EXTERNAL_NOTI = "確認の際、ONEFFICE文書はPDF変換後メール作成に自動添付";

var ID_RES_STRING_TRANSFER_MOBILE_EDITOR_FAIL = "{0}様はモバイルで編集中です。 <br>モバイルは権限要請機能をサポートしません。";

var ID_RES_CONST_DOC_COMMENT_NOTI = "ワンピース文書にコメントが投稿されました。";

var ID_RES_STRING_TOTAL_SEARCH = "ONEFFICE統合検索";

var ID_RES_STRING_NEW_TEMPLATE = "新しいドキュメント";
var ID_RES_STRING_TITLE_TEMPLATE = "新しいドキュメントのテンプレート";

var ID_RES_STRING_RECENT_TEMPATE = "最近使用したテンプレート";
var ID_RES_STRING_MY_FAVOR_TITLE_TEMPLATE = "マイテンプレート";
var ID_RES_STRING_BUSS_REOPORT_TITLE_TEMPLATE = "業務報告";
var ID_RES_STRING_REOPORT_TITLE_TEMPLATE = "レポート";
var ID_RES_STRING_MEETING_TITLE_TEMPLATE = "議事録";

var ID_RES_CONST_STRING_DEST_SHARE_USER = "共有対象を入力してください。";

var ID_RES_STRING_CHART_COLUMN = "系列";
var ID_RES_STRING_CHART_ITEM = "項目";

var ID_RES_STRING_CHART_LABEL = "表記ボックス";

var ID_RES_STRING_DAY_REPORT_TEMPLATE = "日々レポート";
var ID_RES_STRING_DAY_REPORT_CORONA = "在宅勤務の日々レポート";
var ID_RES_STRING_TIME_REPORT_TEMPLATE = "随時レポート";
var ID_RES_STRING_MEETING_REPORT_TEMPLATE = "議事録";
var ID_RES_STRING_MEETING_REPORT_2_TEMPLATE = "議事録2";
var ID_RES_STRING_MEETING_REPORT_3_TEMPLATE = "議事録 3";
var ID_RES_STRING_MEETING_REPORT_4_TEMPLATE = "議事録4";
var ID_RES_STRING_MEETING_REPORT_5_TEMPLATE = "議事録 5";

var ID_RES_STRING_DEV_REPORT_TEMPLATE = "開発レポート";
var ID_RES_STRING_BUS_REPORT_TEMPLATE = "事業計画レポート";
var ID_RES_STRING_WEEK_REPORT_TEMPLATE = "週間レポート";
var ID_RES_STRING_BASIC_REPORT_TEMPLATE = "基本レポート";
var ID_RES_STRING_ANALYZE_TEMPLATE = "分析レポート";

var ID_RES_STRING_GENERAL_FORM_TEMPLATE = "一般レポート";
var ID_RES_STRING_GENERAL_FORM_2_TEMPLATE = "一般レポート2";
var ID_RES_STRING_GENERAL_FORM_3_TEMPLATE = "一般レポート3";
var ID_RES_STRING_PROJECT_FORM_1_TEMPLATE = "プロジェクトレポート1";
var ID_RES_STRING_PROJECT_FORM_2_TEMPLATE = "プロジェクトレポート2";

var ID_RES_STRING_PRODUCT_REPORT_TEMPLATE = "製品レポート";

var ID_RES_STRING_SERVICE_FORM_TEMPLATE = "サービス導入レポート";
var ID_RES_STRING_ADJUST_METHOD_TEMPLATE = "調整案検討レポート";
var ID_RES_STRING_EVENT_PLAN_TEMPLATE = "イベント推進計画書";

var ID_RES_STRING_IMPROVE_FORM_TEMPLATE = "改善レポート";
var ID_RES_STRING_ISSUE_FORM_TEMPLATE = "イシューレポート";
var ID_RES_STRING_CURRENT_FORM_TEMPLATE = "現況レポート";

var ID_RES_STRING_TAX_NOTICE_TEMPLATE = "税務アラーム";
var ID_RES_STRING_TAX_NET_TEMPLATE = "タックスネット";

var ID_RES_STRING_TAX_LIST_TEMPLATE = "事業分析レポート";
var ID_RES_STRING_TAX_SAVING_TEMPLATE = "節税ガイド";

var ID_RES_STRING_FORM_GROUP_BUSS = "業務報告";
var ID_RES_STRING_FORM_GROUP_MEETING = "議事録";
var ID_RES_STRING_FORM_GROUP_REPORT = "レポート";
var ID_RES_STRING_FORM_GROUP_NORMAL = "一般フォーム";
var ID_RES_STRING_FORM_GROUP_TAX = "税務フォーム";
var ID_RES_STRING_FORM_GROUP_ARTICLE = "記事フォーム";

var ID_RES_STRING_VIDEO_LEARN_ONEFFICE = "動画で学ぶ\nONEFFICE";
var ID_RES_STRING_BUSS_ONEFFICE_WRITE = "ワンピースで書く\n業務報告は違う！";

var ID_RES_STRING_INSERT_PAGE_BREAK = "ページ分割";

var ID_RES_STRING_TOP_BOTTOM_POSITION = "上下";
var ID_RES_STRING_LEFT_RIGHT_POSITION = "左右";

var ID_RES_STRING_SELECTED_REPORT = "選択したレポート";
var ID_RES_STRING_SELECTED_DOC = "選択した文書";

var ID_RES_STRING_MERGE_SAME_ITEM = "同項目の集合";
var ID_RES_STRING_MERGE_IN_ORDER = "順番に付ける";

var ID_RES_STRING_MERGE_REPORT_WARNING = "※ONEFFICEで作成されたレポートのみ表示されます。<br />&nbsp&nbsp&nbsp必要な項目を<span style='color:#ED7D31'><u>1回クリックして</u></span>選択してください。";
var ID_RES_STRING_REPORT_SEARCH_DATE = "日付";
var ID_RES_STRING_REPORT_SEARCH_TITLE = "タイトル";

var ID_RES_STRING_TODAY = "今日";
var ID_RES_STRING_LAST_WEEK = "最近1週間";

var ID_RES_STRING_MY_TEMPLATE_1 = "マイテンプレート1";
var ID_RES_STRING_MY_TEMPLATE_2 = "マイテンプレート2";
var ID_RES_STRING_MY_TEMPLATE_3 = "マイテンプレート3";
var ID_RES_STRING_MY_TEMPLATE_4 = "マイテンプレート4";
var ID_RES_STRING_MY_TEMPLATE_5 = "マイテンプレート5";

//파일 이동이나 복사 시 텍스트 추가.
var ID_RES_STRING_COPY_SUBJECT_TEXT = "（コピー）";

var ID_RES_STRING_HIDDEN_LINE = "線非表示";

var ID_RES_STRING_LAYOUT_TABLE = "レイアウトフォームを作成";

var ID_RES_STRING_SUBTITLE = "サブタイトル";
var ID_RES_STRING_BODY = "本文";
var ID_RES_STRING_VIDEO = "ビデオ";
var ID_RES_STRING_DATE = "日付";

var ID_RES_STRING_ENTER_TITLE = "タイトルを入力してください。";
var ID_RES_STRING_ENTER_SUBTITLE = "サブタイトルを入力してください。";
var ID_RES_STRING_ENTER_CONTENT = "内容を入力してください。";

var ID_RES_STRING_INSERT_IMG_AFTER_CLICK = "ダブルクリックして画像を挿入";
var ID_RES_STRING_INSERT_VIDEO_AFTER_CLICK = "ダブルクリックしてビデオを挿入";

var ID_RES_STRING_LIMT_CHAR_COUNT = "文字数制限";

var ID_RES_STRING_EDIT_TIMER_ALERT = "長期間活動がないため読み込みモードに切り替わります。<br/>編集を続けるには確認ボタンを押してください。";
var ID_RES_STRING_EDIT_TIMER_ALERT_READ = "長期間活動がないため読み込みモードに切り替わりました。<br/>再編集するには、再読み込みしてください。";
var ID_RES_STRING_EDIT_TIMER_ALERT_READ2 = "長期間活動がないため読み込みモードに切り替わりました。";
var ID_RES_STRING_EDIT_USER_CHECK = "編集中のユーザーがいません。<br/>確認を押すと編集モードに切り替わります。";

var ID_RES_CONST_STRING_SECURITY = "セキュリティ";

var ID_RES_CONST_STRING_SET_PASSWORD = "パスワード設定";

var ID_RES_CONST_STRING_NOTI_DELETED_FOLDER = "{0}個のフォルダーを削除しました。";
var ID_RES_CONST_STRING_NOTI_DELETED_FOLDER_FILE = "{0}個のフォルダと文書を削除しました。";

var ID_RES_CONST_STRING_INVALID_IMG_URL = "は無効な画像URLです。\n*使用可能ファイル:";

var ID_RES_STRING_DOCUMENT_NAME = "文書タイトル";
var ID_RES_STRING_GO_TO_HOME = "ワンピースホームへ";

var ID_RES_STRING_DOCUMENT_RENAMED = "文書のタイトルが変更されました。";
var ID_RES_STRING_DOCUMENT_RENAMED_FAIL = "文書のタイトル変更に失敗しました。";

var ID_RES_STRING_SETTING = "設定";
var ID_RES_STRING_MINUTES = "分";
var ID_RES_STRING_NOT_USED = "非使用";
var ID_RES_STRING_RIBBON_MENU = "リボンメニュー";
var ID_RES_STRING_TOOLBAR_MENU = "ツールバーメニュー";

var ID_RES_STRING_GET_NEWS_LIST = "記事リンクインポート";
var ID_RES_STRING_POST_NEWS = "記事を登録";
var ID_RES_STRING_GET_CLOUD_IMAGE = "イメージクラウド";
var ID_RES_STRING_POST_IMAGE = "画像を登録";
var ID_RES_STRING_SET_IMAGE_INFO = "画像情報の設定";
var ID_RES_CONST_STRING_DEFAULT_ARTICLE_NAME = "新しい記事";

var ID_RES_STRING_PLACEHOLDER_NEWS_TITLE = "記事のタイトルを入力してください（100文字）";
var ID_RES_STRING_PLACEHOLDER_NEWS_SUBTITLE = "記事のサブタイトルを入力してください。 （150文字）";

var ID_RES_STRING_VOC = "お客様からのお問い合わせ";
var ID_RES_STRING_SEND = "送信";
var ID_RES_STRING_VOC_PLACEHOLDER = "お問い合わせ内容を作成してください。";
var ID_RES_STRING_VOC_SEND_COMPLETE = "お問い合わせを受け付けました。";

var ID_RES_STRING_INSERT_TAB = "タブキーを入力";

var ID_RES_STRING_DEFAULT = "基本";
var ID_RES_STRING_EMPHASIS1 = "強調1";
var ID_RES_STRING_EMPHASIS2 = "強調2";
var ID_RES_STRING_EMPHASIS3 = "強調3";
var ID_RES_STRING_BOX1 = "ボックス1";
var ID_RES_STRING_BOX2 = "ボックス2";
var ID_RES_STRING_BOX3 = "ボックス3";
var ID_RES_STRING_QUOTATION = "引用句";
var ID_RES_STRING_FIRST_LETTER_BIG = "頭文字を大きく";
var ID_RES_STRING_REMOVE_FORMAT = "書式を消す";
var ID_RES_STRING_SUBTITLE1 = "サブタイトル1";
var ID_RES_STRING_SUBTITLE2 = "サブタイトル2";

var ID_RES_STRING_NO_MYINFO = "権限がないため使用が制限されます。\r\n確認を押すとウィンドウが閉じます。";

var ID_RES_STRING_INSERT_FORM_CONTROL = "コントロール挿入";
var ID_RES_STRING_FORM_TAG_RADIO = "ラジオ";

var ID_RES_STRING_CHECK_ALL_CORONA = "在宅勤務のチェックリストをすべて作成してください。";

var ID_RES_STRING_CORONA_PC_CONFIG = "在宅勤務時のパソコン環境設定マニュアル";
var ID_RES_STRING_CORONA_SOFTWARE = "在宅勤務ソリューションの活用マニュアル";
var ID_RES_STRING_CORONA_WORK_PROCESS = "在宅勤務のプロセスマニュアル";
var ID_RES_STRING_CORONA_SECURITY = "在宅勤務のセキュリティチェックマニュアル";

var ID_RES_STRING_ALL = "すべて";
var ID_RES_STRING_OUTER = "外側";
var ID_RES_STRING_INNER = "内側";

var ID_RES_STRING_FIND_END = "文書の最後まで探しました。";

var ID_RES_STRING_TEMP_SAVED = "一時的に保存されました。";
var ID_RES_STRING_MOD_SAVED = "更新履歴が保存されました。";

var ID_RES_STRING_SAVED_GO_REPORT = "内容を更新しました。\nの業務報告のページに移動します。";
var ID_RES_STRING_FAIL_SAVE_REPORT = "レポートの保存に失敗しました。";
var ID_RES_STRING_FAIL_GET_REPORT = "レポートの表示に失敗しました。";
var ID_RES_STRING_FAIL_GET_REPORT_LIST = "レポートの一覧表示に失敗しました。";
var ID_RES_STRING_FAIL_SAVE_FOR_NO_REPORT = "対象レポートの情報がないため保存できません。";
var ID_RES_STRING_TRY_AGAIN_AFTER_CLOSE_WIN = "現在のウィンドウを閉じてもう一度実行してください。";

var ID_RES_STRING_SHOW_CONTENT = "原文を見る";
var ID_RES_STRING_SHOW_CONTENT_AT_NEW_WIN = "新しいウィンドウでレポートの原文を表示";

var ID_RES_STRING_SELECT_REPORT = "レポートを選択してください";
var ID_RES_STRING_MERGE_END = "結合が完了しました。";

var ID_RES_STRING_TITLE_EDIT_HEADER = "ダブルクリックしてヘッダーを編集";
var ID_RES_STRING_TITLE_EDIT_FOOTER = "ダブルクリックしてフッターを編集";

var ID_RES_STRING_RECENT_DELETE = "「リストを削除」";
var ID_RES_STRING_RECENT_DELETE_FAIL = "最近のエントリリストの除去に失敗しました。";

var ID_RES_CONST_STRING_FILELIST_NO_SEARCH = "検索結果がありません";
var ID_RES_STRING_SELECTED_REPORT_NODATA = "選択したレポートがありません";
var ID_RES_STRING_SELECTED_DOC_NODATA = "選択した文書がありません。";

var ID_RES_STRING_SECURITY_DOC_CANNOT_SEND_REPORT = "セキュリティ文書は業務報告を送信できません。";

var ID_RES_STRING_NO_BACKUP_AND_RECOVER = "読み取りモードでは、バックアップと復元機能をサポートしていません。";

var ID_RES_CONST_STRING_SHOW_NUMPAGES = "全ページ表示";
var ID_RES_CONST_STRING_NUMPAGES = "全ページ";

var ID_RES_CONST_STRING_ADD_TASK_SCHEDULE = "主要日程/主要業務を追加";
var ID_RES_CONST_STRING_DELETE_TASK_SCHEDULE = "主要日程/主要業務を削除";

var ID_RES_STRING_AUTO_SAVE_CYCLE = "自動保存サイクル";

var ID_RES_CONST_STRING_HOUR = "じ";
var ID_RES_CONST_STRING_MINUTE = "ぷん";
var ID_RES_CONST_LEGEND = "凡例";

var ID_RES_STRING_ALERT_CHANGE_LANGUAGE = "ONEFFICEの表示言語が{0}に変更されました。";
var ID_RES_STRING_LANGUAGE_KO = "韓国語";
var ID_RES_STRING_LANGUAGE_EN = "英語";
var ID_RES_STRING_LANGUAGE_JA = "日本語";
var ID_RES_STRING_LANGUAGE_CN = "中国語";

var ID_RES_STRING_MY_GROUP = "Myグループ";

var ID_RES_CONST_STRING_PAGE_NUMBER_BOX_MSG = "ページ番号を入力してください";

var ID_RES_CONST_STRING_TABLE_INSERT = "表の生成";
var ID_RES_STRING_LETTER = "文字";

var ID_RES_STRING_INSERT_IMG = "画像の挿入";
var ID_RES_STRING_INSERT_VIDEO = "ビデオの挿入";

/* WE000028862 */ var ID_RES_STRING_LAYOUT_TABLE_LIMIT_ROW = "レイアウトフォームはページをめくることができません";

/* WE000028863 */ var ID_RES_STRING_SELECT_MULTI_ROW = "複数の行を選択してください";
/* WE000028864 */ var ID_RES_STRING_SELECT_MULTI_COL = "複数の列を選択してください";

var ID_RES_CONST_STRING_RETURN_TO_ORIGIN_DOC = "元の文書";
var ID_RES_CONST_STRING_EXTERNAL_BOX = "外部入力ボックス";
var ID_RES_STRING_CURRENT_LIST_STYLE = "Current List";
//NewsEditor
var ID_RES_CONST_STRING_INSERT_IMAGE2 = "イメージ"; 
var ID_RES_PROP_INSERT_IMAGE2 = "イメージ 属性"; 
var ID_RES_PROP_TAG_STRING_IMAGE2 = "イメージ";
var ID_RES_PROP_TAG_STRING_USER_IMAGE2 = "イメージの使用";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE2 = "イメージファイル";
var ID_RES_CONST_STRING_IMAGE_REPLACE2 = "イメージの置換";
var ID_RES_CONST_STRING_IMAGE_SAVEAS2 = "イメージとして保存";
var ID_RES_CONST_STRING_DELETE_IMAGE2 = "イメージの削除";

var ID_RES_DIALOG_STRING_URL_INPUT_YOUTUBE = "YouTube";
var ID_RES_DIALOG_STRING_URL_INPUT_NAVERTV = "NaverTV";
var ID_RES_DIALOG_STRING_URL_INPUT_KAKAOTV = "KakaoTV";

var ID_RES_STRING_SET_LIST_START_NEW = "List Start New";
var ID_RES_STRING_SET_LIST_START_CONTINUE = "List Start Continue";

var ID_RES_CONST_STRING_BROWSER_NEWSROOM = "Article Room";
var ID_RES_CONST_STRING_BROWSER_MYNEWS_LIST = "My Article";
var ID_RES_CONST_STRING_BROWSER_SEND_MYNEWS_LIST = "Registred Article";//
var ID_RES_CONST_STRING_POST_MYNEWS = "Registred";//

var ID_RES_STRING_NEWS_IMAGE_INFO = "Article Image Infomation";
var ID_RES_STRING_CAPTION = "Caption";
var ID_RES_STRING_REPLACE_TEXT = "Replace Text";
var ID_RES_STRING_LINK_URL = "URL";
var ID_RES_STRING_SET_MAIN_IMAGE = "Main Image";

var ID_RES_STRING_NEWS_SEND_INFO = "Post Setting";
var ID_RES_CONST_STRING_NEWS_JOURNALIST_INFO = "Journalist";
var ID_RES_CONST_STRING_NEWS_CLASSIFY_INFO = "Article Category";
var ID_RES_CONST_STRING_NEWS_GRADE_INFO = "Article Grade";
var ID_RES_CONST_STRING_NEWS_JOURNALIST_SEND_INFO = "Registred Jounralist";
var ID_RES_CONST_STRING_NEWS_TITLE_INFO = "Subject / SubTitle";
var ID_RES_CONST_STRING_NEWS_TAG_INFO = "Tag";
var ID_RES_CONST_STRING_NEWS_NAVER_CATEGORY_INFO = "Naver Category";

var ID_RES_STRING_ETC_MEMO = "Memo";
var ID_RES_STRING_ETC_TODO = "Todo";

var ID_RES_STRING_ETC_MEMO_INPUT_PLEASE = "Input Memo";
var ID_RES_STRING_ETC_TODO_INPUT_PLEASE = "Input Todo";

var ID_RES_STRING_WEBSEARCH_IMG_DBCLICK = "Double click on the image to insert it into the body.";

var ID_RES_CONST_STRING_NO_DATA_MEMO = "No Memo";
var ID_RES_CONST_STRING_NO_DATA_TODO = "No Todo";
var ID_RES_STRING_UPDATE_POSTED_NEWS = "Article Update";