var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,a,e){b instanceof String&&(b=String(b));for(var c=b.length,f=0;f<c;f++){var g=b[f];if(a.call(e,g,f,b))return{i:f,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,e){b!=Array.prototype&&b!=Object.prototype&&(b[a]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,a,e,c){if(a){e=$jscomp.global;b=b.split(".");for(c=0;c<b.length-1;c++){var f=b[c];f in e||(e[f]={});e=e[f]}b=b[b.length-1];c=e[b];a=a(c);a!=c&&null!=a&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
!function(b){b.fn.multiselectable=function(a){function e(c){var d=b(this);if(!1===g_browserCHK.mobile){var e=d.parent(),g=d.index(),f=e.find(".multiselectable-previous");f=f.length?f:b(e.find("."+a.selectedClass)[0]).addClass("multiselectable-previous");var k=f.index();if(c.ctrlKey||c.metaKey)d.hasClass(a.selectedClass)?(d.removeClass(a.selectedClass).removeClass("multiselectable-previous"),d.not(".child").length&&d.nextUntil(":not(.child)").removeClass(a.selectedClass)):(e.find(".multiselectable-previous").removeClass("multiselectable-previous"),
d.addClass(a.selectedClass).addClass("multiselectable-previous"),d.not(".child").length&&d.nextUntil(":not(.child)").addClass(a.selectedClass));if(c.shiftKey){e.find(".multiselectable-shift").removeClass(a.selectedClass).removeClass("multiselectable-shift");var h;k<g?h=d.prevUntil(".multiselectable-previous").add(f).add(d):k>g&&(h=d.nextUntil(".multiselectable-previous").add(f).add(d));h.addClass(a.selectedClass).addClass("multiselectable-shift")}else e.find(".multiselectable-shift").removeClass("multiselectable-shift");
c.ctrlKey||c.metaKey||c.shiftKey||(e.find(".multiselectable-previous").removeClass("multiselectable-previous"),d.hasClass(a.selectedClass)||(e.find("."+a.selectedClass).removeClass(a.selectedClass),d.addClass(a.selectedClass).addClass("multiselectable-previous"),d.not(".child").length&&d.nextUntil(":not(.child)").addClass(a.selectedClass)))}a.mousedown(c,d)}function c(c){var d=b(this);a.mouseup(c,d)}function f(c){if(!b(this).is(".ui-draggable-dragging")){var d=b(this),e=d.parent();c.ctrlKey||c.metaKey||
c.shiftKey||(e.find(".multiselectable-previous").removeClass("multiselectable-previous"),e.find("."+a.selectedClass).removeClass(a.selectedClass),d.addClass(a.selectedClass).addClass("multiselectable-previous"),d.not(".child").length&&d.nextUntil(":not(.child)").addClass(a.selectedClass));a.click(c,d)}}a||(a={});a=b.extend({},b.fn.multiselectable.defaults,a);return this.each(function(){var g=b(this);g.data("multiselectable")||g.data("multiselectable",!0).delegate(a.items,"mousedown",e).delegate(a.items,
"mouseup",c).delegate(a.items,"click",f).disableSelection()})};b.fn.multiselectable.defaults={click:function(a,b){},mousedown:function(a,b){},mouseup:function(a,b){},selectedClass:"selected",items:"li"};b.fn.multisortable=function(a){function e(a,e){if(0<e.find("."+c.selectedClass).length){var d=a.data("i"),f=e.find("."+c.selectedClass).filter(function(){return b(this).data("i")<d}).css({position:"",width:"",left:"",top:"",zIndex:""});a.before(f);var g=e.find("."+c.selectedClass).filter(function(){return b(this).data("i")>
d}).css({position:"",width:"",left:"",top:"",zIndex:""});a.after(g);setTimeout(function(){g.add(f).addClass(c.selectedClass)},0)}}a||(a={});var c=b.extend({},b.fn.multisortable.defaults,a);return this.each(function(){var f=b(this);f.multiselectable({selectedClass:c.selectedClass,click:c.click,items:c.items,mousedown:c.mousedown,mouseup:c.mouseup});a.cancel=c.items+":not(."+c.selectedClass+")";a.placeholder=c.placeholder;a.start=function(a,d){if(d.item.hasClass(c.selectedClass)){var e=d.item.parent();
e.find("."+c.selectedClass).each(function(a){b(this).data("i",a)});e=e.find("."+c.selectedClass).length*d.item.outerHeight();d.placeholder.height(e)}c.start(a,d)};a.stop=function(a,b){e(b.item,b.item.parent());c.stop(a,b)};a.sort=function(a,d){var e=d.item.parent(),f=d.item.data("i"),g=parseInt(d.item.css("top").replace("px","")),k=parseInt(d.item.css("left").replace("px",""));b.fn.reverse=Array.prototype._reverse||Array.prototype.reverse;var h=0;b("."+c.selectedClass,e).filter(function(){return b(this).data("i")<
f}).reverse().each(function(){h+=b(this).outerHeight();b(this).css({left:k,top:g-h,position:"absolute",zIndex:1E3,width:d.item.width()})});h=d.item.outerHeight();b("."+c.selectedClass,e).filter(function(){return b(this).data("i")>f}).each(function(){var a=b(this);a.css({left:k,top:g+h,position:"absolute",zIndex:1E3,width:d.item.width()});h+=a.outerHeight()});c.sort(a,d)};a.receive=function(a,b){e(b.item,b.sender);c.receive(a,b)};f.sortable(a).disableSelection()})};b.fn.multisortable.defaults={start:function(a,
b){},stop:function(a,b){},sort:function(a,b){},receive:function(a,b){},click:function(a,b){},mousedown:function(a,b){},mouseup:function(a,b){},selectedClass:"selected",placeholder:"placeholder",items:"li"}}(jQuery);
