var oneffice_cloud_firstload=!1,oneffice_cloud_resize_status_flag=!1,g_readonlyMode=!1,oneffice_cloud_currFolderSeq="",oneffice_cloud_currNEditNumber=0,oneffice_cloud_currentItemList=[],oneffice_cloud_checkedItemList=[],oneffice_cloud_currFolderList=[],oneffice_cloud_chgOwnInfo={},oneffice_cloud_shareIDList=[],oneffice_cloud_mygroup_shareIDList=[],oneffice_cloud_shareLinkPermItemOpened=!1,oneffice_cloud_sharePermORGList=[],oneffice_cloud_sharePermPersonList=[],oneffice_cloud_sharePermIndex=0;
CLOUD_CONST_BROWSER_ITEM_INDEX_RECENT=0;CLOUD_CONST_BROWSER_ITEM_INDEX_MYONEFFICE=1;CLOUD_CONST_BROWSER_ITEM_INDEX_SHARE=2;CLOUD_CONST_BROWSER_ITEM_INDEX_FAVORITE=3;CLOUD_CONST_BROWSER_ITEM_INDEX_TRASHBOX=4;CLOUD_CONST_BROWSER_ITEM_INDEX_FOLDER=5;CLOUD_CONST_BROWSER_ITEM_INDEX_SECURITY=7;CLOUD_CONST_BROWSER_ITEM_INDEX_ONLINE_HELP=8;CLOUD_CONST_BROWSER_ITEM_INDEX_MY_SHARE=9;CLOUD_CONST_BROWSER_ITEM_INDEX_BY_SHARE=10;CLOUD_CONST_BROWSER_ITEM_INDEX_NEWSROOM=11;CLOUD_CONST_BROWSER_ITEM_INDEX_MYNEWS=12;
CLOUD_CONST_BROWSER_ITEM_INDEX_SEND_MYNEWS=13;var oneffice_cloud_SearchMode=!1,oneffice_cloud_backupBrowserMode=0,oneffice_cloud_currentBrowserMode=-99;CLOUD_CONST_BROWSER_MODE_FOLDER_SEQ_BASE=12E3;CLOUD_DIALOG_EDIT_SHARE_OPTION=!1;CLOUD_CONST_STRING_GUIDE_SEQ="ONEFFICE_CLOUD_GUIDE_SEQ";CLOUD_CONST_STRING_VIDEO_MANUAL_SEQ="ONEFFICE_CLOUD_VIDEO_MANUAL_SEQ";CLOUD_CONST_STRING_NEWSROOM_SEQ="QklaV0FUQ0hfTkVXU1JPT01fU0VR";
var g_arrGuideDoc=[{seq:CLOUD_CONST_STRING_GUIDE_SEQ,title:ID_RES_STRING_BUSS_ONEFFICE_WRITE,path:"biz_report",file:"biz_report.html"},{seq:CLOUD_CONST_STRING_VIDEO_MANUAL_SEQ,title:ID_RES_STRING_VIDEO_LEARN_ONEFFICE,path:"video_manual",file:"video_manual.html"},{seq:"ONEFFICE_CLOUD_FAQ_MANUAL_SEQ",title:"ONEFFICE FAQ",path:"faq_manual",file:"faq_manual.html"},{seq:"CORONA_PC_CONFIG_SEQ",title:ID_RES_STRING_CORONA_PC_CONFIG,path:"corona_pc_config",file:"corona_pc_config.html"},{seq:"CORONA_SOFTWARE_SEQ",
title:ID_RES_STRING_CORONA_SOFTWARE,path:"corona_software",file:"corona_software.html"},{seq:"CORONA_WORK_PROCESS_SEQ",title:ID_RES_STRING_CORONA_WORK_PROCESS,path:"corona_work_process",file:"corona_work_process.html"},{seq:"CORONA_SECURITY_SEQ",title:ID_RES_STRING_CORONA_SECURITY,path:"corona_security",file:"corona_security.html"}],nCloudBrowserScrollTimer,bCloudBrowserScrollDown=!1,nCloudBrowserMouseOffY=0,nCloudBrowserFolderScrollTimer,bCloudBrowserFolderScrollDown=!1,nCloudBrowserFolderMouseOffY=
0,nCloudBrowserFolderVScrollTimer,bCloudBrowserFolderVScrollDown=!1,nCloudBrowserFolderMouseOffX=0,oneffice_cloud_search_myonefficeItemList=[],oneffice_cloud_search_shareOutItemList=[],oneffice_cloud_search_shareInItemList=[],oneffice_cloud_search_more_index=0,oneffice_cloud_search_check_one_list=0;SEARCH_PERIOD_OPTION_ALL=0;SEARCH_PERIOD_OPTION_ONE_DAY=1;SEARCH_PERIOD_OPTION_ONE_WEEK=2;SEARCH_PERIOD_OPTION_ONE_MONTH=3;SEARCH_PERIOD_OPTION_SIX_MONTH=4;SEARCH_PERIOD_OPTION_ONE_YEAR=5;
SEARCH_PERIOD_OPTION_MAX=6;SEARCH_TYPE_OPTION_SUBJECT=10;SEARCH_TYPE_OPTION_OWNER=11;SEARCH_TYPE_OPTION_MAX=12;var oneffice_cloud_current_search_BackupItemList=[],oneffice_cloud_myGroupList=[];CLOUD_CONST_SEARCH_USER_INFO_OPTION_ALL=0;CLOUD_CONST_SEARCH_USER_INFO_OPTION_ID=1;CLOUD_CONST_SEARCH_USER_INFO_OPTION_NAME=2;CLOUD_CONST_SEARCH_USER_INFO_OPTION_USER_SEQ=3;CLOUD_CONST_SEARCH_USER_INFO_OPTION_DOC_SEQ=4;var objCloudShareSearchTimer=null,oneffice_cloud_user_info_search_index=0;
CLOUD_CONST_FILE_TYPE_READONLY=100;CLOUD_CONST_FILE_TYPE_SECURITY=200;CLOUD_CONST_FILE_TYPE_SHARE_OUT=300;CLOUD_CONST_FILE_TYPE_SHARE_IN=400;CLOUD_CONST_FILE_TYPE_SEND_MYNEWS=500;CLOUD_POPUP_TYPE_FOLDER_MENU=2E3;CLOUD_POPUP_TYPE_LIST_COMMON_MENU=3E3;CLOUD_POPUP_TYPE_SORT_MENU=4E3;CLOUD_POPUP_TYPE_TRASH_MENU=5E3;CLOUD_POPUP_TYPE_FILTER_MENU=6E3;CLOUD_POPUP_FOLDER_NAVI_LIST_SHOW=!1;CLOUD_CMD_CREATE_FOLDER=0;CLOUD_CMD_CREATE_FILE=1;CLOUD_CMD_MOVE=2;CLOUD_CMD_DELETE=3;CLOUD_CMD_FAVORITE_ON=4;
CLOUD_CMD_FAVORITE_OFF=5;CLOUD_CMD_RENAME=6;CLOUD_CMD_DOC_SECURITY=7;CLOUD_CMD_READONLY_ON=8;CLOUD_CMD_READONLY_OFF=9;CLOUD_CMD_SORT_TITE=10;CLOUD_CMD_SORT_RECENTDATE=11;CLOUD_CMD_SORT_FILESIZE=12;CLOUD_CMD_TRASH_BIN=13;CLOUD_CMD_CHG_OWN=14;CLOUD_CMD_SORT_SHEREDATE=15;CLOUD_CMD_CHG_OWN_CANCEL=16;CLOUD_CMD_SORT_OWNER=17;CLOUD_CMD_UNLINK=18;CLOUD_CMD_SHARE=19;CLOUD_CMD_COPY=20;CLOUD_CMD_MORE=21;CLOUD_CMD_RECOVERY=22;CLOUD_CMD_MERGE=23;CLOUD_CMD_OPEN=24;CLOUD_CMD_LINK_COPY=25;
CLOUD_CMD_DELETE_COMPLETE=26;CLOUD_CMD_CLONE=27;CLOUD_CMD_FILTER_ALL=28;CLOUD_CMD_FILTER_MY=29;CLOUD_CMD_FILTER_BY=30;CLOUD_CMD_SORT_READDATE=31;CLOUD_CMD_SORT_SHEREBYDATE=32;CLOUD_CMD_DELETE_RECENT=33;var g_arrCloudCmd=[];g_arrCloudCmd[0]={id:"cloud_list_menu_new_folder",text:ID_RES_CONST_STRING_CREATE_FOLDER,src:"./image/cloud/icon-menu-newfolder-normal.png"};g_arrCloudCmd[1]={id:"idx_cloud_popup_select_create_file",text:ID_RES_CONST_STRING_CREATE_FILE,src:"./image/cloud/icon_cloud_new_file.png"};
g_arrCloudCmd[2]={id:"idx_cloud_popup_select_move",text:ID_RES_DIALOG_STRING_MOVE,src:"./image/cloud/ico_cloud_move.png"};g_arrCloudCmd[3]={id:"idx_cloud_popup_select_delete",text:ID_RES_CONST_STRING_DELETE,src:"./image/cloud/ico_cloud_delete.png"};g_arrCloudCmd[4]={id:"idx_cloud_popup_select_favorite_on",text:ID_RES_CONST_STRING_SET_FAVORITE_ON,src:"./image/cloud/ico_cloud_favorite_on.png"};g_arrCloudCmd[5]={id:"idx_cloud_popup_select_favorite_off",text:ID_RES_CONST_STRING_SET_FAVORITE_OFF,src:"./image/cloud/ico_cloud_renewal_menu_favorite.png"};
g_arrCloudCmd[6]={id:"idx_cloud_popup_select_rename",text:ID_RES_CONST_STRING_RENAME,src:"./image/cloud/ico_cloud_modify.png"};g_arrCloudCmd[7]={id:"idx_cloud_popup_select_doc_security",text:ID_RES_CONST_STRING_SET_PASSWORD,src:"./image/cloud/ico_cloud_doc_security.png"};g_arrCloudCmd[8]={id:"idx_cloud_popup_select_readonly_on",text:ID_RES_CONST_STRING_SET_READONLY_ON,src:"./image/cloud/ico_cloud_readonly.png"};
g_arrCloudCmd[9]={id:"idx_cloud_popup_select_readonly_off",text:ID_RES_CONST_STRING_SET_READONLY_OFF,src:"./image/cloud/ico_cloud_readonly.png"};g_arrCloudCmd[10]={id:"idx_cloud_popup_select_sort_title",text:ID_RES_CONST_STRING_SORT_TITE,src:"./image/cloud/icon-cloud_check.png"};g_arrCloudCmd[11]={id:"idx_cloud_popup_select_sort_recentdate",text:ID_RES_CONST_STRING_SORT_RECENTDATE,src:"./image/cloud/icon-cloud_check.png"};
g_arrCloudCmd[12]={id:"idx_cloud_popup_select_sort_filesize",text:ID_RES_CONST_STRING_SORT_FILESIZE,src:"./image/cloud/icon-cloud_check.png"};g_arrCloudCmd[13]={id:"idx_cloud_popup_select_trash_bin",text:ID_RES_CONST_STRING_CLEAR_TRASHBOX,src:"./image/cloud/ico_cloud_delete.png"};g_arrCloudCmd[14]={id:"idx_cloud_popup_chgown",text:ID_RES_STRING_CHG_OWN,src:"./image/cloud/ico_cloud_chgown_normal.png"};
g_arrCloudCmd[15]={id:"idx_cloud_popup_select_sort_sheredate",text:ID_RES_CONST_STRING_SORT_SHEREDATE,src:"./image/cloud/icon-cloud_check.png"};g_arrCloudCmd[16]={id:"idx_cloud_popup_chgown_cancel",text:ID_RES_STRING_CHG_OWN_CANCEL,src:"./image/cloud/ico_cloud_chgown_cancel_normal.png"};g_arrCloudCmd[17]={id:"idx_cloud_popup_select_sort_owner",text:ID_RES_CONST_STRING_SORT_OWNER,src:"./image/cloud/icon-cloud_check.png"};
g_arrCloudCmd[18]={id:"cloud_list_menu_unlink",text:ID_RES_CONST_STRING_UNSHARE_DOCUMENT,src:"image/cloud/icon-menu-unlinking-normal.png"};g_arrCloudCmd[19]={id:"cloud_list_menu_share",text:ID_RES_CONST_STRING_ONEFFICE_CONNECT,src:"image/cloud/icon-menu-share-normal.png"};g_arrCloudCmd[20]={id:"cloud_list_menu_copy",text:ID_RES_CONST_STRING_COPY,src:"image/cloud/icon-menu-copy-normal.png"};g_arrCloudCmd[21]={id:"cloud_list_menu_more",text:ID_RED_CONST_STRING_VIEW_MORE,src:"image/cloud/icon-menu-more-normal.png"};
g_arrCloudCmd[22]={id:"cloud_list_menu_recovery",text:ID_RES_CONST_STRING_RESTORE,src:"image/cloud/icon-refresh.png"};g_arrCloudCmd[23]={id:"cloud_list_menu_merge",text:ID_RES_CONST_BTN_MERGE_DOCUMENT,src:"image/cloud/icon-menu-oneffice-normal.png"};g_arrCloudCmd[24]={id:"cloud_list_menu_open",text:ID_RES_CONST_STRING_OPEN_DOCUMENT,src:"image/cloud/icon-menu-fileopen-normal.png"};g_arrCloudCmd[25]={id:"cloud_list_menu_link_copy",text:ID_RES_CONST_STRING_SHARE_LINK_COPY,src:"image/cloud/icon-linkage-normal.png"};
g_arrCloudCmd[26]={id:"cloud_list_menu_delete_complete",text:ID_RES_CONST_STRING_DELETE_COMPLETE,src:"image/cloud/icon-menu-delete-normal.png"};g_arrCloudCmd[27]={id:"cloud_list_menu_clone",text:ID_RES_CONST_STRING_SAVEAS_REMOTE,src:"image/cloud/icon-menu-copy-normal.png"};g_arrCloudCmd[28]={id:"idx_cloud_popup_select_filter_all",text:ID_RES_CONST_STRING_FILTER_ALL,src:"image/cloud/icon-cloud_check.png"};g_arrCloudCmd[29]={id:"idx_cloud_popup_select_filter_my",text:ID_RES_CONST_STRING_FILTER_MY,src:"image/cloud/icon-cloud_check.png"};
g_arrCloudCmd[30]={id:"idx_cloud_popup_select_sort_filter_by",text:ID_RES_CONST_STRING_FILTER_BY,src:"image/cloud/icon-cloud_check.png"};g_arrCloudCmd[31]={id:"idx_cloud_popup_select_sort_readdate",text:ID_RES_CONST_STRING_SORT_READDATE,src:"image/cloud/icon-cloud_check.png"};g_arrCloudCmd[32]={id:"idx_cloud_popup_select_sort_sherebydate",text:ID_RES_CONST_STRING_SORT_SHEREBYDATE,src:"image/cloud/icon-cloud_check.png"};
g_arrCloudCmd[33]={id:"idx_cloud_popup_select_delete_recent",text:ID_RES_STRING_RECENT_DELETE,src:"image/cloud/icon-menu-delete-normal.png"};
g_arrCloudPopup=[CLOUD_CMD_CREATE_FOLDER,CLOUD_CMD_CREATE_FILE,CLOUD_CMD_MOVE,CLOUD_CMD_DELETE,CLOUD_CMD_FAVORITE_ON,CLOUD_CMD_FAVORITE_OFF,CLOUD_CMD_RENAME,CLOUD_CMD_DOC_SECURITY,CLOUD_CMD_READONLY_ON,CLOUD_CMD_READONLY_OFF,CLOUD_CMD_SORT_TITE,CLOUD_CMD_SORT_RECENTDATE,CLOUD_CMD_SORT_FILESIZE,CLOUD_CMD_TRASH_BIN,CLOUD_CMD_CHG_OWN,CLOUD_CMD_SORT_SHEREDATE,CLOUD_CMD_CHG_OWN_CANCEL,CLOUD_CMD_SORT_OWNER,CLOUD_CMD_MERGE,CLOUD_CMD_FILTER_ALL,CLOUD_CMD_FILTER_MY,CLOUD_CMD_FILTER_BY,CLOUD_CMD_SORT_READDATE,
CLOUD_CMD_SORT_SHEREBYDATE];g_arrCloudMenu=[CLOUD_CMD_UNLINK,CLOUD_CMD_SHARE,CLOUD_CMD_MOVE,CLOUD_CMD_COPY,CLOUD_CMD_DELETE,CLOUD_CMD_MORE,CLOUD_CMD_RECOVERY,CLOUD_CMD_MERGE,CLOUD_CMD_LINK_COPY,CLOUD_CMD_CREATE_FOLDER,CLOUD_CMD_DELETE_COMPLETE,CLOUD_CMD_CLONE,CLOUD_CMD_DELETE_RECENT];SHARE_TYPE_OPTION_NOTE=0;SHARE_TYPE_OPTION_MAIL=1;SHARE_TYPE_OPTION_NONE=2;SHARE_TYPE_OPTION_EXTERNAL=3;SHARE_PERMISSION_OPTION_VIEW="R";SHARE_PERMISSION_OPTION_EDIT="W";SHARE_PERMISSION_OPTION_SHAREOFF="OFF";
TOAST_TYPE_OPTION_OK=1;TOAST_TYPE_OPTION_INFO=2;TOAST_TYPE_OPTION_WARN=3;TOAST_TYPE_OPTION_ERROR=4;MESSAGE_CHECK="check";MESSAGE_CONFIRM="confirm";MESSAGE_ALERT="alert";MESSAGE_ERROR="error";
function CloudSelectionInfo(){var d=oneffice_cloud_checkedItemList,c=function(a){var b=0;d.forEach(function(e){a(e)&&b++});return b},f=function(a){var b=0;oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_NEWSROOM&&d.forEach(function(e){a(e)&&(b=1)});return b};this.getCount=function(){return d.length};this.getFileCount=function(){return c(function(a){return 0<(void 0===a.type?a.fileType:a.type)?!0:!1})};this.getFolderCount=function(){return c(function(a){return 0<(void 0===a.type?a.fileType:
a.type)?!1:!0})};this.getMyDocCount=function(){var a=oneffice_cloud_currentBrowserMode;if(a!==CLOUD_CONST_BROWSER_MODE_SHARE&&a!==CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST&&a!==CLOUD_CONST_BROWSER_MODE_SEARCH_RESULT&&a!==CLOUD_CONST_BROWSER_MODE_UNIFIED_SEARCH&&a!==CLOUD_CONST_BROWSER_MODE_RECENT)return this.getCount();var b=oneffice_cloud_myInfoData.id;return c(function(a){return(void 0===a.userData?a.owner_id:a.userData.nOwnerID)===b})};this.getImportantCount=function(){return c(function(a){return 1==
(void 0===a.important?a.docData.bStar:a.important)?!0:!1})};this.getSecurityCount=function(){return c(function(a){return 1==(void 0===a.security_key?a.docData.bSecurity:a.security_key)?!0:!1})};this.getReadonlyCount=function(){return c(function(a){return 1==(void 0===a.readonly?a.docData.bViewer:a.readonly)?!0:!1})};this.getChgOwnCount=function(){return dzeUiConfig.bUseChgOwn?c(function(a){return a.owner_change}):0};this.getShareInCount=function(){var a=oneffice_cloud_myInfoData.id;return c(function(b){var c=
void 0===b.userData?b.owner_id:b.userData.nOwnerID;return 0<(void 0===b.shareData?Number(b.share_count):Number(b.shareData.nShareCount))&&c!==a})};this.getShareOutCount=function(){var a=oneffice_cloud_myInfoData.id;return c(function(b){var c=void 0===b.userData?b.owner_id:b.userData.nOwnerID;return 0<(void 0===b.shareData?Number(b.share_count):Number(b.shareData.nShareCount))&&c===a})};this.isExistedRegNews=function(){return f(function(a){return onefficeUtil.isRegArticle(a.seq)})};return this};
