var ONE_PX2MM=.264583333,CLOUD_CONST_BROWSER_MODE_MYONEFFICE=0,CLOUD_CONST_BROWSER_MODE_RECENT=1,CLOUD_CONST_BROWSER_MODE_FAVORITE=2,CLOUD_CONST_BROWSER_MODE_SHARE=3,CLOUD_CONST_BROWSER_MODE_SECURITY=4,CLOUD_CONST_BROWSER_MODE_TRASHBOX=9,CLOUD_CONST_BROWSER_MODE_SEARCH_RESULT=10,CLOUD_CONST_BROWSER_MODE_UNIFIED_SEARCH=11,CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST=16,CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST=17,CLOUD_CONST_BROWSER_MODE_ONLINE_HELP=20,CLOUD_CONST_BROWSER_MODE_TEMPLATE=21,CLOUD_CONST_BROWSER_MODE_NEWSROOM=
30,CLOUD_CONST_BROWSER_MODE_MYNEWS_LIST=31,CLOUD_CONST_BROWSER_MODE_SEND_MYNEWS_LIST=32,CLOUD_CONST_BROWSER_MODE_MAX=99;CLOUD_CONST_DEVICE_CODE_PC="10";CLOUD_CONST_DEVICE_CODE_IPHONE="21";CLOUD_CONST_DEVICE_CODE_IPAD="22";CLOUD_CONST_DEVICE_CODE_ANDROID_PHONE="31";CLOUD_CONST_DEVICE_CODE_ANDROID_PAD="32";CLOUD_CONST_DEVICE_CODE_ETC="40";CLOUD_CONST_HISTORY_ACTIONCODE_NEWDOC="0";CLOUD_CONST_HISTORY_ACTIONCODE_OPEN="1";CLOUD_CONST_HISTORY_ACTIONCODE_MODIFY="2";
CLOUD_CONST_HISTORY_ACTIONCODE_RENAME="3";CLOUD_CONST_HISTORY_ACTIONCODE_SHARE="4";CLOUD_CONST_HISTORY_ACTIONCODE_UNSHARE="5";CLOUD_CONST_HISTORY_ACTIONCODE_READONLY_ON="6";CLOUD_CONST_HISTORY_ACTIONCODE_READONLY_OFF="7";CLOUD_CONST_HISTORY_ACTIONCODE_SECURITY_ON="8";CLOUD_CONST_HISTORY_ACTIONCODE_SECURITY_CHANGE="9";CLOUD_CONST_HISTORY_ACTIONCODE_SECURITY_OFF="10";CLOUD_CONST_HISTORY_ACTIONCODE_DELETE="11";CLOUD_CONST_HISTORY_ACTIONCODE_RESTORE="12";CLOUD_CONST_HISTORY_ACTIONCODE_REMOVE="13";
CLOUD_CONST_HISTORY_ACTIONCODE_MAKE_COPY="14";CLOUD_CONST_HISTORY_ACTIONCODE_CHG_OWN="15";var langPath="",lang="";"undefined"!==typeof localStorage&&(lang=localStorage.getItem("onefficeLanguage")||"");lang||(lang=navigator.userLanguage||navigator.language||"",lang=lang.toLowerCase());
var CLOUD_CONST_LANG=lang,oneffice_cloud_myInfoData=null,oneffice={currentShareRenderUse:!1,currentShareRenderTime:10,currentShareRenderTimer:null,currentShareListLimit:50,currentShareListOffset:0,drivePath:"index.html",onefficePath:"oneffice.do",onefficeGroupSeq:null,m_ListViewMgr:null,m_FileBrowserListDiv:null,m_FileItemListDiv:null,m_bFolderChangeUpdate:!1,m_bUserAgreement:!1,m_bEmbeded:!1,autoSaveTimer:null,autoSave:!0,autoSaveTime:300,autoTempSaveTime:60,autoSessionCheckTimer:null,autoSessionCheckTime:300,
docSessionTime:360,useLoginApi:!1,onLoadListToServer:!1,onUnloadEventFlag:!1,editUseTimer:null,editUseTime:900,editUseAlertTime:60,editUseAlertTimer:null,editUseAuth:!0,editUseWork:!1,editUseWorkEnd:!1,currFileSeq:"",currFolderSeq:"",currFileSubject:"",currFileRegDate:"",currFileModDate:"",currFileOwnerId:"",currFileOpenDate:"",currFilePath:"",currFileSecurityStatus:!1,unTitleMsg:"Document",emptyContent:"<p><br /></p>",emptyServerContent:'<dze_doc_property class="dze_document_property" printmargin="20,20,20,20,10,12.5" papersize="210,297" pagecolor="#FFFFFF" watermarksrc="" dze_onepage_mode="false" pgcontentsoverflowvisible="false" newdoccreate="NewDocument"></dze_doc_property><p><br /></p>',
docVersion:"",savedContent:"",bModified:!1,bModifiedPos:0,bNewFileStart:!1,bNewFileStartSavedContent:"",parentFileContent:"",bLastSave:!1,bMadeByCopy:!1,strSavedDocNo:null,bMadeByMerge:!1,MERGE_DOC:"merge_doc",arrFolderSeqList:[],bBackupLoadedContent:!1,bTempLoadedContent:!1,tempContent:null,tempSavedContentList:[],backupContentList:[],bUseOnexFile:!1,accessManagerSearchInterval:void 0,requestManagerSearchInterval:void 0,responseReqInterval:void 0,accessInfoRefreshInterval:void 0,accessmanagerUserInfos:[],
bDocViewMode:!0,sortInfo:{sortOption:[],sortAline:[]},getAppEnvType:function(){return objOnefficeLoader.getAppEnvType()},isLoadEditor:function(){try{return"undefined"!=typeof g_arrEditorAreaContainer&&g_arrEditorAreaContainer.length&&g_arrEditorAreaContainer[0].length?!0:!1}catch(a){dalert(a)}},isReadOnlyDoc:function(){try{switch(this.getAppEnvType()){case APPENV.WE:return 1===1*g_onefficeWeTool.m_nDocPermission;default:return 1===1*this.parentFileContent.readonly||!0===this.parentFileContent.readonly}}catch(a){}return!1},
setListViewMgr:function(){oneffice.getAppEnvType()==APPENV.GW&&null==oneffice.m_ListViewMgr&&(oneffice.m_ListViewMgr=g_driveFileListViewMgr(0),"undefined"==typeof g_searchMgr?oneffice.m_ListViewMgr.setSearchMgr(null):oneffice.m_ListViewMgr.setSearchMgr(g_searchMgr))},getListViewMgr:function(){return oneffice.m_ListViewMgr},loadOfficeLayout:function(a){try{switch(!0===fnObjectCheckNull(a)&&(a=g_nActiveEditNumber),objOnefficeLoader.m_nAppEnvType){case APPENV.WE:return onefficeWE.loadOfficeLayout(a);
default:case APPENV.GW:if(!1===oneffice.m_bUserAgreement)onefficeUtil.checkUserAgreement(oneffice.loadOfficeLayout);else return onefficeGW.loadofficeLayout(a)}}catch(b){dalert(b)}},newFile:function(a){try{switch(objOnefficeLoader.m_nAppEnvType){default:case APPENV.GW:return onefficeGW.newFile(a)}}catch(b){dalert(b)}},onErrorCheckSession:function(a,b){try{if("boolean"===typeof b&&!1===b)"function"===typeof a&&a();else switch(objOnefficeLoader.m_nAppEnvType){default:case APPENV.GW:return onefficeCommon.onErrorCheckSession(a)}}catch(d){dalert(d)}},
getBindDocPath:function(a,b,d){try{var c="seq="+(!1===fnObjectCheckNull(a)?a:oneffice.currFileSeq);!1===fnObjectCheckNull(b)?c+="&groupseq="+b:!1===fnObjectCheckNull(oneffice.onefficeGroupSeq)&&(c+="&groupseq="+oneffice.onefficeGroupSeq);if(!1===fnObjectCheckNull(d)){a=[];for(var f in d)a.push(f+"="+d[f]);c+="&"+a.join("&")}d="";for(f=0;4>f;f++)d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));c+="&_t="+d;c=window.btoa(c);return c=oneffice.onefficePath+
"?"+encodeURIComponent(c)}catch(e){dalert(e)}},getEditModeDocPath:function(a,b,d,c){try{var f="";switch(oneffice.getAppEnvType()){case APPENV.WE:b=c="";d=null;var e=onefficeUtil.getRequestParameter("help");a=a==CLOUD_CONST_STRING_VIDEO_MANUAL_SEQ?"1":"";null===e&&(d={help:a});if(0<=document.location.href.indexOf("?"))b=document.location.href.split("?")[1];else return!1;if("object"===typeof d)for(var g in d)c+="&"+g+"="+d[g];f="oneffice.html?"+b+c;break;default:case APPENV.GW:e="";e=a?a:oneffice.currFileSeq;
b&&"undefined"!==typeof b?e+="&groupseq="+b:oneffice.onefficeGroupSeq&&"undefined"!==typeof oneffice.onefficeGroupSeq&&(e+="&groupseq="+oneffice.onefficeGroupSeq);"undefined"!=typeof d&&(e+="&ref="+d);a="";for(g=0;4>g;g++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));a="seq="+(e+("&_t="+a));a=window.btoa(a);f=(c=!0===fnObjectCheckNull(c)?!1:c)?"oneffice.html?"+encodeURIComponent(a):oneffice.onefficePath+"?"+encodeURIComponent(a)}return f}catch(h){dalert(h)}},
getViewModeDocPath:function(a,b){try{var d=oneffice.getAppEnvType(),c="",f="",e="";if(d==APPENV.GW){var g="";g=a?a:oneffice.currFileSeq;oneffice.onefficeGroupSeq&&"undefined"!==typeof oneffice.onefficeGroupSeq&&(g+="&groupseq="+oneffice.onefficeGroupSeq);c="seq="+g}else if(0<=document.location.href.indexOf("?"))f=document.location.href.split("?")[1];else return!1;if("object"===typeof b)for(var h in b)c+="&"+h+"="+b[h];if(d==APPENV.GW){var k=onefficeUtil.getNewSeq();c+="&"+k;c=window.btoa(c);e=dzeEnvConfig.strViewModePageURL+
"?"+encodeURIComponent(c)}else e=dzeEnvConfig.strViewModePageURL+"?"+f+c;return e}catch(l){dalert(l)}}},console=window.console||{log:function(){},dir:function(){},error:function(){},warn:function(){},dirxml:function(){}};dzeEnvConfig.bDebugging||(console.log=function(){},console.dir=function(){},console.error=function(){},console.warn=function(){},console.dirxml=function(){});function dlog(a){dzeEnvConfig.bDebugging&&console.log(a)}
function dalert(a){if(dzeEnvConfig.bDebugging){try{throw Error();}catch(d){var b=d}b&&(b=b.stack.split("\n"),b.splice(0,2),b=b.join("\n"),console.log(a+" \n"+b),alert(a+" \n"+b))}}function getStackTrace(){var a=Error().stack||"";a=a.split("\n").map(function(a){return a.trim()});return a.splice("Error"==a[0]?2:1)};
