var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");function onImageSrcHover(a){var b=a.src.replace(".png","_over.png");a.setAttribute("src",b)}
function onImageSrcUnover(a){var b=a.src.replace("_over.png",".png");a.setAttribute("src",b)}
function makeSearchDefaultUI(){try{oneffice.getListViewMgr().getSearchMgr();var a=document.getElementById("dze_idx_search_myoneffice");if(a){var b=document.createElement("div");b.style.float="left";b.innerHTML='<img src="./image/cloud/ico_cloud_renewal_oneffice.png" />';b.disabled=!0;a.title=ID_RES_CONST_STRING_BROWSER_MY;a.appendChild(b);var c=document.createElement("div");c.id="dze_idx_myoneffice_folder_info_item_name";c.className="cloud_search_info_item_name";c.innerHTML=makeSearchFolderItemName(ID_RES_CONST_STRING_BROWSER_MY);
a.appendChild(c);var d=document.createElement("div");d.className="cloud_search_more_btn";d.setAttribute("index",SEARCH_TYPE.MYONEFFICE);d.innerHTML='<div style="text-align: center; font-size: 12px; margin-left: 5px; margin-top: 2px; float: left;">'+ID_RED_CONST_STRING_VIEW_MORE+'</div><img width="4px" height="7px" src="./image/cloud/ico_cloud_view_more.png" style="margin-top: 7px;float: right; margin-right: 5px;" />';d.onclick=function(a){viewMoreSearchResult(a,this,parseInt(this.getAttribute("index")))};
a.appendChild(d)}var e=document.getElementById("dze_idx_search_shareout");e&&(b=document.createElement("div"),b.style.float="left",b.innerHTML='<img src="./image/cloud/ico_cloud_renewal_share_out.png" />',b.disabled=!0,e.title=ID_RES_CONST_STRING_BROWSER_MY_SHARE_LIST,e.appendChild(b),c=document.createElement("div"),c.id="dze_idx_shareout_folder_info_item_name",c.className="cloud_search_info_item_name",c.innerHTML=makeSearchFolderItemName(ID_RES_CONST_STRING_BROWSER_MY_SHARE_LIST),e.appendChild(c),
d=document.createElement("div"),d.className="cloud_search_more_btn",d.setAttribute("index",SEARCH_TYPE.SHAREOUT),d.innerHTML='<div style="text-align: center; font-size: 12px; margin-left: 5px; margin-top: 2px; float: left;">'+ID_RED_CONST_STRING_VIEW_MORE+'</div><img width="4px" height="7px" src="./image/cloud/ico_cloud_view_more.png" style="margin-top: 7px;float: right; margin-right: 5px;" />',d.onclick=function(a){viewMoreSearchResult(a,this,parseInt(this.getAttribute("index")))},e.appendChild(d));
var f=document.getElementById("dze_idx_search_sharein");f&&(b=document.createElement("div"),b.style.float="left",b.innerHTML='<img src="./image/cloud/ico_cloud_renewal_share_in.png" />',b.disabled=!0,f.title=ID_RES_CONST_STRING_BROWSER_SHARED_BY_LIST,f.appendChild(b),c=document.createElement("div"),c.id="dze_idx_sharein_folder_info_item_name",c.className="cloud_search_info_item_name",c.innerHTML=makeSearchFolderItemName(ID_RES_CONST_STRING_BROWSER_SHARED_BY_LIST),f.appendChild(c),d=document.createElement("div"),
d.className="cloud_search_more_btn",d.setAttribute("index",SEARCH_TYPE.SHAREIN),d.innerHTML='<div style="text-align: center; font-size: 12px; margin-left: 5px; margin-top: 2px; float: left;">'+ID_RED_CONST_STRING_VIEW_MORE+'</div><img width="4px" height="7px" src="./image/cloud/ico_cloud_view_more.png" style="margin-top: 7px;float: right; margin-right: 5px;" />',d.onclick=function(a){viewMoreSearchResult(a,this,parseInt(this.getAttribute("index")))},f.appendChild(d))}catch(g){dalert(g)}}
function makeDateListItemTitle(){var a=ID_RES_CONST_STRING_LAST_MODIFIED_DATE;switch(m_SortType){case VIEWSORT.READDATE:a=ID_RES_CONST_STRING_LAST_READ_DATE;break;case VIEWSORT.SHAREBYDATE:a=ID_RES_CONST_STRING_SHAREBY_DATE;break;case VIEWSORT.SHAREDATE:a=ID_RES_CONST_STRING_SHARE_DATE}return a}
function convertDateDiff(a){var b=new Date,c=a.split("-");if(fnObjectCheckNull(c)||3>c.length)return a;a=c[0];var d=c[1],e=c[2].split(" ")[0];return 0===calculateDateDiff(new Date(a,d,e),new Date(b.getFullYear(),b.getMonth()+1,b.getDate()))?c[2].split(" ")[1].substring(0,5):a.substr(2)+"."+d+"."+e}
function convertDate(a,b){b=""+(void 0!=a.strModifiedDate?a.strModifiedDate:a.moddate);switch(m_SortType){case VIEWSORT.MODDATE:b=""+(void 0!=a.strModifiedDate?a.strModifiedDate:a.moddate);break;case VIEWSORT.READDATE:b=""+(void 0!=a.strAccessedDate?a.strAccessedDate:a.accessdate);break;case VIEWSORT.SHAREBYDATE:case VIEWSORT.SHAREDATE:b="object"===typeof a.share_date?onefficeUtil.timeConverter(a.share_date.time):"object"===typeof a.strShareDate?onefficeUtil.timeConverter(a.strShareDate.time):""+
(void 0!=a.strShareDate?a.strShareDate:a.share_date)}return b}
function makeSearchFolderInfoInit(a){try{if(a){a.innerHTML="";var b=createFolderListItemTitle("cloud_info_text_item",ID_RES_CONST_STRING_IMPORTANT,VIEWSORT.IMPORTANT,"76px");a.appendChild(b);var c=createFolderListItemTitle("cloud_folder_info_item_name",ID_RES_CONST_STRING_DOCUMENT_TITLE,VIEWSORT.NAME);c.className+=" cloud_info_text_item";c.style.marginRight="27px";c.style.paddingTop="0";a.appendChild(c);var d=createFolderListItemTitle("cloud_info_text_item",ID_RES_CONST_STRING_FILE_TYPE,VIEWSORT.TYPE,
"175px"),e=createFolderListItemTitle("cloud_info_text_item",ID_RES_CONST_STRING_FILE_SIZE,VIEWSORT.SIZE,"120px"),f=createFolderListItemTitle("cloud_info_text_item",makeDateListItemTitle(),VIEWSORT.MODDATE,"190px");a.appendChild(d);a.appendChild(f);a.appendChild(e)}}catch(g){dalert(g)}}function makeSearchMatchSpan(a){return'<span class="cloud_search_match_text">'+a+"</span>"}
function makeSearchFolderItemName(a,b){try{return a="<b>"+a+"</b>",!1===fnObjectCheckNull(b)&&(a+=" "+makeSearchMatchSpan("("+b+")")),a}catch(c){dalert(c)}}
function viewMoreSearchResult(a,b,c){try{if(!fnObjectCheckNull(b)){var d=oneffice.getListViewMgr(),e=d.getListViewType(),f=d.getSearchMgr(),g=document.getElementById("dze_idx_search_myoneffice_container"),h=document.getElementById("dze_idx_search_shareout_container"),k=document.getElementById("dze_idx_search_sharein_container");chkBrowserSearchMode()&&resetCheckListFunc(!1);if(b.firstChild.innerText==ID_RED_CONST_STRING_VIEW_MORE)switch(f.setSearchTypeIdx(c),g_LNaviMenuBar.setCurCategory(CLOUD_CONST_BROWSER_MODE_SEARCH_RESULT),
b.firstChild.innerText=ID_RES_CONST_STRING_ALL_SEARCH_RESULT,b.style.width="100px",oneffice_cloud_search_more_index){case SEARCH_TYPE.MYONEFFICE:h.style.display="none";k.style.display="none";updateTotalSearchList(c,oneffice_cloud_search_myonefficeItemList,0);break;case SEARCH_TYPE.SHAREOUT:g.style.display="none";k.style.display="none";updateTotalSearchList(c,oneffice_cloud_search_shareOutItemList,0);break;case SEARCH_TYPE.SHAREIN:g.style.display="none",h.style.display="none",updateTotalSearchList(c,
oneffice_cloud_search_shareInItemList,0)}else f.setSearchTypeIdx(SEARCH_TYPE.NONE),g_LNaviMenuBar.setCurCategory(CLOUD_CONST_BROWSER_MODE_UNIFIED_SEARCH),b.firstChild.innerText=ID_RED_CONST_STRING_VIEW_MORE,b.style.width="56px",f.makeSearchListView(e);setSearchScrollEventHandler()}}catch(m){dalert(m)}}
function updateTotalSearchList(a,b,c){try{var d=oneffice.getListViewMgr(),e=d.getSearchMgr(),f=d.getListViewType(),g=d.getThumbListView(),h=oneffice_cloud_currentItemList,k=e.getKeyword(),m=fnObjectCheckNull(c)||0===c?b.length:c>b.length?b.length:c;switch(a){case SEARCH_TYPE.MYONEFFICE:var l=document.getElementById("dze_idx_search_myoneffice_list");break;case SEARCH_TYPE.SHAREOUT:l=document.getElementById("dze_idx_search_shareout_list");break;case SEARCH_TYPE.SHAREIN:l=document.getElementById("dze_idx_search_sharein_list")}updateSearchContainerStatus(l,
b,a);e.setSearchType(a);for(c=0;c<m;c++)if(f)d.makeThumbnailItem(c,"",0);else{var p=makeFileItem(b[c],c,k,a);0===c&&(p.style.marginTop="0");l.appendChild(p)}d.m_bSync&&d.syncChkFileList(a,b);d.setThumbListView(g);oneffice_cloud_currentItemList=h}catch(n){dalert(n)}}
function updateSearchContainerStatus(a,b,c){try{var d=oneffice.getListViewMgr();d.getSearchMgr();var e=d.getListViewType();a.innerHTML="";0===b.length?a.parentNode.style.display="none":oneffice_cloud_search_more_index?e&&oneffice_cloud_search_more_index&&oneffice_cloud_search_more_index==c&&(a.parentNode.style.display=""):a.parentNode.style.display=""}catch(f){dalert(f)}}
function initSearchEventStatus(){try{document.onkeydown=function(a){if(a.keyCode==ID_KEYCODE_ESCAPE){oneffice_cloud_SearchMode&&searchCloudEnd();a=!1;if(oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_SHARE||oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST||oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST)a=!0;endCurrentSearchStatus(a)}};document.onclick=function(a){removeSearchSelectItems(a)};dzeJ("#dze_idx_cloud_search_input").on("keydown",
function(a){a.keyCode==ID_KEYCODE_ENTER&&searchCloudItems()});dzeJ("#dze_idx_filelist_search_input_text").on("keydown",function(a){a.keyCode==ID_KEYCODE_ENTER&&searchCurrentCloud(this)});var a=document.getElementById("dze_idx_filelist_search");dzeJ(a).on("focusin",function(){dzeJ(a).addClass("active")}).on("focusout",function(){dzeJ(a).removeClass("active")});a&&dzeJ(".cloud_file_list_search_pos").animate({bottom:"126px"},800);var b=document.getElementById("dze_idx_filelist_search_select_period");
b&&(b.setAttribute("searchPeriodValue",0),b.onclick=function(a){selectSearchPeriodCurrentMode(a,b);TBCancelBubbleEvent(a)});var c=document.getElementById("dze_idx_filelist_search_select_type");c&&(c.setAttribute("searchTypeValue",10),c.onclick=function(a){selectSearchTypeCurrentMode(a,c);TBCancelBubbleEvent(a)});var d=document.getElementById("dze_idx_filelist_search_btn");d&&(d.onclick=function(a){searchCurrentCloud();TBCancelBubbleEvent(a)})}catch(e){dalert(e)}}
function selectSearchPeriodCurrentMode(a,b){try{if(!removeSearchSelectItems()){var c=document.createElement("div");c.id="dze_idx_search_select_parent_div";var d=document.createElement("div");d.className="cloud_search_option_select_container";d.style.display="none";for(a=SEARCH_PERIOD_OPTION_ALL;a<SEARCH_PERIOD_OPTION_MAX;a++){var e=getSearchOptionSelectItem(a,"cloud_search_option_select_item");e.onclick=function(a){applySearchPeriod(a,parseInt(this.getAttribute("optionValue")));searchCurrentCloud()};
d.appendChild(e)}c.appendChild(d);b.appendChild(c);dzeJ(d).fadeIn(200)}}catch(f){dalert(f)}}
function selectSearchTypeCurrentMode(a,b){try{if(!removeSearchSelectItems()){var c=document.createElement("div");c.id="dze_idx_search_select_parent_div";var d=document.createElement("div");d.className="cloud_search_option_select_container";d.style.display="none";a=SEARCH_TYPE_OPTION_SUBJECT+1;var e=oneffice_cloud_currentBrowserMode;if(e===CLOUD_CONST_BROWSER_MODE_SHARE||e===CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST||e===CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST)a=SEARCH_TYPE_OPTION_SUBJECT+2;for(e=SEARCH_TYPE_OPTION_SUBJECT;e<
a;e++){var f=getSearchOptionSelectItem(e,"cloud_search_option_select_item");f.onclick=function(a){applySearchType(a,parseInt(this.getAttribute("optionValue")))};d.appendChild(f)}c.appendChild(d);b.appendChild(c);dzeJ(d).fadeIn(200)}}catch(g){dalert(g)}}function removeSearchSelectItems(){try{var a=dzeJ("#dze_idx_search_select_parent_div");return 0<a.length?(a.fadeOut(200,function(){a.remove()}),!0):!1}catch(b){dalert(b)}}
function getSearchOptionSelectItem(a,b){try{var c=document.createElement("div");c.className=b;c.innerText=getSearchOptionSelectItemTitle(a);c.setAttribute("optionValue",a);return c}catch(d){dalert(d)}}
function getSearchOptionSelectItemTitle(a){try{var b="";switch(a){case SEARCH_PERIOD_OPTION_ALL:b=ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ALL;break;case SEARCH_PERIOD_OPTION_ONE_DAY:b=ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_DAY;break;case SEARCH_PERIOD_OPTION_ONE_WEEK:b=ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_WEEK;break;case SEARCH_PERIOD_OPTION_ONE_MONTH:b=ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_MONTH;break;case SEARCH_PERIOD_OPTION_SIX_MONTH:b=ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_SIX_MONTH;
break;case SEARCH_PERIOD_OPTION_ONE_YEAR:b=ID_RES_CONST_STRING_SEARCH_SEARCH_PERIOD_OPTION_ONE_YEAR;break;case SEARCH_TYPE_OPTION_SUBJECT:b=ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT;break;case SEARCH_TYPE_OPTION_OWNER:b=ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_OWNER}return b}catch(c){dalert(c)}}
function applySearchPeriod(a,b){try{var c=document.getElementById("dze_idx_filelist_search_select_period"),d=document.getElementById("dze_idx_filelist_search_select_period_text");c&&d&&d.outerHTML&&(c.setAttribute("searchperiodvalue",b),d.innerText=getSearchOptionSelectItemTitle(b),TBCancelBubbleEvent(a));removeSearchSelectItems()}catch(e){dalert(e)}}
function applySearchType(a,b){try{var c=document.getElementById("dze_idx_filelist_search_select_type"),d=document.getElementById("dze_idx_filelist_search_select_type_text");c&&d&&d.outerHTML&&(c.setAttribute("searchtypevalue",b),d.innerText=getSearchOptionSelectItemTitle(b),TBCancelBubbleEvent(a));removeSearchSelectItems()}catch(e){dalert(e)}}
function searchCurrentCloud(a){try{var b=document.getElementById("dze_idx_filelist_search_select_period").getAttribute("searchperiodvalue"),c=document.getElementById("dze_idx_filelist_search_select_type").getAttribute("searchtypevalue"),d=fnObjectCheckNull(a)?document.getElementById("dze_idx_filelist_search_input_text").value:a.value;g_searchMgr.m_nCurSearchType=SEARCH_TYPE.CUR;g_searchMgr.setKeyword(d);a=!1;if(oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_SHARE||oneffice_cloud_currentBrowserMode===
CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST||oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST)a=!0;if(""==d&&b==SEARCH_PERIOD_OPTION_ALL)return oneffice.currentShareRenderUse=!1,endCurrentSearchStatus(a);0===oneffice_cloud_current_search_BackupItemList.length?oneffice_cloud_current_search_BackupItemList=oneffice_cloud_currentItemList.slice():oneffice_cloud_currentItemList=oneffice_cloud_current_search_BackupItemList.slice();for(var e=oneffice_cloud_currentItemList,f=0;f<e.length;f++)!1===
searchCompareWithOption(b,c,d,e[f])&&e.splice(f--,1);oneffice_cloud_currentItemList=e;setCurItemListPreProcess(oneffice_cloud_currentItemList,!1,a);0===oneffice_cloud_currentItemList.length?(cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_NO_SEARCH_RESULT,2,"screen_center"),endCurrentSearchStatus(a)):(a&&(dzeJ("#dze_idx_filelist").html(""),dzeJ("#drive_thumbnailItemPanel").html(""),oneffice.currentShareListOffset=0),updateSearchFileList(a));if(oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_SHARE||
oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST||oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST)oneffice.currentShareListOffset=0}catch(g){dalert(g)}}
function searchCompareWithOption(a,b,c,d){try{if(a!==SEARCH_PERIOD_OPTION_ALL){var e=new Date,f=d.moddate.split("-");if(fnObjectCheckNull(f)||3>f.length)return!1;var g=f[0],h=f[1],k=f[2].split(" ")[0],m=calculateDateDiff(new Date(g,h,k),new Date(e.getFullYear(),e.getMonth()+1,e.getDate()));switch(parseInt(a)){case SEARCH_PERIOD_OPTION_ONE_DAY:if(1<m)return!1;break;case SEARCH_PERIOD_OPTION_ONE_WEEK:if(7<m)return!1;break;case SEARCH_PERIOD_OPTION_ONE_MONTH:if(31<m)return!1;break;case SEARCH_PERIOD_OPTION_SIX_MONTH:if(183<
m)return!1;break;case SEARCH_PERIOD_OPTION_ONE_YEAR:if(365<m)return!1}}c=c.toLowerCase();if(b==SEARCH_TYPE_OPTION_SUBJECT){if(0<=d.subject.toLowerCase().indexOf(c))return!0}else if(b==SEARCH_TYPE_OPTION_OWNER&&0<=d.owner_name.toLowerCase().indexOf(c))return!0;return!1}catch(l){dalert(l)}}
function endCurrentSearchStatus(a){try{var b=document.getElementById("dze_idx_filelist_search_input_text");if(!fnObjectCheckNull(b)){b.value="";var c=document.getElementById("dze_idx_filelist_search_select_period_text");c&&(c.innerText=ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ALL);g_searchMgr.initSearchInfo();if(a){getListDataProcess(null,!1,null,!0);oneffice.currentShareListOffset=0;var d=parseInt(12E3+oneffice_cloud_currentBrowserMode);g_updateListSuccessCB(!1,convertShareListData(d,oneffice_cloud_currentItemList),
null,!0)}else 0<oneffice_cloud_current_search_BackupItemList.length&&(a=oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_MYONEFFICE?oneffice_cloud_currFolderSeq:null,g_updateListSuccessCB(!0,oneffice_cloud_current_search_BackupItemList.slice(),a));oneffice_cloud_current_search_BackupItemList=[]}}catch(e){dalert(e)}}
function updateSearchFileList(a){try{oneffice.getListViewMgr().getSearchMgr().m_bForceUpdate=!0,g_updateListSuccessCB(!0,oneffice_cloud_currentItemList,null,a),a||updateFileListView()}catch(b){dalert(b)}}function setFolderSearchEnable(a){try{!0!==fnObjectCheckNull(a)&&(document.getElementById("dze_idx_filelist_search").style.display=a?"":"none")}catch(b){dalert(b)}}
function callMyGroupList(a){try{oneffice_cloud_myGroupList=[],onefficeGW.getMyGroupList(function(b){oneffice_cloud_myGroupList=getObjectClone(b);showMyGroupSelect(a)})}catch(b){dalert(b)}}
function showMyGroupSelect(a){try{var b=document.getElementById("idx_dlg"),c=document.createElement("div");c.id="dze_idx_share_document_select_parent_div";c.className="cloud_share_mygroup_parent_div";c.innerHTML=getMyGroupSelectHTML();b.appendChild(c);resizeMyGroupItems();updateMyGroupItemList();!1===fnObjectCheckNull(a)&&0<a.length&&addSelectecItemList(a);addMyGroupEvent()}catch(d){dalert(d)}}
function getMyGroupSelectHTML(){try{var a="";a+='<table cellpadding="0" cellspacing="0" width="100%" height="100%" style="background-color: white">';a+="<tbody>";a+='<tr height="30px">';a+='<td td colspan="3" style="background-color: #1C90FB; padding-left: 10px; color: white; font-weight: bold;">'+ID_RES_STRING_MY_GROUP+"</td>";a+="</tr>";a+="<tr>";a+='<td style="width: 51%; padding: 10px 5px 5px 10px;">';a+='<div id="dze_idx_mygroup_select_mygroup_area" style="border: 1px solid lightgray; height: 100%; overflow: auto;"></div>';
a+="</td>";a+='<td style="width: 9%; padding: 3px;">';a+='<p><button id="dze_idx_cloud_my_group_add_button" class="cloud_icon_button" onclick="" style="width:28px; height:24px; text-align: center;"><img width="16px" height="16px" src="./image/toolbar/minibar_btn_arrow_right.gif" style="vertical-align: middle;"></button></p>';a+='<p><button id="dze_idx_cloud_my_group_del_button" class="cloud_icon_button" onclick="" style="width:28px; height:24px; text-align: center;"><img width="16px" height="16px" src="./image/toolbar/minibar_btn_arrow_left.gif" style="vertical-align: middle;"></button></p>';
a+="</td>";a+='<td style="width: 40%; padding: 10px 10px 5px 5px;">';a+='<div id="dze_idx_mygroup_select_result_title" class="cloud_share_mygroup_select_result_title">\ucd08\ub300\ud558\uae30</div>';a+='<div id="dze_idx_mygroup_select_result_area" style="border: 1px solid lightgray; height: 100%; overflow: auto;"></div>';a+="</td>";a+="</tr>";a+="<tr>";a+='<td td colspan="3" style="text-align: center; vertical-align: top; height: 50px">';a+='<span><button id="dze_idx_cloud_my_group_confirm_button" class="cloud_icon_button" onclick="" style="background-color: #1C90FB; color: white; width:70px; height:28px; text-align: center;">'+
ID_RES_DIALOG_BTN_OK+"</button></span>";a+='<span><button id="dze_idx_cloud_my_group_cancel_button" class="cloud_icon_button" onclick="" style="width:70px; height:28px; text-align: center;">'+ID_RES_DIALOG_BTN_CANCEL+"</button></span>";a+="</td>";a+="</tr>";return a+"</tbody></table>"}catch(b){dalert(b)}}
function resizeMyGroupItems(){try{var a=document.getElementById("dze_idx_mygroup_select_mygroup_area"),b=document.getElementById("dze_idx_mygroup_select_result_title"),c=document.getElementById("dze_idx_mygroup_select_result_area");b&&c&&(a.style.height=a.offsetHeight+"px",b.style.width=c.offsetWidth+"px",c.style.height=a.offsetHeight-20+"px")}catch(d){dalert(d)}}
function updateMyGroupItemList(){try{var a=document.getElementById("dze_idx_mygroup_select_mygroup_area");if(a)for(var b=0;b<oneffice_cloud_myGroupList.length;b++){a.appendChild(makeGroupItem(oneffice_cloud_myGroupList[b].myGroupName+"("+oneffice_cloud_myGroupList[b].members.length+")",!0,oneffice_cloud_myGroupList[b].myGroupId));for(var c=0;c<oneffice_cloud_myGroupList[b].members.length;c++)a.appendChild(makeGroupItem("["+oneffice_cloud_myGroupList[b].members[c].positionNm+"]"+oneffice_cloud_myGroupList[b].members[c].empName,
!1,oneffice_cloud_myGroupList[b].members[c].empSeq))}}catch(d){dalert(d)}}function addSelectecItemList(a){try{var b=document.getElementById("dze_idx_mygroup_select_result_area");if(b)for(var c=0;c<a.length;c++)a[c].positionNm&&b.appendChild(makeGroupItem("["+a[c].positionNm+"]"+a[c].empName,!1,a[c].empSeq,!0))}catch(d){dalert(d)}}
function makeGroupItem(a,b,c,d){try{!0===fnObjectCheckNull(c)&&(c="");!0===fnObjectCheckNull(d)&&(d=!1);var e=document.createElement("p");e.className="cloud_share_mygroup_item";e.setAttribute("itemUniqueKey",c);e.setAttribute("foldergroup",b);e.title=a;b?(e.style="padding: 2px 2px 2px 5px;",e.innerHTML='<img width="16px" height="16px" src="./image/cloud/ico_cloud_folder.png" style="vertical-align: middle;"> '+a):(e.style=d?"padding: 2px 2px 2px 5px;":"padding: 2px 2px 2px 15px;",e.innerHTML='<img width="16px" height="16px" src="./image/cloud/ico_cloud_share_people.png" style="vertical-align: middle;"> '+
a);e.onclick=function(){updateMyGroupItemSelection(c,d)};e.ondblclick=function(){d?delFromMyGroupSelectedItem(c):addToMyGroupSelectedItem(c,b)};return e}catch(f){dalert(f)}}
function addMyGroupEvent(){try{document.getElementById("dze_idx_cloud_my_group_add_button").onclick=function(){var a=getMyGroupSelectedItem();a&&addToMyGroupSelectedItem(a.getAttribute("itemUniqueKey"),a.getAttribute("foldergroup"))},document.getElementById("dze_idx_cloud_my_group_del_button").onclick=function(){var a=getMyGroupSelectedItem(!0);a&&delFromMyGroupSelectedItem(a.getAttribute("itemUniqueKey"))},document.getElementById("dze_idx_cloud_my_group_confirm_button").onclick=function(){applyMyGroupSelect()},
document.getElementById("dze_idx_cloud_my_group_cancel_button").onclick=function(){closeMyGroupSelect()}}catch(a){dalert(a)}}function getMyGroupSelectedItem(a){try{var b=a?document.getElementById("dze_idx_mygroup_select_result_area"):document.getElementById("dze_idx_mygroup_select_mygroup_area");if(b)for(a=0;a<b.childNodes.length;a++)if("lightgray"==b.childNodes[a].style.backgroundColor)return b.childNodes[a]}catch(c){dalert(c)}}
function updateMyGroupItemSelection(a,b){try{var c=b?document.getElementById("dze_idx_mygroup_select_result_area"):document.getElementById("dze_idx_mygroup_select_mygroup_area");if(c)for(b=0;b<c.childNodes.length;b++)c.childNodes[b].getAttribute("itemUniqueKey")==a?c.childNodes[b].style.backgroundColor="lightgray":c.childNodes[b].style.backgroundColor="white"}catch(d){dalert(d)}}
function addToMyGroupSelectedItem(a,b){try{var c=document.getElementById("dze_idx_mygroup_select_result_area");if(c)for(var d=0;d<oneffice_cloud_myGroupList.length;d++){if(b&&oneffice_cloud_myGroupList[d].myGroupId==a){for(var e=0;e<oneffice_cloud_myGroupList[d].members.length;e++)!1===existMyGroupSelectedItem(oneffice_cloud_myGroupList[d].members[e].empSeq)&&c.appendChild(makeGroupItem("["+oneffice_cloud_myGroupList[d].members[e].positionNm+"]"+oneffice_cloud_myGroupList[d].members[e].empName,!1,
oneffice_cloud_myGroupList[d].members[e].empSeq,!0));break}for(e=0;e<oneffice_cloud_myGroupList[d].members.length;e++)if(oneffice_cloud_myGroupList[d].members[e].empSeq==a&&!1===existMyGroupSelectedItem(oneffice_cloud_myGroupList[d].members[e].empSeq)){c.appendChild(makeGroupItem("["+oneffice_cloud_myGroupList[d].members[e].positionNm+"]"+oneffice_cloud_myGroupList[d].members[e].empName,!1,oneffice_cloud_myGroupList[d].members[e].empSeq,!0));return}}}catch(f){dalert(f)}}
function delFromMyGroupSelectedItem(a){try{var b=document.getElementById("dze_idx_mygroup_select_result_area");if(b)for(var c=0;c<b.childNodes.length;c++)b.childNodes[c].getAttribute("itemUniqueKey")==a&&b.removeChild(b.childNodes[c])}catch(d){dalert(d)}}function existMyGroupSelectedItem(a){try{var b=document.getElementById("dze_idx_mygroup_select_result_area");if(b)for(var c=0;c<b.childNodes.length;c++)if(b.childNodes[c].getAttribute("itemUniqueKey")==a)return!0;return!1}catch(d){dalert(d)}}
function applyMyGroupSelect(){try{var a=document.getElementById("dze_idx_mygroup_select_result_area");if(a){for(var b=[],c=0;c<oneffice_cloud_mygroup_shareIDList.length;c++)oneffice_cloud_mygroup_shareIDList[c].searchItem&&b.push(oneffice_cloud_mygroup_shareIDList[c]);oneffice_cloud_mygroup_shareIDList=[];var d=!1;for(c=0;c<a.childNodes.length;c++){d=!1;for(var e=0;!d&&e<oneffice_cloud_myGroupList.length;e++)for(var f=0;!d&&f<oneffice_cloud_myGroupList[e].members.length;f++)a.childNodes[c].getAttribute("itemUniqueKey")==
oneffice_cloud_myGroupList[e].members[f].empSeq&&(oneffice_cloud_mygroup_shareIDList.push(oneffice_cloud_myGroupList[e].members[f]),d=!0)}a=!1;for(c=0;c<b.length;c++){for(f=0;f<oneffice_cloud_mygroup_shareIDList.length;f++)oneffice_cloud_mygroup_shareIDList[f].empSeq==b[c].empSeq&&(a=!0);0==a&&oneffice_cloud_mygroup_shareIDList.push(b[c])}initOrgSelectedItem()}closeMyGroupSelect()}catch(g){dalert(g)}}
function closeMyGroupSelect(){try{var a=document.getElementById("dze_idx_share_document_select_parent_div");a&&a.parentNode.removeChild(a)}catch(b){dalert(b)}}
function initOrgSelectedItem(){try{var a=document.getElementById("dze_idx_share_document_selected_user"),b=document.getElementById("dze_idx_share_document_selected_user_input");if(!fnObjectCheckNull(a)){for(var c=0;c<a.childNodes.length;c++)"cloud_dialog_share_document_selected_item"==a.childNodes[c].className&&a.removeChild(a.childNodes[c--]);for(c=0;c<oneffice_cloud_shareIDList.length;c++){var d=makeOrgSelectedItem(oneffice_cloud_shareIDList[c]);a.insertBefore(d,b)}for(c=0;c<oneffice_cloud_mygroup_shareIDList.length;c++)d=
makeOrgSelectedItemOnMyGroup(oneffice_cloud_mygroup_shareIDList[c]),a.insertBefore(d,b);var e=document.getElementById("dze_idx_share_document_selected_user_input"),f=document.getElementById("dze_idx_share_info_shared_user_div");d?(updateSearchInputWidth(),e&&(e.org_placeholder=e.placeholder,e.placeholder="")):e&&e.org_placeholder&&(e.placeholder=e.org_placeholder);f&&(f.style.height=document.getElementsByClassName("duzon_dialog_body_content")[0].offsetHeight+"px");repositionCloseButton();setRepositionDialogOnCenter()}}catch(g){dalert(g)}}
function updateSearchInputWidth(){try{var a=document.getElementById("dze_idx_share_document_selected_user"),b=document.getElementById("dze_idx_share_document_selected_user_input");b.style.width="50px";var c=a.offsetWidth-b.offsetLeft-22;b.style.width=(50>c?50:c)+"px";10>b.offsetLeft&&(b.style.width="100%")}catch(d){dalert(d)}}
function addOrgSelectedEvent(){try{var a=document.getElementById("dze_idx_share_document_selected_user"),b=document.getElementById("dze_idx_share_document_selected_user_input");a&&b&&(a.onclick=function(){b.focus()},b.onkeydown=function(a){var b=a.keyCode;ID_KEYCODE_BACKSPACE===b?checkValidCharInput(a):(ID_KEYCODE_ARROW_TOP===b||ID_KEYCODE_ARROW_BOTTOM===b)&&TBCancelBubbleEvent(a)},b.onkeyup=function(a){!checkValidCharInput(a)||this.dze_prevValue&&this.dze_prevValue===this.value||(searchUserOnKeyInput(CLOUD_CONST_SEARCH_USER_INFO_OPTION_NAME,
this.value,300),this.dze_prevValue=this.value)});dzeJ("[name$='dze_share_noti_type']").click(function(){var a=dzeJ("#dze_idx_share_document_add_comment");"dze_share_noti_type_oneffice"==this.id||"dze_share_noti_type_external"==this.id?a.hide(250):a.show(250);a=dzeJ("#cloud_share_container .cloud_share_dialog_td_click_btn");var b=dzeJ("#dze_idx_share_document_selected_user").parent(),e=dzeJ("#dze_idx_share_external_noti");"dze_share_noti_type_external"==this.id?(a.fadeOut(250),b.fadeOut(250),e.fadeIn(250)):
(a.fadeIn(250),b.fadeIn(250),e.fadeOut(250));setTimeout(function(){setRepositionDialogOnCenter()},260)})}catch(c){dalert(c)}}
function checkValidCharInput(a){try{switch(a.keyCode){case ID_KEYCODE_TAB:case ID_KEYCODE_SHIFT:case ID_KEYCODE_CTRL:case ID_KEYCODE_ALT:case ID_KEYCODE_PAUSE:case ID_KEYCODE_CAPSLOCK:case ID_KEYCODE_PAGE_UP:case ID_KEYCODE_PAGE_DOWN:case ID_KEYCODE_END:case ID_KEYCODE_HOME:case ID_KEYCODE_ARROW_LEFT:case ID_KEYCODE_ARROW_RIGHT:case ID_KEYCODE_INSERT:return!1;case ID_KEYCODE_ENTER:var b=document.getElementsByClassName("cloud_search_user_info_item_div_sel")[0];b&&(applySearchUserInfoList(a,b.userName,
b.userSeq,!0,b.userLoginId,b.emailAddr),TBCancelBubbleEvent(a));return!1;case ID_KEYCODE_ARROW_TOP:return(b=document.getElementsByClassName("cloud_search_user_info_item_div_sel")[0])&&b.previousSibling&&(b.previousSibling.className="cloud_search_user_info_item_div_sel",b.className="cloud_search_user_info_item_div",b.previousSibling.offsetTop<b.parentNode.scrollTop&&(b.parentNode.scrollTop=b.previousSibling.offsetTop)),TBCancelBubbleEvent(a),!1;case ID_KEYCODE_ARROW_BOTTOM:if((b=document.getElementsByClassName("cloud_search_user_info_item_div_sel")[0])&&
b.nextSibling){b.nextSibling.className="cloud_search_user_info_item_div_sel";b.className="cloud_search_user_info_item_div";var c=b.nextSibling.offsetTop+b.nextSibling.offsetHeight;0>b.parentNode.offsetHeight+b.parentNode.scrollTop-c&&(b.parentNode.scrollTop=c-b.parentNode.offsetHeight)}TBCancelBubbleEvent(a);return!1;case ID_KEYCODE_BACKSPACE:if("keydown"==a.type&&""==a.target.value){var d=document.getElementsByClassName("cloud_dialog_share_document_selected_item");0<d.length&&(removeOrgSelectedItem(d[d.length-
1].getAttribute("superkey")),updateSearchInputWidth())}}return!0}catch(e){dalert(e)}}
function searchUserOnKeyInput(a,b,c){try{fnObjectCheckNull(c)&&(c=300);objCloudShareSearchTimer&&clearTimeout(objCloudShareSearchTimer);if(""==b)return cancelSearchUserInfoList();2>b.length||(objCloudShareSearchTimer=setTimeout(function(){var c=oneffice_cloud_user_info_search_index+=1;onefficeCommon.getSearchUserInfoList(a,b,function(a){c==oneffice_cloud_user_info_search_index&&makeSearchUserInfoList(a)})},c))}catch(d){dalert(d)}}
function makeSearchUserInfoList(a){try{if(fnObjectCheckNull(a)||0==a.length)return cancelSearchUserInfoList();document.getElementById("dze_idx_search_user_info_list_parent_div")&&cancelSearchUserInfoList();var b=document.getElementById("idx_dlg"),c=document.createElement("div");c.id="dze_idx_search_user_info_list_parent_div";c.innerHTML='<div id="dze_idx_search_user_info_list_div" style="position: absolute; width: 100%; height: 100%; left: 0; top: 0;"></div>';c.onclick=function(){cancelSearchUserInfoList()};
var d=document.createElement("div");d.id="dze_idx_search_user_info_list";d.className="cloud_search_user_info_list_container";for(var e=document.getElementById("dze_idx_share_document_selected_user").parentNode,f=e.offsetTop,g=e.offsetParent;g&&!dzeJ(g).hasClass("duzon_dialog");)f+=g.offsetTop,g=g.offsetParent;d.style.top=f+e.offsetHeight+"px";for(e=0;e<a.length;e++){var h=getSearchUserSelectItem(a[e],e);h&&(h.onclick=function(a){applySearchUserInfoList(a,this.userName,this.userSeq,!1,this.userLoginId,
this.emailAddr)},d.appendChild(h))}c.appendChild(d);b.appendChild(c)}catch(k){dalert(k)}}
function applySearchUserInfoList(a,b,c,d,e,f){try{if(1==fnObjectCheckNull(b)||1==fnObjectCheckNull(c)){var g=document.getElementsByClassName("cloud_search_user_info_item_div_sel");if(null==g)return;b=g[0].userName;c=g[0].userSeq;e=g[0].userLoginId;f=g[0].emailAddr}a=!1;for(g=0;g<oneffice_cloud_mygroup_shareIDList.length;g++)oneffice_cloud_mygroup_shareIDList[g].empSeq==c&&(cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_ALREADY_IN_USER,2),a=!0);0==a&&oneffice_cloud_mygroup_shareIDList.push({empName:b,
empSeq:c,searchItem:!0,loginId:e,emailAddr:f});initOrgSelectedItem();cancelSearchUserInfoList();objCloudShareSearchTimer&&clearTimeout(objCloudShareSearchTimer);var h=document.getElementById("dze_idx_share_document_selected_user_input");h.value="";h.placeholder="";0==fnObjectCheckNull(d)&&d&&h.focus()}catch(k){dalert(k)}}
function cancelSearchUserInfoList(){try{var a=document.getElementById("dze_idx_search_user_info_list"),b=document.getElementById("dze_idx_search_user_info_list_div"),c=document.getElementById("dze_idx_search_user_info_list_parent_div");return a||b||c?(a&&a.parentNode.removeChild(a),b&&b.parentNode.removeChild(b),c&&c.parentNode.removeChild(c),!0):!1}catch(d){dalert(d)}}
function getSearchUserSelectItem(a,b){try{if(null==a.path_name)return null;var c=a.path_name.split("|"),d=0;2<=c.length&&c[0]==c[1]&&(d=1);var e=c[d];for(d+=1;d<c.length;d++)e+="-"+c[d];var f=document.createElement("div");f.className="cloud_search_user_info_item_div";f.userName=a.name;f.userSeq=a.id;f.userLoginId=a.login_id;f.emailAddr=a.emailAddr;f.title=a.name+" "+a.duty_name+"\r\n"+e;c="";c='<table width="100%" cellspacing="0" cellpadding="1" style="border-collapse:collapse;">';c+="<tbody>";c+=
"<tr>";c+='<td width="40px" height="32px" style="text-align: center; border:0;" rowspan="2" colspan="1">';c+='<img class="cloud_search_user_info_pic" style="margin: 0 3px;" src="'+a.pic+'"></img>';c+="</td>";c+='<td width="210px" height="20px" style="border:0">';c+='<p class="cloud_search_user_info_main_name" style="width: 210px;">'+a.name+" "+a.duty_name+"</p>";c+="</td>";c+="</tr>";c+="<tr>";c+='<td width="210px" height="20" style="border:0;">';c+='<p class="cloud_search_user_info_sub_path">'+e+
"</p>";c+="</td>";c+="</tr>";f.innerHTML=c+"</tbody></table>";0==fnObjectCheckNull(b)&&0==b?f.className="cloud_search_user_info_item_div_sel":f.style.borderTop="1px solid lightgray";return f}catch(g){dalert(g)}}
function getSearchUserSimpleSelectItem(a,b,c,d,e,f){try{b=fnObjectCheckNull(b)?-1:b;fnObjectCheckNull(c);d=fnObjectCheckNull(d)?"R":d;oneffice_cloud_sharePermIndex+=1;c="";var g=document.createElement("div");g.className="cloud_search_simple_user_info_item_div";0<=b?(c=a.share_id,"2"==a.share_type?g.setAttribute("userName",a.share_comp_name):g.setAttribute("userName",a.share_org_name),g.setAttribute("userSeq",c),g.setAttribute("userLoginId",a.share_login_id)):(c=a.id,g.setAttribute("userName",a.name),
g.setAttribute("userSeq",c),g.setAttribute("userLoginId",a.login_id));c="";var h=a.share_org_name;fnObjectCheckNull(a.share_org_real_name)||a.share_org_name!=a.share_org_real_name&&0<a.share_org_real_name.length&&(h=a.share_org_name+"("+a.share_org_real_name+")");"2"==a.share_type&&(h=a.share_comp_name);c=0<=b?c+('<img title="'+h+'" class="cloud_search_user_info_pic" src="./image/cloud/img-profile-group-0'+(b%5+1)+'.png">'):c+('<img title="'+a.name+" "+a.duty_name+'" class="cloud_search_user_info_pic" src="'+
a.pic+'">');c+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; height: 27px; margin-top: 4px;">';c+="<tbody>";c+="<tr>";c+='<td style="width: 285px">';c+='<p class="cloud_search_user_info_main_name">'+(0<=b?h:a.name+" "+a.duty_name)+"</p>";c+="</td>";c+='<td style="width: 2px; padding: 0px;"></td>';f?(c+="<td"+(e?' colspan="3"':"")+' style="width: 74px;">',c+='<p style="width: 74px; text-align: right;"><span style="color: #999999;">'+ID_RES_CONST_STRING_OWNER+"</span></p>",
c+="</td>"):e?(c+='<td id="dze_idx_share_info_open_share_perm_'+oneffice_cloud_sharePermIndex+'" class="cloud_share_dialog_td_click_btn" shareType='+d.toLowerCase()+">",c+=getSharePermissionSelectButtonHTML("r"===d.toLowerCase()?SHARE_PERMISSION_OPTION_VIEW:SHARE_PERMISSION_OPTION_EDIT,oneffice_cloud_sharePermIndex),c+="</td>",c+='<td width="2px" style="padding: 0px;"></td>',c+='<td class="cloud_share_dialog_td_click_btn" style="width: 24px;">',c+='<img id="dze_idx_share_info_remove_btn_'+oneffice_cloud_sharePermIndex+
'" style="display: inline-block; vertical-align: middle;" src="./image/cloud/icon-close.png" onclick="removeCurrentPermission('+oneffice_cloud_sharePermIndex+')">',c+="</td>"):c+='<td style="width: 74px;"></td>';c+="</tr>";g.innerHTML=c+"</tbody></table>";return g}catch(k){dalert(k)}}function tempClick_copyShareLink(){}function tempClick_setShareDocumentPermission(){}
function removeCurrentPermission(a){try{if(!fnObjectCheckNull(a)){var b=document.getElementById("dze_idx_share_info_open_share_perm_"+a),c=document.getElementById("dze_idx_share_info_remove_btn_"+a);if("cloud_share_dialog_td_click_btn"==b.className)if(c.src="./image/cloud/icon-refresh.png",b&&(b.setAttribute("class","cloud_share_dialog_td_click_btn_disabled"),b.firstElementChild.outerHTML=b.firstElementChild.outerHTML.replace('onclick="','onclick="tempClick_'),b.style.backgroundColor="#F5F5F5"),0==
a){var d=b.parentNode;d.children[1].style.backgroundColor="#F5F5F5";d.children[3].style.backgroundColor="#F5F5F5";d.children[5].style.backgroundColor="#F5F5F5";d.children[3].setAttribute("class","cloud_share_dialog_td_click_btn_disabled");d.children[3].firstElementChild.outerHTML=d.children[3].firstElementChild.outerHTML.replace('onclick="','onclick="tempClick_')}else b.parentElement.getElementsByClassName("cloud_search_user_info_main_name")[0].style.opacity=.6;else c.src="./image/cloud/icon-close.png",
b&&(b.setAttribute("class","cloud_share_dialog_td_click_btn"),b.firstElementChild.outerHTML=b.firstElementChild.outerHTML.replace('onclick="tempClick_','onclick="'),b.style.backgroundColor=""),0==a?(d=b.parentNode,d.children[1].style.backgroundColor="",d.children[3].style.backgroundColor="",d.children[5].style.backgroundColor="",d.children[3].setAttribute("class","cloud_share_dialog_td_click_btn"),d.children[3].firstElementChild.outerHTML=d.children[3].firstElementChild.outerHTML.replace('onclick="tempClick_',
'onclick="')):b.parentElement.getElementsByClassName("cloud_search_user_info_main_name")[0].style.opacity=1}}catch(e){dalert(e)}}
function removeFromSharedUserList(a){try{for(var b=document.getElementsByClassName("cloud_search_simple_user_info_item_div"),c=0;c<b.length;c++)a==b[c].getAttribute("userSeq")&&(b[c].parentNode.removeChild(b[c]),c--);a=0;var d=document.getElementsByClassName("cloud_share_info_user_list");for(b=0;b<d.length;b++){var e=d[b].getElementsByClassName("cloud_search_simple_user_info_item_div").length;d[b].getElementsByTagName("span")[0].innerText="("+e+")";a+=e}document.getElementById("dze_idx_share_dialog_sharing_user_status").innerText=
String.format(ID_RES_CONST_STRING_SHARE_COUNT_STATUS,a);repositionCloseButton()}catch(f){dalert(f)}}
function getShareInfoDocumentContent(a,b){try{var c="";c+='<div id="dze_idx_share_info_container" class="cloud_share_info_container" docSeq='+a+">";c+='<div id="dze_idx_share_info_open_link_div" style="display:none;">';c+='<table cellpadding="0" cellspacing="0" width="100%" height="100%" style="background-color: white">';c+="<tbody>";c+="<tr>";c+="<td>";c+='<div class="cloud_share_dialog_sharing_user_info_title"><span>'+ID_RES_CONST_STRING_OPEN_LINK+"</span></div>";c+=getShareInfoOpenLink(a,b);c+=
"</td>";c+="</tr>";c+="</tbody>";c+="</table>";c+="</div>";c+='<div id="dze_idx_share_info_shared_user_div" style="display:none;">';c+='<div class="cloud_share_dialog_sharing_user_info_title"><span>'+ID_RES_CONST_STRING_SHARED_USER+"</span></div>";c+='<div id="dze_idx_permitted_user_list_div"></div>';c+="</div>";c+="</div>";loadPermittedUserInfo(a,!0,b);return c}catch(d){dalert(d)}}
function getShareLinkListContent(){try{for(var a=oneffice.getListViewMgr(),b='<div style="max-height:'+(g_objLayerKit.getLayerWindow().innerHeight-250)+'px; overflow:auto;">',c="",d=0;d<oneffice_cloud_checkedItemList.length;d++){var e=a.getDocTitle(oneffice_cloud_checkedItemList[d]);c=onefficeGW.getDocumentShareOpenURL(oneffice_cloud_checkedItemList[d].seq,oneffice_cloud_myInfoData.group_seq);0<d&&(b+='<div style="height:12px;"></div>',b+='<div style="height:12px; border-top:1px solid #EDEDED;"></div>');
b+='<table width="370" cellspacing=0 cellpadding=0 border=0>';b+="<tr>";b+='<td style="width:21px;height:21px; padding:0 2px 2px;" colspan="1">';b+='<img style="padding-top:4.5px;" src="./image/cloud/ico_cloud_share_link.png"></img>';b+="</td>";b+='<td width="349px" height="21px" colspan="6" style="border:0px; padding: 0 0 0 5px;">';b+='<p style="font-size:15px; text-overflow:ellipsis; white-space:nowrap; overflow:hidden; width:339px;">'+e+"</p>";b+="</td>";b+="</tr>";b+="<tr>";b+='<td style="width:285px; height:21px; border:1px solid #EDEDED; padding:4px; margin-right:5px;" colspan="5">';
b+='<p style="text-overflow:ellipsis; white-space:nowrap; overflow:hidden; width:285px;">'+c+"</p>";b+="</td>";b+='<td style="width:5px;"></td>';b+='<td width="70px" height="21px" style="border:1px solid #EDEDED; margin-left:5px; cursor:pointer;" colspan="1">';b+='<p style="text-align:center;" onclick="copyShareLink(\''+c+"');\">"+ID_RES_CONST_STRING_SHARE_LINK_COPY+"</p>";b+="</td>";b+="</tr>";b+="</table>"}return b+"</div>"}catch(f){dalert(f)}}
function getShareInfoOpenLink(a,b){try{var c=onefficeGW.getDocumentShareOpenURL(a,oneffice_cloud_myInfoData.group_seq);a="";var d="r";oneffice.parentFileContent&&oneffice.parentFileContent.share_perm&&(d=oneffice.parentFileContent.share_perm);a+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; margin: 0px 30px;">';a+="<tbody>";a+="<tr>";a+='<td style="text-align: center; border:0px;">';a+='<img style="display: table-cell; margin-right: 6px;" src="./image/cloud/icon-link.png">';
a+="</td>";a+='<td style="text-align: center; border:1px solid lightgray;">';a+='<p id="dze_idx_share_document_link" sharemode="R" title="'+c+'" style="width:224px;">'+c+"</p>";a+="</td>";a+='<td width="2px" style="padding: 0px;"></td>';a+='<td class="cloud_share_dialog_td_click_btn">';a+='<p id="dze_idx_share_link_copy" style="width: 53px; opacity:1;" onclick="copyShareLink(\''+c+"', true);\">"+ID_RES_CONST_STRING_SHARE_LINK_COPY+"</p>";a+="</td>";a+='<td width="2px" style="padding: 0px;"></td>';
b&&(a+='<td id="dze_idx_share_info_open_share_perm_0" class="cloud_share_dialog_td_click_btn" shareType="'+d+'">',a+=getSharePermissionSelectButtonHTML(SHARE_PERMISSION_OPTION_VIEW),a+="</td>");a+='<td width="2px" style="padding: 0px;"></td>';b&&(a+='<td class="cloud_share_dialog_td_click_btn" style="width: 24px;">',a+='<img id="dze_idx_share_info_remove_btn_0" style="display: inline-block; vertical-align: middle;" src="./image/cloud/icon-close.png" onclick="removeCurrentPermission(0)">',a+="</td>");
a+="</tr>";return a+"</tbody></table>"}catch(e){dalert(e)}}
function getSharePermissionSelectButtonHTML(a,b,c){try{fnObjectCheckNull(b)&&(b=0);fnObjectCheckNull(c)&&(c=!1);var d="";d+='<div id="dze_idx_share_permission_select_button_'+b+'" class="cloud_icon_no_boder_button" style="'+(0<b||c?"margin:0; float:right;":"")+(c?"background-color:lightgray;":"")+'" onclick="'+(c?"":"setShareDocumentPermission("+b+")")+'" shareViewMode="'+a+'">';switch(a){case SHARE_PERMISSION_OPTION_VIEW:d+='<img src="./image/cloud/ico_cloud_share_view.png" style="vertical-align: middle; padding-left:3px;" />';break;
case SHARE_PERMISSION_OPTION_EDIT:d+='<img src="./image/cloud/ico_cloud_share_edit.png" style="vertical-align: middle; padding-left:3px;" />';break;case SHARE_PERMISSION_OPTION_SHAREOFF:d+='<img src="./image/cloud/ico_cloud_share_unlink.png" style="vertical-align: middle; padding-left:3px;" />'}!1===c&&(d+='<img src="./image/cloud/ico_cloud_arrow_bottom.png" style="margin-left:2px;" />');return d+" </div>"}catch(e){dalert(e)}}
function setShareDocumentPermission(a){try{if(fnObjectCheckNull(a)&&(a=0),!removeShareDetailSelectItems()){var b=document.getElementById("idx_dlg"),c=document.createElement("div");c.id="dze_idx_share_document_select_parent_div";c.innerHTML='<div id="dze_idx_share_document_select_div" style="position: absolute; width: 100%; height: 100%; left: 0; top: 0;"></div>';c.onclick=function(){removeShareDetailSelectItems()};var d=document.createElement("div");d.id="dze_idx_share_document_select_permission";
d.className="cloud_share_document_select_org_permission";var e=getSharePermissionSelectItem(SHARE_PERMISSION_OPTION_VIEW,"cloud_share_document_select_permission");e.onclick=function(b){applyShareDocumentPermission(b,SHARE_PERMISSION_OPTION_VIEW,a)};var f=getSharePermissionSelectItem(SHARE_PERMISSION_OPTION_EDIT,"cloud_share_document_select_permission");f.onclick=function(b){applyShareDocumentPermission(b,SHARE_PERMISSION_OPTION_EDIT,a)};d.appendChild(e);d.appendChild(f);if(0==a&&0==dzeJ("#dze_idx_share_info_container").length){var g=
getSharePermissionSelectItem(SHARE_PERMISSION_OPTION_SHAREOFF,"cloud_share_document_select_permission");g.onclick=function(b){applyShareDocumentPermission(b,SHARE_PERMISSION_OPTION_SHAREOFF,a)};d.appendChild(g)}c.appendChild(d);b.appendChild(c);var h=document.getElementById("dze_idx_share_permission_select_button_"+a);setRepositionPermissionButtonSubDiv(d,h.parentNode)}}catch(k){dalert(k)}}
function removeShareDetailSelectItems(){try{var a=document.getElementById("dze_idx_share_document_select_div"),b=document.getElementById("dze_idx_share_document_select_permission"),c=document.getElementById("dze_idx_share_document_select_parent_div"),d=document.getElementById("dze_idx_share_type_select_div"),e=document.getElementById("dze_idx_share_type_select_permission"),f=document.getElementById("dze_idx_share_type_select_parent_div");return a||b||c||d||e||f?(b&&b.parentNode.removeChild(b),a&&
a.parentNode.removeChild(a),c&&c.parentNode.removeChild(c),d&&d.parentNode.removeChild(d),e&&e.parentNode.removeChild(e),f&&f.parentNode.removeChild(f),!0):!1}catch(g){dalert(g)}}
function setRepositionPermissionButtonSubDiv(a,b){try{if(a&&b){for(var c=b.offsetTop,d=b.offsetLeft,e=b.offsetParent;e&&!g_objPropertyUtil.hasClass(e,"duzon_dialog")&&"BODY"!==e.nodeName;)c+=e.offsetTop,d+=e.offsetLeft,e=e.offsetParent;for(e=b.parentNode;e&&!g_objPropertyUtil.hasClass(e,"duzon_dialog")&&"BODY"!==e.nodeName;)c-=e.scrollTop,d-=e.scrollLeft,e=e.parentNode;a.style.top=c+b.offsetHeight+"px";a.style.left=d+b.offsetWidth-a.offsetWidth+"px"}}catch(f){dalert(f)}}
function getShareDocumentSelectedMode(){try{var a="R",b=document.getElementById("dze_idx_share_permission_select_button_1");if(fnObjectCheckNull(b))return a;switch(b.getAttribute("shareViewMode")){case SHARE_PERMISSION_OPTION_VIEW:a="R";break;case SHARE_PERMISSION_OPTION_EDIT:a="W";break;case SHARE_PERMISSION_OPTION_SHAREOFF:a="S"}return a}catch(c){dalert(c)}}
function applyShareDocumentPermission(a,b,c,d){try{fnObjectCheckNull(c)&&(c=0);fnObjectCheckNull(d)&&(d=!0);var e=document.getElementById("dze_idx_share_permission_select_button_"+c);if(e&&e.outerHTML){e.outerHTML=getSharePermissionSelectButtonHTML(b,c);if(0==c){var f=document.getElementById("dze_idx_share_dialog_openlink_status"),g=document.getElementById("dze_idx_share_link_copy"),h=SHARE_TARGET.ALL,k=0;if(SHARE_PERMISSION_OPTION_SHAREOFF==b){for(var m=0;d&&m<oneffice_cloud_checkedItemList.length;m++)onefficeGW.unshareDocument(oneffice_cloud_checkedItemList[m].seq,
h,"",function(){k++;k===oneffice_cloud_checkedItemList.length&&(oneffice.parentFileContent.share_perm=0,dlog("\uacf5\uc720 \ud574\uc81c \uc644\ub8cc"))});f&&(f.innerText=ID_RES_CONST_STRING_STATUS_OFF);1===oneffice_cloud_checkedItemList.length&&(g.parentNode.className="cloud_share_dialog_td_click_btn_disabled",g.style.opacity=.5,g.onclick=null);updateShareBtnStatus(!1)}else{b=SHARE_PERMISSION_OPTION_VIEW==b?"R":"W";for(m=0;d&&m<oneffice_cloud_checkedItemList.length;m++)onefficeGW.shareDocument(oneffice_cloud_checkedItemList[m].seq,
h,"",b,function(a,b){k++;k===oneffice_cloud_checkedItemList.length&&(oneffice.parentFileContent.share_perm=b.share_perm,dlog("\uacf5\uc720 \uc644\ub8cc"))});f&&(f.innerText=ID_RES_CONST_STRING_STATUS_ON);var l="";1===oneffice_cloud_checkedItemList.length&&(l=onefficeGW.getDocumentShareOpenURL(oneffice_cloud_checkedItemList[0].seq,oneffice_cloud_myInfoData.group_seq),g.parentNode.className="cloud_share_dialog_td_click_btn",g.style.opacity=1,g.onclick=function(){copyShareLink(l,!0)});updateShareBtnStatus(!0)}}TBCancelBubbleEvent(a)}removeShareDetailSelectItems()}catch(p){dalert(p)}}
function getSharePermissionSelectItem(a,b){try{var c=document.createElement("div"),d=document.createElement("img");c.className=b;switch(a){case SHARE_TYPE_OPTION_MAIL:d.src="./image/cloud/ico_cloud_share_mail.png";d.style.float="left";c.innerText=ID_RES_CONST_STRING_MAIL_SHARE;break;case SHARE_TYPE_OPTION_NOTE:d.src="./image/cloud/ico_cloud_share_message.png";d.style.float="left";c.innerText=ID_RES_CONST_STRING_NOTE_SHARE;break;case SHARE_TYPE_OPTION_NONE:d.src="./image/cloud/ico_cloud_cancel.png";
d.style.float="left";c.innerText=ID_RES_DIALOG_STRING_NO_SELECT;break;case SHARE_PERMISSION_OPTION_VIEW:d.src="./image/cloud/ico_cloud_share_view.png";d.style.float="left";c.innerText=ID_RES_CONST_STRING_VIEWABLE;break;case SHARE_PERMISSION_OPTION_EDIT:d.src="./image/cloud/ico_cloud_share_edit.png";d.style.float="left";c.innerText=ID_RES_CONST_STRING_EDITABLE;break;case SHARE_PERMISSION_OPTION_SHAREOFF:d.src="./image/cloud/ico_cloud_share_unlink.png",d.style.float="left",c.innerText=ID_RES_CONST_STRING_LINK_OFF}a!==
SHARE_TYPE_OPTION_NOTE&&a!==SHARE_PERMISSION_OPTION_VIEW&&(c.style.borderTop="1px solid lightgray");c.appendChild(d);return c}catch(e){dalert(e)}}
function getShareDialogOpenLinkHTML(){try{var a="";a=1===oneffice_cloud_checkedItemList.length?onefficeGW.getDocumentShareOpenURL(oneffice_cloud_checkedItemList[0].seq,oneffice_cloud_myInfoData.group_seq):String.format(ID_RES_CONST_STRING_SELECTED_MULTI_DOCUMENT,oneffice_cloud_checkedItemList.length);var b="";b+='<span style="float:left;font-size:12px;font-weight:bold; padding-bottom:5px;">'+ID_RES_CONST_STRING_OPEN_LINK+"</span>";b+='<span id="dze_idx_share_dialog_openlink_status" style="float:right; color: #4AA6FB; font-size:11px; padding-bottom:5px;">'+
ID_RES_CONST_STRING_STATUS_OFF+"</span>";b+='<div style="width:100%; height:34px;display:flex;">';b+='<div style="border:1px solid lightgray;margin-right:2px;overflow:hidden;display:flex;align-items:center;">';b+='<p id="dze_idx_share_document_link" style="padding: 5px;" sharemode="R" title="'+a+'">'+a+"</p>";b+="</div>";b+='<div class="cloud_share_dialog_td_click_btn_disabled" style="margin-right:2px;flex-grow:0;display:table-cell; vertical-align:middle;">';b+='<p id="dze_idx_share_link_copy" style="opacity:0.5;white-space:nowrap;padding:5px;">'+
ID_RES_CONST_STRING_SHARE_LINK_COPY+"</p>";b+="</div>";b+='<div class="cloud_share_dialog_td_click_btn" style="flex-grow:0;display:table-cell; vertical-align:middle;">';b+=getSharePermissionSelectButtonHTML(SHARE_PERMISSION_OPTION_SHAREOFF);return b+"</div></div>"}catch(c){dalert(c)}}
function getShareDialogUserSharingHTML(){try{var a="";a+='<div id="cloud_share_container">';a+='<span id="dze_idx_share_dialog_sharing_user_status" onclick="openCloseUserSharing()" style="display:none; float:right; color: #4AA6FB; font-size:11px; padding-bottom:5px; cursor:pointer;">'+String.format(ID_RES_CONST_STRING_SHARE_COUNT_STATUS,0)+" ></span>";a+='<table width="100%" cellspacing="0" cellpadding="1" style="border-collapse:collapse;">';a+="<tbody>";a+='<tr style="height:33px;">';a+='<td style="font-size: 12px; font-weight: bold;">'+
ID_RES_CONST_STRING_USER_SHARING+"</td>";!1===g_browserCHK.isWebView()&&(a+='<td class="cloud_share_dialog_td_click_btn" style="width:45px;">',a+='<button id="dze_idx_cloud_share_group" class="cloud_icon_border_button" onclick="callOrganizationChart()" style=""><img src="./image/cloud/ico_cloud_org_chart.png" style="vertical-align: middle;"></button>',a+="</td>",a+='<td width="1px"></td>');a+='<td class="cloud_share_dialog_td_click_btn" style="width:45px;">';a+='<button id="dze_idx_cloud_my_group" class="cloud_icon_border_button" onclick="callMyGroupList(oneffice_cloud_mygroup_shareIDList)" style=""><img src="./image/cloud/ico_cloud_mygroup.png" style="vertical-align: middle;"></button>';
a+="</td>";a+='<td width="1px"></td>';a+='<td class="cloud_share_dialog_td_click_btn" style="width:45px;">';a+=getSharePermissionSelectButtonHTML(SHARE_PERMISSION_OPTION_VIEW,1);a+="</td>";a+="</tr>";a+='<tr style="height:4px;"></tr>';a+="<tr>";a+='<td colspan="6" style="text-align: center; border:1px solid lightgray;">';a+='<div id="dze_idx_share_document_selected_user"><input id="dze_idx_share_document_selected_user_input" placeholder="'+ID_RES_CONST_STRING_DEST_SHARE_USER+'" class="cloud_dialog_share_document_selected_user_input" type="text" style="padding:0px"></input></div>';
a+="</td>";a+="</tr>";a+="</tbody>";a+="</table>";a+="</div>";a+='<form id="frmOrgChartPop" name="frmOrgChartPop" method="post" style="display:none; width:0px; height:0px;">';a+='<input type="text" name="selectMode" value="ud"/>';a+='<input type="text" name="selectItem" value="m"/>';a+='<input id="dze_idx_share_selected_items" type="text" name="selectedItems" value=""/>';a+='<input type="text" name="callback" value="callbackOrgSelectList"/>';a+='<input type="text" name="callbackUrl" value="'+ONEFFICE_GW_API_ORGANIZATION_CALLBACK+
'"/>';return a+"</form>"}catch(b){dalert(b)}}
function getShareDialogMessageHTML(){try{var a=0<g_objEditContainer.length?"":" disabled",b="";b+='<div style="margin-top:4px;">';b+='<textarea id="dze_idx_share_document_add_comment" placeholder="'+ID_RES_CONST_STRING_ADD_MESSAGE+'"></textarea>';b+="<div class='duzon_dialog_share_noti_type'>";b+="<div><input type='radio' name='dze_share_noti_type' id='dze_idx_share_noti_type_note' checked /><label for='dze_idx_share_noti_type_note'>"+ID_RES_CONST_STRING_NOTE+"</label></div>";b+="<div><input type='radio' name='dze_share_noti_type' id='dze_idx_share_noti_type_mail'/><label for='dze_idx_share_noti_type_mail'>"+
ID_RES_CONST_STRING_MAIL+"</label></div>";b+="<div><input type='radio' name='dze_share_noti_type' id='dze_share_noti_type_oneffice'/><label for='dze_share_noti_type_oneffice'>"+ID_RES_CONST_STRING_BROWSER_SHARE+"</label></div>";b+="<div><input type='radio' name='dze_share_noti_type' id='dze_share_noti_type_external'"+a+"/><label for='dze_share_noti_type_external'>"+ID_RES_STRING_SEND_EXTERNAL+"</label></div>";b+="</div>";b+="<p id='dze_idx_share_external_noti' style='color:blue; display:none;'>\u203b "+
ID_RES_STRING_SEND_EXTERNAL_NOTI+"</p>";return b+"</div>"}catch(c){dalert(c)}}function applyShareSelectedItems(){try{for(var a=document.getElementById("dze_idx_share_selected_items"),b="",c=0;c<oneffice_cloud_shareIDList.length;c++)0!==c&&(b+=","),b+=oneffice_cloud_shareIDList[c].superKey;a.value=b}catch(d){dalert(d)}}
function callOrganizationChart(){try{var a=ONEFFICE_GW_API_ORGANIZATION,b=window.open("","cmmOrgPop","width=1200,height=800,scrollbars=no,resizable=yes,scrollbars=yes");frmOrgChartPop.target="cmmOrgPop";frmOrgChartPop.method="post";frmOrgChartPop.action=a;applyShareSelectedItems();frmOrgChartPop.submit();b.focus()}catch(c){dalert(c)}}
function callbackOrgSelectList(a){try{a.isSave?(oneffice_cloud_shareIDList=g_bBrowserType_IE||g_bBrowserType_EDGE?JSON.parse(JSON.stringify(a.returnObj)):getObjectClone(a.returnObj),initOrgSelectedItem()):dlog("\uc0ac\uc6a9\uc790\uac00 \ud31d\uc5c5\uc744 \ucde8\uc18c\ud558\uc600\uc2b5\ub2c8\ub2e4.")}catch(b){dalert(b)}}
function makeOrgSelectedItem(a){try{var b=document.createElement("div");b.className="cloud_dialog_share_document_selected_item";b.innerHTML="c"==a.empDeptFlag?a.compName:""!==a.empSeq?a.empName:a.deptName;b.setAttribute("superKey",a.superKey);b.innerHTML+=' <img width="14px" height="14px" src="./image/cloud/ico_cloud_cancel_seleted.png" style="position:relative; top:3px;" onclick="removeOrgSelectedItem(\''+a.superKey+"')\"/>";return b}catch(c){dalert(c)}}
function makeOrgSelectedItemOnMyGroup(a){try{var b=document.createElement("div");b.className="cloud_dialog_share_document_selected_item";b.innerHTML=a.empName;b.setAttribute("superKey",a.empSeq);b.innerHTML+=' <img width="14px" height="14px" src="./image/cloud/ico_cloud_cancel_seleted.png" style="position:relative; top:3px;" onclick="removeOrgSelectedItem(\''+a.empSeq+"')\"/>";return b}catch(c){dalert(c)}}
function removeOrgSelectedItem(a){try{for(var b=document.getElementsByClassName("cloud_dialog_share_document_selected_item"),c=0;c<b.length;c++)b[c].getAttribute("superKey")===a&&b[c].parentNode.removeChild(b[c]);if(0==b.length){var d=document.getElementById("dze_idx_share_document_selected_user_input");d&&d.org_placeholder&&(d.placeholder=d.org_placeholder)}for(c=0;c<oneffice_cloud_shareIDList.length;c++)oneffice_cloud_shareIDList[c].superKey===a&&oneffice_cloud_shareIDList.splice(c,1);for(c=0;c<
oneffice_cloud_mygroup_shareIDList.length;c++)oneffice_cloud_mygroup_shareIDList[c].empSeq===a&&oneffice_cloud_mygroup_shareIDList.splice(c,1)}catch(e){dalert(e)}}
function updateSharePermissionList(a){try{if(!1===(fnObjectCheckNull(a)?!1:a)&&0==oneffice_cloud_shareLinkPermItemOpened)return!1;a=!1;for(var b=0,c=[],d=document.getElementsByClassName("cloud_search_simple_user_info_item_div"),e=0;d&&e<d.length;e++)if("0.6"==d[e].getElementsByClassName("cloud_search_user_info_main_name")[0].style.opacity){for(var f=d[e].getAttribute("userSeq"),g=0;g<oneffice_cloud_sharePermORGList.length;g++)if(f==oneffice_cloud_sharePermORGList[g].share_id){c.push(oneffice_cloud_sharePermORGList[g]);
oneffice_cloud_sharePermORGList.splice(g,1);break}for(g=0;g<oneffice_cloud_sharePermPersonList.length;g++)if(f==oneffice_cloud_sharePermPersonList[g].share_id){c.push(oneffice_cloud_sharePermPersonList[g]);oneffice_cloud_sharePermPersonList.splice(g,1);break}}0<c.length&&(b=c.length,unShareDocumentWithSelectList(c));oneffice.getListViewMgr().m_nUpdateSharePermCnt=b;0===oneffice_cloud_shareIDList.length&&0===oneffice_cloud_mygroup_shareIDList.length&&(a=!0);return a}catch(h){dalert(h)}}
function changeSharePermissionList(a){try{for(var b=0,c=0<dzeJ("#dze_idx_share_info_container").length?dzeJ("#dze_idx_share_info_container").attr("docSeq"):oneffice.currFileSeq,d=dzeJ(".cloud_search_simple_user_info_item_div"),e=0;e<d.length;e++)if(1<d[e].getElementsByClassName("cloud_share_dialog_td_click_btn").length){var f=d[e].getElementsByClassName("cloud_share_dialog_td_click_btn")[0],g=f.getAttribute("sharetype"),h=f.firstElementChild.getAttribute("shareviewmode");if(g.toLowerCase()!=h.toLowerCase()){for(var k=
d[e].getAttribute("userSeq"),m,l=0;l<oneffice_cloud_sharePermORGList.length;l++)if(k==oneffice_cloud_sharePermORGList[l].share_id){m=parseInt(oneffice_cloud_sharePermORGList[l].share_type,10)==SHARE_TARGET.COMPANY?SHARE_TARGET.COMPANY:SHARE_TARGET.DEPARTMENT;break}for(l=0;l<oneffice_cloud_sharePermPersonList.length;l++)if(k==oneffice_cloud_sharePermPersonList[l].share_id){m=SHARE_TARGET.PERSON;break}if(""==c)for(l=0;l<oneffice_cloud_checkedItemList.length;l++)b++,onefficeGW.shareDocument(oneffice_cloud_checkedItemList[l].seq,
m,k,h,function(b){void 0!=a&&a();dlog("\uac1c\uc778 \uacf5\uc720 \uc644\ub8cc")});else b++,onefficeGW.shareDocument(c,m,k,h,function(b){void 0!=a&&a();dlog("\uac1c\uc778 \uacf5\uc720 \uc644\ub8cc")})}}return b}catch(p){dalert(p)}}function getShareNotificationType(){try{for(var a=document.getElementsByName("dze_share_noti_type"),b=0;b<a.length;b++)if(a[b].checked)return b;return-1}catch(c){dalert(c)}}
function openCloseUserSharing(){try{var a=document.getElementsByClassName("duzon_dialog_body_content")[0],b=document.getElementById("dze_idx_share_info_shared_user_div");fnObjectCheckNull(a)||fnObjectCheckNull(b)||(b.style&&"none"==b.style.display?(oneffice_cloud_shareLinkPermItemOpened=!0,a.style.width=a.offsetWidth-28+"px",a.style.float="left",b.style.height=a.offsetHeight+"px",b.style.display="",a.parentNode.style.width=a.offsetWidth+b.offsetWidth+"px",repositionCloseButton()):(a.style.width="auto",
a.style.float="",b.style.display="none",a.parentNode.style.width=""),setRepositionDialogOnCenter())}catch(c){dalert(c)}}
function repositionCloseButton(){try{var a=document.getElementById("dze_idx_share_info_shared_user_div"),b=document.getElementById("dze_idx_permitted_user_list_div"),c=document.getElementsByClassName("cloud_share_dialog_sharing_user_info_close_btn")[0];if(b&&c){var d=a.offsetWidth-b.offsetWidth;d=a.offsetWidth-b.offsetWidth;changeCss(".cloud_share_dialog_sharing_user_info_close_btn","right",d+"px",document)}}catch(e){dalert(e)}}
function loadSharingUserInfo(a){try{var b=oneffice.getListViewMgr().getShareOwnerID(oneffice_cloud_checkedItemList[0]);if(1===oneffice_cloud_checkedItemList.length&&(""===b||b===oneffice_cloud_myInfoData.id)){var c=document.getElementsByClassName("duzon_dialog_body_content")[0];if(c){var d=document.createElement("div");d.id="dze_idx_share_info_shared_user_div";d.style.display="none";d.className="cloud_share_dialog_sharing_user_info_container";b="";b+='<div class="cloud_share_dialog_sharing_user_info_title"><span>'+
ID_RES_CONST_STRING_SHARED_USER+"</span></div>";d.innerHTML=b+'<div id="dze_idx_permitted_user_list_div"></div><div class="cloud_share_dialog_sharing_user_info_close_btn" onclick="openCloseUserSharing()"><img src="./image/cloud/btn_close_share_user.png"/></div>';c.parentNode.appendChild(d)}loadPermittedUserInfo(oneffice_cloud_checkedItemList[0].seq,!1,a);setRepositionDialogOnCenter()}}catch(e){dalert(e)}}
function loadPermittedUserInfo(a,b,c){try{oneffice.getListViewMgr().getListViewType(),fnObjectCheckNull(b)&&(b=!1),onefficeGW.getShareInfo(a,function(a){var d=document.getElementById("dze_idx_permitted_user_list_div");if(!fnObjectCheckNull(d))if(d.innerHTML="",0===a.length){var f=document.createElement("p");f.style.float="left";f.style.color="gray";f.innerHTML=ID_RES_DIALOG_STRING_NONE;d.appendChild(f);cmnDlg.initPosition();dzeJ(cmnDlg.getDlg()).show()}else{a.sort(function(a,b){return a.share_date.time-
b.share_date.time});f=[];oneffice_cloud_sharePermORGList=[];oneffice_cloud_sharePermPersonList=[];oneffice_cloud_sharePermIndex=document.getElementById("dze_idx_share_permission_select_button_1")?1:0;for(var g=0;g<a.length;g++){var h=a[g];parseInt(a[g].share_type,10)==SHARE_TARGET.ALL?0===f.length&&f.push(h):parseInt(a[g].share_type,10)==SHARE_TARGET.DEPARTMENT?oneffice_cloud_sharePermORGList.push(h):parseInt(a[g].share_type,10)==SHARE_TARGET.COMPANY?oneffice_cloud_sharePermORGList.push(h):(h.owner_login_id!==
h.share_login_id||objOnefficeLoader.isDev()&&h.owner_id!==h.share_id)&&oneffice_cloud_sharePermPersonList.push(h)}g=0<oneffice_cloud_sharePermORGList.length?oneffice_cloud_sharePermORGList:[];0<oneffice_cloud_sharePermPersonList.length&&(g=g.concat(oneffice_cloud_sharePermPersonList));g.unshift({share_login_id:a[0].owner_login_id,share_perm:"W"});b?(0<f.length&&(a=document.getElementById("dze_idx_share_info_open_link_div"),h=document.getElementById("dze_idx_share_info_open_share_perm_0"),a&&(a.style.display=
""),null!=h&&(h.innerHTML="R"==f[0].share_perm?getSharePermissionSelectButtonHTML(SHARE_PERMISSION_OPTION_VIEW):getSharePermissionSelectButtonHTML(SHARE_PERMISSION_OPTION_EDIT),dzeJ(h.parentNode).attr("sharetype",f[0].share_perm.toLowerCase()))),d.appendChild(makeRenewPermittedUserItem(g,b,c)),0<g.length&&(document.getElementById("dze_idx_share_info_shared_user_div").style.display=""),document.getElementById("dze_idx_share_info_container").parentNode.style.padding="0",setRepositionDialogOnCenter()):
(d.appendChild(makeRenewPermittedUserItem(g,b,c)),0<f.length&&("R"==f[0].share_perm?applyShareDocumentPermission(null,SHARE_PERMISSION_OPTION_VIEW,0,!1):applyShareDocumentPermission(null,SHARE_PERMISSION_OPTION_EDIT,0,!1)),(d=document.getElementById("dze_idx_share_dialog_sharing_user_status"))&&0<g.length&&(d.style.display="",d.innerText=String.format(ID_RES_CONST_STRING_SHARE_COUNT_STATUS,oneffice_cloud_sharePermORGList.length+oneffice_cloud_sharePermPersonList.length)+" >"));setTimeout(function(){var a=
document.getElementsByClassName("cloud_share_info_user_list");if(null!=a&&0<a.length){var b=a[0].getElementsByClassName("cloud_search_simple_user_info_item_div");a=a[a.length-1].getElementsByClassName("cloud_search_simple_user_info_item_div");0<b.length&&(b[0].style.borderTop="0px",b[b.length-1].style.paddingBottom="1px");0<a.length&&(a[a.length-1].style.paddingBottom="10px")}cmnDlg.initPosition();dzeJ(cmnDlg.getDlg()).show()},200)}})}catch(d){dalert(d)}}
function makeRenewPermittedUserItem(a,b,c){try{var d=document.getElementById("dze_idx_permitted_user_list_div");d&&(d.style.display="");var e=document.createElement("div");e.className="cloud_share_info_user_list";e.style.padding="0";c||(e.style.width="390px");for(var f=0;f<a.length;f++)null!=a[f].share_login_id?function(){var d=0===f,h=a[f].share_login_id,k=a[f].share_perm;onefficeCommon.getSearchUserInfoList(CLOUD_CONST_SEARCH_USER_INFO_OPTION_ID,h,function(a){if(0<a.length){for(var f=0;f<a.length&&
a[f].login_id!==h;f++);f!=a.length&&(a=getSearchUserSimpleSelectItem(a[f],-1,b,k,c,d),d?e.insertBefore(a,e.firstChild):e.appendChild(a))}})}():null!=a[f].share_org_id?e.appendChild(getSearchUserSimpleSelectItem(a[f],f,b,a[f].share_perm,c)):function(){var d=0===f,h=a[f].share_id,k=a[f].share_perm;onefficeCommon.getSearchUserInfoList(CLOUD_CONST_SEARCH_USER_INFO_OPTION_ID,h,function(a){if(0<a.length){for(var f=0;f<a.length&&a[f].id!=h;f++);f!=a.length&&e.appendChild(getSearchUserSimpleSelectItem(a[f],
-1,b,k,c,d))}})}();return e}catch(g){dalert(g)}}
function getShareDocumentContentV2(){try{var a=document.createElement("div");a.className="cloud_share_dialog_main_container";var b=document.createElement("div");b.innerHTML=getShareDialogOpenLinkHTML();var c=document.createElement("div");c.style.cssText="margin-top: 25px; padding-top: 20px; border-top: 1px solid #eee;";var d=document.createElement("div");d.innerHTML=getShareDialogUserSharingHTML();var e=document.createElement("div");e.id="dze_idx_share_dialog_message_container";e.innerHTML=getShareDialogMessageHTML();
a.appendChild(b);a.appendChild(c);a.appendChild(d);a.appendChild(e);return a.outerHTML}catch(f){dalert(f)}}function createFolderMenu(a){try{!0!==fnObjectCheckNull(a)&&makeHomePopupWithType(CLOUD_POPUP_TYPE_FOLDER_MENU,a)}catch(b){dalert(b)}}function createCommonMenu(a){try{!0!==fnObjectCheckNull(a)&&makeHomePopupWithType(CLOUD_POPUP_TYPE_LIST_COMMON_MENU,a)}catch(b){dalert(b)}}
function createSortMenu(a){try{!0!==fnObjectCheckNull(a)&&makeHomePopupWithType(CLOUD_POPUP_TYPE_SORT_MENU,a)}catch(b){dalert(b)}}function createFilterMenu(a){try{!0!==fnObjectCheckNull(a)&&makeHomePopupWithType(CLOUD_POPUP_TYPE_FILTER_MENU,a)}catch(b){dalert(b)}}function createTrashMenu(a){try{!0!==fnObjectCheckNull(a)&&makeHomePopupWithType(CLOUD_POPUP_TYPE_TRASH_MENU,a)}catch(b){dalert(b)}}
function makeHomePopupWithType(a,b){try{if(dzeJ(".dze_idx_cloud_control_active").removeClass("dze_idx_cloud_control_active"),!closeHomePopup()){var c=document.createElement("div");c.id="dze_idx_new_item_select_parent_div";c.innerHTML='<div class="dze_idx_new_item_select_parent_sub_div" style="position: absolute; width: 100%; height: 100%; left: 0; top: 0;"></div>';c.onclick=function(){closeHomePopup()};var d=document.createElement("div");d.className="cloud_select_popup_container";switch(a){case CLOUD_POPUP_TYPE_FOLDER_MENU:dzeJ(".folder_nav_list_item").last().addClass("dze_idx_cloud_control_active");
dzeJ(".dze_idx_cloud_control_hover_dropdown").attr("src","./image/cloud/ico_cloud_menu_dropdown_active.png");addFolderMenuItemList(d);break;case CLOUD_POPUP_TYPE_LIST_COMMON_MENU:dzeJ("#cloud_list_menu_more").addClass("dze_idx_cloud_control_active");var e=dzeJ(b).find("img");e.attr("src",e.attr("src").replace("icon-menu-more-normal","icon-menu-more-click"));addCommonMenuItemList(d);break;case CLOUD_POPUP_TYPE_SORT_MENU:dzeJ("#dze_idx_cloud_control_sort").find("span:eq(0)").addClass("dze_idx_cloud_control_active");
addSortMenuItemList(d);break;case CLOUD_POPUP_TYPE_TRASH_MENU:addTrashMenuItemList(d);break;case CLOUD_POPUP_TYPE_FILTER_MENU:dzeJ("#dze_idx_cloud_control_filter").find("span:eq(0)").addClass("dze_idx_cloud_control_active"),addFilterMenuItemList(d)}c.appendChild(d);document.getElementById("dze_idx_cloud_container").appendChild(c);repositionHomePopup(a,b)}}catch(f){dalert(f)}}
function repositionHomePopup(a,b){try{if(!1===fnObjectCheckNull(b)){var c=dzeJ(b).offset(),d=dzeJ(".cloud_select_popup_container");if(d){d.css("top",c.top+35+"px");d.css("left",c.left+"px");var e=document.body;___cloudSelectPopupData.show=!0;___cloudSelectPopupData.nType=a;___cloudSelectPopupData.prevBodyWidth=e.style.width}}}catch(f){dalert(f)}}
function closeHomePopup(){try{var a=dzeJ("#cloud_list_menu_more.dze_idx_cloud_control_active").find("img"),b=dzeJ(".dze_idx_cloud_control_hover_dropdown");null!=a&&0<a.length&&a.attr("src",a.attr("src").replace("icon-menu-more-click","icon-menu-more-normal"));null!=b&&0<b.length&&b.attr("src","./image/cloud/ico_cloud_menu_dropdown.png");dzeJ(".dze_idx_cloud_control_active").removeClass("dze_idx_cloud_control_active");var c=dzeJ("#dze_idx_new_item_select_parent_div");if(0<c.length)return c.children(":nth-child(2)").slideUp(300,
function(){c.remove()}),___initCloudSelectPopupData(),!0;___initCloudSelectPopupData();return!1}catch(d){dalert(d)}}
function getHomePopupItem(a,b){try{var c=g_arrCloudCmd[a];if(c){var d=document.createElement("div");d.className="cloud_select_popup_item";d.id=c.id;d.innerText=c.text;var e=document.createElement("img");e.src=c.src;e.style.float="left";e.style.padding="0 7px 0 0";switch(a){case CLOUD_CMD_SORT_TITE:case CLOUD_CMD_SORT_RECENTDATE:case CLOUD_CMD_SORT_READDATE:case CLOUD_CMD_SORT_SHEREBYDATE:case CLOUD_CMD_SORT_FILESIZE:case CLOUD_CMD_SORT_SHEREDATE:case CLOUD_CMD_SORT_OWNER:m_SortOption!=a&&(e.style.opacity=
0);break;case CLOUD_CMD_FILTER_ALL:case CLOUD_CMD_FILTER_MY:case CLOUD_CMD_FILTER_BY:m_FilterOption!=a&&(e.style.opacity=0)}d.appendChild(e);d.onclick=function(c){executeCloudCommand(c,a,d,b)};return d}}catch(f){dalert(f)}}
function updateFilterSortList(){switch(m_FilterOption){case CLOUD_CMD_FILTER_ALL:m_SortOption=CLOUD_CMD_SORT_READDATE;m_SortType=VIEWSORT.READDATE;break;case CLOUD_CMD_FILTER_MY:m_SortOption=CLOUD_CMD_SORT_READDATE;m_SortType=VIEWSORT.READDATE;break;case CLOUD_CMD_FILTER_BY:m_SortOption=CLOUD_CMD_SORT_SHEREBYDATE,m_SortType=VIEWSORT.SHAREBYDATE}}
function executeCloudCommand(a,b,c,d){try{var e=oneffice.getListViewMgr(),f=oneffice_cloud_checkedItemList;switch(b){case CLOUD_CMD_CREATE_FOLDER:newFolder(a);break;case CLOUD_CMD_CREATE_FILE:oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_NEWSROOM||oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_MYNEWS_LIST||oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_SEND_MYNEWS_LIST?newArticle():newFile(!1);break;case CLOUD_CMD_MOVE:"folder_popup"===d?copyFileInBrowser(a,
oneffice_cloud_currFolderList,!0,!0):copyFileInBrowser(a,f,!0);break;case CLOUD_CMD_DELETE:"folder_popup"===d?onefficeGW.deleteDocument(oneffice_cloud_currFolderList[0],!0):onefficeGW.deleteDocumentList(f,!0);break;case CLOUD_CMD_FAVORITE_ON:"folder_popup"===d?onefficeGW.setFavorite(oneffice_cloud_currFolderSeq,!0):onefficeGW.setFavorite(f[0].seq,!0);break;case CLOUD_CMD_FAVORITE_OFF:"folder_popup"===d?onefficeGW.setFavorite(oneffice_cloud_currFolderList[0],!1):onefficeGW.setFavorite(f[0].seq,!1);
break;case CLOUD_CMD_RENAME:"folder_popup"===d?renameFile(a,oneffice_cloud_currFolderList[0],!0):renameFile(a,f[0]);break;case CLOUD_CMD_DOC_SECURITY:setDocumentSecurity(a,f[0]);break;case CLOUD_CMD_READONLY_ON:onefficeGW.setReadonly(f[0].seq,!0);break;case CLOUD_CMD_READONLY_OFF:onefficeGW.setReadonly(f[0].seq,!1);break;case CLOUD_CMD_SORT_TITE:m_SortOption=CLOUD_CMD_SORT_TITE;m_SortType=VIEWSORT.NAME;e.m_nSortArrowImgDegree=-90;updateSortFileList();break;case CLOUD_CMD_SORT_RECENTDATE:m_SortOption=
CLOUD_CMD_SORT_RECENTDATE;m_SortType=VIEWSORT.MODDATE;e.m_nSortArrowImgDegree=90;updateSortFileList();break;case CLOUD_CMD_SORT_READDATE:m_SortOption=CLOUD_CMD_SORT_READDATE;m_SortType=VIEWSORT.READDATE;e.m_nSortArrowImgDegree=90;updateSortFileList();break;case CLOUD_CMD_SORT_SHEREBYDATE:m_SortOption=CLOUD_CMD_SORT_SHEREBYDATE;m_SortType=VIEWSORT.SHAREBYDATE;e.m_nSortArrowImgDegree=90;updateSortFileList();break;case CLOUD_CMD_SORT_FILESIZE:m_SortOption=CLOUD_CMD_SORT_FILESIZE;m_SortType=VIEWSORT.SIZE;
updateSortFileList();break;case CLOUD_CMD_SORT_SHEREDATE:m_SortOption=CLOUD_CMD_SORT_SHEREDATE;m_SortType=VIEWSORT.SHAREDATE;updateSortFileList();break;case CLOUD_CMD_SORT_OWNER:m_SortOption=CLOUD_CMD_SORT_OWNER;m_SortType=VIEWSORT.OWNER;updateSortFileList();break;case CLOUD_CMD_TRASH_BIN:onefficeGW.clearTrashbox();break;case CLOUD_CMD_CHG_OWN:viewChgOwnReqDlg(a);break;case CLOUD_CMD_CHG_OWN_CANCEL:viewChgOwnCancelDlg(a);break;case CLOUD_CMD_UNLINK:unShareDocument(a);break;case CLOUD_CMD_SHARE:setShareDocument(a);
break;case CLOUD_CMD_COPY:case CLOUD_CMD_CLONE:oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_NEWSROOM||oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_MYNEWS_LIST?copyFileInNewsRoom(a,f,!1):copyFileInBrowser(a,f,!1);break;case CLOUD_CMD_DELETE_COMPLETE:onefficeGW.deleteCompleteDocument(f);break;case CLOUD_CMD_MORE:createCommonMenu(c);break;case CLOUD_CMD_RECOVERY:onefficeGW.restoreDocument(f);break;case CLOUD_CMD_MERGE:newFile(!0);this.resetCheckListFunc();break;case CLOUD_CMD_OPEN:onefficeGW.openDocument(f[0].seq);
break;case CLOUD_CMD_LINK_COPY:copyShareLink();break;case CLOUD_CMD_FILTER_ALL:m_FilterType=VIEWFILTER.ALL;m_FilterOption=CLOUD_CMD_FILTER_ALL;updateFilterSortList();updateSortFileList(!0);break;case CLOUD_CMD_FILTER_MY:m_FilterType=VIEWFILTER.MY;m_FilterOption=CLOUD_CMD_FILTER_MY;updateFilterSortList();updateSortFileList(!0);break;case CLOUD_CMD_FILTER_BY:m_FilterType=VIEWFILTER.BY;m_FilterOption=CLOUD_CMD_FILTER_BY;updateFilterSortList();updateSortFileList(!0);break;case CLOUD_CMD_DELETE_RECENT:deleteRecentList(f)}}catch(g){dalert(g)}}
function addCreateItemList(a){try{[CLOUD_CMD_CREATE_FILE,CLOUD_CMD_CREATE_FOLDER].forEach(function(b){a.appendChild(getHomePopupItem(b))})}catch(b){dalert(b)}}function addFolderMenuItemList(a){try{[CLOUD_CMD_MOVE,CLOUD_CMD_DELETE,CLOUD_CMD_FAVORITE_ON,CLOUD_CMD_RENAME].forEach(function(b){a.appendChild(getHomePopupItem(b,"folder_popup"))})}catch(b){dalert(b)}}
function addCommonMenuItemList(a){try{var b=oneffice.getListViewMgr().getMenuList();getMoreMenuList(b).forEach(function(b){a.appendChild(getHomePopupItem(b))})}catch(c){dalert(c)}}function getMoreMenuList(a){try{var b=getMoreMenuListAtTab(),c=getMoreMenuListAtSelection(),d=b.filter(function(a){return-1!==c.indexOf(a)});a&&(d=d.filter(function(b){return 0>a.indexOf(b)}));return d}catch(e){dalert(e)}}
function getMoreMenuListAtTab(){try{var a=null;switch(oneffice_cloud_currentBrowserMode){case CLOUD_CONST_BROWSER_MODE_MYONEFFICE:case CLOUD_CONST_BROWSER_MODE_SHARE:case CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST:case CLOUD_CONST_BROWSER_MODE_RECENT:case CLOUD_CONST_BROWSER_MODE_FAVORITE:case CLOUD_CONST_BROWSER_MODE_SECURITY:case CLOUD_CONST_BROWSER_MODE_SEARCH_RESULT:case CLOUD_CONST_BROWSER_MODE_UNIFIED_SEARCH:a=[CLOUD_CMD_FAVORITE_ON,CLOUD_CMD_FAVORITE_OFF,CLOUD_CMD_RENAME,CLOUD_CMD_READONLY_ON,
CLOUD_CMD_MERGE,CLOUD_CMD_READONLY_OFF,CLOUD_CMD_CHG_OWN,CLOUD_CMD_CHG_OWN_CANCEL,CLOUD_CMD_DOC_SECURITY];break;case CLOUD_CONST_BROWSER_MODE_NEWSROOM:case CLOUD_CONST_BROWSER_MODE_MYNEWS_LIST:case CLOUD_CONST_BROWSER_MODE_SEND_MYNEWS_LIST:a=[CLOUD_CMD_RENAME];break;default:a=[]}return a}catch(b){dalert(b)}}
function getMoreMenuListAtSelection(){try{var a=oneffice.getListViewMgr().getSelectionInfo();if(!a)return[];var b=[],c=a.getMyDocCount(),d=a.getImportantCount(),e=a.getReadonlyCount(),f=a.getChgOwnCount(),g=a.getSecurityCount(),h=a.getCount(),k=a.getFileCount(),m=a.getFolderCount(),l=1<h;g_arrCloudPopup.forEach(function(a){var n=!1;switch(a){case CLOUD_CMD_FAVORITE_ON:l||1!==k||c!==k||0!==d||(n=!0);break;case CLOUD_CMD_FAVORITE_OFF:l||1!==k||c!==k||1!==d||(n=!0);break;case CLOUD_CMD_RENAME:l||1!==
c||(n=!0);break;case CLOUD_CMD_READONLY_ON:l||1!==k||c!==k||0!==e||(n=!0);break;case CLOUD_CMD_READONLY_OFF:l||1!==k||c!==k||1!==e||(n=!0);break;case CLOUD_CMD_CHG_OWN:dzeUiConfig.bUseChgOwn&&0<h&&0===f&&c===k+m&&(n=!0);break;case CLOUD_CMD_CHG_OWN_CANCEL:dzeUiConfig.bUseChgOwn&&0<h&&f===h&&c===k+m&&(n=!0);break;case CLOUD_CMD_DOC_SECURITY:l||1!==k||c!==k||(n=!0);break;case CLOUD_CMD_MERGE:0===m&&0<h&&0===g&&(n=!0)}n&&b.push(a)});return b}catch(p){dalert(p)}}
function addSortMenuItemList(a){try{if(dlog(m_SortOption),oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_RECENT)m_FilterOption===CLOUD_CMD_FILTER_BY&&a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_SHEREBYDATE)),a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_READDATE));else if(a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_TITE)),a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_RECENTDATE)),a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_FILESIZE)),oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_SHARE||
oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST||oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_SHARED_BY_LIST)a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_SHEREDATE)),oneffice_cloud_currentBrowserMode!==CLOUD_CONST_BROWSER_MODE_MY_SHARE_LIST&&a.appendChild(getHomePopupItem(CLOUD_CMD_SORT_OWNER))}catch(b){dalert(b)}}
function addFilterMenuItemList(a){try{oneffice_cloud_currentBrowserMode==CLOUD_CONST_BROWSER_MODE_RECENT&&(a.appendChild(getHomePopupItem(CLOUD_CMD_FILTER_ALL)),a.appendChild(getHomePopupItem(CLOUD_CMD_FILTER_MY)),a.appendChild(getHomePopupItem(CLOUD_CMD_FILTER_BY)))}catch(b){dalert(b)}}function addTrashMenuItemList(a){try{a.appendChild(getHomePopupItem(CLOUD_CMD_TRASH_BIN))}catch(b){dalert(b)}}
function updateSortFileList(a){oneffice.m_FileItemListDiv.innerHTML="";clearShareProcess();var b=oneffice.getListViewMgr();if(a)return getFolderItemsInRecent(100,function(a){!1===oneffice_cloud_firstload&&0===a.length?(oneffice_cloud_firstload=!0,changeCurBrowserMode(CLOUD_CONST_BROWSER_MODE_RECENT),selectBrowserFolderItem("",!0)):g_updateListSuccessCB(!0,a)}),!1;oneffice_cloud_currentItemList=onefficeUtil.SortFileList(oneffice_cloud_currentItemList,b.m_nSortArrowImgDegree);updateFileList(oneffice_cloud_currFolderSeq,
!1);setCurThumbListData(oneffice_cloud_currFolderSeq);onefficeUtil.updateUserSortConfig(!0)}
function folderArrowClickEvent(a,b,c,d){if(1==a.parentNode.parentNode.getAttribute("open")){for(b=a.parentNode.parentNode.childNodes.length-1;1<=b;b--)"div"==a.parentNode.parentNode.childNodes[b].nodeName.toLowerCase()&&a.parentNode.parentNode.removeChild(a.parentNode.parentNode.childNodes[b]);a.parentNode.parentNode.setAttribute("open",0);a.innerHTML="<img src='./image/cloud/ico_cloud_arrow_right.png' />"}else onefficeGW.viewSubFolderTree(b+1,c,a.parentNode.parentNode,!1,d,function(b){0<b?(a.parentNode.parentNode.setAttribute("open",
1),a.innerHTML="<img src='./image/cloud/ico_cloud_arrow_bottom.png' />"):(a.parentNode.parentNode.setAttribute("open",0),a.innerHTML="\u3000")})}
function subTreeArrowIconChange(a){if(""!==a){var b=dzeJ('.viewFolderTreeItems[folderseq="'+a+'"]');a=dzeJ('.viewFolderTreeItems[folderseq="'+a+'"] > div:eq(0) > span:eq(1) > img');var c=a.attr("src");-1<c.indexOf("ico_cloud_arrow_right.png")?a.click():(a.attr("src",c.replace("blank.gif","/cloud/ico_cloud_arrow_bottom.png")),b[0].setAttribute("open","1"),b[0].ondblclick=function(a){this.childNodes[0].getElementsByTagName("span")[1].click();TBCancelBubbleEvent(a)},a[0].parentNode.onclick=function(a){var c=
b[0].getAttribute("folderdepth"),d=b[0].getAttribute("folderseq");folderArrowClickEvent(this,Number(c),d,function(a){onefficeGW.selectFolderSeq(a)});TBCancelBubbleEvent(a)})}}
function convertToText(a){switch(a){case CLOUD_CMD_SORT_TITE:return ID_RES_CONST_STRING_SORT_TITE;case CLOUD_CMD_SORT_RECENTDATE:return ID_RES_CONST_STRING_SORT_RECENTDATE;case CLOUD_CMD_SORT_FILESIZE:return ID_RES_CONST_STRING_SORT_FILESIZE;case CLOUD_CMD_SORT_SHEREDATE:return ID_RES_CONST_STRING_SORT_SHEREDATE;case CLOUD_CMD_SORT_SHEREBYDATE:return ID_RES_CONST_STRING_SORT_SHEREBYDATE;case CLOUD_CMD_SORT_READDATE:return ID_RES_CONST_STRING_SORT_READDATE;case CLOUD_CMD_SORT_OWNER:return ID_RES_CONST_STRING_SORT_OWNER;
case CLOUD_CMD_FILTER_ALL:return ID_RES_CONST_STRING_FILTER_ALL;case CLOUD_CMD_FILTER_MY:return ID_RES_CONST_STRING_FILTER_MY;case CLOUD_CMD_FILTER_BY:return ID_RES_CONST_STRING_FILTER_BY}}
function getChgOwnReqDlgContent(){var a='<div style="width:400px; font-size:13px; overflow:hidden;">'+('<div class="duzon_dialog_label_title" style="margin: 0px 0px 5px 1px;">'+ID_RES_STRING_CHG_OWN_TARGET+"</div>");a=a+'<div class="duzon_dialog_row" style="height:32px;margin-bottom:10px;"><div id="dze_idx_share_document_selected_user" style="border:1px solid lightgray;flex-grow: 1;">'+('<input id="dze_idx_share_document_selected_user_input" placeholder="'+ID_RES_STRING_CHG_OWN_PLACEHOLDER+'" class="cloud_dialog_share_document_selected_user_input" type="text" style="padding:0px;"></input>');
a+="</div>";!1===g_browserCHK.isWebView()&&(a+='<button id="dze_idx_cloud_share_group" class="cloud_share_dialog_td_click_btn cloud_icon_border_button" style="width:55px; height:100%; border:1px solid lightgray; margin-left:2px;" onclick="callOrganizationChart()"><img src="./image/cloud/ico_cloud_org_chart.png" style="vertical-align:middle;"></button>');a=a+'<button id="dze_idx_cloud_my_group" class="cloud_share_dialog_td_click_btn cloud_icon_border_button" style="width:55px; height:100%; border:1px solid lightgray; margin-left:2px;" onclick="callMyGroupList(oneffice_cloud_mygroup_shareIDList)"><img src="./image/cloud/ico_cloud_mygroup.png" style="vertical-align:middle;"></button></div><form id="frmOrgChartPop" name="frmOrgChartPop" method="post" style="display:none; width:0px; height:0px;"><input type="text" name="selectMode" value="u"/><input type="text" name="selectItem" value="s"/><input id="dze_idx_share_selected_items" type="text" name="selectedItems" value=""/><input type="text" name="callback" value="callbackOrgSelectList"/>'+
('<input type="text" name="callbackUrl" value="'+ONEFFICE_GW_API_ORGANIZATION_CALLBACK+'"/>');return a+"</form>"}function setSortItemList(a,b){m_SortOption=a;updateSortFileList()};
