var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(n){g(n)}}:b}var d,g,f=new e(function(a,b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return f};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,
d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");
var onefficeCommon={bExceptionExit:!1,onErrorCheckSession:function(a){try{switch(objOnefficeLoader.m_nAppEnvType){case APPENV.WE:var b=onefficeUtil.getCookieValue("AUTH_A_TOKEN");b&&0<b.trim().length&&"function"===typeof a&&a();break;case APPENV.GW:onefficeCommon.checkSession(function(b){"success"==b.result&&"1"==b.data.login?"function"===typeof a&&a():(!0===oneffice.useLoginApi?onefficeGW.viewLoginForm():onefficeCommon.showExpireSessionDialog(b.data.login_url),onefficeUtil.showDocSubject(),onefficeUtil.updateProgressBar(!0,
!0))})}}catch(c){dalert(c)}},checkSession:function(a){try{duzon_http.ajax({type:"get",url:ONEFFICE_SERVER_API_GET_CHECK_SESSION,async:!0,data:{},dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(b){"success"!==b.result&&dlog(b);"function"===typeof a&&a(b)},error:function(a){onefficeCommon.showServerErrorDialog();onefficeUtil.showDocSubject();onefficeUtil.updateProgressBar(!0,!0)}})}catch(b){dalert(b)}},getAccessUserFunctionInfo:function(a){try{duzon_http.ajax({type:"get",
url:ONEFFICE_SERVER_API_BASE_PATH+"getAccessUserFunctionInfo.do",async:!1,data:{},dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(b){if("success"!==b.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,"getAccessUserFunctionInfo",2,"screen_center")});else b=b.data,"function"===typeof a&&a(b)},error:function(a){dlog("getAccessUserFunctionInfo")}})}catch(b){dalert(b)}},getOnefficeUserEnv:function(a){try{duzon_http.ajax({type:"get",
url:ONEFFICE_SERVER_API_GET_ONEFFICE_USER_ENV,async:!1,data:{},dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(b){if("success"!==b.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,"ONEFFICE_SERVER_API_GET_ONEFFICE_USER_ENV",2,"screen_center")});else b=b.data,"function"===typeof a&&a(b[0])},error:function(a){dlog("error:getOnefficeUserEnv")}})}catch(b){dalert(b)}},updateOnefficeUserEnv:function(a,b,c){try{a={user_env:a},
!1===fnObjectCheckNull(b)&&(a.user_agree=b),duzon_http.ajax({type:"post",url:ONEFFICE_SERVER_API_POST_UPDATE_USER_ENV,async:!1,data:a,dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(a){if("success"!==a.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,"ONEFFICE_SERVER_API_POST_UPDATE_USER_ENV",2,"screen_center")});else"function"===typeof c&&c(a.result)},error:function(a){dlog("error:updateOnefficeUserEnv")}})}catch(d){dalert(d)}},
getSecurityInfo:function(a,b,c,d){try{if(this.isOnefficeGuideDoc(a))c(0);else{var e=fnObjectCheckNull(b)?"":b,f=onefficeUtil.getRequestParameter("groupseq");duzon_http.ajax({type:"post",url:ONEFFICE_SERVER_API_GET_SECURITY_INFO,async:!0,data:fnObjectCheckNull(f)?{doc_no:a,security_key:e}:{doc_no:a,security_key:e,groupSeq:f},dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(a){if("success"!==a.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,
ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT,2,"screen_center");"function"===typeof d&&d()});else 0<a.status&&(oneffice.currFileSecurityStatus=!0),"function"===typeof c&&c(a.status)},error:function(a){"function"===typeof d&&d(a);dalert(a)}})}}catch(g){dalert(g)}},getHTMLContent:function(a,b,c){try{var d=this.getOnefficeGuideDoc(a);if(d){var e=d.file;e=dzeEnvConfig.strPath_Document+e.split(".")[0]+"/"+e;duzon_http.readFile(e,{timeout:3E4,success:function(c){"SUCCESS"!==c.resultMessage&&dlog(c.resultMessage);
if(c){var f=onefficeCommon.newFileContent();f.seq=a;f.content=c;f.subject=d&&d.title?d.title:e.substring(e.lastIndexOf("/")+1);f.content_size=c.length;"function"===typeof b&&b(f)}},error:function(a){"function"===typeof c&&c(a);dlog("error:getHTMLContent.readFile")}})}else c(null)}catch(f){dalert(f)}},getFileContent:function(a,b,c,d,e,f,g){try{if(oneffice_cloud_currentBrowserMode===CLOUD_CONST_BROWSER_MODE_TRASHBOX)return!1;if(this.isOnefficeGuideDoc(a))onefficeCommon.getHTMLContent(a,b,c);else{"undefined"==
typeof e&&(e=onefficeUtil.getRequestParameter("groupseq"));var k=1==fnObjectCheckNull(f)?!1:f;!0===fnObjectCheckNull(g)&&(g=!0);var h=[];h.doc_no=a;!1===fnObjectCheckNull(e)&&(h.groupSeq=e);!1===fnObjectCheckNull(d)&&(h.security_key=d);duzon_http.ajax({type:"post",url:ONEFFICE_SERVER_API_GET_DOCUMENT,async:!0,data:h,dataType:"json",pid:"P536",timeout:3E4,loading_screen:g,loading_image_url:"",loading_image_size:[],success:function(a){if("success"===a.result&&a.data)"function"===typeof b&&b(onefficeCommon.convertDataToContent(a.data,
fnObjectCheckNull(h.security_key)?!1:!0),a);else oneffice.onErrorCheckSession(function(){k?b(null):!0!==g_browserCHK.mobile?(cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT,2,"screen_center"),setTimeout(function(){document.location.href=oneffice.drivePath},1E3)):cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT,99,"mobile")})},error:function(a){"function"===typeof c&&c(a);dalert(a)}})}}catch(l){dalert(l)}},getTempFileContent:function(a,
b,c,d,e,f,g){try{this.isOnefficeGuideDoc(a)?onefficeCommon.getHTMLContent(a,b,c):("undefined"==typeof e&&(e=onefficeUtil.getRequestParameter("groupseq")),!0===fnObjectCheckNull(g)&&(g=!0),f=[],f.doc_no=a,!1===fnObjectCheckNull(e)&&(f.groupSeq=e),!1===fnObjectCheckNull(d)&&(f.security_key=d),duzon_http.ajax({type:"post",url:ONEFFICE_SERVER_API_GET_DOCUMENT,async:!0,data:f,dataType:"json",pid:"P536",timeout:3E4,loading_screen:g,loading_image_url:"",loading_image_size:[],success:function(a){"success"===
a.result&&a.data?b(!0):b(!1)},error:function(a){"function"===typeof c&&c(a);dalert(a)}}))}catch(k){dalert(k)}},accessUserFunction:function(a){try{var b=onefficeCommon.getUserInfoOsAppType(),c=onefficeUtil.getRequestParameter("groupseq");duzon_http.ajax({type:"post",url:ONEFFICE_SERVER_API_POST_ACCESS_USER_FUNCTION,async:!0,data:fnObjectCheckNull(c)?{os_type:b.os_type,app_type:b.app_type,call_url:a}:{os_type:b.os_type,app_type:b.app_type,call_url:a,groupSeq:c},dataType:"json",timeout:3E4,loading_screen:!0,
loading_image_url:"",loading_image_size:[],bShowLoading:!1,success:function(a){dlog("accessUserFunction Response : "+a.result)},error:function(a){dlog("error:accessUserFunction")}})}catch(d){dalert(d)}},getUserInfoOsAppType:function(){try{var a="13",b="13";g_browserCHK.mobile&&(g_browserCHK.iOS?(a="01",b=g_browserCHK.iPad?"12":"11"):g_browserCHK.android?(a="02",b=g_browserCHK.androidtablet?"12":"11"):(a="03",b="11"));return{os_type:a,app_type:b}}catch(c){dalert(c)}},convertDataToContent:function(a,
b){try{if("undefined"===typeof a.doc_no)return null;var c=onefficeCommon.newFileContent();c.seq=a.doc_no;c.type=a.doc_type?a.doc_type:0;c.folderSeq=a.folder_no?a.folder_no:"";var d=new Date;c.regdate=a.reg_date?a.reg_date:d.getTime();a.doc_name&&(c.subject=a.doc_name);c.content=a.content?a.content:"";c.content_size=a.content_size?a.content_size:0;c.owner_id=a.owner_id?a.owner_id:"";c.owner_login_id=a.owner_login_id?a.owner_login_id:"";c.owner_name=a.owner_name?a.owner_name:"";c.owner_org_id=a.owner_org_id?
a.owner_org_id:"";c.owner_org_name=a.owner_org_name?a.owner_org_name:"";c.keyword=a.keyword?a.keyword:"";c.readonly=a.readonly?a.readonly:0;c.moddate=a.mod_date?a.mod_date:d.getTime();c.accessdate=a.access_date?a.access_date:d.getTime();c.important=a.important?a.important:0;c.deleted=a.deleted?a.deleted:"";c.share_id=a.share_id?a.share_id:"";c.share_type=a.share_type?a.share_type:0;c.share_perm=a.share_perm?a.share_perm:"R";c.share_date=a.share_date?a.share_date:"";c.share_count=a.share_count?a.share_count:
0;c.my_id=a.my_id?a.my_id:"";c.security_key=a.security_key?a.security_key:"0";c.bSecure=b;c.strThumbnail=a.thumbnail&&a.thumbnail.length?a.thumbnail:"";c.openFileDate=a.openFileDate?a.openFileDate:"";c.openPath=a.openPath?a.openPath:"";c.mobile_gateway_url=a.mobile_gateway_url;c.gw_url=a.gw_url;if(dzeUiConfig.bUseChgOwn){var e=oneffice_cloud_chgOwnInfo.req_doc_list;e&&-1<e.indexOf(c.seq)&&(c.owner_change=!0)}return c}catch(f){dalert(f)}},newFileContent:function(){return{type:1,seq:"",folderSeq:"",
subject:"",content:"",content_size:0,owner_id:"",owner_login_id:"",owner_name:"",owner_org_id:"",owner_org_name:"",owner_change:!1,keyword:"",readonly:0,regdate:"",moddate:"",accessdate:"",important:0,deleted:0,share_id:"",share_type:0,share_perm:"R",share_date:"",share_count:"",security_key:"0",strThumbnail:"",bSecure:!1}},getCheckPasswordForm:function(){try{var a=document.createElement("div");a.id="dze_idx_check_password_container";a.style.width="auto";a.style.height="auto";var b=document.createElement("label");
b.innerText=ID_RES_CONST_STRING_INPUT_PASSWORD+"\r\n\n";a.appendChild(b);var c=document.createElement("input");c.id="dze_idx_check_password_input";c.style="width:308px; font-size: 24px !important; padding: 0 5px; border-width: 1px;";c.setAttribute("type","password");c.setAttribute("maxlength","20");c.setAttribute("autocomplete","off");a.appendChild(c);return a.outerHTML}catch(d){dalert(d)}},getDocOpenAllow:function(){try{if(0==g_browserCHK.mobile)return onefficeCommon.getDocOpenAllowWeb();var a="";
a=g_browserCHK.iPad||g_browserCHK.androidtablet?a+'<div class="doc_info_top_div" style="border-bottom: 0px; padding: 0; transform: scale(0.8);">':a+'<div class="doc_info_top_div">';a+='\t<div class="doc_alert_icon">';a+='\t\t<img src="'+dzeEnvConfig.strPath_Image+'dialog/icon_quest.png">';a+="\t</div>";a+='\t<div id="dze_idx_doc_allow_title" class="doc_alert_title"></div>';a+='\t<div class="doc_alert_title">'+ID_RES_CONST_STRING_ALLOW_PERMISSION+"</div>";a+="</div>";g_browserCHK.iPad||g_browserCHK.androidtablet?
(a+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; width:568px; margin:40px;">',a+="\t<tbody>",a+='\t\t<tr style="border-top:1px solid #dddddd;">',a+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT+"</td>",a+='\t\t\t<td colspan="3" id="dze_idx_doc_info_subject" class="doc_info_detail_pad"></td>',a+="\t\t</tr>",a+='\t\t<tr style="border-top:1px solid #dddddd;">',a+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_CONST_STRING_CREATE_DATE+
"</td>",a+='\t\t\t<td id="dze_idx_doc_info_newdate" class="doc_info_detail_pad"></td>',a+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_CONST_STRING_MODIFY_DATE+"</td>",a+='\t\t\t<td id="dze_idx_doc_info_moddate" class="doc_info_detail_pad"></td>',a+="\t\t</tr>",a+='\t\t<tr style="border-top:1px solid #dddddd;">',a+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_DIALOG_STRING_SIZE+"</td>",a+='\t\t\t<td id="dze_idx_doc_info_size" class="doc_info_detail_pad"></td>',a+="\t\t\t<td></td>",a+="\t\t\t<td></td>"):
(a+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; width:568px; margin:40px;">',a+="\t<tbody>",a+="\t\t<tr>",a+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT+"</td>",a+='\t\t\t<td id="dze_idx_doc_info_subject" class="doc_info_detail"></td>',a+="\t\t</tr>",a+="\t\t<tr>",a+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_CREATE_DATE+"</td>",a+='\t\t\t<td id="dze_idx_doc_info_newdate" class="doc_info_detail"></td>',a+="\t\t</tr>",
a+="\t\t<tr>",a+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_MODIFY_DATE+"</td>",a+='\t\t\t<td id="dze_idx_doc_info_moddate" class="doc_info_detail"></td>',a+="\t\t</tr>",a+="\t\t<tr>",a+='\t\t\t<td class="doc_info_title">'+ID_RES_DIALOG_STRING_SIZE+"</td>",a+='\t\t\t<td id="dze_idx_doc_info_size" class="doc_info_detail"></td>');a+="\t\t</tr>";a+="\t</tbody>";return a+"</table>"}catch(b){dalert(b)}},getDocOpenAllowWeb:function(){try{var a="";a+='<div class="doc_info_top_div" style="padding: 0 0 10px;">';
a+='\t<div class="doc_alert_icon">';a+='\t\t<img src="'+dzeEnvConfig.strPath_Image+'dialog/icon_quest.png">';a+="\t</div>";a+='\t<div id="dze_idx_doc_allow_title" class="doc_alert_title"></div>';a+='\t<div class="doc_alert_title">'+ID_RES_CONST_STRING_ALLOW_PERMISSION+"</div>";a+="</div>";a+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; width:568px; margin:10px 40px 0;">';a+="\t<tbody>";a+="\t\t<tr>";a+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT+
"</td>";a+='\t\t\t<td id="dze_idx_doc_info_subject" class="doc_info_detail"></td>';a+="\t\t</tr>";a+="\t\t<tr>";a+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_CREATE_DATE+"</td>";a+='\t\t\t<td id="dze_idx_doc_info_newdate" class="doc_info_detail"></td>';a+="\t\t</tr>";a+="\t\t<tr>";a+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_MODIFY_DATE+"</td>";a+='\t\t\t<td id="dze_idx_doc_info_moddate" class="doc_info_detail"></td>';a+="\t\t</tr>";a+="\t\t<tr>";a+='\t\t\t<td class="doc_info_title">'+
ID_RES_DIALOG_STRING_SIZE+"</td>";a+='\t\t\t<td id="dze_idx_doc_info_size" class="doc_info_detail"></td>';a+="\t\t</tr>";return a+"\t</tbody></table>"}catch(b){dalert(b)}},getDocOpenInfo:function(a){try{var b="";a?(b=g_browserCHK.iPad||g_browserCHK.androidtablet?b+'<div class="doc_info_top_div" style="border-bottom: 0px; padding: 0; transform: scale(0.8);">':b+'<div class="doc_info_top_div">',b+='\t<div id="dze_idx_doc_info_thumb">',b+="\t</div>",b+='\t<div id="dze_idx_doc_info_ico_sec" class="doc_info_icon" style="background-color: #fe785e; display: none;">',
b+='\t\t<img style="padding: 16px;" src="'+dzeEnvConfig.strPath_Image+'dialog/icon_doc_security.png">',b+="\t</div>",b+='\t<div id="dze_idx_doc_info_ico_read" class="doc_info_icon" style="background-color: #4a80f7; display: none;">',b+='\t\t<img style="padding: 16px;" src="'+dzeEnvConfig.strPath_Image+'dialog/icon_doc_readonly.png">',b+="\t</div>",b+='\t<div id="dze_idx_doc_info_ico_share" class="doc_info_icon" style="background-color: #05b59e; display: none;">',b+='\t\t<img style="padding: 16px;" src="'+
dzeEnvConfig.strPath_Image+'dialog/icon_doc_share.png">',b+="\t</div>",b+='\t<div id="dze_idx_doc_info_ico_mod" class="doc_info_icon" style="background-color: #a358ef; display: none;">',b+='\t\t<img style="padding: 16px;" src="'+dzeEnvConfig.strPath_Image+'dialog/icon_doc_modify.png">',b+="\t</div>"):(b=g_browserCHK.iPad||g_browserCHK.androidtablet?b+'<div class="doc_info_top_div" style="border-bottom: 0px; padding: 0; transform: scale(0.8);">':b+'<div class="doc_info_top_div">',b+='\t<div class="doc_alert_icon">',
b+='\t\t<img src="'+dzeEnvConfig.strPath_Image+'dialog/icon_alert.png">',b+="\t</div>",b+='\t<div class="doc_alert_title">'+ID_RES_CONST_STRING_NO_PERMMISION+"</div>",b+='\t<div class="doc_alert_title_detail">'+ID_RES_CONST_STRING_NO_PERMMISION_INFO+"</div>");b+="</div>";g_browserCHK.iPad||g_browserCHK.androidtablet?(b+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; width:800px; margin:0 50px;">',b+="\t<tbody>",b+='\t\t<tr style="border-top:1px solid #dddddd;">',b+='\t\t\t<td class="doc_info_title_pad">'+
ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_subject" class="doc_info_detail_pad"></td>',b+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_OWNER+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_owner" class="doc_info_detail_pad"></td>',b+="\t\t</tr>",b+='\t\t<tr style="border-top:1px solid #dddddd;">',b+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_CONST_STRING_CREATE_DATE+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_newdate" class="doc_info_detail_pad"></td>',
b+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_CONST_STRING_MODIFY_DATE+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_moddate" class="doc_info_detail_pad"></td>',b+="\t\t</tr>",b+='\t\t<tr style="border-top:1px solid #dddddd;">',b+='\t\t\t<td class="doc_info_title_pad">'+ID_RES_DIALOG_STRING_SIZE+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_size" class="doc_info_detail_pad"></td>',b+="\t\t\t<td></td>",b+="\t\t\t<td></td>"):(b+='<table cellspacing="0" cellpadding="1" style="border-collapse:collapse; width:568px; margin:40px;">',
b+="\t<tbody>",b+="\t\t<tr>",b+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_subject" class="doc_info_detail"></td>',b+="\t\t</tr>",b+="\t\t<tr>",b+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_OWNER+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_owner" class="doc_info_detail"></td>',b+="\t\t</tr>",b+="\t\t<tr>",b+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_CREATE_DATE+"</td>",b+=
'\t\t\t<td id="dze_idx_doc_info_newdate" class="doc_info_detail"></td>',b+="\t\t</tr>",b+="\t\t<tr>",b+='\t\t\t<td class="doc_info_title">'+ID_RES_CONST_STRING_MODIFY_DATE+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_moddate" class="doc_info_detail"></td>',b+="\t\t</tr>",b+="\t\t<tr>",b+='\t\t\t<td class="doc_info_title">'+ID_RES_DIALOG_STRING_SIZE+"</td>",b+='\t\t\t<td id="dze_idx_doc_info_size" class="doc_info_detail"></td>');b+="\t\t</tr>";b+="\t</tbody>";return b+"</table>"}catch(c){dalert(c)}},
getDocRequestConfirm:function(){try{var a="";a+='<div class="doc_info_top_div">';a+='\t<div class="doc_alert_icon">';a+='\t\t<img src="'+dzeEnvConfig.strPath_Image+'dialog/icon_confirm.png">';a+="\t</div>";a+='\t<div class="doc_alert_title">'+ID_RES_CONST_STRING_REQUEST_CONFIRM+"</div>";return a+"</div>"}catch(b){dalert(b)}},getDocAllowMessage:function(a){try{var b="";b+='<div class="doc_info_top_div">';b+='\t<div class="doc_alert_icon">';b+='\t\t<img src="'+dzeEnvConfig.strPath_Image+'dialog/icon_confirm.png">';
b+="\t</div>";return b+('\t<div class="doc_alert_title">'+a+"</div>")+"</div>"}catch(c){dalert(c)}},getMyInfo:function(a,b,c){try{"undefined"==typeof b&&(b=!0),!0===fnObjectCheckNull(c)&&(c=!0),!0!==onefficeCommon.bExceptionExit&&duzon_http.ajax({type:"get",url:ONEFFICE_SERVER_API_GET_MY_INFO,async:c,data:{},dataType:"json",timeout:!0===c?3E4:5E3,loading_screen:!0,loading_image_url:"",loading_image_size:[],bShowLoading:!1,success:function(c){!0===b&&"success"!==c.result?(oneffice.onErrorCheckSession(function(){0<
document.location.href.indexOf(oneffice.drivePath)&&cmnCtrlToast.showToastMsg(null,"GET_MY_INFO_FAIL",2,"screen_center")}),onefficeCommon.bExceptionExit=!0,"undefined"===typeof c.result&&cmnMsg.showMsg(MESSAGE_ALERT,ID_RES_STRING_NO_MYINFO,null,[ID_RES_DIALOG_BTN_OK],function(){window.close()})):(c&&c.data&&(c.data.report_yn="Y"),"function"===typeof a&&a(c.data))},error:function(a){302==a.status&&(onefficeCommon.bExceptionExit=!0,cmnMsg.showMsg(MESSAGE_ALERT,ID_RES_STRING_NO_MYINFO,null,[ID_RES_DIALOG_BTN_OK],
function(){window.close()}));dalert(a)}})}catch(d){dalert(d)}},getDocumentAccessInfo:function(a,b,c){try{!0===fnObjectCheckNull(c)&&(c=!0),duzon_http.ajax({type:"get",url:ONEFFICE_SERVER_API_GET_DOCUMENT_ACCESS_INFO,async:c,data:{doc_no:a},dataType:"json",timeout:!0===c?3E4:5E3,loading_screen:!0,loading_image_url:"",loading_image_size:[],bShowLoading:!1,success:function(a){if("success"!==a.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,"GET_DOCUMENT_ACCESS_INFO_FAIL",
2,"screen_center")});else"function"===typeof b&&b(a.data)},error:function(a){dalert(a)}})}catch(d){dalert(d)}},getSearchUserInfoList:function(a,b,c,d){try{!0===fnObjectCheckNull(d)&&(d=!0),duzon_http.ajax({type:"get",url:ONEFFICE_SERVER_API_GET_SEARCH_USER_INFO_LIST,async:d,data:{option:a,txt_search:b},dataType:"json",timeout:!0===d?3E4:5E3,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(a){if("success"!==a.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,
"ONEFFICE_SERVER_API_GET_SEARCH_USER_INFO_LIST",2,"screen_center")});else a=a.data,"function"===typeof c&&c(a)},error:function(a){dlog("error:getSearchUserInfoList")}})}catch(e){dalert(e)}},accessDocumentHistory:function(a,b,c,d){try{if(fnObjectCheckNull(d)&&(d=0),fnObjectCheckNull(oneffice_cloud_myInfoData))3<=d||setTimeout(function(){onefficeCommon.accessDocumentHistory(a,b,c,d+1)},100);else{var e=onefficeCommon.getDeviceInfo(),f={doc_no:a,action_user:oneffice_cloud_myInfoData.id,action_user_name:oneffice_cloud_myInfoData.duty_name?
oneffice_cloud_myInfoData.name+" "+oneffice_cloud_myInfoData.duty_name:oneffice_cloud_myInfoData.name,action_code:b,device_info:e.device_type};!1===fnObjectCheckNull(c)&&(f.action_data=c);duzon_http.ajax({type:"post",url:ONEFFICE_SERVER_API_POST_ACCESS_DOCUMENT_HISTORY,async:!0,data:f,dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],bShowLoading:!1,success:function(a){if("success"!==a.result)oneffice.onErrorCheckSession(function(){cmnCtrlToast.showToastMsg(null,
"ONEFFICE_SERVER_API_POST_ACCESS_DOCUMENT_HISTORY",2,"screen_center")})},error:function(a){dlog("error:accessDocumentHistory")}})}}catch(g){dalert(g)}},getDeviceInfo:function(){try{var a=CLOUD_CONST_DEVICE_CODE_PC;g_browserCHK.mobile&&(a=g_browserCHK.iOS?g_browserCHK.iPad?CLOUD_CONST_DEVICE_CODE_IPAD:CLOUD_CONST_DEVICE_CODE_IPHONE:g_browserCHK.android?g_browserCHK.androidtablet?CLOUD_CONST_DEVICE_CODE_ANDROID_PAD:CLOUD_CONST_DEVICE_CODE_ANDROID_PHONE:CLOUD_CONST_DEVICE_CODE_ETC);return{device_type:a}}catch(b){dalert(b)}},
getGPSLocation:function(a){try{navigator.geolocation?navigator.geolocation.getCurrentPosition(function(b){b=[b.coords.latitude,b.coords.longitude];"function"===typeof a&&a(b)},function(b){dlog("onefficeCommon.getGPSLocation error");"function"===typeof a&&a(null)},{enableHighAccuracy:!1,maximumAge:0,timeout:Infinity}):(dlog("GPS not supported."),"function"===typeof a&&a(null))}catch(b){dalert(b)}},openWindow:function(a,b,c){try{if(g_browserCHK.isWebView()&&g_browserCHK.iOS&&dzeUiConfig.bUseHybridInterface){var d=
{};a||(a="about:blank");/^https?:\/\/|^\/\//i.test(a)&&!startsWith(a,"/")&&(a+="/");d.subUrl=a;d.pushYn="_self"!=b||window.name!=b?"y":"n";d.title="ONEFFICE";callApp("gotoPage",d)}else return window.open.apply(window,Array.prototype.slice.call(arguments));return null}catch(e){dalert(e)}},isOnefficeGuideDoc:function(a){return this.getOnefficeGuideDoc(a)?!0:!1},getOnefficeGuideDoc:function(a){try{for(var b=g_arrGuideDoc,c=0,d=b.length;c<d;c++)if(b[c].seq==a)return b[c];return null}catch(e){dalert(e)}},
showExpireSessionDialog:function(a){try{duzon_dialog.viewDialog(null,0,ID_RES_CONST_STRING_LOGIN_GUIDE_TITLE,ID_RES_CONST_STRING_LOGIN_GUIDE_CONTENT,2,[ID_RES_DIALOG_BTN_OK,ID_RES_DIALOG_BTN_CANCEL],[function(b){duzon_dialog.closeDialog();window.open().location=a;setTimeout(function(){onefficeCommon.showContinueDialog()},3E3)},function(a){confirm(ID_RES_CONST_STRING_CLOSE_WINDOW)?window.close():duzon_dialog.closeDialog()}],function(){},function(){},!0,"screen_center")}catch(b){dalert(b)}},showServerErrorDialog:function(){try{cmnMsg.showMsg(MESSAGE_ERROR,
ID_RES_CONST_STRING_SERVER_ERROR_CONTENT,null,[ID_RES_DIALOG_BTN_OK],function(){cmnMsg.hideMsg()},null,!0)}catch(a){dalert(a)}},showContinueDialog:function(){try{var a=ID_RES_CONST_STRING_DOCUMENT_CONTINUE_WRITE;oneffice.currFileSeq||(a=ID_RES_CONST_STRING_DOCUMENT_RELOAD);cmnMsg.showMsg(MESSAGE_ALERT,a,null,[ID_RES_DIALOG_BTN_OK],function(){cmnMsg.hideMsg();if(!oneffice.currFileSeq)document.location.reload();else if("editor"==pageLocation){var a=getEditorHTMLCode(!1,0,!0,!0);onefficeUtil.checkSameContent(a)||
(onefficeUtil.showDocSubject(ID_RES_CONST_STRING_SAVING_DATA),onefficeGW.saveFile(oneffice.currFileSeq,oneffice.currFolderSeq,oneffice.currFileSubject,a,0,function(){onefficeUtil.setSavedContent(a);onefficeGW.setCurrFileInfo(oneffice.currFileSeq,oneffice.currFolderSeq,oneffice.currFileSubject,oneffice.currFileRegDate);onefficeUtil.updateProgressBar(!0)},!0))}})}catch(b){dalert(b)}},simpleSaveFile:function(a,b){try{void 0===a&&(a=0);var c=getEditorHTMLCode(!1,0,!0,!0);onefficeGW.saveFile(oneffice.currFileSeq,
oneffice.currFolderSeq,oneffice.currFileSubject,c,a,function(){onefficeUtil.setSavedContent(c);void 0!=b&&b()})}catch(d){dalert(d)}}},Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",c=0;for(a=Base64._utf8_encode(a);c<a.length;){var d=a.charCodeAt(c++);var e=a.charCodeAt(c++);var f=a.charCodeAt(c++);var g=d>>2;d=(d&3)<<4|e>>4;var k=(e&15)<<2|f>>6;var h=f&63;isNaN(e)?k=h=64:isNaN(f)&&(h=64);b=b+Base64._keyStr.charAt(g)+Base64._keyStr.charAt(d)+
Base64._keyStr.charAt(k)+Base64._keyStr.charAt(h)}return b},decode:function(a){var b="",c=0;for(a=a.replace(/[^A-Za-z0-9\+\/=]/g,"");c<a.length;){var d=Base64._keyStr.indexOf(a.charAt(c++));var e=Base64._keyStr.indexOf(a.charAt(c++));var f=Base64._keyStr.indexOf(a.charAt(c++));var g=Base64._keyStr.indexOf(a.charAt(c++));d=d<<2|e>>4;e=(e&15)<<4|f>>2;var k=(f&3)<<6|g;b+=String.fromCharCode(d);64!=f&&(b+=String.fromCharCode(e));64!=g&&(b+=String.fromCharCode(k))}return b=Base64._utf8_decode(b)},_utf8_encode:function(a){a=
a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){var b="",c=0;for(c1=c2=0;c<a.length;){var d=a.charCodeAt(c);128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),
c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3)}return b}},dynamicScriptCall=function(a,b){try{"undefined"==typeof b&&(b=function(){});for(var c=dzeEnvConfig.strPath_Dir+a,d=document.getElementsByTagName("head")[0],e=d.getElementsByTagName("script"),f="",g=!1,k=0;k<e.length;k++)if(f=e[k].getAttribute("src"),null!=f&&0<=f.indexOf(a)){g=!0;break}if(1==g)b();else{var h=document.createElement("script");h.setAttribute("type","text/javascript");h.setAttribute("src",c+"?ver="+
objOnefficeLoader.getVer());var l=!1;document.all?h.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||l||(l=!0,b())}:h.onload=function(){b()};d.appendChild(h)}}catch(m){dalert(m)}},dynamicScriptCallDirect=function(a){return new Promise(function(b,c){try{var d=dzeEnvConfig.strPath_Dir+a,e=document.getElementsByTagName("head")[0],f=e.getElementsByTagName("script");c="";for(var g=!1,k=0;k<f.length;k++)if(c=f[k].getAttribute("src"),null!=c&&0<=c.indexOf(a)){g=!0;break}if(1==
g)b();else{var h=document.createElement("script");h.setAttribute("type","text/javascript");h.setAttribute("src",d+"?ver="+objOnefficeLoader.getVer());h.defer=!0;var l=h.async=!1;document.all?h.onreadystatechange=function(){if("loaded"==this.readyState||"complete"==this.readyState)l||(l=!0),b()}:h.onload=function(){dlog("DynamicScript.onload");b()};e.appendChild(h)}}catch(m){dalert(m)}})},getDocSeqByUrl=function(a){try{if(0>a.indexOf("oneffice.do")&&0>a.indexOf("oneffice.html")&&0>a.indexOf("oneffice_view.html"))return null;
var b=decodeURIComponent(a);b=b.substring(b.indexOf("?")+1);b=Base64.decode(b);return b=b.substring(b.indexOf("=")+1,b.indexOf("&"))}catch(c){dalert(c)}};
