var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
var g_OrgPrintMarginHTML="",g_DirectShowMode=!1,g_HybridViewMode=!1,total_page_height=0,total_page_no=1,g_chartIDS=[],slideList=[],g_slideNo=1,totalSlideCount=1,g_bSlideMode=!1,g_cursorStyle=0,g_ZoomRatioIndex=0,currentSlideIndex=1;
function fnLoadViewModeSuccessCB(a,b){try{setSkinToolBar();setCustomDisplay();var c=a.content;c=replaceImgSrcWithDataSrc(c);b.innerHTML=c;oneffice.currFileSubject=a.subject;oneffice.currFileSeq=a.seq;oneffice.parentFileContent=a;oneffice.onefficeGroupSeq=onefficeUtil.getRequestParameter("groupseq");oneffice.m_bEmbeded="embeded"===onefficeUtil.getRequestParameter("load_type");var d=document.getElementsByTagName("head")[0];insertEditorStyleCSS(d);setCustomEleInfo(b,d);document.getElementsByTagName("title")[0].innerHTML=
"undefined"!=typeof oneffice.currFileSubject&&null!=oneffice.currFileSubject&&""!=oneffice.currFileSubject?oneffice.currFileSubject+" - ONEFFICE VIEWER":"ONEFFICE VIEWER";document.body.scrollTop=0;document.body.style.overflowX="hidden";document.body.style.width="100%";document.body.style.height="100%";seperatePage(a,b);replaceEditorTempTagsFromEditor(0,document);g_objVideoControl&&g_objVideoControl.convToImgAll(document.body);var e=document.createElement("div");e.id="totalPageContainer";if(1===1*
a.readonly||!0===a.readonly)e.className="unselectable",e.ondragstart=function(){return!1};document.body.appendChild(e);var f=document.getElementsByClassName("dze_printpreview_pagebox");total_page_no=f.length;for(a=total_page_no-1;0<=a;a--)0==e.childNodes.length?e.appendChild(f[a]):e.insertBefore(f[a],e.childNodes[0]),total_page_height+=f[a].offsetHeight+15;setImageLoadingLazyForView(e);g_objOnefficeShot.setBodyPgContainer(e);document.body.scrollTop=0;setTimeout(function(){document.body.style.overflowX=
"auto";for(var a=document.getElementsByTagName("img"),b=a.length-1;0<=b;b--)null!==a[b].getAttribute("chart_data")&&canvas_create(a[b].parentNode,a[b]);scrollChartAnimation()},500);var g=document.getElementsByTagName("head"),h=document.createElement("meta");h.setAttribute("name","viewport");var m=onefficeUtil.getRequestParameter("bSlide"),n=window.screen.width;e=800;try{e=document.getElementById("totalPageContainer").firstChild.offsetWidth}catch(r){e=800}f=n/e;var p=window.screen.height-120;!0===
g_browserCHK.iOS&&!0===g_browserCHK.iPad&&(p=90===Math.abs(window.orientation)?window.screen.width-200:window.screen.height-200);b=1090;try{b=document.getElementById("totalPageContainer").firstChild.offsetHeight}catch(r){b=1024}p/=b;p<f&&m&&(f=p);n<e&&!0===g_browserCHK.iOS&&!0!==g_browserCHK.iPad?h.setAttribute("content","initial-scale="+f+", minimum-scale="+f+", maximum-scale=2, user-scalable=yes, width="+e):h.setAttribute("content","height=device-width");g[0].appendChild(h);var l=onefficeUtil.getRequestParameter("hybrid");
if(l&&"hApp"==l){g_HybridViewMode=!0;resizeOnHybridView(f);viewHybridComunication();var t=onefficeUtil.getRequestParameter("newEdit");t&&"newDoc"==t&&setTimeout(function(){goOnefficeEdit()},0);if("true"===m)for(document.body.style.backgroundColor="#888888",a=0;a<slideList.length;a++)slideList[a].style.position="absolute",0<a?(slideList[a].style.display="",slideList[a].style.opacity="0"):(slideList[a].style.display="",slideList[a].style.opacity="1"),slideList[a].style.transition="opacity .3s linear"}(0<
dzeUiConfig.arrCustomImgSrcRemoveDomain.length||!0===dzeUiConfig.autoAddImgSrcRemoveDomain)&&removeContentsOriginStr();(g_browserCHK.iOS||g_browserCHK.sf)&&dzeJ("p,td,span").filter(function(){return(0<=this.style.fontFamily.indexOf("[\ub354\uc874]")||objOnefficeLoader.m_bDomainDuzon)&&""==this.style.letterSpacing}).css("letter-spacing","-0.25px");var k=document.querySelectorAll("button.dze_play_button");forEach(k,function(a,b){b.addEventListener("click",function(a){if(g_objVideoControl&&g_objVideoControl.onClick(a))return TBCancelBubbleEvent(a),
!1})},this)}catch(r){dalert(r)}}
function resizeOnHybridView(a){try{document.body.style.height=window.screen.height-56+"px";if(1==fnObjectCheckNull(a)){var b=window.screen.width;a=800;try{a=document.getElementById("totalPageContainer").firstChild.offsetWidth}catch(f){a=800}var c=b/a}else c=a;var d=document.getElementById("totalPageContainer");d.style.transform="scale("+c+")";d.style.transformOrigin="left top";for(a=b=0;a<d.childNodes.length;a++)b+=d.childNodes[a].offsetHeight;d.style.height=b+30+"px";d.style.display="table";var e=
1<c?d.offsetWidth/c:d.offsetWidth*c;d.style.width=e+"px";1>c&&(d.style.marginLeft="calc(50% - "+e/2+"px)")}catch(f){dalert(f)}}
function viewHybridComunication(){try{window.addEventListener("message",function(a){var b=a.data;if(b.hasOwnProperty("uiEvent"))switch(b.uiEvent){case "resize":resizeOnHybridView();break;case "goEdit":goOnefficeEdit();break;case "showSlide":fnHandler_slideShow(a,0,g_nActiveEditNumber);break;case "getSlideInfo":sendHybridMessageSlide("totalSlideNum",slideList.length);sendHybridMessageSlide("currentSlideNum",currentSlideIndex);break;case "slideGo":goMobileSlide(b.uiEventData)}}),sendHybridMessageSlide("iframeDone",
"")}catch(a){dalert(a)}}function sendHybridMessageSlide(a,b){try{1!=fnObjectCheckNull(a)&&window.parent.postMessage({uiEvent:a,uiEventData:b},"*")}catch(c){dalert(c)}}function goMobileSlide(a){for(var b=0;b<slideList.length;b++)slideList[b].style.position="absolute",b==a-1?(slideList[b].style.display="",slideList[b].style.opacity="1"):(slideList[b].style.display="",slideList[b].style.opacity="0")}
function fnLoadViewMode(){try{if(objOnefficeLoader.setEditorMode(EDITORMODE.VIEWER),!0===dzeUiConfig.bIndependentEdit){var a=document.createElement("div");fnLoadViewModeSuccessCB(opener.oneffice.parentFileContent,a);oneffice.m_bEmbeded&&setZoomMode(1);!0!==g_browserCHK.mobile&&setTimeout(function(){createSlideController();createSlideShowMenu();!0===g_DirectShowMode&&(createContextMenu(),setSlideShowMode(!0,1,!1))},500)}else oneffice.onErrorCheckSession(function(){var a=oneffice.getAppEnvType(),c=
document.createElement("div"),d="";if(a==APPENV.GW){d=onefficeUtil.getRequestParameter("seq");a=onefficeUtil.getRequestParameter("previewOk");if(!d){closeViewer();return}a&&null!=opener&&"undefined"!=typeof opener.oneffice&&"undefined"!=typeof opener.oneffice.parentFileContent&&opener.oneffice.parentFileContent?fnLoadViewModeSuccessCB(opener.oneffice.parentFileContent,c):onefficeCommon.getSecurityInfo(d,"",function(a){0!=a?checkPasswordAndView(d):onefficeCommon.getFileContent(d,function(a){fnLoadViewModeSuccessCB(a,
c);oneffice.m_bEmbeded&&setZoomMode(1);onefficeCommon.accessUserFunction("openDoc");onefficeCommon.getMyInfo(function(b){"undefined"==typeof b?oneffice_cloud_myInfoData=null:(oneffice_cloud_myInfoData=b,onefficeCommon.accessDocumentHistory(d,CLOUD_CONST_HISTORY_ACTIONCODE_OPEN),!0===g_browserCHK.mobile&&!0===dzeUiConfig.bMobileEdit&&(b=!1,""!==a.share_date&&(b=!0,onefficeUtil.sendCommentStatus(1)),createMobileController(b)))},!1)},function(){!0===g_browserCHK.mobile?cmnCtrlToast.showToastMsg(null,
ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT,1E3):(cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT,3,"screen_center"),setTimeout(function(){onefficeWE||(document.location.href=oneffice.drivePath)},3500))})})}else{g_onefficeWeTool.m_bViewer=!0;g_onefficeWeTool.m_ctrlViewer=c;if(!onefficeWE.openFileProcess()){alert(ID_RES_CONST_STRING_WE_NOT_SUPPORTED);document.location.href=WEDRIVE_MAIN_LOCATION;return}duzon_http.hideLoading()}a=!1;var e=1;if(a=onefficeUtil.getRequestParameter("bShowMode"))g_DirectShowMode=
!0,e=onefficeUtil.getRequestParameter("currentPage"),-1==e&&(e=1);g_DirectShowMode&&!0!==g_browserCHK.mobile||(document.body.style.opacity="1");!0!==g_browserCHK.mobile&&setTimeout(function(){createSlideController();createSlideShowMenu();!0===g_DirectShowMode&&(createContextMenu(),setSlideShowMode(!0,parseInt(e),!1),document.body.style.opacity="1")},500)},dzeUiConfig.bAlwaysCheckSession)}catch(b){dalert(b)}}
function checkPasswordAndView(a){try{cmnDlg.viewBasicDlg(null,0,ID_RES_CONST_STRING_DOCUMENT_SECURITY+" "+ID_RES_CONST_STRING_OPEN_DOCUMENT,onefficeCommon.getCheckPasswordForm(),[ID_RES_DIALOG_BTN_OK,ID_RES_DIALOG_BTN_CANCEL],[function(b){checkPasswordInputValueOnView(a)},function(a){duzon_dialog.closeDialog();setTimeout(function(){document.location.href=oneffice.drivePath},500)}],function(){document.getElementById("dze_idx_check_password_input").onkeydown=function(b){ID_KEYCODE_ENTER==b.keyCode&&
checkPasswordInputValueOnView(a);ID_KEYCODE_ESCAPE==b.keyCode&&setTimeout(function(){document.location.href=oneffice.drivePath},500)}},function(){},!0)}catch(b){dalert(b)}}
function checkPasswordInputValueOnView(a){try{var b=document.getElementById("dze_idx_check_password_input");onefficeCommon.getSecurityInfo(a,b.value,function(c){if(2!=c)g_browserCHK.mobile?cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_NOTI_CHECK_PASSWORD_ERROR,2):alert(ID_RES_CONST_STRING_NOTI_CHECK_PASSWORD_ERROR),b.focus(),b.setSelectionRange(0,b.value.length);else{duzon_dialog.closeDialog();var d=document.createElement("div");onefficeCommon.getFileContent(a,function(b){fnLoadViewModeSuccessCB(b,
d);onefficeCommon.accessUserFunction("openDoc");onefficeCommon.getMyInfo(function(c){"undefined"==typeof c?oneffice_cloud_myInfoData=null:(oneffice_cloud_myInfoData=c,onefficeCommon.accessDocumentHistory(a,CLOUD_CONST_HISTORY_ACTIONCODE_OPEN),!0===g_browserCHK.mobile&&!0===dzeUiConfig.bMobileEdit&&(c=!1,""!==b.share_date&&(c=!0,onefficeUtil.sendCommentStatus(1)),createMobileController(c)))},!1)},function(){!0===g_browserCHK.mobile?cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT,
1E3):(cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT,3,"screen_center"),setTimeout(function(){onefficeWE||(document.location.href=oneffice.drivePath)},3500))},b.value)}})}catch(c){dalert(c)}}
function setCustomEleInfo(a,b){try{var c=null,d=null,e="#FFFFFF",f=g_objHeaderFooter||new HeaderFooter,g=g_objPageNumber||new PageNumber;f.init();g.init();for(var h=a.firstElementChild;h;){var m=h.nodeName.toLowerCase(),n=h.nextElementSibling;if("dze_doc_property"==m){var p=h.attributes;if(p){for(var l=0,t=p.length;l<t;l++){var k=p[l];if(k){var r=k.nodeName.toLowerCase();switch(r){case DZE_CUSTOM_ATT_NEW_DOC_CREATE:if(g_browserCHK.mobile&&"NewDocument"===k.nodeValue){var u=onefficeUtil.getRequestParameter("hybrid");
u&&"hApp"==u&&(g_HybridViewMode=!0,onefficeUtil.setCookieValue("hybridEdit","1",10),window.parent.postMessage({uiEvent:"newDocEdit"},"*"))}break;case DZE_CUSTOM_ATT_PAGEMARGIN:d=getstrMarginArray(k.nodeValue);break;case DZE_CUSTOM_ATT_PAPERSIZE:c=getstrPaperSizeArray(k.nodeValue);dzeUiConfig.nSettingPaperSize.width=parseFloat(c[0]);dzeUiConfig.nSettingPaperSize.height=parseFloat(c[1]);break;case DZE_CUSTOM_ATT_PAGECOLOR:if(e=k.nodeValue)changeCss(".dze_printpreview_pagebox","background-color",e,document),
dzeUiConfig.sSettingPaperColor=e;break;case DZE_CUSTOM_ATT_DIFF_FIRST_PAGE:case DZE_CUSTOM_ATT_DIFF_ODD_EVEN_PAGE:case DZE_CUSTOM_ATT_ODD_HEADER:case DZE_CUSTOM_ATT_EVEN_HEADER:case DZE_CUSTOM_ATT_FIRST_HEADER:case DZE_CUSTOM_ATT_ODD_FOOTER:case DZE_CUSTOM_ATT_EVEN_FOOTER:case DZE_CUSTOM_ATT_FIRST_FOOTER:f.setHeaderFooterAttribute(r,k.nodeValue);break;case DZE_CUSTOM_ATT_ONEPAGE_MODE:dzeUiConfig.bOfficeOnePageLongMode=null==k.nodeValue||""==k.nodeValue?!1:duzon_http.parseJSON(k.nodeValue);break;case DZE_CUSTOM_ATT_PAGE_OVERFLOWVISIBLE:var v=
k.nodeValue,q="false"==v||null==v?!1:!0;q?(dzeUiConfig.bOfficePgOverflowVisible=q,changeCss(".dze_printpreview_pagebox_body","overflow","visible",document),changeCss(".dze_printpreview_pagebox","overflow","visible",document)):(dzeUiConfig.bOfficePgOverflowVisible=q,changeCss(".dze_printpreview_pagebox_body","overflow","",document),changeCss(".dze_printpreview_pagebox","overflow","hidden",document));break;case DZE_CUSTOM_ATT_PGNUM:g&&g.importFromAttNode(k)}}}a.removeChild(h)}}if("dze_"!=m.substring(0,
4))break;h=n}setViewerPageMarginInfo(d,0);setPrintMarginInfo(a,b,d,c)}catch(w){dalert(w)}}function setPrintMarginInfo(a,b,c,d){try{if(a="",c&&c.length){a=c[0]+"mm "+c[1]+"mm "+c[2]+"mm "+c[3]+"mm ";var e="portrait";d[0]>d[1]&&(e="landscape");var f=document.createElement("style");f.setAttribute("type","text/css");f.setAttribute("media","print");f.innerHTML="@page{ margin : "+a+"; size:"+e+";  }";g_OrgPrintMarginHTML=c;b.appendChild(f)}}catch(g){dalert(g)}}
function setViewerPageMarginInfo(a){try{a&&a.length?(dzeUiConfig.nSettingPaperMargin.top=parseFloat(a[0]),dzeUiConfig.nSettingPaperMargin.right=parseFloat(a[1]),dzeUiConfig.nSettingPaperMargin.bottom=parseFloat(a[2]),dzeUiConfig.nSettingPaperMargin.left=parseFloat(a[3]),dzeUiConfig.nSettingPaperMargin.headerTop=parseFloat(a[4]),dzeUiConfig.nSettingPaperMargin.footerBottom=parseFloat(a[5])):(a=getDefaultMarginArray(),a.split(" "));var b=dzeUiConfig.nSettingPaperSize,c=dzeUiConfig.nSettingPaperMargin,
d=b.width-c.left-c.right,e=b.height-c.top-c.bottom;changeCss(".dze_printpreview_pagebox","width",b.width+"mm",document);!0===dzeUiConfig.bOfficeOnePageLongMode?(changeCss(".dze_printpreview_pagebox","height","auto",document),changeCss(".dze_printpreview_pagebox","min-height",b.height+"mm",document),changeCss(".dze_printpreview_pagebox","display","block",document)):changeCss(".dze_printpreview_pagebox","height",b.height+"mm",document);dzeUiConfig.bOfficePgOverflowVisible?(changeCss(".dze_printpreview_pagebox_body",
"overflow","visible",document),changeCss(".dze_printpreview_pagebox","overflow","visible",document)):(changeCss(".dze_printpreview_pagebox_body","","",document),changeCss(".dze_printpreview_pagebox","overflow","hidden",document));changeCss(".dze_printpreview_pagebox_header","width",d+"mm",document);changeCss(".dze_printpreview_pagebox_header","min-height",c.top+"mm",document);changeCss(".dze_printpreview_pagebox_header","max-height",b.height/2-c.headerTop-10+"mm",document);changeCss(".dze_printpreview_pagebox_header",
"padding",c.headerTop+"mm "+c.right+"mm 0mm "+c.left+"mm",document);changeCss(".dze_printpreview_pagebox_body","width",d+"mm",document);changeCss(".dze_printpreview_pagebox_body","padding","0mm "+c.right+"mm 0mm "+c.left+"mm",document);!0===dzeUiConfig.bOfficeOnePageLongMode?(changeCss(".dze_printpreview_pagebox_body","height","auto",document),changeCss(".dze_printpreview_pagebox_body","overflow","visible",document),changeCss(".dze_printpreview_pagebox_body","min-height",e+"mm",document)):changeCss(".dze_printpreview_pagebox_body",
"max-height",e+"mm",document);changeCss(".dze_printpreview_pagebox_footer","width",d+"mm",document);changeCss(".dze_printpreview_pagebox_footer","min-height",c.bottom+"mm",document);changeCss(".dze_printpreview_pagebox_footer","max-height",b.height/2-c.footerBottom-10+"mm",document);changeCss(".dze_printpreview_pagebox_footer","padding","0mm "+c.right+"mm "+c.footerBottom+"mm "+c.left+"mm",document)}catch(f){dalert(f)}}
function getDefaultMarginArray(){try{return dzeUiConfig.nSettingPaperMargin.top+" "+dzeUiConfig.nSettingPaperMargin.right+" "+dzeUiConfig.nSettingPaperMargin.bottom+" "+dzeUiConfig.nSettingPaperMargin.left+" "+dzeUiConfig.nSettingPaperMargin.headerTop+" "+dzeUiConfig.nSettingPaperMargin.footerBottom}catch(a){dalert(a)}}function getstrPaperSizeArray(a){try{var b="270,210";a&&(b=a,b=b.split(","));return b}catch(c){dalert(c)}}
function getstrMarginArray(a){try{var b=getDefaultMarginArray();a?(b=a,b=b.split(",")):g_OrgPrintMarginHTML.length&&(b=g_OrgPrintMarginHTML);return b}catch(c){dalert(c)}}
function canvas_create(a,b){var c=document.createElement("div"),d=b.getAttribute("chart_id"),e=b.clientWidth+"px",f=b.clientHeight+"px";c.setAttribute("id","container_"+d);c.style.width=e;c.style.height=f;c.style.display="inline-block";a.insertBefore(c,b);if(b.offsetParent&&c.offsetParent&&b.offsetParent.tagName!==c.offsetParent.tagName){a=g_objPositionUtil.getClassNameLeft(b,"dze_printpreview_pagebox_body");var g=g_objPositionUtil.getClassNameTop(b,"dze_printpreview_pagebox_body");c.style.left=a;
c.style.top=g}b.style.visibility="hidden";d="canvas_"+d;a=document.createElement("canvas");a.setAttribute("id",d);a.setAttribute("width",e);a.setAttribute("height",f);c.appendChild(a);c=document.getElementById(d).getContext("2d");a=b.getAttribute("chart_data");onefficeChart.initialize();onefficeChart.convStringToChartData(a);onefficeChart.makeViewChart(c,e,f,d);b.parentNode.removeChild(b)}
function seperatePage(a,b){try{!0!==dzeUiConfig.bOfficePagingMode&&changeCss(".dze_printpagebreak_guide","display","none",document);for(var c=g_objHeaderFooter,d=document.createElement("div");b.childNodes.length;)d.appendChild(b.childNodes[0]);for(var e=null,f=b=null,g=null,h=0,m=0;d.childNodes.length;){h++;if(1==h){m++;e=document.createElement("div");e.className="dze_printpreview_pagebox";e.setAttribute("pageNum",m);oneffice.m_bEmbeded||(e.style="border: 1px solid lightgray;");e.style.margin="15px auto";
e.style.backgroundColor=dzeUiConfig.sSettingPaperColor;(function(){if(!g_browserCHK.mobile){var a=m;e.onmouseover=function(){execSlideMouseOver(a)};e.onmouseout=function(){execSlideMouseOut(a)};e.ondblclick=function(){execSlideDblClick(a)};e.onclick=function(){execSlideClick(a)}}})();f=document.createElement("div");f.className="dze_printpreview_pagebox_header";b=document.createElement("div");b.className="dze_printpreview_pagebox_body";g=document.createElement("div");g.className="dze_printpreview_pagebox_footer";
f.innerHTML=c.getPageHeaderContents(m-1);g.innerHTML=c.getPageFooterContents(m-1);e.appendChild(f);e.appendChild(b);e.appendChild(g);if(""!=dzeUiConfig.sWatermarkImageSrc){var n=document.createElement("div");n.className="watermarkContainer";e.appendChild(n)}!0!==dzeUiConfig.bUsebottomCreatorBackgroundStyle||oneffice.m_bEmbeded||e.appendChild(g_objPageControl.makePageBottomCreator())}var p=d.childNodes[0];b.appendChild(p);"dze_printpagebreak"==p.className&&(document.body.appendChild(e),setPageLayoutForOnefficeView(e,
m-1),h=0)}""!=dzeUiConfig.sWatermarkImageSrc&&(changeCss(".watermarkContainer","width",dzeUiConfig.nSettingPaperSize.width+"mm",document),changeCss(".watermarkContainer","height",dzeUiConfig.nSettingPaperSize.height+"mm",document),changeCss(".watermarkContainer","background","url('"+dzeUiConfig.sWatermarkImageSrc+"') no-repeat center center;",document));document.body.appendChild(e);setPageLayoutForOnefficeView(e,m-1);var l=document.body.getElementsByTagName("video");for(c=0;c<l.length;c++)if(l[c].getAttribute("draggable")&&
l[c].removeAttribute("draggable"),!0!==dzeUiConfig.bIndependentEdit&&(g_browserCHK.iOS||g_browserCHK.sf)&&0<=l[c].firstChild.src.indexOf(ONEFFICE_SERVER_API_GET_ATTACHMENTDATA+"?seq=")){var t=l[c].firstChild.src,k=t.split("/gw/onefficeApi/")[0],r=t.split("/"),u=r[r.length-1].split("seq=")[1],v=u.split("-")[0];if(0<=k.indexOf("bizboxa.com")){var q=onefficeUtil.getRequestParameter("groupseq");l[c].firstChild.src=k+"/upload/"+q+"/onefficeFile/"+a.owner_id+"/"+v+"/"+u}else l[c].firstChild.src=k+"/upload/onefficeFile/"+
a.owner_id+"/"+v+"/"+u;l[c].firstChild.src=l[c].firstChild.src.replace(a.gw_url,a.mobile_gateway_url)}for(c=0;c<document.body.childNodes.length;c++)"div"==document.body.childNodes[c].nodeName.toLowerCase()&&"dze_printpreview_pagebox"==document.body.childNodes[c].className&&slideList.push(document.body.childNodes[c]);totalSlideCount=slideList.length;if((a=g_objPageNumber)&&0!==a.type&&!oneffice.m_bEmbeded)for(c=0;c<totalSlideCount;c++)slideList[c]&&slideList[c].appendChild(a.createDiv(slideList[c],
c,totalSlideCount));else for(c=0;c<totalSlideCount;c++)if(slideList[c]){var w=document.createElement("div");w.className="slidePageNumLayer";w.innerHTML=slideList[c].getAttribute("pageNum")+"/"+totalSlideCount;slideList[c].appendChild(w)}!0===g_browserCHK.mobile&&(changeCss(".dze_printpreview_pagebox","margin","0 auto 5px auto",document),changeCss(".slidePageNumLayer","font-size","50px",document));window.onscroll=function(){scrollChartAnimation();nowScrolling||(nowScrolling=!0,showAllPageNumLayer(!0),
startScrollCheck())}}catch(x){dalert(x)}}
function setPageLayoutForOnefficeView(a,b){try{if(a){var c=this.setPageLayoutForOnefficeView.cacheHeight,d=this.setPageLayoutForOnefficeView.paperMarginPx,e=this.setPageLayoutForOnefficeView.paperSizePx,f=this.setPageLayoutForOnefficeView.hfMaxHeight;if(!c){var g=g_objCommonUtil;c=[];d=cloneSimpleObject(dzeUiConfig.nSettingPaperMargin);d.left=+g.convMMToPx(d.left).toFixed(2);d.top=+g.convMMToPx(d.top).toFixed(2);d.right=+g.convMMToPx(d.right).toFixed(2);d.bottom=+g.convMMToPx(d.bottom).toFixed(2);
d.headerTop=+g.convMMToPx(d.headerTop).toFixed(2);d.footerBottom=+g.convMMToPx(d.footerBottom).toFixed(2);e=cloneSimpleObject(dzeUiConfig.nSettingPaperSize);e.width=+g.convMMToPx(e.width).toFixed(2);e.height=+g.convMMToPx(e.height).toFixed(2);f=+g.convMMToPx(dzeUiConfig.nSettingPaperSize.height/2-10).toFixed(2);this.setPageLayoutForOnefficeView.cacheHeight=c;this.setPageLayoutForOnefficeView.paperMarginPx=d;this.setPageLayoutForOnefficeView.paperSizePx=e;this.setPageLayoutForOnefficeView.hfMaxHeight=
f}g=g_objHeaderFooter;var h=a.childNodes[0],m=a.childNodes[1],n=a.childNodes[2];g.isBlankHeaderFooter(h)?(h.style.paddingTop="0px",h.style.minHeight=d.top+"px"):(h.style.paddingTop=d.headerTop+"px",h.style.minHeight=Math.max(d.top-d.headerTop,0)+"px");var p=g.getPageType(b)|g.HEADER,l=c[p];l||(l=h.offsetHeight,c[p]=l);var t=g.getPageType(b)|g.FOOTER,k=c[t];k||(k=n.offsetHeight,c[t]=k);var r=Math.max(d.top,l),u=Math.max(d.bottom,k),v=e.height-(r+u);dzeUiConfig.bOfficeOnePageLongMode?(m.style.height=
"auto",m.style.minHeight=e.height-(r+u)+"px",n.style.position="relative"):(m.style.height=v+"px",n.style.position="");if(l>=Math.floor(f)){var q=document.createElement("div");q.style.position="absolute";q.style.top=f+"px";q.style.left="0mm";q.style.right="0mm";q.style.height=v+"px";q.style.backgroundColor=dzeUiConfig.sSettingPaperColor;h.appendChild(q)}g.isBlankHeaderFooter(n)?(n.style.paddingBottom="0px",n.style.minHeight=d.bottom+"px"):(n.style.paddingBottom=d.footerBottom+"px",n.style.minHeight=
"0px",n.style.marginTop=Math.max(d.bottom+d.footerBottom-k,0)+"px")}}catch(w){dalert(w)}}var prevScrollTop=0,nowScrolling=!1,scrollCheckTimer=null;function startScrollCheck(){try{scrollCheckTimer=setInterval(function(){if(!0!==bIsZoomout){var a=document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop;if(a==prevScrollTop){if(!nowScrolling)return;nowScrolling=!1;showAllPageNumLayer(!1);stopScrollCheck()}prevScrollTop=a}},1E3)}catch(a){dalert(a)}}
function stopScrollCheck(){try{scrollCheckTimer&&(clearInterval(scrollCheckTimer),scrollCheckTimer=null)}catch(a){dalert(a)}}
function scrollChartAnimation(){try{for(var a=document.body.clientHeight,b=document.body.getElementsByTagName("canvas"),c=[],d=0;d<b.length;d++)if(0<=b[d].id.indexOf("canvas_chart")){var e=b[d].id,f=g_chartIDS.indexOf(e),g=b[d].getBoundingClientRect();0<=g.top&&0<=g.bottom&&g.bottom<=a?0>f&&(c.push(e),g_chartIDS.push(e)):(0>=g.bottom||g.top>=a)&&0<=f&&g_chartIDS.splice(f,1)}0<c.length&&setChartAnimation(!0,c)}catch(h){dalert(h)}}
function insertEditorStyleCSS(a){try{var b=document.createElement("link");b.setAttribute("rel","stylesheet");b.setAttribute("type","text/css");var c=g_strContentsCSS+"?ver="+objOnefficeLoader.getVer();b.setAttribute("href",c);a.appendChild(b);b=document.createElement("link");b.setAttribute("rel","stylesheet");b.setAttribute("type","text/css");c=dzeEnvConfig.strPath_CSS+"editor_style_inherit.css?ver="+objOnefficeLoader.getVer();b.setAttribute("href",c);a.appendChild(b);var d=document.createElement("style"),
e=GetInitStyleString(!0);d.innerHTML=e;a.appendChild(d)}catch(f){dalert(f)}}
function closeViewer(){try{!0!==dzeUiConfig.bOfficePagingMode&&changeCss(".dze_printpagebreak_guide","display","",document),objOnefficeLoader.setEditorMode(EDITORMODE.EDITOR),!0!==g_browserCHK.mobile?(cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_WARNING_INVALID_DOCUMENT_CALL,2,"screen_center"),setTimeout(function(){"undefined"!==typeof onefficeWe&&onefficeWE||(document.location.href=oneffice.drivePath)},1E3)):cmnCtrlToast.showToastMsg(null,ID_RES_CONST_STRING_WARNING_INVALID_DOCUMENT_CALL,2,
"mobile")}catch(a){dalert(a)}}function changeDocBgColor(a){try{for(var b=document.getElementsByTagName("style"),c=0;c<b.length;c++)-1!=b[c].innerHTML.indexOf("background-color")&&(b[c].innerHTML=a)}catch(d){dalert(d)}}
var beforePrint=function(){try{changeCss(".dze_printpreview_pagebox","margin","auto",document),setViewerPageMarginInfo([["0"],["0"],["0"],["0"]],1),showSlideController(!1),showAllPageNumLayer(!1)}catch(a){dalert(a)}},afterPrint=function(){try{changeCss(".dze_printpreview_pagebox","margin","15px auto",document);var a=getstrMarginArray(null);setViewerPageMarginInfo(a,2);showSlideController(!0);!1===g_bSlideMode&&showAllPageNumLayer(!0)}catch(b){dalert(b)}};
function setSlideShowMode(a,b,c){var d=!1;"undefined"===typeof c?d=!0:0==c&&(d=!0);try{if(!0!==dzeUiConfig.bOfficeOnePageLongMode&&g_bSlideMode!==a){g_bSlideMode=a;for(c=0;c<slideList.length;c++)1==a?(slideList[c].style.display="none",slideList[c].style.opacity="0"):(slideList[c].style.display="",slideList[c].style.opacity="1");setSlideShowScreenScale();if(!0===a)window.addEventListener&&(window.addEventListener("keydown",addSlideShowKeyDownEvent,!1),window.addEventListener("resize",setSlideShowScreenScale,
!1),window.addEventListener("mousedown",addSlideShowMouseDownEvent,!1),window.addEventListener("mousemove",addSlideShowMouseMoveEvent,!1),window.addEventListener("click",addSlideShowClickEvent,!1),window.addEventListener("mousewheel",addSlideShowWeelEvent,!1),window.addEventListener("DOMMouseScroll",addSlideShowWeelEvent,!1),window.addEventListener("contextmenu",addSlideShowContextmenu,!1));else{window.removeEventListener&&(window.removeEventListener("keydown",addSlideShowKeyDownEvent,!1),window.removeEventListener("resize",
setSlideShowScreenScale,!1),window.removeEventListener("mousedown",addSlideShowMouseDownEvent,!1),window.removeEventListener("mousemove",addSlideShowMouseMoveEvent,!1),window.removeEventListener("click",addSlideShowClickEvent,!1),window.removeEventListener("mousewheel",addSlideShowWeelEvent,!1),window.removeEventListener("DOMMouseScroll",addSlideShowWeelEvent,!1));var e=document.getElementById("dze_idx_oneffice_show_contextmenu_container");e&&document.body.removeChild(e);setSlideShowCursorStyle(-1)}!0===
a?(g_slideNo=1,"number"===typeof b&&(g_slideNo=b),setFullScreen(),showSlide(),showSlideController(!1)):(setFullScreen(),showSlideController(!0),allMovieReset());a&&d&&cmnMsg.showMsg(MESSAGE_CHECK,ID_RES_CONST_STRING_SLIDE_SHOW_CONFIRM,null,[ID_RES_DIALOG_BTN_OK],function(){cmnMsg.hideMsg();document.getElementById("dze_idx_oneffice_go_show_slide_btn").click()})}}catch(f){dalert(f)}}
function addSlideShowKeyDownEvent(a){try{if(!0===g_objOnefficeShot.m_bShow)27===a.keyCode&&(document.body.style.overflow="hidden",g_bSlideMode?showSlide():slideList.forEach(function(a){a.style.display="";a.style.opacity="1"}));else{if("hidden"!==document.body.style.overflowY)if(!document.body.msRequestFullscreen){if(a.keyCode==ID_KEYCODE_ARROW_TOP){0<document.body.scrollTop&&(document.body.scrollTop=Math.max(0,document.body.scrollTop-30));TBCancelBubbleEvent(a);return}if(a.keyCode==ID_KEYCODE_ARROW_BOTTOM){document.body.scrollHeight-
document.body.scrollTop>document.body.clientHeight&&(document.body.scrollTop=Math.min(document.body.scrollHeight-document.body.scrollTop,document.body.scrollTop+30));TBCancelBubbleEvent(a);return}}else if(a.keyCode==ID_KEYCODE_ARROW_TOP||a.keyCode==ID_KEYCODE_ARROW_BOTTOM)return;if(a.keyCode==ID_KEYCODE_PAGE_DOWN||a.keyCode==ID_KEYCODE_ARROW_RIGHT||a.keyCode==ID_KEYCODE_ARROW_BOTTOM)showNextSlide(),TBCancelBubbleEvent(a);if(a.keyCode==ID_KEYCODE_PAGE_UP||a.keyCode==ID_KEYCODE_ARROW_LEFT||a.keyCode==
ID_KEYCODE_ARROW_TOP)showPrevSlide(),TBCancelBubbleEvent(a)}}catch(b){dalert(b)}}
function setSlideShowScreenScale(){try{var a=0;a=document.documentElement.scrollWidth?window.innerHeight?window.innerHeight:document.documentElement.clientHeight:document.body.scrollHeight;if(!0===g_bSlideMode){zoomOutList(!1);var b=a/Math.round(dzeUiConfig.nSettingPaperSize.height/ONE_PX2MM);b=b.toFixed(2);document.body.style.overflow="hidden";document.body.style.width="100%";document.body.style.height="100%";changeCss(".dze_printpreview_pagebox","margin","0px auto",document);for(var c=document.getElementsByClassName("dze_printpreview_pagebox"),
d=0;d<c.length;d++)c[d].style.transform="scale("+b+")",c[d].style.msTransform="scale("+b+")",c[d].style.WebkitTransform="scale("+b+")",c[d].style.transformOrigin="center top",c[d].style.msTransformOrigin="center top",c[d].style.margin="0px auto",c[d].style.borderWidth="0px";showAllPageNumLayer(!1)}else{document.body.removeAttribute("style");document.body.style.backgroundColor=!0===g_browserCHK.mobile?"#F6F7F9":"#000000";changeCss(".dze_printpreview_pagebox","margin","15px auto",document);c=document.getElementsByClassName("dze_printpreview_pagebox");
for(d=0;d<c.length;d++)c[d].style.transform="scale(1)",c[d].style.msTransform="scale(1)",c[d].style.WebkitTransform="scale(1)",c[d].style.transformOrigin="",c[d].style.msTransformOrigin="",c[d].style.margin="15px auto",c[d].style.borderWidth="1px";!0===bIsZoomout&&zoomOutList(!1);setSlidePositionInSlideList(g_slideNo,!1);showAllPageNumLayer(!0)}}catch(e){dalert(e)}}var g_clickMouseMove=!1,g_movePrevX=0,g_movePrevY=0;
function addSlideShowMouseMoveEvent(a){try{if(0<a.buttons&&!document.body.msRequestFullscreen){var b=g_movePrevY?a.screenY-g_movePrevY:0;if("hidden"!==document.body.style.overflowY){var c=document.getElementById("totalPageContainer"),d=null;d=dzeEnvConfig.strPath_Image+"grab.cur";document.body.style.cursor="url("+d+"), pointer";slideList[g_slideNo-1]&&(slideList[g_slideNo-1].style.cursor="url("+d+"), pointer");0>b&&0<document.body.scrollTop?document.body.scrollTop+=b:0<b&&c.scrollHeight-document.body.scrollTop>
document.body.clientHeight&&(document.body.scrollTop+=b);dlog(" ShowMouseMove movementY = "+b+" evnt.screenY = "+a.screenY);document.documentElement.scrollHeight;document.documentElement.offsetHeight;document.documentElement.clientHeight}g_movePrevX=a.screenX;g_movePrevY=a.screenY;g_clickMouseMove=!0}}catch(e){dalert(e)}}function addSlideShowMouseDownEvent(a){try{dlog(" addSlideShowMouseDownEvent evnt.clientY = "+a.clientY+" evnt.screenY ="+a.screenY),TBCancelBubbleEvent(a)}catch(b){dalert(b)}}
function addSlideShowClickEvent(a){try{if(dlog(" addSlideShowClickEvent= "+a.clientY+" evnt.buttons = "+a.buttons),g_movePrevY=g_movePrevX=0,1!=g_objOnefficeShot.bShow){var b=document.getElementById("dze_idx_oneffice_show_contextmenu_container");b&&"none"!==b.style.display?b.style.display="none":(!0!==g_clickMouseMove?showNextSlide():"hidden"!==document.body.style.overflowY&&setSlideShowCursorStyle(g_cursorStyle),g_clickMouseMove=!1)}}catch(c){dalert(c)}}var g_MouseScrollStop=0;
function addSlideShowContextmenu(a){try{var b=document.getElementById("dze_idx_oneffice_show_contextmenu_container");b&&(window.outerWidth===screen.width&&window.outerHeight===screen.height?(document.getElementById("dze_idx_oneffice_context_show_slide_btn").style.display="none",document.getElementById("dze_idx_oneffice_context_close_show_slide_btn").style.display=""):void 0!==document.fullScreenElement&&null===document.fullScreenElement||void 0!==document.msFullscreenElement&&null===document.msFullscreenElement||
void 0!==document.mozFullScreen&&!document.mozFullScreen||void 0!==document.webkitIsFullScreen&&!document.webkitIsFullScreen?(document.getElementById("dze_idx_oneffice_context_show_slide_btn").style.display="",document.getElementById("dze_idx_oneffice_context_close_show_slide_btn").style.display="none"):(document.getElementById("dze_idx_oneffice_context_show_slide_btn").style.display="none",document.getElementById("dze_idx_oneffice_context_close_show_slide_btn").style.display=""),b.style.display=
"block",b.style.left=a.clientX,b.style.top=a.clientY)}catch(c){dalert(c)}}
function addSlideShowWeelEvent(a){try{if(!1===g_objOnefficeShot.m_bShow&&!document.body.msRequestFullscreen){var b=a||window.event;if(0>Math.max(-1,Math.min(1,b.wheelDelta||-b.detail))){if("hidden"===document.body.style.overflowY){showNextSlide();return}if(document.body.scrollHeight-document.body.scrollTop<=document.body.clientHeight&&0===g_MouseScrollStop){g_MouseScrollStop=1;return}1===g_MouseScrollStop?(g_MouseScrollStop=document.body.scrollTop=0,showNextSlide()):2===g_MouseScrollStop&&(g_MouseScrollStop=
0)}else if("hidden"===document.body.style.overflowY)showPrevSlide();else{if(0>=document.body.scrollTop&&0===g_MouseScrollStop){g_MouseScrollStop=2;return}if(2===g_MouseScrollStop){g_MouseScrollStop=0;if(1==g_slideNo)return;showPrevSlide();document.body.scrollTop=document.body.scrollHeight-document.body.clientHeight}else 1===g_MouseScrollStop&&(g_MouseScrollStop=0)}TBCancelBubbleEvent(a)}}catch(c){dalert(c)}}
function showPageNumLayer(a,b){try{var c=a.childNodes[a.childNodes.length-1];c&&"slidePageNumLayer"==c.className&&(!0===b?"block"!=c.style.display&&(c.style.display="block"):"none"!=c.style.display&&(c.style.display="none"))}catch(d){dalert(d)}}function showAllPageNumLayer(a){try{if(0!=slideList.length&&!0!==dzeUiConfig.bOfficeOnePageLongMode&&!oneffice.m_bEmbeded)for(var b=0;b<slideList.length;b++)showPageNumLayer(slideList[b],a)}catch(c){dalert(c)}}
function showSlide(){try{if(0!=slideList.length&&!0!==dzeUiConfig.bOfficeOnePageLongMode){var a=slideList[g_slideNo-1];if("undefiend"!=typeof a){for(var b=a.getElementsByTagName("canvas"),c=[],d=0;d<b.length;d++)0<=b[d].id.indexOf("canvas_chart")&&c.push(b[d].id);0<c.length&&(dlog("showSlide = "+this),setChartAnimation(!0,c));var e=a.getElementsByTagName("table");for(d=0;d<e.length;d++)b=/\.gif/,e[d].style.backgroundImage&&b.test(e[d].style.backgroundImage)&&(e[d].style.backgroundImage=e[d].style.backgroundImage.replace(/\.gif[\?0-9]*/,
".gif?"+(new Date).getTime()));allMovieReset();var f=a.getElementsByTagName("video");for(d=0;d<f.length;d++)f[d].currentTime=0,"Auto"==f[d].getAttribute("playtype")&&f[d].play();duzon_dialog.fade("in",a,function(){showToastMsg(g_slideNo+" "+ID_RES_CONST_STRING_PAGE,1.5)},30)}}}catch(g){dalert(g)}}
function hideSlide(a,b){try{0!=slideList.length&&!0!==dzeUiConfig.bOfficeOnePageLongMode&&(a=g_slideNo-1,"undefined"!=typeof slideList[a]&&(slideList[a].style.display="none","function"===typeof b&&b()))}catch(c){dalert(c)}}function showNextSlide(){try{g_slideNo<totalSlideCount?hideSlide("up",function(){g_slideNo+=1;0<document.body.scrollTop&&(document.body.scrollTop=0);showSlide()}):showToastMsg(ID_RES_CONST_STRING_LAST_PAGE,1.5)}catch(a){dalert(a)}}
function showPrevSlide(){try{1<g_slideNo?hideSlide("down",function(){--g_slideNo;0<document.body.scrollTop&&(document.body.scrollTop=0);showSlide()}):showToastMsg(ID_RES_CONST_STRING_FIRST_PAGE,2)}catch(a){dalert(a)}}
function setFullScreen(){try{var a=document.body;if(!0===g_bSlideMode){if(void 0!==document.fullScreenElement&&null===document.fullScreenElement||void 0!==document.msFullscreenElement&&null===document.msFullscreenElement||void 0!==document.mozFullScreen&&!document.mozFullScreen||void 0!==document.webkitIsFullScreen&&!document.webkitIsFullScreen)a.requestFullScreen?a.requestFullScreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():a.msRequestFullscreen&&
a.msRequestFullscreen()}else document.cancelFullScreen?document.cancelFullScreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen()}catch(b){dalert(b)}}var toastMsgTimer=null;
function showToastMsg(a,b){try{if(!oneffice.m_bEmbeded){var c=document.getElementById("dze_idx_oneffice_show_msg");c||(c=document.createElement("div"),c.id="dze_idx_oneffice_show_msg",c.className="oneffice_show_msg",document.body.appendChild(c));c.innerHTML=a;null!=toastMsgTimer&&(clearTimeout(toastMsgTimer),c.style.display="none");duzon_dialog.fade("in",c,function(){toastMsgTimer=setTimeout(function(){toastMsgTimer=null;duzon_dialog.fade("out",c,function(){})},1E3*b)})}}catch(d){dalert(d)}}
function createSlideController(){try{if(!oneffice.m_bEmbeded){var a=document.createElement("div");a.id="dze_idx_oneffice_slide_controller";a.className="oneffice_slide_controller";a.style.display="none";a.onmouseenter=function(a){duzon_dialog.fade("in",this);TBCancelBubbleEvent(a)};a.onmouseleave=function(a){this.style.opacity="0"};a.onmousedown=function(a){TBCancelBubbleEvent(a)};var b=document.createElement("div");b.id="idx_btn_show_slide";b.className="btn_show_slide_ctl";b.style.marginBottom="20px";
b.innerHTML=ID_RES_CONST_STRING_SLIDE_SHOW;b.onclick=function(){createContextMenu();setSlideShowMode(!0,1,!0)};b.onmouseover=function(){this.className="btn_show_slide_ctl_over"};b.onmouseout=function(){this.className="btn_show_slide_ctl"};b.onmousedown=function(){this.className="btn_show_slide_ctl_down"};b.onmouseup=function(){this.className="btn_show_slide_ctl_over"};var c=document.createElement("div");c.id="idx_btn_show_thumbnail";c.className="btn_show_slide_ctl";c.innerHTML=IE_RES_CONST_STRING_THUMBNAIL_VIEW;
c.onclick=function(){showPgThumbnailView()};c.onmouseover=function(){this.className="btn_show_slide_ctl_over"};c.onmouseout=function(){this.className="btn_show_slide_ctl"};c.onmousedown=function(){this.className="btn_show_slide_ctl_down"};c.onmouseup=function(){this.className="btn_show_slide_ctl_over"};var d=document.createElement("div");d.id="idx_btn_show_zoomout";d.className="btn_show_slide_ctl";d.innerHTML=ID_RES_CONST_STRING_ZOOM_OUT+"(-)";d.onclick=function(){zoomOutList(!0,!0)};d.onmouseover=
function(){this.className="btn_show_slide_ctl_over"};d.onmouseout=function(){this.className="btn_show_slide_ctl"};d.onmousedown=function(){this.className="btn_show_slide_ctl_down"};d.onmouseup=function(){this.className="btn_show_slide_ctl_over"};var e=document.createElement("div");e.id="idx_btn_show_zoomin";e.className="btn_show_slide_ctl";e.style.display="none";e.innerHTML=ID_RES_CONST_STRING_ZOOM_IN+"(+)";e.onclick=function(){zoomOutList(!1,!0)};e.onmouseover=function(){this.className="btn_show_slide_ctl_over"};
e.onmouseout=function(){this.className="btn_show_slide_ctl"};e.onmousedown=function(){this.className="btn_show_slide_ctl_down"};e.onmouseup=function(){this.className="btn_show_slide_ctl_over"};var f=document.createElement("div");f.id="idx_btn_show_scrolltop";f.className="btn_show_slide_ctl";f.style.marginTop="20px";f.innerHTML="Top";f.onclick=function(){setSlidePositionInSlideList(1,!0)};f.onmouseover=function(){this.className="btn_show_slide_ctl_over"};f.onmouseout=function(){this.className="btn_show_slide_ctl"};
f.onmousedown=function(){this.className="btn_show_slide_ctl_down"};f.onmouseup=function(){this.className="btn_show_slide_ctl_over"};document.createElement("div").className="btn_show_slide_ctl_spacer";var g=document.createElement("div");g.className="btn_show_slide_ctl_spacer";document.createElement("div").className="btn_show_slide_ctl_spacer";!0!==dzeUiConfig.bOfficeOnePageLongMode&&(a.appendChild(b),a.appendChild(c));a.appendChild(g);a.appendChild(d);a.appendChild(e);a.appendChild(f);document.body.appendChild(a);
showSlideController(!0)}}catch(h){dalert(h)}}function showSlideController(a){try{oneffice.m_bEmbeded||(document.getElementById("dze_idx_oneffice_slide_controller").style.display=!0===a?"":"none",showSlideShowMenu(!a))}catch(b){dalert(b)}}
function createContextMenu(){if(!document.getElementById("dze_idx_oneffice_show_contextmenu_container")){var a=document.createElement("div");a.id="dze_idx_oneffice_show_contextmenu_container";a.className="dze_oneffice_context_menu_container";var b="<div class='dze_menu_sub_parent'><div class='dze_menu_sub_contentChild'>"+ID_RES_CONST_STRING_ZOOM_INOUT+"</div><div class='dze_menu_sub_iconChild'>></div>",c=createcommonDivMenu("dze_idx_oneffice_context_next_slide_btn","dze_oneffice_context_slideshow_btn",
null,ID_RES_CONST_STRING_NEXT_SLIDE,0),d=createcommonDivMenu("dze_idx_oneffice_context_prev_slide_btn","dze_oneffice_context_slideshow_btn",null,ID_RES_CONST_STRING_PREV_SLIDE,1),e=createcommonDivMenu("dze_idx_oneffice_context_move_slide_btn","dze_oneffice_context_slideshow_btn",null,ID_RES_CONST_STRING_MOVE_SLIDE,2),f=createcommonDivMenu("dze_idx_oneffice_context_zoom_slide_btn","dze_oneffice_context_slideshow_btn",null,b,3);createSubZoomOutMenu(f,"dze_idx_oneffice_context_zoomRatio_box");f.onmouseover=
function(a){setZoomCheck("dze_idx_oneffice_context_zoomRatio_box");this.lastChild.style.display="block";a=document.getElementById("dze_idx_oneffice_context_cursor_btn").clientWidth;this.lastChild.style.left=a;this.lastChild.style.top="0px"};f.onmouseleave=function(a){this.lastChild.style.display="none"};if(0<dzeUiConfig.aSlideShowCursorList.length){b="<div class='dze_menu_sub_parent'><div class='dze_menu_sub_contentChild'>"+ID_RES_CONST_STRING_POINTER_OPTION+"</div><div class='dze_menu_sub_iconChild'>></div>";
var g=createcommonDivMenu("dze_idx_oneffice_context_cursor_btn","dze_oneffice_context_slideshow_btn",null,b,4);createSubCursorMenu(g,"dze_idx_oneffice_context_cursor_box");g.onmouseover=function(a){setCurorCheck("dze_idx_oneffice_context_cursor_box");this.lastChild.style.display="block";a=document.getElementById("dze_idx_oneffice_context_cursor_btn").clientWidth;this.lastChild.style.left=a;this.lastChild.style.top="0px"};g.onmouseleave=function(a){this.lastChild.style.display="none"}}b=createcommonDivMenu("dze_idx_oneffice_context_show_slide_btn",
"dze_oneffice_context_slideshow_btn",null,ID_RES_CONST_STRING_VIEW_SHOW,6);b.onclick=function(a){setFullScreen();displaySlideShowMenu(!0);var b=document.getElementById("dze_idx_oneffice_show_contextmenu_container");b&&(b.style.display="none");TBCancelBubbleEvent(a);setTimeout(function(){displaySlideShowMenu(!1)},3E3)};var h=createcommonDivMenu("dze_idx_oneffice_context_close_show_slide_btn","dze_oneffice_context_slideshow_btn",null,ID_RES_CONST_STRING_SLIDE_SHOW_EXIT,6);h.onclick=function(a){!0===
g_DirectShowMode?window.close():setSlideShowMode(!1);TBCancelBubbleEvent(a)};a.appendChild(c);a.appendChild(d);a.appendChild(e);c=document.createElement("div");c.className="context_Menu_Separator";a.appendChild(c);a.appendChild(f);a.appendChild(g);c=document.createElement("div");c.className="context_Menu_Separator";a.appendChild(c);a.appendChild(b);a.appendChild(h);document.body.appendChild(a)}}
function createSubZoomOutMenu(a,b){try{var c=document.createElement("div");c.id=b;c.className="dze_oneffice_show_cursor_box";a.appendChild(c);a=[ID_RES_CONST_SLIDESHOW_ZOOM_HEIGHT,ID_RES_CONST_SLIDESHOW_ZOOM_WIDTH,ID_RES_CONST_SLIDESHOW_ZOOM_125,ID_RES_CONST_SLIDESHOW_ZOOM_150,ID_RES_CONST_SLIDESHOW_ZOOM_175];for(b=0;b<a.length;b++){var d=document.createElement("div");d.className="dze_menu_sub_parent";var e=document.createElement("div");e.className="dze_menu_sub_contentChild";e.innerHTML=a[b];d.appendChild(e);
var f=document.createElement("div");f.className="dze_menu_sub_iconChild";f.innerHTML=0==b?"<img src='image/icon_check.png' style='visibility: visible;'></img>":"<img src='image/icon_check.png' style='visibility: hidden;'></img>";d.appendChild(f);d.onclick=function(a){setZoomRatio(a.srcElement.parentNode.parentNode,a.srcElement.parentNode);displaySlideShowMenu(!1);TBCancelBubbleEvent(a)};c.onmouseleave=function(a){"dze_idx_oneffice_context_zoom_slide_btn"!==a.srcElement.parentElement.id&&(a.srcElement.style.display=
"none",TBCancelBubbleEvent(a))};c.appendChild(d)}}catch(g){dalert(g)}}function setZoomCheck(a){if(a=$_(a))for(var b=a.childElementCount,c=0;c<b;c++)g_ZoomRatioIndex===c&&(a.childNodes[c].lastChild.lastChild.style.visibility=c!==g_ZoomRatioIndex?"hidden":"visible")}
function setCurorCheck(a){a=$_(a);var b=a.childElementCount,c=document.body.style.cursor;dlog("document.body.style.cursor = "+c);var d=0;0<c.indexOf("red")?d=1:0<c.indexOf("blue")?d=2:0<c.indexOf("green")?d=3:0<c.indexOf("yellow")?d=4:0<c.indexOf("stick")&&(d=5);if(a)for(c=0;c<b;c++)a.childNodes[c].lastChild.lastChild.style.visibility=c!==d?"hidden":"visible"}
function createSubCursorMenu(a,b){try{var c=document.createElement("div");c.id=b;c.className="dze_oneffice_show_cursor_box";a.appendChild(c);a="";for(b=0;b<dzeUiConfig.aSlideShowCursorList.length;b++){var d=document.createElement("div");d.className="dze_oneffice_show_cursor_box_unit";var e=document.createElement("img");a=dzeEnvConfig.strPath_Image+dzeUiConfig.aSlideShowCursorList[b]+".png";e.src=a;e.width=16;e.height=16;e.style.marginRight="8px";var f=document.createElement("span");f.style.width=
"130px";f.innerHTML=dzeUiConfig.aSlideShowCursorList[b].split(".")[0].replace(/_/," ");0==b&&(f.textContent=ID_RES_DIALOG_STRING_BASIC);d.appendChild(e);d.appendChild(f);var g=document.createElement("div");g.innerHTML=0==b?"<img src='image/icon_check.png' style='visibility: visible;'></img>":"<img src='image/icon_check.png' style='visibility: hidden;'></img>";d.appendChild(g);d.setAttribute("cursorNo",b);d.onclick=function(a){var b=a.srcElement.parentElement.getAttribute("cursorNo");setSlideShowCursorStyle(parseInt(b));
displaySlideShowMenu(!1);TBCancelBubbleEvent(a)};c.onmouseleave=function(a){"dze_idx_oneffice_context_cursor_btn"!==a.srcElement.parentElement.id&&(a.srcElement.style.display="none",TBCancelBubbleEvent(a))};c.appendChild(d)}}catch(h){}}
function createcommonDivMenu(a,b,c,d,e){var f=document.createElement("div");f.id=a;f.className=b;null!==c?(f.style.display="flex",f.style.alignItems="center",a=document.createElement("img"),a.src="image/"+c,a.style.marginLeft="17px",a.style.marginRight="8px",f.appendChild(a),c=document.createTextNode(d),f.appendChild(c),f.setAttribute("btnType",e)):f.innerHTML=d;f.setAttribute("btnType",e);f.onclick=function(a){var b=a.srcElement.getAttribute("btnType");if(0==b)showNextSlide();else if(1==b)showPrevSlide();
else if(2==b)showPgThumbnailView();else if(3==b||4==b)this.lastChild.style.display="block"==this.lastChild.style.display?"none":"block",4==b?setCurorCheck("dze_idx_oneffice_cursor_box"):setZoomCheck("dze_idx_oneffice_zoomRatio_box");0!=b&&1!=b&&2!=b||displaySlideShowMenu(!1);TBCancelBubbleEvent(a)};return f}
function createSlideShowMenu(){try{if(!oneffice.m_bEmbeded){var a=document.createElement("div");a.id="dze_idx_oneffice_show_menu_container";a.className="dze_oneffice_show_menu_container";a.style.display="none";a.onmousedown=function(a){TBCancelBubbleEvent(a)};a.onmouseup=function(a){TBCancelBubbleEvent(a)};a.onclick=function(a){TBCancelBubbleEvent(a)};a.onmouseover=function(a){!0===g_bSlideMode&&(displaySlideShowMenu(!0),TBCancelBubbleEvent(a))};a.onmouseleave=function(a){!0===g_bSlideMode&&(displaySlideShowMenu(!1),
TBCancelBubbleEvent(a))};var b=createcommonDivMenu("dze_idx_oneffice_go_next_slide_btn","dze_oneffice_slide_show_btn","icon_slide_next.png",ID_RES_CONST_STRING_NEXT_SLIDE,0),c=createcommonDivMenu("dze_idx_oneffice_go_prev_slide_btn","dze_oneffice_slide_show_btn","icon_slide_pre.png",ID_RES_CONST_STRING_PREV_SLIDE,1),d=createcommonDivMenu("dze_idx_oneffice_go_move_slide_btn","dze_oneffice_slide_show_btn","icon_slide_move.png",ID_RES_CONST_STRING_MOVE_SLIDE,2),e=createcommonDivMenu("dze_idx_oneffice_go_zoom_slide_btn",
"dze_oneffice_slide_show_btn","icon_slide_expand.png",ID_RES_CONST_STRING_ZOOM_INOUT,4);createSubZoomOutMenu(e,"dze_idx_oneffice_zoomRatio_box");if(0<dzeUiConfig.aSlideShowCursorList.length){var f=createcommonDivMenu("dze_idx_oneffice_cursor_show_btn","dze_oneffice_slide_show_btn","icon_slide_pointer.png",ID_RES_CONST_STRING_POINTER_OPTION,4);createSubCursorMenu(f,"dze_idx_oneffice_cursor_box")}var g=createcommonDivMenu("dze_idx_oneffice_go_show_slide_btn","dze_oneffice_slide_show_btn","icon_slide_exit.png",
ID_RES_CONST_STRING_VIEW_SHOW,6);g.onclick=function(a){setFullScreen();displaySlideShowMenu(!0);TBCancelBubbleEvent(a);setTimeout(function(){displaySlideShowMenu(!1)},3E3)};var h=createcommonDivMenu("dze_idx_oneffice_close_show_slide_btn","dze_oneffice_slide_show_btn","icon_slide_exit.png",ID_RES_CONST_STRING_SLIDE_SHOW_EXIT,6);h.onclick=function(a){!0===g_DirectShowMode?window.close():setSlideShowMode(!1);TBCancelBubbleEvent(a)};a.appendChild(b);a.appendChild(c);c.style.marginTop="10px";a.appendChild(d);
d.style.marginTop="10px";a.appendChild(e);e.style.marginTop="10px";0<dzeUiConfig.aSlideShowCursorList.length&&(a.appendChild(f),f.style.marginTop="10px");a.appendChild(g);g.style.marginTop="10px";a.appendChild(h);h.style.marginTop="10px";document.body.appendChild(a)}}catch(m){dalert(m)}}function showSlideShowMenu(a){try{if(!oneffice.m_bEmbeded){var b=document.getElementById("dze_idx_oneffice_show_menu_container");b&&(b.style.opacity="0",b.style.display=!0===a?"":"none")}}catch(c){dalert(c)}}
function setZoomRatio(a,b){zoomOutList(!1);for(var c=-1,d=0;d<a.childElementCount;d++)b===a.childNodes[d]&&(c=d);a=a.getElementsByClassName("dze_menu_sub_iconChild");for(d=0;d<a.length;d++)a[d].firstElementChild.style.visibility="hidden";b.childNodes[1].firstElementChild.style.visibility="visible";-1==c?console.alert("error Selected -1"):(setZoomMode(c),showAllPageNumLayer(!1))}
function setZoomMode(a){try{var b=1,c=ONE_PX2MM;switch(a){case 0:b=(document.documentElement.scrollWidth?window.innerHeight?window.innerHeight:document.documentElement.clientHeight:document.body.scrollHeight)/Math.floor(dzeUiConfig.nSettingPaperSize.height/c);break;case 1:b=(document.documentElement.clientWidth-20)/Math.floor(dzeUiConfig.nSettingPaperSize.width/c);break;case 2:b=1.25;break;case 3:b=1.5;break;case 4:b=1.75}b=b.toFixed(2);1<b?(document.body.style.overflowX="hidden",document.body.style.overflowY=
"auto"):(document.body.style.overflowX="hidden",document.body.style.overflowY="hidden");document.body.style.width="100%";document.body.style.height="100%";oneffice.m_bEmbeded&&(document.body.className="unselectable",document.body.style.pointerEvents="none");changeCss(".dze_printpreview_pagebox","margin","0px auto",document);if(oneffice.m_bEmbeded){var d=document.getElementById("totalPageContainer");d.style.width="calc(100% / "+b+")";d.style.transform="scale("+b+")";d.style.msTransform="scale("+b+
")";d.style.WebkitTransform="scale("+b+")";d.style.transformOrigin="center top";d.style.msTransformOrigin="center top";d.style.margin="0px auto";d.style.borderWidth="0px";d.style.background="white"}else{var e=document.getElementsByClassName("dze_printpreview_pagebox");for(c=0;c<e.length;c++)e[c].style.transform="scale("+b+")",e[c].style.msTransform="scale("+b+")",e[c].style.WebkitTransform="scale("+b+")",e[c].style.transformOrigin="center top",e[c].style.msTransformOrigin="center top",e[c].style.margin=
"0px auto",e[c].style.borderWidth="0px"}g_ZoomRatioIndex=a}catch(f){dalert(f)}}
function displaySlideShowMenu(a){try{if(!oneffice.m_bEmbeded){var b=document.getElementById("dze_idx_oneffice_show_menu_container");b&&(!0===a?(window.outerWidth===screen.width&&window.outerHeight===screen.height?(document.getElementById("dze_idx_oneffice_go_show_slide_btn").style.display="none",document.getElementById("dze_idx_oneffice_close_show_slide_btn").style.display="flex"):void 0!==document.fullScreenElement&&null===document.fullScreenElement||void 0!==document.msFullscreenElement&&null===
document.msFullscreenElement||void 0!==document.mozFullScreen&&!document.mozFullScreen||void 0!==document.webkitIsFullScreen&&!document.webkitIsFullScreen?(document.getElementById("dze_idx_oneffice_go_show_slide_btn").style.display="flex",document.getElementById("dze_idx_oneffice_close_show_slide_btn").style.display="none"):(document.getElementById("dze_idx_oneffice_go_show_slide_btn").style.display="none",document.getElementById("dze_idx_oneffice_close_show_slide_btn").style.display="flex"),b.style.opacity=
"1.0"):(b.style.opacity="0",document.getElementById("dze_idx_oneffice_show_contextmenu_container")&&(document.getElementById("dze_idx_oneffice_show_contextmenu_container").style.display="none"),document.getElementById("dze_idx_oneffice_zoomRatio_box").style.display="none",document.getElementById("dze_idx_oneffice_cursor_box").style.display="none"))}}catch(c){dalert(c)}}
function setSlideShowCursorStyle(a){try{if(0!=slideList.length){g_cursorStyle=a;var b=null;1<=a&&(b=dzeEnvConfig.strPath_Image+dzeUiConfig.aSlideShowCursorList[a]+".cur");document.body.style.cursor="url("+b+"), pointer";for(a=0;a<slideList.length;a++)slideList[a].style.cursor=b?"url("+b+"), pointer":"default"}}catch(c){dalert(c)}}var bIsZoomout=!1;
function zoomOutList(a,b){try{window.scrollTo(0,0);!0!==b&&(b=!1);30<total_page_no&&(b=!1);var c=1;!0===a&&(c=.25);var d=document.getElementById("totalPageContainer");g_bSlideMode?document.body.style.height="100%":(!0===a?execZooming(d,"out",c,b):execZooming(d,"in",c,b),document.body.style.height=Math.ceil(total_page_height*c)+10+"px");var e=document.getElementsByClassName("slidePageNumLayer");for(b=0;b<e.length;b++)e[b].style.fontSize=!0===a?"50pt":"";!0!==g_bSlideMode&&(bIsZoomout=a);!0===a?(document.getElementById("idx_btn_show_zoomout").style.display=
"none",document.getElementById("idx_btn_show_zoomin").style.display=""):(document.getElementById("idx_btn_show_zoomout").style.display="",document.getElementById("idx_btn_show_zoomin").style.display="none")}catch(f){dalert(f)}}
function execZooming(a,b,c,d){try{if("undefined"==typeof d&&(d=!0),!0!==d)setZoom(a,c);else{var e=1;e="out"==b?1:.25;var f=setInterval(function(){if("out"==b){if(e-=.05,e<=c){setZoom(a,c);clearTimeout(f);return}}else if(e+=.05,e>=c){setZoom(a,c);clearTimeout(f);return}setZoom(a,e)},30)}}catch(g){dalert(g)}}
function setZoom(a,b){a.style.webkitTransform="scale("+b+")";a.style.msTransform="scale("+b+")";a.style.transform="scale("+b+")";a.style.transformOrigin="center top";a.style.msTransformOrigin="center top"}function execSlideDblClick(a){try{!0===g_bSlideMode||oneffice.m_bEmbeded||!0===bIsZoomout||!0===g_bSlideMode||setSlideShowMode(!g_bSlideMode,a)}catch(b){dalert(b)}}
function execSlideClick(a){try{if(!1!==bIsZoomout&&!0!==g_bSlideMode){var b=slideList[a-1];b&&(b.removeAttribute("style"),b.style.backgroundColor=dzeUiConfig.sSettingPaperColor);zoomOutList(!1,!1);setSlidePositionInSlideList(a,!1)}}catch(c){dalert(c)}}
function execSlideMouseOver(a){try{if(!1!==bIsZoomout&&!0!==g_bSlideMode){var b=slideList[a-1];b&&(b.style.transform="scale(1.1)",b.style.msTransform="scale(1.1)",b.style.WebkitTransform="scale(1.1)",b.style.transformOrigin="center top",b.style.msTransformOrigin="center top",b.style.borderWidth="10px",b.style.borderColor="#1c90fb",b.style.borderStyle="solid",b.style.zIndex="10001",b.style.cursor="pointer",1<a?a==total_page_no?b.style.marginTop="-130px":(b.style.marginTop="-80px",b.style.marginBottom=
"75px"):b.style.marginBottom="-20px")}}catch(c){dalert(c)}}function execSlideMouseOut(a){try{if(!1!==bIsZoomout&&!0!==g_bSlideMode){var b=slideList[a-1];b&&(b.removeAttribute("style"),b.style.backgroundColor=dzeUiConfig.sSettingPaperColor)}}catch(c){dalert(c)}}
function setSlidePositionInSlideList(a,b){try{if("undefined"==typeof b&&(b=!0),g_bSlideMode)document.body.style.overflow="hidden",g_slideNo<=totalSlideCount?hideSlide("up",function(){g_slideNo=a;showSlide()}):showToastMsg(ID_RES_CONST_STRING_LAST_PAGE,1.5);else{var c=a-1;if("undefined"!=typeof slideList[c]){var d=0;d=document.documentElement.scrollWidth?window.innerHeight?window.innerHeight:document.documentElement.clientHeight:document.body.scrollHeight;var e=slideList[c].offsetTop-(d-Math.floor(dzeUiConfig.nSettingPaperSize.height/
ONE_PX2MM))/2;!0===bIsZoomout&&(e=Math.floor(e/2));if(!0===b)var f=0,g=setInterval(function(){f+=300;f>=e?(window.scrollTo(0,e),clearInterval(g)):window.scrollTo(0,f)},10);else setTimeout(function(){window.scrollTo(0,e)},100)}}}catch(h){dalert(h)}}
function showPgThumbnailView(){try{!1===g_objOnefficeShot.m_bCreate&&slideList.forEach(function(a){a.style.display="";a.style.opacity="1"}),document.body.style.overflow="auto",g_objOnefficeShot.getShotScreenContainerViewer(slideList),document.body.scrollTop=0}catch(a){dalert(a)}}
function createMobileController(a){try{if(!0===g_browserCHK.mobile&&oneffice.getAppEnvType()!=APPENV.WE&&!onefficeCommon.isOnefficeGuideDoc(oneffice.currFileSeq)&&oneffice_cloud_myInfoData&&oneffice.parentFileContent){var b=document.createElement("div");b.id="dze_idx_oneffice_mobile_control_container";b.className="dze_oneffice_mobile_control_container";b.style.opacity="0";!1===g_browserCHK.iPad&&!1===g_browserCHK.androidtablet&&(b.style.bottom="75px");var c=document.createElement("div");c.className=
"dze_oneffice_mobile_control_unit";c.onclick=function(a){if("0"!=dzeJ(".dze_oneffice_mobile_control_unit").parent().css("opacity")){showMobileControlContainer(!1);var b={url:oneffice.getEditModeDocPath(oneffice.currFileSeq,oneffice.onefficeGroupSeq,"mode_change_edit"),mode:"r"};b="app://onefficeOpenIn/"+Base64.encode(JSON.stringify(b));if(!0===g_browserCHK.iOS){var c=document.createElement("a");c.href=b;c.click()}else document.location.href=b;TBCancelBubbleEvent(a)}};b.appendChild(c);document.body.appendChild(b);
window.addEventListener("click",function(a){g_HybridViewMode?window.parent.postMessage({uiEvent:"tap"},"*"):g_objNodeUtil.getLoopParentElement(a.target||a.srcElement,"a")||showMobileControlContainer(!bStatusMobileController)},!1);dzeJ(b).on({touchstart:function(){dzeJ(this).addClass("dze_oneffice_mobile_control_unit_on")},touchend:function(){dzeJ(this).removeClass("dze_oneffice_mobile_control_unit_on")}});!0===a&&onefficeUtil.openDocComment()}}catch(d){dalert(d)}}
var bStatusMobileController=!1,bShowMobileControllerTimer=null;function showMobileControlContainer(a){try{var b=document.getElementById("dze_idx_oneffice_mobile_control_container");bStatusMobileController=!0;null!==bShowMobileControllerTimer?(clearTimeout(bShowMobileControllerTimer),b.style.opacity="1"):duzon_dialog.fade("in",b);bShowMobileControllerTimer=setTimeout(function(){dzeJ(b).animate({opacity:"0"},300);bStatusMobileController=!1},2500)}catch(c){dalert(c)}}
function goOnefficeEdit(){try{removeHash();var a=document.location.href.replace(/oneffice(_view)*\.(html|do)/,"oneffice.html");g_HybridViewMode&&onefficeUtil.setCookieValue("hybridEdit","1",10);onefficeUtil.setCookieValue("edtM","1",10);document.location.href=a}catch(b){dalert(b)}}function allMovieReset(){var a=document.getElementById("totalPageContainer");if(!fnObjectCheckNull(a)){a=a.getElementsByTagName("video");for(var b=0;b<a.length;b++)a[b].pause()}}
window.onresize=function(){window.outerWidth===screen.width&&window.outerHeight===screen.height&&(dlog("Document FULL ScREEN CHANGE"),displaySlideShowMenu(!0),setChartAnimation(!0))};
function setChartAnimation(a,b){if(!0===a){a={duration:1E3,easing:"easeOutBounce",bRestartAnimation:!0};for(var c=onefficeChart.showViewCharts.length,d=0;d<c;d++){var e=onefficeChart.showViewCharts[d].id;"undefined"!==typeof b&&0>b.indexOf(e)||(e=onefficeChart.showViewCharts[d].chartHandler,e.options.tooltips.enabled=!0,e.options.animation={animateScale:!0,animateRotate:!0},e.update(a))}}else for(c=onefficeChart.showViewCharts.length,a={duration:0,bRestartAnimation:!1},d=0;d<c;d++)e=onefficeChart.showViewCharts[d].chartHandler,
e.options.tooltips.enabled=!1,e.options.animation=null,e.update(a)}var g_objShowMgr=new function(){this.showNSlide=function(a){try{if(a&&g_slideNo<=totalSlideCount)return hideSlide("up",function(){g_slideNo=a;showSlide()}),!0;showToastMsg(ID_RES_CONST_STRING_INVALID_CALL,1.5);return!1}catch(b){dalert(b)}}};
function replaceImgSrcWithDataSrc(a){try{return g_bBrowserType_SF||g_browserCHK.iOS?a.replace(/(<(?:img).*?)(src)(=".*?"[^>]+>)/g,function(a,c,d,e){return c+"src='data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==' data-src"+e}):a}catch(b){return dalert(b),a}}
function setImageLoadingLazyForView(a){try{if(!a||1!==a.nodeType)return!1;g_bBrowserType_SF||g_browserCHK.iOS?"undefined"!==typeof pageLocation&&"view"===pageLocation&&dzeJ(a).find("img").Lazy({visibleOnly:!0}):g_bBrowserType_CR&&forEach(a.querySelectorAll("img"),function(a,c){c.setAttribute("loading","lazy")});return!0}catch(b){dalert(b)}};
