/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// resource.js -	다국어 지원용 resource 모음(KOREAN)
//					
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


// 전체 적용되는 리소스 선언
var ID_RES_GLOBAL_DEFAULT_FONT_FAMILY = "굴림";				//1
var ID_RES_GLOBAL_FONT_FAMILY_TYPE_1 = "돋움";

// ComboBox Size Layer(comboboxwin) 리소스 선언
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_8 = "가나다라 ABCD";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_24 = "가나다 ABC";
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_36 = "가나 AB";			//5
var ID_RES_COOMBOBOX_WIN_SIZE_TEXT_MAX = "가나";
var ID_RES_COOMBOBOX_FONT_NAME_0 = "돋움";
var ID_RES_COOMBOBOX_FONT_NAME_1 = "돋움체";
var ID_RES_COOMBOBOX_FONT_NAME_2 = "굴림";
var ID_RES_COOMBOBOX_FONT_NAME_3 = "굴림체";					//10
var ID_RES_COOMBOBOX_FONT_NAME_4 = "바탕";
var ID_RES_COOMBOBOX_FONT_NAME_5 = "바탕체";
var ID_RES_COOMBOBOX_FONT_NAME_6 = "궁서";
var ID_RES_COOMBOBOX_FONT_NAME_7 = "맑은 고딕";
var ID_RES_COOMBOBOX_FONT_NAME_8 = "arial";					//15
var ID_RES_COOMBOBOX_FONT_NAME_9 = "tahoma";
var ID_RES_COOMBOBOX_FONT_NAME_10 = "times new roman";

// 글관련 서식 제거 문구 선언
var ID_RES_COMBOBOX_REMOVE_FONT_FAMILY = "기본";
var ID_RES_COMBOBOX_REMOVE_FONT_SIZE = "기본";
var ID_RES_COMBOBOX_REMOVE_LETTER_SPACING = "기본";			//20
var ID_RES_COMBOBOX_REMOVE_LINE_HEIGHT = "기본";

// 에디터 문자상수(initconst) 리소스 선언
var ID_RES_CONST_STRING_BOLD = "굵게";
var ID_RES_CONST_STRING_ITALIC = "기울임꼴";
var ID_RES_CONST_STRING_UNDERLINE = "밑줄";
var ID_RES_CONST_STRING_JUSTIFYLEFT = "왼쪽 맞춤";				//25
var ID_RES_CONST_STRING_JUSTIFYCENTER = "가운데 맞춤";
var ID_RES_CONST_STRING_JUSTIFYRIGHT = "오른쪽 맞춤";
var ID_RES_CONST_STRING_JUSTIFYJUSTIFY = "양쪽 맞춤";
var ID_RES_CONST_STRING_ORDERLIST = "문단 번호 모양";
var ID_RES_CONST_STRING_UNORDERLIST = "글머리표 모양";			//30
var ID_RES_CONST_STRING_STRIKE = "취소선";
var ID_RES_CONST_STRING_SUBSCRIPT = "아래 첨자";
var ID_RES_CONST_STRING_SUPERSCRIPT = "위 첨자";
var ID_RES_CONST_STRING_OUTDENT = "내어쓰기";
var ID_RES_CONST_STRING_INDENT = "들여쓰기";					//35
var ID_RES_CONST_STRING_UNDO = "되돌리기";
var ID_RES_CONST_STRING_REDO = "다시하기";
var ID_RES_CONST_STRING_FONT_NAME = "글꼴 종류";
var ID_RES_CONST_STRING_FONT_SIZE = "글꼴 크기";
var ID_RES_CONST_STRING_FORE_COLOR = "글꼴 색";					//40
var ID_RES_CONST_STRING_BACK_COLOR = "글꼴 배경색";		
var ID_RES_CONST_STRING_TABLE_CREATE = "표";
var ID_RES_CONST_STRING_TABLE_ADD_ROW = "위에 행 삽입";
var ID_RES_CONST_STRING_TABLE_ADD_ROW_DOWN = "아래에 행 삽입";
var ID_RES_CONST_STRING_TABLE_COPY_ROW_DOWN = "행 추가(복사)";	//45
var ID_RES_CONST_STRING_TABLE_DELETE_ROW = "행 삭제";
var ID_RES_CONST_STRING_TABLE_ADD_COL = "왼쪽에 열 삽입";
var ID_RES_CONST_STRING_TABLE_ADD_COL_RIGHT = "오른쪽에 열 삽입";
var ID_RES_CONST_STRING_TABLE_DELETE_COL = "열 삭제";
var ID_RES_CONST_STRING_TABLE_MERGE_CELL = "셀 병합";			//50
var ID_RES_CONST_STRING_TABLE_SPLIT_ROW = "행 분할";
var ID_RES_CONST_STRING_TABLE_SPLIT_COL = "열 분할";
var ID_RES_CONST_STRING_TABLE_SELECT = "선택";

var ID_RES_CONST_STRING_IMAGE_INSERT = "이미지 삽입/속성";
var ID_RES_CONST_STRING_FLASH_INSERT = "플래시 삽입/속성";		//55
var ID_RES_CONST_STRING_MEDIA_INSERT = "동영상 삽입/속성";
var ID_RES_CONST_STRING_FULLSCREEN = "전체화면";
var ID_RES_CONST_STRING_TABLE_CELL_PROPERTY = "셀&nbsp;속성";
var ID_RES_CONST_STRING_TABLE_PROPERTY = "표&nbsp;속성";
var ID_RES_CONST_STRING_MARK_INSERT = "특수문자 삽입";			//60
var ID_RES_CONST_STRING_TABLE_TEMPLETE_INSERT = "표 생성(템플릿)";


var ID_RES_CONST_STRING_ADJUST_HWP_BASIC = "한글보정";
var ID_RES_CONST_STRING_ADJUST_DOC_BASIC = "워드보정";
var ID_RES_CONST_STRING_HORIZONTAL_RULE = "수평선 삽입";
var ID_RES_CONST_STRING_LETTER_SPACING = "글간격";				//65
var ID_RES_CONST_STRING_LINE_HEIGHT = "줄간격";
var ID_RES_CONST_STRING_BODY_BG_COLOR = "문서 배경색";
var ID_RES_CONST_STRING_BODY_BG_IMAGE = "문서 배경이미지";
var ID_RES_CONST_STRING_DOC_TEMPLETE = "편집블럭 삽입";
var ID_RES_CONST_STRING_PREVIEW = "미리보기";					//70
var ID_RES_CONST_STRING_HIDE_MINIBAR = "미니바 숨기기";
var ID_RES_CONST_STRING_WRITE_AREA_SET = "편집영역 설정";
var ID_RES_CONST_STRING_SHOW_EDITABLE_AREA = "편집영역 보이기";
var ID_RES_CONST_STRING_SAVEAS = "파일 내려받기";
var ID_RES_CONST_STRING_PRINT = "인쇄";						//75
var ID_RES_CONST_STRING_Z_INDEX_SETTING = "z-Index 설정";
var ID_RES_CONST_STRING_TEXT_BOX = "글상자";
var ID_RES_CONST_STRING_OBJECT_POSITION = "객체 Position 설정";
var ID_RES_CONST_STRING_RESPONSIVE_WIDTH = "반응형 크기 확인";
var ID_RES_CONST_STRING_DOC_LAYOUT = "레이아웃 설정";			//80
var ID_RES_CONST_STRING_HEADING_SIZE = "스타일";
var ID_RES_CONST_STRING_RESPONSIVE_SET = "반응형 일괄설정";
var ID_RES_CONST_STRING_FORM_TABLE = "표 편집블럭";
var ID_RES_CONST_STRING_DRAW_TABLE = "쉬운 표 삽입";


//파일 메뉴 
var ID_RES_CONST_STRING_FILE_NEW				= "새로 만들기";	//85
var ID_RES_CONST_STRING_FILE_OPEN				= "열기";
var ID_RES_CONST_STRING_FILE_DOCFORM			= "문서 양식";
var ID_RES_CONST_STRING_FILE_LAYOUT				= "레이아웃 템플릿";

//편집 메뉴 
var ID_RES_CONST_STRING_CUT						= "잘라내기";
var ID_RES_CONST_STRING_COPY					= "복사하기";	//90
var ID_RES_CONST_STRING_PASTE					= "붙여넣기";
var ID_RES_CONST_STRING_EDIT_PASTESPECIAL		= "골라 붙이기";
var ID_RES_CONST_STRING_SELECT_ALL				= "전체선택";
var ID_RES_CONST_STRING_EDIT_SEARCH				= "찾기";		//95
var ID_RES_CONST_STRING_EDIT_REPLACE			= "바꾸기";
var ID_RES_CONST_STRING_REPLACE_CASE			= "대/소문자 바꾸기";

//보기 메뉴 
var ID_RES_CONST_STRING_VIEW_EDIT				= "편집 보기";
var ID_RES_CONST_STRING_VIEW_HTML				= "HTML 보기";

//삽입 메뉴 
var ID_RES_CONST_STRING_INSERT_IMAGE			= "그림";		//100
var ID_RES_CONST_STRING_INSERT_OBJECT			= "개체";
var ID_RES_CONST_STRING_INSERT_SPECIALCHARS		= "기호";
var ID_RES_CONST_STRING_INSERT_EMOTICONS		= "이모티콘";
var ID_RES_CONST_STRING_INSERT_BOOKMARK			= "책갈피";
var ID_RES_CONST_STRING_HYPERLINK_INSERT		= "하이퍼 링크";			//105
var ID_RES_CONST_STRING_HYPERLINK_MODIFY		= "하이퍼링크 고치기";
var ID_RES_CONST_STRING_HYPERLINK_REMOVE		= "하이퍼링크 지우기";

//서식 메뉴 
var ID_RES_CONST_STRING_STYLE_FONT				= "글꼴";
var ID_RES_CONST_STRING_STYLE_PARAGRAPH			= "단락";
var ID_RES_CONST_STRING_STYLE_STYLE				= "스타일";			//110
var ID_RES_CONST_STRING_STYLE_UNORDEREDLIST		= "글머리 기호";
var ID_RES_CONST_STRING_STYLE_ORDEREDLIST		= "번호 매기기";
var ID_RES_CONST_STRING_STYLE_INCREASEORDER		= "수준 증가";
var ID_RES_CONST_STRING_STYLE_DECREASEORDER		= "수준 감소";

//표 메뉴 
var ID_RES_CONST_STRING_TABLE_CELL_STYLE		= "테두리 및 배경";		//115
var ID_RES_CONST_STRING_TABLE_ADD_ROW_COL		= "줄/칸 추가하기";
var ID_RES_CONST_STRING_TABLE_DELETE_ROW_COL	= "줄/칸 지우기";
var ID_RES_CONST_STRING_TABLE_SPLIT_CELL		= "셀 분할";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_HEIGHT	= "행 높이를 같게";
var ID_RES_CONST_STRING_TABLE_CELL_SAME_WIDTH	= "열 너비를 같게";		//120
var ID_RES_CONST_STRING_TABLE_CELL_ALIGN		= "셀맞춤";
var ID_RES_CONST_STRING_TABLE_MADANG			= "표 스타일";
var ID_RES_CONST_STRING_TABLE_FORMULA			= "계산식";
var ID_RES_CONST_STRING_TABLE_NUMBER_FORMAT		= "1,000단위 구분쉼표";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICALALIGN	= "셀 세로 정렬";	//125

var ID_RES_CONST_STRING_TABLE_BLOCK_FORMULA		= "블록 계산식";
//var ID_RES_CONST_STRING_TABLE_FORMULA			= "계산식";
var ID_RES_CONST_STRING_TABLE_SELECT_FORMULA	= "선택 계산식";
var ID_RES_CONST_STRING_TABLE_EASY_FORMULA	= "쉬운 계산식";

//도움말
var ID_RES_CONST_STRING_HELP_SHORTCUTS = "단축키 도움말";				//130
var ID_RES_CONST_STRING_HELP = "동영상 매뉴얼";
var ID_RES_CONST_STRING_PRODUCT_INFO = "제품 정보";


//2depth 메뉴
var ID_RES_CONST_STRING_INSERT_OBJECT_MOVIE = "비디오";
var ID_RES_CONST_STRING_INSERT_OBJECT_FILE = "파일";
var ID_RES_CONST_STRING_INSERT_OBJECT_HR = "가로줄";					//135

var ID_RES_CONST_STRING_STYLE_STYLE_BASIC = "기본";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT1 = "제목1";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT2 = "제목2";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT3 = "제목3";
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT4 = "제목4";				//140
var ID_RES_CONST_STRING_STYLE_STYLE_SUBJECT5 = "제목5";

var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_TOP = "위쪽 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_MIDDLE = "가운데 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_VERTICAL_BOTTOM = "아래쪽 정렬";

var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTALALIGN	= "셀 가로 정렬";	//145
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_LEFT = "왼쪽 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_CENTER = "가운데 정렬";
var ID_RES_CONST_STRING_TABLE_CELL_HORIZONTAL_RIGHT = "오른쪽 정렬";

var ID_RES_CONST_STRING_TABLE_BLOCK_SUM = "블록 합계";
var ID_RES_CONST_STRING_TABLE_BLOCK_AVG = "블록 평균";					//150
var ID_RES_CONST_STRING_TABLE_BLOCK_MUL = "블록 곱";

var ID_RES_CONST_STRING_TABLE_HORIZONTAL_SUM = "가로 합계";
var ID_RES_CONST_STRING_TABLE_VERTICAL_SUM = "세로 합계";
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_AVERAGE = "가로 평균";
var ID_RES_CONST_STRING_TABLE_VERTICAL_AVERAGE = "세로 평균";			//155
var ID_RES_CONST_STRING_TABLE_HORIZONTAL_MULTIPLY = "가로 곱";
var ID_RES_CONST_STRING_TABLE_VERTICAL_MULTIPLY = "세로 곱";

var ID_RES_CONST_STRING_TABLE_ADD_NUMBER_FORMAT = "자릿점 넣기";
var ID_RES_CONST_STRING_TABLE_REMOVE_NUMBER_FORMAT = "자릿점 빼기";


//-- 툴바에만 존재하는 버튼
var ID_RES_CONST_STRING_STYLE_INCREASE_FONTSIZE = "글꼴 크기 크게";		//160
var ID_RES_CONST_STRING_STYLE_DECREASE_FONTSIZE = "글꼴 크기 작게";

// 폼태그 버튼
var ID_RES_CONST_STRING_FORM_TAG_SWITCH = "폼 컨트롤 선택전환";
var ID_RES_CONST_STRING_FORM_TAG_CHECKBOX = "선택상자";
var ID_RES_CONST_STRING_FORM_TAG_SELECT = "목록상자";

// 양식 템플릿
var ID_RES_CONST_STRING_TEMPLETE_FORM = "양식 템플릿";					//165

// 빈문단삽입
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_STARTPOINT = "시작점 문단삽입";
var ID_RES_CONST_STRING_INSERT_PARAGRAPH_ENDPOINT = "끝지점 문단삽입";

// 표 삭제
var ID_RES_CONST_STRING_TABLE_DELETE_TABLE = "표 삭제";

// 삽입 - 문단
var ID_RES_CONST_STRING_INSERT_PARAGRAPH = "문단";

// 서식 - 글자모양 - 보통모양 버튼 텍스트
var ID_RES_CONST_STRING_NORMAL = "보통모양";							//170

//표 - 표 텍스트로 변환
var ID_RES_CONST_STRING_TABLE_CONVERT_TEXT = "표 텍스트로 변환";

// 테이블생성 Layer(tablesize) 리소스 선언
var ID_RES_TABLE_SIZE_SELECT = "선 택";
var ID_RES_TABLE_SIZE_CANCEL = "취 소";

// 툴빌더(toolbuilder) 리소스 선언
var ID_RES_TOOL_STRING_MENU_FILE = "파일";
var ID_RES_TOOL_STRING_MENU_EDIT = "편집";							//175
var ID_RES_TOOL_STRING_MENU_VIEW = "보기";
var ID_RES_TOOL_STRING_MENU_INSERT = "삽입";
var ID_RES_TOOL_STRING_MENU_BASIC = "서식";
var ID_RES_TOOL_STRING_MENU_TABLE = "표";
var ID_RES_TOOL_STRING_MENU_HELP = "도움말";							//180
var ID_RES_TOOL_STRING_TAB_PREVIEW = "미리보기";
var ID_RES_TOOL_STRING_TAB_EDIT = "편집보기";
var ID_RES_TOOL_STRING_TAB_SOURCE = "HTML보기";

// 사용자메세지(usermsg) 리소스 선언
var ID_RES_USER_MSG_STRING_ALERT_CUT = "브라우저 보안 설정상 실행할 수 없습니다\nCtrl+X 키보드 명령어로는 실행하실 수는 있습니다";
var ID_RES_USER_MSG_STRING_ALERT_COPY = "브라우저 보안 설정상 실행할 수 없습니다\nCtrl+C 키보드 명령어로는 실행하실 수는 있습니다";	//185
var ID_RES_USER_MSG_STRING_ALERT_PASTE = "브라우저 보안 설정으로 인해 클립보드에 접근이 제한되어 있습니다.\n키보드(Ctrl+V)를 이용하여 주시기 바랍니다.";
var ID_RES_USER_MSG_STRING_WARNING_SCRIPT = "소스 코드상에 스크립트를 포함할 수 없습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_MEDIA = "동영상 삽입은 IE 6,7,8 만 지원됩니다\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_IFRAME = "소스 코드상에 iframe 태그를 포함할 수 없습니다\n";
var ID_RES_USER_MSG_STRING_WARNING_NO_SOURCE_EDIT = "양식폼 사용자 모드에서는 소스창을 사용할 수 없습니다\n";				//190
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_2 = "파이어폭스에서는 3버전 이상부터 지원됩니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_FLASH_FF_EDIT = "파이어폭스 편집모드 설정상 지원되지 않습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_NO_SUPPORT_FORM_MODE = "코드검사는 양식관리자 또는 사용자모드에서는 지원되지 않습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_ATTIRIBUTE_CHARACTER = "속성값으로 <,>,&,\',\" 등은 사용할 수 없습니다\n";
//var ID_RES_USER_MSG_STRING_WARNING_INVALID_COLOR_CODE = "유효한 색상코드를 입력하셔야 합니다.\n 예) #0099ff\n";		//195
//var ID_RES_USER_MSG_STRING_WARNING_IN_CONTROL_KEY_NO_SOURCE_EDIT = "키보드 제어용에서는 소스창을 사용할 수 없습니다";

// 문서보정(leftviewui) 리소스 선언
var ID_RES_ADJUST_VIEW_CLOSE = "닫기";

// 편집창 Title 리소스 선언
var ID_RES_EDIT_TITLE_STRING = "글입력부분";

var ID_RES_PROP_BUILDER_BLOCK_PROP_ITEM_APPLY = "적용";

// 양식 저작(Form Table) 리소스 선언
var ID_RES_PROP_FORM_WIN_TITLE = "양식 레이아웃";
var ID_RES_PROP_TAG_SELECT_WIN_TITLE = "목록 상자";
var ID_RES_PROP_MAPPING_CODE_WIN_TITLE = "양식 코드";
var ID_RES_PROP_MAPPING_CSS_WIN_TITLE = "양식 CSS 설정";
var ID_RES_PROP_TEMPLETE_FORM_WIN_TITLE = "양식 템플릿";					//205

// 컨텍스트 메뉴
var ID_RES_PROP_INSERT_IMAGE = "그림 속성";
var ID_RES_PROP_INSERT_FILE = "파일 속성";

var ID_RES_DIALOG_BTN_OK = "확인";
var ID_RES_DIALOG_BTN_CANCEL = "취소";
var ID_RES_DIALOG_BTN_NOCOLOR = "색 없음";								//210
var ID_RES_DIALOG_TAB_GENERAL = "일반";
var ID_RES_DIALOG_TAB_BORDER = "테두리";
var ID_RES_DIALOG_TAB_BACKGROUND = "배경";
var ID_RES_DIALOG_FORM_LIST1 = "샘플항목1";
var ID_RES_DIALOG_FORM_LIST2 = "샘플항목2";								//215
var ID_RES_DIALOG_FORM_LIST3 = "샘플항목3";
var ID_RES_DIALOG_MAPPINGCODE_TAB1 = "전자결재양식";
var ID_RES_DIALOG_MAPPINGCODE_TAB2 = "공문양식";
var ID_RES_DIALOG_CONFIRM_SAVE = "<p>작성중인 내용이 있습니다.</p><p>저장하시겠습니까?</p>";
var ID_RES_DIALOG_CONFIRM_YES = "예";								//220
var ID_RES_DIALOG_CONFIRM_NO = "아니오";
var ID_RES_DIALOG_CONFIRM_EMPTY_DOC = "문서가 비어있습니다. 확인해 주세요.";
var ID_RES_DIALOG_ALERT_SELECTFILE = "파일을 선택 해 주세요.";
var ID_RES_DIALOG_CONFIRM_FILE_DELETE_CONTENT = "파일을 불러오면 작성중인 내용이 삭제됩니다.<br/>파일을 불러 오시겠습니까?";
var ID_RES_DIALOG_ALERT_ALLOWFILES = "파일은 업로드 불가합니다.\n업로드 가능 파일";	//225
var ID_RES_DIALOG_ALERT_SELECTIMAGE = "이미지파일을 선택한 후 업로드 버튼을 클릭해 주세요.";
var ID_RES_DIALOG_ALERT_SELECT_VALID_IMAGE = "정상적인 이미지를 삽입해주세요.";
var ID_RES_DIALOG_ALERT_FIND_INPUT_TEXT = "찾을 내용을 입력 해 주세요.";
var ID_RES_DIALOG_ALERT_FIND_ERROR = "검색 중 에러가 발생했습니다.";
var ID_RES_DIALOG_ALERT_FIND_NOTHING = "해당 내용을 찾지 못했습니다.";			//230
var ID_RES_DIALOG_CONFIRM_FIND_END = "문서의 끝까지 찾았습니다.<br/>문서 처음부터 계속 찾으시겠습니까?";
var ID_RES_DIALOG_CONFIRM_FIND_FIRST = "문서의 처음까지 찾았습니다.<br/>문서 끝부터 계속 찾으시겠습니까?";
var ID_RES_DIALOG_ALERT_REPLACE_INPUT_TEXT = "바꿀 내용을 입력 해 주세요.";
var ID_RES_DIALOG_ALERT_REPLACE_ERROR = "바꾸기 진행 중 에러가 발생했습니다.";
var ID_RES_DIALOG_ALERT_REPLACEALL_COMPLETE = "모두 바꾸기가 완료되었습니다.";	//235
var ID_RES_DIALOG_ALERT_REPLACE_N = "개 항목이 바뀌었습니다.";
var ID_RES_DIALOG_TITLE_FIND_REPLACE = "찾기 및 바꾸기";
var ID_RES_DIALOG_BTN_REPLACEALL = "모두바꾸기";
var ID_RES_DIALOG_BTN_FIND_NEXT = "다음찾기";
var ID_RES_DIALOG_TITLE_EXT_MOVIE = "외부 동영상";						//240
var ID_RES_DIALOG_TITLE_FILE_INSERT = "파일 삽입";
var ID_RES_DIALOG_BTN_INSERT = "넣기";
var ID_RES_DIALOG_TITLE_WEBEDITOR_INFO = "DOUZONE ONEFFICE 정보";

var ID_RES_DIALOG_LIST_TITLE_FORM_AREA = "분류";
var ID_RES_DIALOG_LIST_TITLE_FORM_SELECT = "양식";					//245
var ID_RES_DIALOG_ALERT_SELECT_DOCFORM = "서식 양식을 선택 해 주세요.";
var ID_RES_DIALOG_CONFIRM_DOCFORM_DELETE_CONTENT = "서식 양식을 삽입하면 편집하던 문서 내용이 삭제됩니다.<br/>삽입 하시겠습니까?";
var ID_RES_DIALOG_ALERT_SELECT_LAYOUT_DESIGN = "레이아웃 디자인을 선택 해 주세요.";
var ID_RES_DIALOG_CONFIRM_LAYOUT_DELETE_CONTENT = "레아아웃을 삽입하면 편집하던 문서 내용이 삭제됩니다.<br/>삽입 하시겠습니까?";

var ID_RES_DIALOG_STRING_FILE_PATH = "파일 경로";						//250
var ID_RES_DIALOG_STRING_URL_INPUT = "URL 입력";
var ID_RES_DIALOG_STRING_UPLOAD = "업로드";
var ID_RES_DIALOG_STRING_SIZE = "크기";
var ID_RES_DIALOG_STRING_WIDTH = "너비";
var ID_RES_DIALOG_STRING_HEIGHT = "높이";
var ID_RES_DIALOG_STRING_KEEP_RATIO = "비율 유지";
var ID_RES_DIALOG_STRING_SET_ORG = "크기 원래대로";
var ID_RES_DIALOG_STRING_MARGIN = "여백";
var ID_RES_DIALOG_STRING_MARGIN_LEFT = "왼쪽 여백";
var ID_RES_DIALOG_STRING_MARGIN_TOP = "위쪽 여백";						//260
var ID_RES_DIALOG_STRING_MARGIN_RIGHT = "오른쪽 여백";	
var ID_RES_DIALOG_STRING_MARGIN_BOTTOM = "아래쪽 여백";
var ID_RES_DIALOG_STRING_ALIGN_BASIC = "기본";
var ID_RES_DIALOG_STRING_ALIGN_LEFT = "왼쪽";
var ID_RES_DIALOG_STRING_ALIGN_CENTER = "가운데";
var ID_RES_DIALOG_STRING_ALIGN_RIGHT = "오른쪽";
var ID_RES_DIALOG_ALERT_MAX_VALUE = "최대값을 벗어났습니다.\n최대값 : ";
var ID_RES_DIALOG_ALERT_MIN_VALUE = "최소값을 벗어났습니다.\n최소값 : ";
var ID_RES_DIALOG_ALERT_NUMBER_ONLY = "숫자만 입력 가능합니다.";
var ID_RES_DIALOG_ALERT_SELECT_VALID_URL = "이미지 URL을 다시 한번 확인 해 주세요!";	//270
var ID_RES_DIALOG_ALERT_UPLOAD_ERROR = "업로드시 오류가 발생했습니다. 다시 한번 시도해 주세요.";
var ID_RES_DIALOG_ALERT_INSERT_IMAGE = "이미지를 먼저 등록해주세요.";
var ID_RES_DIALOG_STRING_NO_STYLE_TEXT = "서식 없는 텍스트";
var ID_RES_DIALOG_STRING_HTML_STYLE_TEXT = "HTML 형식";
var ID_RES_DIALOG_STRING_FIND_TEXT = "찾을 내용";
var ID_RES_DIALOG_STRING_REPLACE_TEXT = "바꿀 내용";
var ID_RES_DIALOG_STRING_FIND_OPTION = "검색 옵션";
var ID_RES_DIALOG_STRING_CASESENSITIVE = "대소문자 구분";
var ID_RES_DIALOG_STRING_COMPLETEWORD = "온전한 낱말";
var ID_RES_DIALOG_STRING_IGNORESPACE = "띄어쓰기 무시";							//280
var ID_RES_DIALOG_STRING_FIND_DERECTION = "검색 방향";
var ID_RES_DIALOG_STRING_FIND_DOWN = "아래쪽";
var ID_RES_DIALOG_STRING_FIND_UP = "위쪽";
var ID_RES_DIALOG_STRING_INPUT_SOURCE = "소스 입력";
var ID_RES_DIALOG_STRING_MOVIE_INPUT_GUIDE = "object 또는 iframe 소스코드 입력해 주세요.";
var ID_RES_DIALOG_STRING_INPUT_MOVIE_SOURCE = "동영상 소스를 입력 해 주세요.";
var ID_RES_DIALOG_STRING_VIEW_TEXT = "표시할 텍스트";
var ID_RES_DIALOG_ALERT_ALLOW_FORMAT = "포멧만 지원합니다.";
var ID_RES_DIALOG_STRING_CHARACTER_AREA = "문자 영역";
var ID_RES_DIALOG_STRING_CHARACTER_SELECT = "문자 선택";					//290
var ID_RES_DIALOG_STRING_RECECT_USE_CHARACTER = "최근에 사용한 문자";

var ID_RES_DIALOG_ALERT_SELECT_CHARACTER = "문자를 선택해 주세요.";
var ID_RES_CONST_STRING_CHARACTER_GENERAL = "일반/기호";
var ID_RES_CONST_STRING_CHARACTER_ENG_NUMBER = "영어/숫자";
var ID_RES_CONST_STRING_CHARACTER_GREEK = "그리스어";
var ID_RES_CONST_STRING_CHARACTER_LINE = "선문자";
var ID_RES_CONST_STRING_CHARACTER_UNIT = "단위기호";
var ID_RES_CONST_STRING_CHARACTER_CIRCLE = "원문자";
var ID_RES_CONST_STRING_CHARACTER_BRAKETCHAR = "괄호문자";
var ID_RES_CONST_STRING_CHARACTER_FRACTION_SCRIPT = "분수/첨자";			//300
var ID_RES_CONST_STRING_CHARACTER_ARROW = "화살표";
var ID_RES_CONST_STRING_CHARACTER_BRAKET = "괄호";
var ID_RES_CONST_STRING_CHARACTER_MATH = "수학연산";
var ID_RES_CONST_STRING_CHARACTER_PUNCTUATION_MARKS = "문장부호";
var ID_RES_CONST_STRING_CHARACTER_CURRENCY = "화폐기호";

var ID_RES_DIALOG_STRING_BOOKMARK_NAME = "책갈피 이름";
var ID_RES_DIALOG_STRING_BOOKMARK_LIST = "책갈피 목록";
var ID_RES_DIALOG_STRING_MOVE = "이동";
var ID_RES_DIALOG_STRING_BOOKMARK_SORT_STANDARD = "책갈피 정렬 기준";
var ID_RES_DIALOG_STRING_NAME = "이름";									//310
var ID_RES_DIALOG_STRING_POSITION = "위치";
var ID_RES_DIALOG_ALERT_INPUT_BOOKMARK_NAME = "책갈피 이름을 입력해 주세요";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_DELTE_BOOKMARK_ITEM = "북마크 목록에서 삭제할 항목을 선택해 주세요";
var ID_RES_DIALOG_ALERT_INPUT_SELECT_MOVE_BOOKMARK_ITEM = "북마크 목록에서 이동할 항목을 선택해 주세요";

var ID_RES_DIALOG_STRING_LINK_TYPE = "링크 종류";
var ID_RES_DIALOG_STRING_WEB_ADDR = "웹 주소";
var ID_RES_DIALOG_STRING_LINK_TARGET = "연결 문서 열기";
var ID_RES_DIALOG_STRING_LINK_CURRENT_WINDOW = "같은 창으로";
var ID_RES_DIALOG_STRING_LINK_NEW_WINDOW = "새 창으로";
var ID_RES_DIALOG_STRING_LINK_NO_CONNECT = "연결 안함";						//320
var ID_RES_DIALOG_STRING_LIST_SELECT = "선택";
var ID_RES_DIALOG_ALERT_SELECT_BOOKMARK = "책갈피를 선택해 주세요";
var ID_RES_DIALOG_ALERT_INPUT_WEB_ADDR = "웹주소를 입력해 주세요";

var ID_RES_DIALOG_STRING_LETTERSPACING = "자간";
var ID_RES_DIALOG_STRING_BASIC = "기본";
var ID_RES_DIALOG_STRING_PROPERTY = "속성";
var ID_RES_DIALOG_STRING_FONT_STYLE_PREVIEW = "가나다ABCabc123※○";

var ID_RES_DIALOG_STRING_ALIGN_TYPE = "정렬 방식";
var ID_RES_DIALOG_STRING_NORMAL = "보통";
var ID_RES_DIALOG_STRING_SPACING = "간격";								//330
var ID_RES_DIALOG_STRING_LINEHEIGHT = "줄간격";
var ID_RES_DIALOG_STRING_PARAGRAPH_TOP = "단락위";
var ID_RES_DIALOG_STRING_PARAGRAPH_BOTTOM = "단락아래";
var ID_RES_DIALOG_STRING_FIRST_PARAGRAPH = "첫줄";

var ID_RES_DIALOG_STRING_NONE = "없음";
var ID_RES_DIALOG_STRING_VERSION = "버전";


var ID_RES_DIALOG_STRING_FORM_BASE_SIZE = "기준 크기 / 높이";
var ID_RES_DIALOG_STRING_FORM_HEIGHT_MSG = "높이 설정은<br />양식 생성시 반영됨";
var ID_RES_DIALOG_STRING_FORM_OUTLINE = "외곽선";
var ID_RES_DIALOG_STRING_FORM_TYPE = "유형";								//340
var ID_RES_DIALOG_STRING_FORM_COLOR = "색상";
var ID_RES_DIALOG_STRING_FORM_MULTI_SELECT = "다중선택 :<br />&nbsp;&nbsp;Ctrl키 + 객체 선택";
var ID_RES_DIALOG_STRING_FORM_MULTI_OTHER_SELECT = "다중선택 :<br />&nbsp;&nbsp;객체 선택->shift 키-><br />&nbsp;&nbsp;다른 객체 선택";
var ID_RES_DIALOG_STRING_FORM_COPY_PASTE = "복사/붙여넣기 :<br />&nbsp;&nbsp;객체 선택 후 Ctrl키 + V";
var ID_RES_DIALOG_STRING_FORM_COPY_MOVE = "이동 :<br />&nbsp;&nbsp;상하좌우 화살표 키";
var ID_RES_DIALOG_STRING_FORM_RESIZE = "크기조정 :<br />&nbsp;&nbsp;Ctrl 키 + 화살표 키";
var ID_RES_DIALOG_STRING_FORM_PRE_APPLY = "미리적용";
var ID_RES_DIALOG_ALERT_FORM_SIZE = "크기(width) 단위가 % 인 경우만 지원하고 있습니다.";

var ID_RES_PROP_TAG_STRING_ROW_NUM = "줄 수";
var ID_RES_PROP_TAG_STRING_COL_NUM = "칸 수";								//350
var ID_RES_PROP_TAG_STRING_ROW_COL = "줄 / 칸";
var ID_RES_PROP_TAG_STRING_SIZE_DEFINE = "크기 지정";
var ID_RES_PROP_TAG_STRING_WIDTH_UNIT = "너비 단위";
var ID_RES_PROP_TAG_STRING_ALL_CELL_INNER_MARGIN = "모든 셀의 여백";
var ID_RES_PROP_TAG_STRING_TABLE_ALIGN = "정렬";

var ID_RES_PROP_TAG_STRING_FILL = "채우기";								//360
var ID_RES_PROP_TAG_STRING_NO_COLOR_FILL = "색 채우기 없음";
var ID_RES_PROP_TAG_STRING_COLOR = "색";
var ID_RES_PROP_TAG_STRING_FACE_COLOR = "면 색";

var ID_RES_PROP_TAG_STRING_IMAGE = "그림";
var ID_RES_PROP_TAG_STRING_USER_IMAGE = "그림 사용";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE = "그림 파일";
var ID_RES_PROP_TAG_STRING_FILL_TYPE = "채우기 유형";
var ID_RES_PROP_TAG_STRING_REPEAT = "반복";
var ID_RES_PROP_TAG_STRING_REPEAT_HOR = "가로 반복";
var ID_RES_PROP_TAG_STRING_REPEAT_VER = "세로 반복";						//370
var ID_RES_PROP_TAG_STRING_REPEAT_NO = "반복 안함";

var ID_RES_PROP_TAG_LIST_NUM = "목록 개수";
var ID_RES_PROP_TAG_LIST_CONTENT = "목록 내용";

var ID_RES_PROP_TAG_ADD_ROW = "줄 추가하기";
var ID_RES_PROP_TAG_UP = "위쪽";
var ID_RES_PROP_TAG_DOWN = "아래쪽";
var ID_RES_PROP_TAG_ADD_COL = "칸 추가하기";

var ID_RES_PROP_TAG_SET_INNER_MARGIN = "안 여백 지정";

var ID_RES_PROP_TAG_STRING_LEFT = "왼쪽";
var ID_RES_PROP_TAG_STRING_TOP = "위쪽";									//380
var ID_RES_PROP_TAG_STRING_RIGHT = "오른쪽";								
var ID_RES_PROP_TAG_STRING_BOTTOM = "아래쪽";
var ID_RES_PROP_TAG_STRING_CENTER = "가운데";

var ID_RES_PROP_TAG_STRING_ALIGN_HOR = "가로정렬";
var ID_RES_PROP_TAG_STRING_ALIGN_VER = "세로정렬";
var ID_RES_PROP_TAG_STRING_ALIGN_TOP = "위쪽 맞춤";
var ID_RES_PROP_TAG_STRING_ALIGN_MIDDLE = "가운데 맞춤";
var ID_RES_PROP_TAG_STRING_ALIGN_BOTTOM = "아래쪽 맞춤";

var ID_RES_PROP_TAG_STRING_APPLY_RANGE= "적용 범위";
var ID_RES_PROP_TAG_STRING_SELECTED_CELL = "선택된 셀";
var ID_RES_PROP_TAG_STRING_ALL_CELL = "모든 셀";							//390

var ID_RES_PROP_TAG_STRING_SELECT_CELL_EDITOR = "적용할 셀을 편집창에서 선택하세요.";
var ID_RES_PROP_TAG_STRING_NO_CALC_SELECTED_CELL = "계산 불가한 항목이 선택되었습니다.";
var ID_RES_PROP_TAG_STRING_SELECT_CELL = "셀 선택";
var ID_RES_PROP_TAG_STRING_CALC_TYPE = "계산 방법";
var ID_RES_PROP_TAG_STRING_CALC_SUM = "합계";
var ID_RES_PROP_TAG_STRING_CALC_AVG = "평균";
var ID_RES_PROP_TAG_STRING_CALC_MUL = "곱";
var ID_RES_PROP_TAG_STRING_CALC_RESULT = "계산 결과";
var ID_RES_PROP_TAG_STRING_SPLIT_ROW_COL = "줄/칸 나누기";					//400

var ID_RES_PROP_TEMPLETE_STRING_FORM_SUBJECT = "양식 제목";
var ID_RES_PROP_TEMPLETE_STRING_SUBJECT = "제목";
var ID_RES_PROP_TEMPLETE_STRING_SIZE_ITEM_SET = "크기 / 항목 설정";
var ID_RES_PROP_TEMPLETE_STRING_AUTO = "자동";
var ID_RES_PROP_ALERT_ONLY_NUMBER_CALC = "숫자만 계산이 가능합니다.";

var ID_RES_DIALOG_SHORTCUTS_TITLE = "단축키";
var ID_RES_DIALOG_SHORTCUTS_MENU_PATH = "메뉴경로";
var ID_RES_DIALOG_SHORTCUTS_FUNCTION = "기능";
var ID_RES_DIALOG_SHORTCUTS_BASIC = "기본 단축키";
var ID_RES_DIALOG_SHORTCUTS_SPACE = "빈칸 삽입";							//410
var ID_RES_DIALOG_SHORTCUTS_ENTER = "문단 나누기";
var ID_RES_DIALOG_SHORTCUTS_LEFT = "한 글자 왼쪽으로";
var ID_RES_DIALOG_SHORTCUTS_RIGHT = "한 글자 오른쪽으로";
var ID_RES_DIALOG_SHORTCUTS_DOWN = "한 줄 아래로";
var ID_RES_DIALOG_SHORTCUTS_UP = "한 줄 위로";
var ID_RES_DIALOG_SHORTCUTS_RIGHT_WORD = "한 단어 오른쪽으로";
var ID_RES_DIALOG_SHORTCUTS_LEFT_WORD = "한 단어 왼쪽으로";
var ID_RES_DIALOG_SHORTCUTS_DOWN_PARAGRAPH = "한 문단 아래로";
var ID_RES_DIALOG_SHORTCUTS_UP_PARAGRAPH = "한 문단 위로";
var ID_RES_DIALOG_SHORTCUTS_HOME = "줄 처음으로";							//420
var ID_RES_DIALOG_SHORTCUTS_END = "줄 끝으로";
var ID_RES_DIALOG_SHORTCUTS_HOME_PAGE = "화면 처음으로";
var ID_RES_DIALOG_SHORTCUTS_END_PAGE = "화면 끝으로";
var ID_RES_DIALOG_SHORTCUTS_DELETE = "뒷글자 지우기";
var ID_RES_DIALOG_SHORTCUTS_BACKSPACE = "앞글자 지우기";
var ID_RES_DIALOG_SHORTCUTS_DELETE_WORD = "한 단어 지우기";
var ID_RES_DIALOG_SHORTCUTS_DELETE_PREV_WORD = "앞 단어 지우기";

var ID_RES_DIALOG_SHORTCUTS_FILE = "파일 메뉴";
var ID_RES_DIALOG_SHORTCUTS_EDIT = "편집 메뉴";
var ID_RES_DIALOG_SHORTCUTS_INSERT = "삽입 메뉴";							//430
var ID_RES_DIALOG_SHORTCUTS_STYLE = "서식 메뉴";	
var ID_RES_DIALOG_SHORTCUTS_TABLE = "표 메뉴";

var ID_RES_CONST_STRING_CLEAR = "해제";

var ID_RES_CONST_STRING_INCREASE_LETTERSPACING = "자간 넓게";
var ID_RES_CONST_STRING_DECREASE_LETTERSPACING = "자간 좁게";

var ID_RES_CONST_STRING_INCREASE_MARGIN_LEFT = "왼쪽 여백 늘리기";
var ID_RES_CONST_STRING_DECREASE_MARGIN_LEFT = "왼쪽 여백 줄이기";
var ID_RES_CONST_STRING_INCREASE_MARGIN_RIGHT = "오른쪽 여백 늘리기";
var ID_RES_CONST_STRING_DECREASE_MARGIN_RIGHT = "오른쪽 여백 줄이기";

var ID_RES_CONST_STRING_FIRST_PARAGRAPH_OUTDENT = "첫 줄 내어쓰기";			//440
var ID_RES_CONST_STRING_FIRST_PARAGRAPH_INDENT = "첫 줄 들여쓰기";

var ID_RES_CONST_STRING_INCREASE_LINEHEIGHT = "줄 간격 넓게";
var ID_RES_CONST_STRING_DECREASE_LINEHEIGHT = "줄 간격 좁게";

var ID_RES_CONST_STRING_SELECT_CURRENT_CELL = "현재 셀 선택";
var ID_RES_CONST_STRING_MOVE_CELL_UNIT = "셀 단위로 커서 이동";
var ID_RES_CONST_STRING_MOVE_NEXT_CELL = "표 안에서 다른 셀로 이동(정방향)";
var ID_RES_CONST_STRING_MOVE_PREV_CELL = "표 안에서 다른 셀로 이동(역방향)";

var ID_RES_CONST_STRING_BLOCK_ALL_COL = "칸 전체 블록";
var ID_RES_CONST_STRING_BLOCK_ALL_ROW = "줄 전체 블록";
var ID_RES_CONST_STRING_MULTI_CELL_SELECT = "다중 셀 선택 시";				//450
var ID_RES_CONST_STRING_ARROW_KEY = "방향키";

var ID_RES_CONST_STRING_STANDARD = "표준";
var ID_RES_CONST_STRING_USER_DEFINE = "사용자 정의";
var ID_RES_CONST_STRING_USER_SET = "사용자 지정";
var ID_RES_CONST_STRING_REPLACE_CASE_CAPITAL = "모두 대문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_SMALL = "모두 소문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_REVERSE = "대소문자 바꿈";
var ID_RES_CONST_STRING_REPLACE_CASE_LETTER = "단어 첫 글자 대문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_SENTENCE = "문장 첫 글자 대문자로";
var ID_RES_CONST_STRING_REPLACE_CASE_PARAGRAPH = " 문단 첫 글자 대문자로";		//460
var ID_RES_CONST_BTN_DELETE = "삭제";
var ID_RES_CONST_INSERT_IMAGE_PARAGRAPH_ALIGN = "본문 정렬";

var ID_RES_CONST_STRING_NEW_COLOR = "새 색";
var ID_RES_CONST_STRING_CURRENT_COLOR = "현재 색";
var ID_RES_CONST_STRING_OTHER_COLOR = "다른 색";
var ID_RES_CONST_STRING_RECENT_COLOR = "최근 사용한 색";
var ID_RES_CONST_STRING_ADD_USER_COLOR = "사용자 지정 색에 추가";
var ID_RES_CONST_STRING_RED = "빨강";
var ID_RES_CONST_STRING_GREEN = "녹색";
var ID_RES_CONST_STRING_BLUE = "파랑";									//470
var ID_RES_CONST_STRING_HUE = "색상";
var ID_RES_CONST_STRING_SATURATION = "채도";
var ID_RES_CONST_STRING_LIGHTNESS = "명도";

var ID_RES_CONST_MSG_ALERT_NO_RECENT_COLOR = "최근 사용한 색이 없습니다.";
var ID_RES_CONST_MSG_ALERT_DELETE_RECENT_COLOR = "최근 사용한 색을 모두 삭제하시겠습니까?";

var ID_RED_CONST_STRING_ALIGN_LEFT_TOP		= "왼쪽 위 정렬";
var ID_RED_CONST_STRING_ALIGN_LEFT_MIDDLE	= "왼쪽 가운데 정렬";
var ID_RED_CONST_STRING_ALIGN_LEFT_BOTTOM	= "왼쪽 아래 정렬";
var ID_RED_CONST_STRING_ALIGN_CENTER_TOP	= "위쪽 가운데 정렬";
var ID_RED_CONST_STRING_ALIGN_CENTER_MIDDLE = "정가운데 정렬";					//480
var ID_RED_CONST_STRING_ALIGN_CENTER_BOTTOM = "아래쪽 가운데 정렬";
var ID_RED_CONST_STRING_ALIGN_RIGHT_TOP		= "오른쪽 위 정렬";
var ID_RED_CONST_STRING_ALIGN_RIGHT_MIDDLE	= "오른쪽 가운데 정렬";
var ID_RED_CONST_STRING_ALIGN_RIGHT_BOTTOM	= "오른쪽 아래 정렬";
var ID_RED_CONST_STRING_TABLE_CELL_BACKCOLOR	= "음영";

var ID_RES_CONST_STRING_COLOR_STANDARD = "표준 색";
var ID_RES_CONST_STRING_COLOR_THEME = "테마 색";

var ID_RES_CONST_STRING_EMOTICONS_FEEL = "감정";
var ID_RES_CONST_STRING_EMOTICONS_ACTION = "행동";
var ID_RES_CONST_STRING_EMOTICONS_ETC = "기타";							//490
var ID_RES_DIALOG_STRING_CATEGORY_AREA = "분류";
var ID_RES_DIALOG_STRING_EMOTICON_SELECT = "이모티콘 선택";
var ID_RES_DIALOG_STRING_RECECT_USE_EMOTICONS = "최근에 사용한 이모티콘";

var ID_RES_UI_TOGGLE_STRING_RIBBON = "리본 메뉴 스타일";
var ID_RES_UI_TOGGLE_STRING_TOOLBAR = "툴바 메뉴 스타일";
var ID_RES_CONST_STRING_PRINT_PAGE_BREAK = "페이지 나누기";
var ID_RES_CONST_STRING_VIEW_RULERBAR = "눈금자";
var ID_RES_DIALOG_STRING_CASCADE_ORDERLIST = "다단계 목록";
var ID_RES_CONST_STRING_COPY_EXT_STYLE = "서식 복사";

var ID_RES_CONST_STRING_BORDER_TYPE = "테두리 종류";					//500
var ID_RES_CONST_STRING_BORDER_THICKNESS = "테두리 두께";
var ID_RES_CONST_STRING_BORDER_COLOR = "테두리 색";
var ID_RES_CONST_STRING_RESET_PICTURE = "원래대로";

var ID_RES_CONST_STRING_NO_LINE = "선 없음";
var ID_RES_CONST_STRING_SOLID_LINE = "실선";
var ID_RES_CONST_STRING_DASHED_LINE = "파선";
var ID_RES_CONST_STRING_DOTTED_LINE = "점선";
var ID_RES_CONST_STRING_DOUBLE_LINE = "이중선";

var ID_RES_CONST_STRING_TABLE_SELECT_CELL = "셀 선택";
var ID_RES_CONST_STRING_TABLE_SELECT_COL = "열 선택";					//510
var ID_RES_CONST_STRING_TABLE_SELECT_ROW = "행 선택";
var ID_RES_CONST_STRING_TABLE_SELECT_TABLE = "표 선택";

var ID_RES_CONST_STRING_IMAGE_TO_TABLE = "폼봇";
var ID_RES_DIALOG_ALERT_SELECT_TABLE_STYLE = "스타일을 선택해주세요.";

var ID_RES_CONST_STRING_TEXTBOX	= "텍스트 상자";//"텍스트상자";

var ID_RES_CONST_TAB_COLOR_AND_BORDER = "색 및 선";
var	ID_RES_DIALOG_BTN_MODIFY = "수정";
var ID_RES_CONST_TEXTATT = "글꼴";
var ID_RES_CONST_TEXTATT_STYLE = "글꼴 스타일";
var ID_RES_CONST_VERTICAL_ALIGN = "세로 맞춤";							//520

var ID_RES_CONST_STRING_INNER_MARGIN = "안쪽 여백";
var ID_RES_CONST_STRING_OUTER_MARGIN = "바깥 여백";
var ID_RES_CONST_STRING_LINE = "선";
var ID_RES_CONST_STRING_LINE_WIDTH = "두께";
var ID_RES_CONST_STRING_LINE_STYLE = "종류";

var ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO = "정상적인 동영상을 삽입해주세요.";
var ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO_EMPTY = "업로드할 동영상을 선택해주세요.";
var ID_RES_CONST_STRING_WEB_SEARCH = "웹검색";
var ID_RES_CONST_STRING_NO_SEARCH_RESULT = "검색된 결과가 없습니다.";
var ID_RES_CONST_STRING_INPUT_SEARCH_KEYWORD = "검색어를 입력해 주세요.";
var ID_RES_CONST_STRING_CONV_KOREAN = "한영변환";						//530
var ID_RED_CONST_STRING_ENCYCLOPEDIA = "백과사전";
var ID_RED_CONST_STRING_IMAGE = "이미지";
var ID_RED_CONST_STRING_NEWS = "뉴스";
var ID_RED_CONST_STRING_VIEW_MORE = "더보기";
var ID_RED_CONST_STRING_SEARCHING = "검색중";
var ID_RES_CONST_STRING_HIGHLIGHTER = "형광펜";
var ID_RES_CONST_ALERT_HIGHLIGHTER_MODE = "ESC 키를 누르면 형광펜 모드가 해제됩니다.";
var ID_RES_CONST_TABLE_CELL_PASTE = "복사한셀 붙여넣기";
var ID_RES_CONST_ALERTTABLE_CELL_PASTE_MODE = "ESC키를 누르면 복사한 셀 붙여넣기가 해제됩니다.";

var ID_RES_PROP_INSERT_VIDEO = "비디오 속성";							//540
var ID_RES_PROP_TEXTBOX_CONTENTS = "내용";
var ID_RES_CONST_STRING_SAVEAS_REMOTE = "사본 만들기";
var ID_RES_CONST_STRING_SAVE_REMOTE = "저장하기";

var ID_RES_CONST_STRING_NEW_DOCUMENT = "새 문서";
var ID_RES_CONST_STRING_NEW_FOLDER = "새 폴더";
var ID_RES_CONST_STRING_OPEN_DOCUMENT = "열기";
var ID_RES_CONST_STRING_SET_FAVORITE_ON = "중요 표시";
var ID_RES_CONST_STRING_SET_FAVORITE_OFF = "중요 표시 해제";
var ID_RES_CONST_STRING_RENAME = "이름 변경";
var ID_RES_CONST_STRING_COPY = "복사";									//550
var ID_RES_CONST_STRING_SET_READONLY_ON = "읽기전용 설정";
var ID_RES_CONST_STRING_SET_READONLY_OFF = "읽기전용 해제";
var ID_RES_CONST_STRING_CLEAR_TRASHBOX = "휴지통 비우기";
var ID_RES_CONST_STRING_RESTORE = "복원";
var ID_RES_CONST_STRING_DELETE_COMPLETE = "영구 삭제";
var ID_RES_CONST_STRING_SHARE_DOCUMENT = "공유";
var ID_RES_CONST_STRING_UNSHARE_DOCUMENT = "공유 해제";

var ID_RES_CONST_STRING_PLEASE_INPUT_FOLDER_NAME = "폴더명을 입력해주세요.";
var ID_RES_CONST_STRING_PLEASE_INPUT_RENAME = "변경할 이름을 입력해주세요.";
var ID_RES_CONST_STRING_CONFIRM_DELETE_DOCUMENT = "'{0}' 문서를 삭제하시겠습니까?";								//560
var ID_RES_CONST_STRING_CONFIRM_DELETE_FOLDER = "폴더를 삭제하면 내부 파일도 모두 삭제됩니다. <br/>삭제하시겠습니까?";
var ID_RES_CONST_STRING_CONFIRM_DELETE_SELECTED_DOCUMENT = "{0}개의 문서를 삭제하시겠습니까?";
var ID_RES_CONST_STRING_CONFIRM_DELETE_SELECTED_FOLDER_FILE = "폴더를 삭제하면 내부 문서도 모두 삭제됩니다.<br/>선택 된 항목들을 삭제하시겠습니까?";
var ID_RES_CONST_STRING_NOTI_DELETED_DOCUMENT = "{0}개의 문서를 삭제하였습니다.";
var ID_RES_CONST_STRING_ALREADY_DELETED_DOCUMENT = "삭제되었거나, 권한이 변경된 문서입니다.";
var ID_RES_CONST_STRING_WARNING_FILE_DUPLICATE = "같은 이름의 폴더/문서가 존재합니다. 다른 이름을 입력해주세요.";
var ID_RES_CONST_STRING_WARNING_CANNOT_MOVE_SELECTED_FOLDER = "선택된 폴더로 이동할 수 없습니다.";

var ID_RES_CONST_STRING_PRINT_MARGIN_SETTING = "페이지 여백설정";
var ID_RES_CONST_STRING_PRINT_MARGIN_NARROW = "좁게";
var ID_RES_CONST_STRING_PRINT_MARGIN_NORMAL = "보통";							//570
var ID_RES_CONST_STRING_PRINT_MARGIN_WIDE = "넓게";

var ID_RES_CONST_STRING_BROWSER_MY = "내 문서함";
var ID_RES_CONST_STRING_BROWSER_RECENT = "ONEFFICE HOME";
var ID_RES_CONST_STRING_BROWSER_SHARE = "공유문서함";
var ID_RES_CONST_STRING_BROWSER_FAVORITE = "중요문서함";
var ID_RES_CONST_STRING_BROWSER_TRASHBOX = "휴지통";
var ID_RES_CONST_STRING_BROWSER_SEARCH_RESULT = "총 {0}개의 검색결과";

var ID_RES_CONST_STRING_PAPER = "용지";
var ID_RES_CONST_STRING_PAGE_SETUP = "페이지 설정";
var ID_RES_CONST_STRING_PAPER_ORIENTATION_SERO = "세로";
var ID_RES_CONST_STRING_PAPER_ORIENTATION_GARO = "가로";							//580

var ID_RES_CONST_STRING_NOTI_COPIED_DOCUMENT = "문서를 {0}(으)로 복사하였습니다.";
var ID_RES_CONST_STRING_NOTI_MOVED_DOCUMENT = "{0} 문서를 {1}(으)로 이동하였습니다.";
var ID_RES_CONST_STRING_NOTI_MOVED_DOCUMENT_LIST = "{0}개의 문서를 이동하였습니다.";
var ID_RES_CONST_STRING_NOTI_SHARE_DOCUMENT = "{0} 문서가 공유되었습니다.";
var ID_RES_CONST_STRING_NOTI_UNSHARE_DOCUMENT = "{0} 문서의 공유가 해제되었습니다.";
var ID_RES_CONST_STRING_NOTI_UNSHARE_MULTI_DOCUMENT = "{0}개 문서의 공유가 해제되었습니다.";

var ID_RES_CONST_STRING_TEXTBOX_FILL_COLOR = "채우기 색";
var ID_RES_CONST_STRING_TEXTBOX_BORDER_COLOR = "테두리 색";

var ID_RES_CONST_STRING_INSERT_CHART = "차트";
var ID_RES_CONST_STRING_NOTI_DELETE_CONFIRM = "정말 삭제하시겠습니까?";			//590
var ID_RES_CONST_STRING_COMPLETE_DELETE_CONFIRM = "영구 삭제 시 삭제된 파일은 복구할 수 없습니다.<br>영구 삭제 하시겠습니까?";			//590

var ID_RES_CONST_STRING_PAGE_DELETE_CONFIRM = "페이지 내용도 함께 삭제됩니다.<br>페이지를 삭제하시겠습니까?";			//590

var ID_RES_CONST_STRING_GROUP_CHART = "조직도";
var ID_RES_CONST_STRING_PAGE_SETTING = "페이지 설정";
var ID_RES_CONST_STRING_PASTE_CELL = "셀 붙여넣기 옵션";
var ID_RES_CONST_STRING_PASTE_CELL_INSERT = "새 행으로 삽입";
var ID_RES_CONST_STRING_PASTE_CELL_OVER_ALL = "셀 덮어쓰기";
var ID_RES_CONST_STRING_PASTE_CELL_OVER_CONTENT = "내용 붙여넣기";

var ID_RES_CONST_STRING_SHARE_LINK_COPY = "링크 복사";
var ID_RES_CONST_STRING_CONVERT_ELE_TO_IMG = "캔버스";

var ID_RES_CONST_STRING_BROWSER_MY_SHARE_LIST = "공유한 문서";
var ID_RES_CONST_STRING_BROWSER_SHARED_BY_LIST = "공유받은 문서";				//600

var ID_RES_CONST_STRING_SHARE_PERMISSION_VIEW = "링크가 있는 모든 사용자 보기 가능";
var ID_RES_CONST_STRING_SHARE_PERMISSION_EDIT = "링크가 있는 모든 사용자 편집 가능";

var ID_RES_UI_TOGGLE_STRING_MENUSTYLE = "메뉴 스타일";
var ID_RES_CONST_STRING_WARNING_INVALID_DOCUMENT_CALL = "잘못된 문서링크 입니다.";

var ID_RES_CONST_STRING_NOTI_MOVED_LIST_FAIL = "{0}개의 문서 이동이 실패하였습니다.";
var ID_RES_CONST_STRING_NOTI_COPIED_LIST_FAIL = "문서 복사가 실패하였습니다.";
var ID_RES_CONST_STRING_NOTI_DELETE_FAIL_DOCUMENT_LIST = "{0}개의 문서 삭제가 실패하였습니다.";

var ID_RES_CONST_STRING_CONFIRM_DELETE_SHARE_DOCUMENT = "공유 문서 입니다.\n{0}개의 문서를 삭제하시겠습니까?";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_SHARE_DOCUMENT = "공유 문서가 포함되어 있습니다.\n{0}개의 문서를 삭제하시겠습니까?";
var ID_RES_CONST_STRING_CONFIRM_DELETE_IMPORTANT_DOCUMENT = "중요 문서 입니다.\n{0}개의 문서를 삭제하시겠습니까?";							//610
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_IMPORTANT_DOCUMENT = "중요 문서가 포함되어 있습니다.\n{0}개의 문서를 삭제하시겠습니까?";
var ID_RES_CONST_STRING_CONFIRM_DELETE_CONTAINS_SHARE_IMPORTANT_DOCUMENT = "중요 문서와 공유 문서가 포함되어 있습니다.\n{0}개의 문서를 삭제하시겠습니까?";

var ID_RES_CONST_STRING_GO_TO_MOVILE_VIEWER = "모바일뷰어로 이동합니다.";
var ID_RES_CONST_STRING_INVALID_CALL = "잘못된 호출입니다.";
var ID_RES_CONST_STRING_SAVED = "저장되었습니다.";
var ID_RES_CONST_STRING_AUTO_SAVED = "자동저장 되었습니다.";
var ID_RES_CONST_STRING_MOVE_TO_PARENT_FOLDER = "상위폴더로 이동";
var ID_RES_CONST_STRING_DISABLE_POPUP_BLOCKER = "팝업차단을 해제해 주세요.";
var ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT = "권한이 없거나, 없는 문서입니다.";           //620
var ID_RES_CONST_STRING_UNAUTHORIZED_OR_MISSING_DOCUMENT_2 = "권한이 없거나<br />없는 문서입니다.";
var ID_RES_CONST_STRING_DELETE_CONTAINS_IMPORTANT_DOCUMENT = "삭제된 문서는 열람할 수 없습니다.";
var ID_RES_CONST_STRING_DELETE_CONTAINS_IMPORTANT_FOLDER = "삭제된 폴더는 열람할 수 없습니다.";

var ID_RES_CONST_STRING_RECENT_NO_SHARE_DOCUMENT = "공유 권한이 해제되어 열람할 수 없습니다.";

var ID_RES_CONST_STRING_READ_ONLY = "읽기전용";
var ID_RES_CONST_STRING_OPENED_READ_ONLY = "읽기전용으로 열렸습니다.";
var ID_RES_CONST_STRING_OPENED_READ_ONLY_DOCUMENT = "읽기전용으로 열린 문서입니다.";
var ID_RES_CONST_STRING_SET_READ_ONLY = "읽기 전용 설정되었습니다.";
var ID_RES_CONST_STRING_SET_EDITABLE = "읽기 전용 해제되었습니다.";
var ID_RES_CONST_STRING_CHANGED_TO_READ_ONLY = "읽기전용으로 변경되었습니다.";

var ID_RES_CONST_STRING_ENTER_SUBJECT = "제목을 입력해 주세요";

var ID_RES_CONST_STRING_RECOVERED = "복구되었습니다.";
var ID_RES_CONST_STRING_RECOVERED_ALL = "전부 복구되었습니다.";           //630
var ID_RES_CONST_STRING_RECOVERY_FAILED = "복구에 실패했습니다.";
var ID_RES_CONST_STRING_FULL_RECOVERY_FAILED = "전체 복구에 실패했습니다.";
var ID_RES_CONST_STRING_SOME_RECOVERY_FAILED = "일부 복구에 실패했습니다.";

var ID_RES_CONST_STRING_DELETED = "삭제되었습니다.";
var ID_RES_CONST_STRING_DELETED_ALL = "전부 삭제되었습니다.";
var ID_RES_CONST_STRING_DELETE_ALL_FAIL = "전체 삭제에 실패했습니다.";
var ID_RES_CONST_STRING_DELETE_SOME_FAIL = "일부 삭제에 실패했습니다.";
var ID_RES_CONST_STRING_TRASH_IS_EMPTY = "휴지통이 비워졌습니다.";
var ID_RES_CONST_STRING_SAVING_DATA = "데이터를 저장하고 있습니다.";

var ID_RES_CONST_STRING_SELECT_IS_EMPTY = "최근 조회한 문서가 없습니다.";
var ID_RES_CONST_STRING_SELECT_IS_EMPTY_NEWDOC = "+ 새로만들기";
var ID_RES_CONST_STRING_SELECT_IS_EMPTY_TEMPLATE_MSG = "또는 템플릿으로 문서를 생성해보세요.";

var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_SET_UP = "중요문서 설정되었습니다.";           //640
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_NOT_SET_UP = "중요문서 해제되었습니다.";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_SET = "중요문서(설정됨)";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_NOT_SET = "중요문서(해제됨)";
var ID_RES_CONST_STRING_IMPORTANT_DOCUMENT_CAN_SET_BY_OWNER = "중요문서 설정은 문서 소유자만 할 수 있습니다.";

var ID_RES_CONST_STRING_ENTENR_ID = "아이디를 입력해 주세요!";
var ID_RES_CONST_STRING_LOGIN_FAIL_ENTER_CORRETLY = "로그인이 실패되었습니다. 정확히 입력해 주세요!";
var ID_RES_CONST_STRING_LAST_MODIFIED_DATE = "최근수정날짜";
var ID_RES_CONST_STRING_LAST_READ_DATE = "최근조회날짜";
var ID_RES_CONST_STRING_SHAREBY_DATE = "공유받은날짜";
var ID_RES_CONST_STRING_SHARETO_DATE = "공유한날짜";
var ID_RES_CONST_STRING_SHARE_DATE = "공유날짜";
var ID_RES_CONST_STRING_FILE_SIZE = "파일 크기";
var ID_RES_CONST_STRING_OWNER = "소유자";
var ID_RES_CONST_STRING_DELETED_DOCUMENT = "삭제된 문서";         //650
var ID_RES_CONST_STRING_COMMING_SOON = "준비중입니다.";
var ID_RES_CONST_STRING_USAGE = "사용량";
var ID_RES_CONST_STRING_SHARED_DOCUMENT = "공유문서";
var ID_RES_CONST_STRING_COPIED = "복사되었습니다.";
var ID_RES_CONST_STRING_FOLDER_LOCATION = "폴더 위치";
var ID_RES_CONST_STRING_CUSTOM_SHARE = "사용자 지정 공유";
var ID_RES_CONST_STRING_CLOSE_CUSTOM_SHARE = "사용자 지정 공유 닫기";
var ID_RES_CONST_STRING_USER_SELECTION = "사용자 선택";
var ID_RES_CONST_STRING_ADD_MESSAGE = "메시지 추가";          //660
var ID_RES_CONST_STRING_VIEWABLE = "보기 가능";
var ID_RES_CONST_STRING_EDITABLE = "편집 가능";
var ID_RES_CONST_STRING_NOT_MODIFIED = "수정된 내역이 없습니다.";
var ID_RES_CONST_STRING_NO_CELL_COPIED = "복사한 셀이 없습니다.";
var ID_RES_CONST_STRING_DOCUMENT_TITLE = "문서제목";
var ID_RES_CONST_STRING_SAVE_PATH = "저장경로";

var ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE = "파일은 업로드 할 수 없는 파일입니다.\n* 사용가능파일:";
var ID_RES_CONST_STRING_ALIGN = "맞춤";
var ID_RES_CONST_STRING_HORIZONTAL_WIDTH = "가로 너비";
var ID_RES_CONST_STRING_VERTICAL_HEIGHT = "세로 높이";                //670

var ID_RES_CONST_STRING_KEEP_ORG_HEIGHT = "원본 높이 유지";
var ID_RES_CONST_STRING_NEW_BLOCK_REFERENCE_HEIGHT = "신규 블럭은<br />기준 높이로 설정";
var ID_RES_CONST_STRING_PAPER_ORIENTATION = "용지방향";
var ID_RES_CONST_STRING_PAPER_COLOR = "배경색상";

var ID_RES_CONST_STRING_PAGE = "페이지";
var ID_RES_CONST_STRING_FIRST_PAGE = "첫 페이지 입니다.";
var ID_RES_CONST_STRING_LAST_PAGE = "마지막 페이지 입니다.";
var ID_RES_CONST_STRING_NEXT = "다음";
var ID_RES_CONST_STRING_PREV = "이전";
var ID_RES_CONST_STRING_VIEW_SHOW = "쇼 보기";                //680

var ID_RES_CONST_STRING_CELL_CONTENTS_COPIED = "셀내용이 복사되었습니다.";
var ID_RES_CONST_STRING_CANNOT_INSERT_CELL_SHAPE_DIFFERENT = "복사한셀과 대상 셀의 모양이 달라 삽입할 수 없습니다.";
var ID_RES_CONST_STRING_CLICK_INSERT_POSITION = "삽입할 위치를 클릭 하세요!";
var ID_RES_CONST_STRING_CANCLED_INSERT_CHART = "차트 삽입이 취소되었습니다.";
var ID_RES_CONST_STRING_CHART_TYPE = "차트 유형";
var ID_RES_CONST_STRING_AXIS_TRANSFORMATION = "축 변환";
var ID_RES_CONST_STRING_TRANSFORMATION = "변환";

var ID_RES_CONST_STRING_SLIDE_SHOW = "슬라이드쇼";
var ID_RES_CONST_STRING_ZOOM_OUT = "작게보기";
var ID_RES_CONST_STRING_ZOOM_IN = "원래대로";               //690
var ID_RES_CONST_STRING_SLIDE_SHOW_EXIT = "쇼 종료";
var ID_RES_CONST_STRING_BACKGROUND_COLOR = "배경색";
var ID_RES_CONST_STRING_CANNOT_READ_DOCUMENT_FORMAT = "양식 문서 포맷을 표현할 수 없습니다";
var ID_RES_CONST_STRING_LOSE_ALL_CONTINUE = "기존 작성한 내용은 초기화됩니다.<br/>계속 진행하시겠습니까?";
var ID_RES_CONST_STRING_READ_ONLY_DOCUMENT = "읽기전용문서";

var ID_RES_CONST_STRING_ENTER_DETAIL = "내용을 입력해 주세요.";

var ID_RES_CONST_STRING_DOCUMENT_SECURITY = "문서 보안";
var ID_RES_CONST_STRING_SECURITY_DOCUMENTS = "보안 문서";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_SETTING = "문서보안 설정";
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_RESET = "문서보안 변경해제";			//700
var ID_RES_CONST_STRING_DOCUMENT_SECURITY_SETTING_NOTE = "주의:\n암호를 잊으면 문서를 복구할 수 없습니다.\n암호는 대소문자를 구분하며, 4자 이상 20자 이하로 입력 가능합니다.";
var ID_RES_CONST_STRING_DOCUMENT_PASSWORD = "문서 암호";
var ID_RES_CONST_STRING_DOCUMENT_NEW_PASSWORD = "새 암호";
var ID_RES_CONST_STRING_PASSWORD_CONFIRMATION = "암호 확인";
var ID_RES_CONST_STRING_NOTI_CONFIRMATION_PASSWORD_ERROR = "확인 암호가 일치하지 않습니다.";
var ID_RES_CONST_STRING_NOTI_CHECK_PASSWORD_ERROR = "현재 암호가 설정된 암호와 일치하지 않습니다.";
var ID_RES_CONST_STRING_NOTI_DUPLICATE_PASSWORD_ERROR = "새 암호가 현재 암호와 동일합니다.";
var ID_RES_CONST_STRING_NOTI_PASSWORD_LENGTH_ERROR = "암호는 4자 이상 10자 이하로 입력 가능합니다. 다시 입력해주시기 바랍니다.";
var ID_RES_CONST_STRING_NOTI_WRONG_PASSWORD_ERROR = "암호가 정확하지 않습니다. \"Caps Lock\"이 켜져 있는지, 대소문자를 구분하여 입력하였는지 확인하시기 바랍니다.";
var ID_RES_CONST_STRING_INPUT_PASSWORD = "암호를 입력하세요.";					//710
var ID_RES_CONST_STRING_CHANGE_PASSWORD = "암호 변경";
var ID_RES_CONST_STRING_UNSET_PASSWORD = "암호 해제";

var ID_RES_CONST_STRING_IMAGE_REPLACE = "그림 바꾸기";
var ID_RES_CONST_STRING_IMAGE_SAVEAS = "그림으로 저장";
var ID_RES_CONST_STRING_ONEFFICE_CONNECT = "원피스 커넥트";
var ID_RES_CONST_STRING_DOC_OPEN = "불러오기";
var ID_RES_CONST_STRING_IMAGE_CROPPER = "이미지 자르기";

var ID_RES_CONST_STRING_SET_COMPLETE_PASSWORD = "암호가 설정되었습니다.";
var ID_RES_CONST_STRING_CHANGE_COMPLETE_PASSWORD = "암호가 변경되었습니다.";
var ID_RES_CONST_STRING_UNSET_COMPLETE_PASSWORD = "암호가 해제되었습니다."; 
var ID_RES_CONST_STRING_DOWNLOAD_PDF = "PDF 다운로드";						//720

var ID_RES_CONST_STRING_SHARE_PERMISSION_OFF = "끄기 (특정 사용자만 공유)";
var ID_RES_CONST_STRING_MAIL_SHARE = "메일 공유";
var ID_RES_CONST_STRING_NOTE_SHARE = "쪽지 공유";
var ID_RES_CONST_STRING_CHAT_SHARE = "대화방 공유";
var ID_RES_CONST_STRING_SHARE_PERMISSION_LINK = "링크가 있는 모든 사용자";
var ID_RES_CONST_STRING_PERMISSION_ALLOW_USER = "권한이 있는 사용자";

var ID_RES_CONST_STRING_NOTI_SHARE_MULTI_DOCUMENT = "{0}개 문서가 공유되었습니다.";
var ID_RES_CONST_STRING_DOC_ZOOM = "확대/축소";
var ID_RES_CONST_STRING_DOC_ZOOM_FIT_WIDTH = "페이지 너비에 맞춤";
var ID_RES_CONST_STRING_DOC_ZOOM_FIT_PAGE = "페이지 크기에 맞춤";						//730
var ID_RES_CONST_STRING_NOTI_DO_NOT_DELETE = "이 페이지는 삭제할 수 없습니다.";
var ID_RES_CONST_STRING_GET_REMOTE_SITE_CONTENT = "웹&nbsp;양식";
var ID_RES_CONST_STRING_SUPPORT_ONLY_ENTIRE_ROW_COL = "전체행 또는 전체열만 잘라내기가 가능합니다.";

var ID_RES_CONST_STRING_SELECTED_MULTI_DOCUMENT = "{0}개 문서가 선택되었습니다.";
var ID_RES_CONST_STRING_SHARED_OK = "공유됨";
var ID_RES_CONST_STRING_SHARED_NO = "공유되지 않음";

var ID_RES_CONST_STRING_SHARE_STATUS_CHANGED = "변경된 공유 내역이 반영되었습니다.";
var ID_RES_CONST_STRING_SHARE_STATUS_NOT_CHANGED = "변경된 공유 내역이 없습니다.";
var ID_RES_CONST_STRING_WE_NOT_SUPPORTED = "지원하지 않습니다.";
var ID_RES_CONST_STRING_IE_NOT_SUPPORT_LANDSCAPE_PRINT = "IE는 가로방향 인쇄를 지원하지 않습니다.";				//740

var ID_RES_CONST_STRING_SHARE_FAX = "팩스공유";
var ID_RES_CONST_STRING_DOC_SECURE_GRADE = "문서보안 등급삽입";
var ID_RES_CONST_STRING_ALERT_CHOICE_DOC_SECURE_GRADE = "문서보안 등급을 선택해 주세요.";
var IE_RES_CONST_STRING_THUMBNAIL_VIEW = "썸네일보기";

var ID_RES_CONST_STRING_INVITE_YOU_SHARE_DOCUMENT = "{0} 님이 다음 문서를 {1} 하도록 초대하였습니다.";
var ID_RES_CONST_STRING_DOCUMENT_OPEN = "문서 열기";
var ID_RES_CONST_STRING_DOCUMENT_SHARE = "문서 공유";
var ID_RES_CONST_STRING_SHOW = "보기";
var ID_RES_CONST_STRING_POINTER_OPTION = "포인터 옵션";

var ID_RES_CONST_STRING_NOTI_EXIST_TEMP_DOCUMENT = "제목이 지정되지 않은 문서가 존재합니다.";							//750
var ID_RES_CONST_STRING_NOTI_DENY_UNSHARE_DEPARTSHARE_DOCUMENT = "부서 공유가 된 문서는 공유 해제가 제한됩니다.";
var ID_RES_CONST_STRING_TABLE_LOCK_EDIT_CELL = "셀 편집제한";
var ID_RES_CONST_STRING_NOT_EDITABLE_AREA = "편집이 제한된 영역입니다.";

var ID_RES_CONST_STRING_SAVE_DOCUMENT_FIRST = "문서를 먼저 저장 해주세요.";

var ID_RES_CONST_STRING_PROTECT_PRIVACY = "개인정보보호";
var ID_RES_CONST_STRING_SELECT_PRIVACY = "개인 정보 선택";
var ID_RES_CONST_STRING_SELECT_PROTECT_CHAR = "보호 문자 선택";
var ID_RES_CONST_STRING_PROTECT = "보호하기";
var ID_RES_CONST_STRING_PROTECT_ALL = "모두 보호";
var ID_RES_CONST_STRING_PHONE_NUMBER = "전화번호";							//760
var ID_RES_CONST_STRING_E_MAIL = "전자 우편";
var ID_RES_CONST_STRING_RESIDENT_REGISTRATION_NUMBER = "주민등록번호";
var ID_RES_CONST_STRING_ALERT_SELECT_PRIVACY = "개인 정보를 선택해 주세요.";
var ID_RES_CONST_STRING_NOTI_MARKING_PRIVACY_COUNT = "개인 정보 보호하기를 {0}번 했습니다.";
var ID_RES_CONST_STRING_DOCUMENT_BACKUP = "문서 백업 및 복원";

var ID_RES_CONST_STRING_PRIVACY_PASSWORD = "개인 정보 암호";
var ID_RES_CONST_STRING_DISABLE_PRIVACY = "개인정보 보호해제";
var ID_RES_CONST_STRING_DISABLE_PRIVACY_FAIL = "개인 정보 보호 해제에 실패하였습니다.";
var ID_RES_CONST_STRING_DISABLE_PRIVACY_DONE = "개인 정보 보호 해제되었습니다.";
var ID_RES_CONST_STRING_WEBSEARCH_SUPPLY = "검색결과제공";					//770

var ID_RES_CONST_STRING_HEADER = "머리글";
var ID_RES_CONST_STRING_FOOTER = "바닥글";
var ID_RES_CONST_STRING_HEADER_FOOTER = "머리글/바닥글";

var ID_RES_CONST_STRING_FIRST_HEADER = "첫 페이지 머리글";
var ID_RES_CONST_STRING_FIRST_FOOTER = "첫 페이지 바닥글";
var ID_RES_CONST_STRING_EVEN_HEADER = "짝수 페이지 머리글";
var ID_RES_CONST_STRING_EVEN_FOOTER = "짝수 페이지 바닥글";
var ID_RES_CONST_STRING_ODD_HEADER = "홀수 페이지 머리글";
var ID_RES_CONST_STRING_ODD_FOOTER = "홀수 페이지 바닥글";

var ID_RES_CONST_STRING_EDIT_HEADER = "머리글 편집";             //780
var ID_RES_CONST_STRING_EDIT_FOOTER = "바닥글 편집";
var ID_RES_CONST_STRING_CLOSE_HEADER_FOOTER = "머리글/바닥글 닫기";
var ID_RES_CONST_STRING_REMOVE_HEADER = "머리글 제거";
var ID_RES_CONST_STRING_REMOVE_FOOTER = "바닥글 제거";

var ID_RES_CONST_STRING_GO_TO_HEADER = "머리글로 이동";
var ID_RES_CONST_STRING_GO_TO_FOOTER = "바닥글로 이동";

var ID_RES_CONST_STRING_HEADER_MARGIN_FROM_TOP = "머리글(위쪽)";
var ID_RES_CONST_STRING_FOOTER_MARGIN_FROM_BOTTOM = "바닥글(아래쪽)";

var ID_RES_CONST_STRING_OPTIONS = "옵션";
var ID_RES_CONST_STRING_DIFFERENT_FIRST_PAGE = "첫 페이지를 다르게 지정";                //790
var ID_RES_CONST_STRING_DIFFERENT_ODD_EVEN_PAGES = "짝수와 홀수 페이지를 다르게 지정";
var ID_RES_CONST_STRING_SHOW_DOCUMENT_TEXT = "문서 텍스트 표시";
var ID_RES_CONST_STRING_SHOW_RIBBON_TOOLBARS_ALWAYS = "리본툴바 항상 보이기";
var ID_RES_CONST_STRING_HIDE_RIBBON_TOOLBARS = "리본툴바 감추기";

var ID_RES_CONST_STRING_DELETE_IMAGE = "그림 삭제";
var ID_RES_CONST_STRING_DELETE_VIDEO = "비디오 삭제";

var ID_RES_DIALOG_STRING_ALIGN_MIDDLE = "가운데";
var ID_RES_DIALOG_STRING_ALIGN_TOP = "위";
var ID_RES_TOOL_STRING_MENU_HOME = "홈";
var ID_RES_TOOL_STRING_MENU_LAYOUT = "레이아웃";					// 800
var ID_RES_CONST_STRING_HELP_ONLINE = "온라인 매뉴얼";

var ID_RES_DIALOG_STRING_NO_SELECT = "선택 안함";
var ID_RES_DIALOG_STRING_AUTO_PLAY = "자동 재생";
var ID_RES_CONST_STRING_VIEWING = "열람";
var ID_RES_CONST_STRING_CHART_DATA_SORT = "데이터 순서";
var ID_RES_CONST_STRING_CHART_DATA_SORT_REVERSE = "역방향";

var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ALL = "전체기간";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_DAY = "1일";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_WEEK = "1주";
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_ONE_MONTH = "1개월";					// 810
var ID_RES_CONST_STRING_SEARCH_PERIOD_OPTION_SIX_MONTH = "6개월";
var ID_RES_CONST_STRING_SEARCH_SEARCH_PERIOD_OPTION_ONE_YEAR = "1년";

var ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_SUBJECT = "제목";
var ID_RES_CONST_STRING_SEARCH_TYPE_OPTION_OWNER = "소유자";
var ID_RES_CONST_STRING_BROWSER_UNIFIED_SEARCH_RESULT = "\"{0}\"에 대한 \"{1}\"건의 결과를 검색하였습니다.";
var ID_RES_CONST_STRING_ALL_SEARCH_RESULT = "전체 검색결과";
var ID_RES_CONST_STRING_SEND_BIZBOX_REPORT = "업무보고 보내기";
var ID_RES_CONST_STRING_UPDATE_BIZBOX_REPORT = "업무보고 업데이트";

var ID_RES_CONST_STRING_DOCUMENT_HISTORY = "문서 이력";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_VIEW_LARGER = "크게 보기";					// 820
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_ACTION_TYPE = "구분";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_SHARE_INFO = "공유 정보";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_DEVIDE_INFO = "기기정보";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_ACCESS = "접근";
var ID_RES_CONST_STRING_DOCUMENT_HISTORY_SHARE_ALL = "전체 공유";

var ID_RES_CONST_STRING_ADD = "추가";
var ID_RES_CONST_STRING_DELETE = "삭제";

var ID_RES_CONST_STRING_ADD_SCHEDULE = "일정추가";
var ID_RES_CONST_STRING_DELETE_SCHEDULE = "일정삭제";
var ID_RES_CONST_STRING_ADD_TASK = "업무추가";					// 830
var ID_RES_CONST_STRING_DELETE_TASK = "업무삭제";
var ID_RES_CONST_STRING_ALERT_NOT_AVAILABLE_IN_ONEPAGE_MODE = "단일페이지 모드에서는 사용할 수 없습니다.";
var ID_RES_CONST_STRING_ONEPAGE_MODE = "페이지분리";
var ID_RES_CONST_STRING_ONEPAGE_MODE_ON = "단일 페이지";
var ID_RES_CONST_STRING_ONEPAGE_MODE_OFF = "다중 페이지";
var ID_RES_CONST_STRING_PAPER_SIZE = "용지 사이즈";
var ID_RES_CONST_STRING_NOTI_HYPERLINK_GUIDE = "링크를 따라가려면 <Ctrl>키를 누른 채 클릭합니다.";

var ID_RES_CONST_STRING_SHAPES = "도형";
var ID_RES_CONST_STRING_SHAPES_FORMAT = "도형서식";
var ID_RES_CONST_STRING_SHAPES_CHANGE = "도형 모양변경";					// 840도형 모양 변경
var ID_RES_CONST_STRING_SHAPES_STYLE = "도형 스타일";
var ID_RES_CONST_STRING_SHAPES_FILL = "도형 채우기";
var ID_RES_CONST_STRING_SHAPES_BORDER = "도형 윤곽선";
var ID_RES_CONST_STRING_SHAPES_TEXT_ALIGN = "텍스트 맞춤";
var ID_RES_CONST_STRING_SHAPES_LAYOUT = "텍스트 줄 바꿈";
var ID_RES_CONST_STRING_SHAPES_MOVE_FRONT = "앞으로 가져오기";
var ID_RES_CONST_STRING_SHAPES_MOVE_FRONT_EDGE = "맨 앞으로 가져오기";
var ID_RES_CONST_STRING_SHAPES_MOVE_BACK = "뒤로 보내기";
var ID_RES_CONST_STRING_SHAPES_MOVE_BACK_EDGE = "맨 뒤로 보내기";
var ID_RES_CONST_STRING_SHAPES_ALIGN = "맞춤";					// 850
var ID_RES_CONST_STRING_SHAPES_ROTATE = "회전";
var ID_RES_CONST_STRING_SHAPES_TRANSPARENT = "투명도";
var ID_RES_CONST_STRING_SHAPES_FILL_NONE = "채우기 없음";
var ID_RES_CONST_STRING_SHAPES_FILL_SOLID = "단색 채우기";
var ID_RES_CONST_STRING_SHAPES_STYLE_TEMPLATE = "기본 스타일";
var ID_RES_CONST_STRING_SHAPES_TEXT_ALIGN_MIDDLE = "중간";

var ID_RES_CONST_STRING_SHAPES_SQUARE_RIGHT_ANGLE = "직사각형";
var ID_RES_CONST_STRING_SHAPES_SQUARE_ROUNDED = "모서리가 둥근 직사각형";
var ID_RES_CONST_STRING_SHAPES_SQUARE_TRAPEZOID = "사다리꼴";					// 860
var ID_RES_CONST_STRING_SHAPES_SQUARE_PARALLELOGRAM = "평행사변형";
var ID_RES_CONST_STRING_SHAPES_SQUARE_DIAMOND = "마름모";

var ID_RES_CONST_STRING_SHAPES_TRIANGLE_ISOSCELES_TOP = "위쪽 이등변 삼각형";
var ID_RES_CONST_STRING_SHAPES_TRIANGLE_ISOSCELES_RIGHT = "오른쪽 이등변 삼각형";
var ID_RES_CONST_STRING_SHAPES_TRIANGLE_RIGHT_ANGLE = "직각 삼각형";

var ID_RES_CONST_STRING_SHAPES_CIRCLE = "원";
var ID_RES_CONST_STRING_SHAPES_ELLIPSE = "타원";	

var ID_RES_CONST_STRING_SHAPES_ARROW_RIGHT = "오른쪽 화살표";
var ID_RES_CONST_STRING_SHAPES_ARROW_TOP = "위쪽 화살표";
var ID_RES_CONST_STRING_SHAPES_ARROW_LEFT_RIGHT = "좌우 화살표";					// 870
var ID_RES_CONST_STRING_SHAPES_ARROW_TOP_BOTTOM = "상하 화살표";

var ID_RES_CONST_STRING_SHAPES_LINE_NORMAL = "선";
var ID_RES_CONST_STRING_SHAPES_LINE_ARROW_UNI_DIRECTION = "단방향 화살표";
var ID_RES_CONST_STRING_SHAPES_LINE_ARROW_BI_DIRECTION = "양방향 화살표";

var ID_RES_CONST_STRING_LIST_NO_START = "다음 번호로 시작";

var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_TOP = "위쪽";
var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_MIDDLE = "가운데";
var ID_RES_CONST_STRING_OBJ_TXT_VALIGN_BOTTOM = "아래쪽";
var ID_RES_CONST_STRING_OBJ_ALIGN_TOP = "위쪽 맞춤";
var ID_RES_CONST_STRING_OBJ_ALIGN_MIDDLE = "중간 맞춤";					// 880
var ID_RES_CONST_STRING_OBJ_ALIGN_BOTTOM = "아래쪽 맞춤";

var ID_RES_CONST_STRING_OBJ_ROTATE_RIGHT_90 = "오른쪽으로 90도 회전";
var ID_RES_CONST_STRING_OBJ_ROTATE_LEFT_90 = "왼쪽으로 90도 회전";
var ID_RES_CONST_STRING_OBJ_ROTATE_FLIP_VERTICAL = "상하 대칭";
var ID_RES_CONST_STRING_OBJ_ROTATE_FLIP_HORIZONTAL = "좌우 대칭";
var ID_RES_CONST_STRING_OBJ_ROTATE_OTHERS = "기타 회전 옵션";

var ID_RES_CONST_STRING_TXTLAYOUT_IN_LINE_WIDTH_TEXT = "텍스트 줄 안";
var ID_RES_CONST_STRING_TXTLAYOUT_SQUARE = "정사각형";
var ID_RES_CONST_STRING_TXTLAYOUT_TIGHT = "빽빽하게";
var ID_RES_CONST_STRING_TXTLAYOUT_THROUGH = "투과하여";					// 890
var ID_RES_CONST_STRING_TXTLAYOUT_TOPANDBOTTOM = "위/아래";
var ID_RES_CONST_STRING_TXTLAYOUT_BEHIND_TEXT = "텍스트 뒤";
var ID_RES_CONST_STRING_TXTLAYOUT_IN_FRONT_OF_TEXT = "텍스트 앞";
var ID_RES_CONST_STRING_TXTLAYOUT_LEFT_TEXT = "텍스트 왼쪽";
var ID_RES_CONST_STRING_TXTLAYOUT_RIGHT_TEXT = "텍스트 오른쪽";
var ID_RES_CONST_STRING_TXTLAYOUT_OTHERS = "기타 레이아웃 옵션";
var ID_RES_CONST_STRING_LINE_NOCOLOR = "윤곽선 없음";
var ID_RES_CONST_STRING_LINE_OTHER_COLOR = "다른 윤곽선 색";

var ID_RES_CONST_STRING_COUNT = "건";
var ID_RES_CONST_STRING_ARROW = "화살표";                                   //900
var ID_RES_CONST_STRING_ARROW_NONE = "화살표 없음";
var ID_RES_CONST_STRING_ARROW1 = "화살표1";
var ID_RES_CONST_STRING_ARROW2 = "화살표2";
var ID_RES_CONST_STRING_ARROW3 = "화살표3";
var ID_RES_CONST_STRING_ARROW4 = "화살표4";
var ID_RES_CONST_STRING_ARROW5 = "화살표5";
var ID_RES_CONST_STRING_ARROW6 = "화살표6";
var ID_RES_CONST_STRING_ARROW7 = "화살표7";
var ID_RES_CONST_STRING_ARROW8 = "화살표8";
var ID_RES_CONST_STRING_ARROW9 = "화살표9";								//910
var ID_RES_CONST_STRING_ARROW10 = "화살표10";								

var ID_RES_CONST_STRING_GET_BIZBOX_REPORT_LIST = "업무보고 가져오기";

var ID_RES_CONST_STRING_SHAPES_PLACING = "텍스트 배치";
var ID_RES_CONST_STRING_SHAPES_DISTANCE_WITH_TEXT = "텍스트와의 간격";
var ID_RES_CONST_STRING_SHAPES_RATIO = "배율";
var ID_RES_CONST_STRING_SHAPES_FIXED_RATIO = "가로 세로 비율 고정";
var ID_RES_CONST_STRING_SHAPES_ADD_TEXT = "텍스트 추가";

var ID_RES_CONST_STRING_OPEN_LINK = "오픈 링크";
var ID_RES_CONST_STRING_SHARED_USER = "공유 중인 사용자";
var ID_RES_CONST_STRING_PEOPLE_COUNT = "명";								//920
var ID_RES_CONST_STRING_USER_SHARING = "사용자 공유";
var ID_RES_CONST_STRING_STATUS_ON = "켜짐";
var ID_RES_CONST_STRING_STATUS_OFF = "꺼짐";
var ID_RES_CONST_STRING_LINK_OFF = "링크 끄기";
var ID_RES_CONST_STRING_SHARE_NOTI_TYPE = "보내기 방식";
var ID_RES_CONST_STRING_MAIL = "메일 전송";
var ID_RES_CONST_STRING_NOTE = "쪽지 전송";
var ID_RES_CONST_STRING_ONEFFICE = "원피스";
var ID_RES_CONST_STRING_SHARE_COUNT_STATUS = "공유 중 ({0})";

var ID_RES_CONST_STRING_FIXED_RATIO = "비율 고정";						//930
var ID_RES_CONST_STRING_CHANGE_PROTECT_PASSWORD = "보호 암호변경";
var ID_RES_CONST_STRING_FOREIGNER_NUMBER = "외국인등록번호";
var ID_RES_CONST_STRING_CREDITCARD_NUMBER = "신용카드 번호";
var ID_RES_CONST_STRING_IP_ADDRESS = "접근 IP";
var ID_RES_CONST_STRING_BIRTHDAY = "생년월일";
var ID_RES_CONST_STRING_USER_DEFINE_SETTING = "사용자 정의 설정";
var ID_RES_CONST_STRING_DISPLAY_FORM_SETTING = "표시 형식 설정";

var ID_RES_CONST_STRING_CHART_DATA_CONVERT = "데이터 변환";
var ID_RES_CONST_STRING_CHART_DATA_XY_CONVERT = "행/열 변환";
var ID_RES_CONST_STRING_CHART_DATA_ORDER_CONVERT = "순서 변환";			//940
var ID_RES_CONST_STRING_CHART_TYPE_BAR = "세로막대";
var ID_RES_CONST_STRING_CHART_TYPE_HBAR = "가로막대";
var ID_RES_CONST_STRING_CHART_TYPE_LINE = "꺽은선";
var ID_RES_CONST_STRING_CHART_TYPE_LINE_CUBIC = "곡선";
var ID_RES_CONST_STRING_CHART_TYPE_PIE = "원";
var ID_RES_CONST_STRING_CHART_TYPE_DOUGHNUT = "도넛";
var ID_RES_CONST_STRING_CHART_TYPE_RADAR = "방사";
var ID_RES_CONST_STRING_CHART_TYPE_POLARAREA = "부채";
var ID_RES_CONST_STRING_CHART_TITLE = "차트 제목";
var ID_RES_CONST_STRING_CHART_DATA_TITLE = "차트 데이터";
var ID_RES_CONST_STRING_MODIFY_CHART_DATA = "차트 데이터 편집";
var ID_RES_CONST_STRING_MODIFY_CHART_TYPE = "차트 종류 변경";
var ID_RES_CONST_STRING_CHART_LEGEND_VIEW = "범례 표기";					//950
var ID_RES_CONST_STRING_CHART_DATA_VIEW = "데이터 표기";
var ID_RES_CONST_STRING_CHART_DATA_VIEW_OK = "표기함";
var ID_RES_CONST_STRING_CHART_DATA_LABEL = "데이터 레이블";
var ID_RES_CONST_STRING_CHART_TITLE_PADDING = "차트와의 간격";

var ID_RES_CONST_STRING_PAGE_CONTENTS = "페이지 내용";
var ID_RES_CONST_STRING_PAGE_CONTENTS_OVERFLOW_ON = "자동 맞춤 안함";
var ID_RES_CONST_STRING_PAGE_CONTENTS_OVERFLOW_OFF = "자동 맞춤";

var ID_RES_CONST_BTN_MERGE_DOCUMENT = "문서 취합";

var ID_RES_CONST_STRING_TABLE_COLLAPSE = "셀과 셀 사이 선을 1개로 표현";

var ID_RES_CONST_STRING_INSERT_NEW_PAGE = "새 페이지";
var ID_RES_CONST_STRING_PAGE_MANAGEMENT = "페이지 관리";
var ID_RES_CONST_STRING_INSERT_EMPTY_PAGE = "빈 페이지 삽입";					// 960
var ID_RES_CONST_STRING_COPY_PAGE = "페이지 복사";
var ID_RES_CONST_STRING_PASTE_PAGE = "페이지 붙여넣기";
var ID_RES_CONST_STRING_DELETE_PAGE = "페이지 삭제";
var ID_RES_CONST_STRING_ABOVE_PAGE = "페이지 위";
var ID_RES_CONST_STRING_BELOW_PAGE = "페이지 아래";
var ID_RES_CONST_STRING_INSERT_TABLE_WITH_CHART = "차트삽입시 데이터 테이블도 합께 삽입";

var ID_RES_CONST_STRING_KEEP_TEXT_ONLY = "텍스트만 유지";
var ID_RES_CONST_STRING_INSERT_AS_NESTED_TABLE = "표 중첩";

var ID_RES_CONST_STRING_RECEIVED_REPORT = "받은보고서";
var ID_RES_CONST_STRING_SENT_REPORT = "보낸보고서";      					// 970
var ID_RES_CONST_STRING_REFERENCE_REPORT = "참조보고서";
var ID_RES_CONST_STRING_PUBLIC_REPORT = "공개보고서";

var ID_RES_CONST_STRING_BROWSER_SECURITY = "보안문서함";

var ID_RES_CONST_STRING_SHARED_DATE = "공유날짜";

var ID_RES_CONST_STRING_EXTEND_FUNC = "확장기능";
var ID_RES_SEND_MAIL_FAIL = "메일 전송에 실패 하였습니다";
var ID_RES_CONST_STRING_ALREADY_IN_USER = "이미 포함된 사용자입니다.";
var ID_RES_CONST_STRING_IMPORTANT = "중요";
var ID_RES_CONST_STRING_FILE_TYPE = "문서종류";

var ID_RES_CONST_STRING_CREATE_FOLDER = "새폴더";							// 980
var ID_RES_CONST_STRING_CREATE_FILE = "새문서";
var ID_RES_CONST_STRING_CHANGES_NOT_SAVED = "변경사항이 저장되지 않을 수 있습니다.";

var ID_RES_CONST_STRING_DIRECT_GO = "바로가기";
var ID_RES_CONST_STRING_LOGIN_GUIDE_TITLE = "로그인 안내";
var ID_RES_CONST_STRING_LOGIN_GUIDE_CONTENT = "세션이 만료되어 재로그인이 필요합니다.<br />새로운 페이지에서 로그인 하신 후 다시 시도하시기 바랍니다.<br />로그인 페이지를 새로운 페이지로 열겠습니까?";
var ID_RES_CONST_STRING_SERVER_ERROR_TITLE = "네트워크 오류 안내";
var ID_RES_CONST_STRING_SERVER_ERROR_CONTENT = "네트워크 오류가 발생하였습니다.<br />잠시후 다시 시도해 주세요.";
var ID_RES_CONST_STRING_INSERT_QRCODE = "QR코드";

var ID_RES_CONST_PANEL_TITLE_DOC_INFO= "문서 상세정보";
var ID_RES_CONST_PANEL_TITLE_DOC_ACCESS = "문서접근관리";							// 990
var ID_RES_CONST_PANEL_TITLE_DOC_COMMENT = "문서 댓글";
var ID_RES_CONST_PANEL_TITLE_DOC_CHART = "차트 서식";
var ID_RES_CONST_TOAST_EDIT_AUTH_REQUEST_CANCEL = "편집 권한 요청이 취소되었습니다.";
var ID_RES_CONST_TOAST_EDIT_AUTH_PASS_SUCCESS = "편집 권한을 이관하였습니다.";
var ID_RES_CONST_TOAST_REJECT_EDIT_REQUEST = "편집 권한 요청이 거절되었습니다.";
var ID_RES_CONST_TOAST_OTHER_USED_REQUEST = "다른 사용자가 편집 권한을 요청 중입니다.";
var ID_RES_CONST_TOAST_ACCESS_MANAGER_TITLE = "권한 요청";
var ID_RES_CONST_STRING_DELETE_DIV = "점선 테두리 지우기";

var ID_RES_CONST_STRING_QRCODE_FITST_INFO = "첫 페이지 우측 상단";
var ID_RES_CONST_STRING_QRCODE_LAST_INFO = "문서 본문 하단";

var ID_RES_CONST_STRING_SORT_TITE = "문서 제목";							// 1000
var ID_RES_CONST_STRING_SORT_RECENTDATE = "최근 수정 날짜";
var ID_RES_CONST_STRING_SORT_READDATE = "최근 조회 날짜";
var ID_RES_CONST_STRING_SORT_SHEREBYDATE = "공유 받은 날짜";
var ID_RES_CONST_STRING_SORT_FILESIZE = "파일 크기";
var ID_RES_CONST_STRING_SORT_SHEREDATE = "공유 날짜";
var ID_RES_CONST_STRING_SORT_OWNER = "소유자";

var ID_RES_CONST_STRING_FILTER_ALL = "모든 문서";
var ID_RES_CONST_STRING_FILTER_MY = "내 문서";
var ID_RES_CONST_STRING_FILTER_BY = "공유 받은 문서";

var ID_RES_CONST_STRING_CREATE_DATE = "생성 날짜";
var ID_RES_CONST_STRING_MODIFY_DATE = "수정 날짜";
var ID_RES_CONST_STRING_NO_PERMMISION = "열람 권한이 없습니다.";
var ID_RES_CONST_STRING_NO_PERMMISION_INFO = "소유자에게 권한을 요청하세요.";
var ID_RES_CONST_STRING_REQUEST_PERMMISION = "권한 요청";
var ID_RES_CONST_STRING_REQUEST_CONFIRM = "권한을 요청하였습니다.";
var ID_RES_CONST_STRING_REQUEST_ALLOW = "권한이 허용되었습니다.";
var ID_RES_CONST_STRING_REQUEST_NOT_ALLOW = "권한을 허용하지 않았습니다.";      // 1010
var ID_RES_CONST_STRING_SOMEONE_PERM = "{0}님이 문서를 {1}할 수 있도록";
var ID_RES_CONST_STRING_ALLOW_PERMISSION = "권한을 허용하시겠습니까?";
var ID_RES_CONST_STRING_ALLOW = "허용";
var ID_RES_CONST_STRING_DENY = "거부";
var ID_RES_CONST_STRING_ALREADY_ALLOW_DOCUMENT = "권한이 허용된 문서입니다.";

var ID_RES_CONST_PANEL_FILE_SELECT_NONE = "파일 또는 문서를 선택하세요.";
var ID_RES_CONST_PANEL_MENU_DETAIL_INFO = "자세히 보기";
var ID_RES_CONST_PANEL_EDITING_USER = "편집 중인 사용자";
var ID_RES_CONST_PANEL_VIEWING_USER = "열람 중인 사용자";
var ID_RES_CONST_PANEL_REQUEST_WRITE_AUTH = "권한요청";     // 1020
var ID_RES_CONST_PANEL_PASS_WRITE_AUTH = "권한이관";
var ID_RES_CONST_PANEL_CANCEL_REQUEST_WRITE_AUTH = "요청취소";
var ID_RES_CONST_PANEL_CREATE_NEW_DOC = "새 문서 생성";
var ID_RES_CONST_STRING_YEAR = "년";
var ID_RES_CONST_STRING_MONTH = "월";
var ID_RES_CONST_STRING_DAY = "일";
var ID_RES_CONST_STRING_AM = "오전";
var ID_RES_CONST_STRING_PM = "오후";
var ID_RES_CONST_PANEL_MSG_REQUEST_WRITE_AUTH_FROM = "다음 사용자가 편집 권한을 요청하였습니다.";
var ID_RES_CONST_PANEL_MSG_CONFIRM_WRITE_AUTH = "편집 권한을 {0}하시겠습니까?";    // 1030
var ID_RES_CONST_PANEL_MSG_REJECT_WRITE_AUTH = "편집 권한 요청이 {0}되었습니다.";
var ID_RES_CONST_PANEL_MSG_DUPLICATED_REQUEST = "다른 사용자가 편집 권한을 {0}입니다.";
var ID_RES_CONST_PANEL_REQUEST = "요청";
var ID_RES_CONST_PANEL_PASS_TO = "이관";
var ID_RES_CONST_PANEL_REJECT = "거절";
var ID_RES_CONST_PANEL_REQUESTING = "요청 중";
var ID_RES_CONST_PANEL_REQUEST_WRITE_SUCCESS = "편집 권한을 이관 받았습니다.";
var ID_RES_CONST_PANEL_AM_EDITOR_OUT = "편집자가 문서를 닫고 나갔습니다.";

var ID_RES_CONST_STRING_WRAP_TEXT = "텍스트 줄 바꿈";

var ID_RES_CONST_STRING_DEFAULT_FILE_NAME = "제목없는 문서";      // 1040
var ID_RES_CONST_STRING_DEFAULT_FOLDER_NAME = "제목없는 폴더";

var ID_RES_CONST_STRING_PAGE_MOVE = "페이지 이동";
var ID_RES_CONST_STRING_SLIDE_SHOW_CONFIRM = "브라우저 정책으로 인해 확인시<br />전체 슬라이드쇼 모드로 진입합니다.";
var ID_RES_CONST_STRING_NEXT_SLIDE = "다음 슬라이드";
var ID_RES_CONST_STRING_PREV_SLIDE = "이전 슬라이드";
var ID_RES_CONST_STRING_MOVE_SLIDE = "슬라이드 이동";
var ID_RES_CONST_STRING_ZOOM_INOUT = "확대/축소";

var ID_RES_CONST_SLIDESHOW_ZOOM_HEIGHT  = "페이지 높이맞춤";
var ID_RES_CONST_SLIDESHOW_ZOOM_WIDTH   = "페이지 너비맞춤";
var ID_RES_CONST_SLIDESHOW_ZOOM_125     = "125%";       // 1050
var ID_RES_CONST_SLIDESHOW_ZOOM_150     = "150%";
var ID_RES_CONST_SLIDESHOW_ZOOM_175     = "175%";

var ID_RES_CONST_STRING_CURRENT_SLIDE_SHOW = "현재부터 쇼 재생";
var ID_RES_CONST_STRING_TOOLBAR_100 = "100% 맞춤";

var ID_RES_CONST_STRING_PGNUM = "페이지 번호";
var ID_RES_CONST_STRING_PGNUM_FORMAT = "페이지번호 서식";
var ID_RES_CONST_STRING_PGNUM_REMOVE = "페이지번호 제거";

var ID_RES_CONST_STRING_FORMAT_STYLE = "서식 스타일";
var ID_RES_CONST_STRING_NUM_FORMAT = "번호 모양";
var ID_RES_CONST_STRING_NUM_POS = "번호 위치";      // 1060

var ID_RES_CONST_STRING_TEXT_STYLE = "텍스트 스타일";

var ID_RES_CONST_STRING_PGNUMERING = "페이지 번호 매기기";
var ID_RES_CONST_STRING_PGNUM_START = "시작 페이지 지정";

var ID_RES_CONST_STRING_PGNUM_NO = "번호 없음";

var ID_RED_CONST_STRING_TOP_LEFT = "왼쪽 위";
var ID_RED_CONST_STRING_TOP_CENTER	= "가운데 위";
var ID_RED_CONST_STRING_TOP_RIGHT	= "오른쪽 위";
var ID_RED_CONST_STRING_BOTTOM_LEFT = "왼쪽 아래";
var ID_RED_CONST_STRING_BOTTOM_CENTER = "가운데 아래";
var ID_RED_CONST_STRING_BOTTOM_RIGHT = "오른쪽 아래";        // 1070

var ID_RES_CONST_STRING_FONT_STYLE = "글꼴 스타일";
var ID_RES_CONST_STRING_DOCUMENT_CONTINUE_WRITE = "문서를 이어서 작성합니다.";
var ID_RES_CONST_STRING_DOCUMENT_RELOAD = "문서를 다시 불러옵니다.";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_LOADED = "{0}에 임시저장된 문서를 열람하는 중입니다.";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_OPEN = "{0}에 임시저장된 문서가 있어 [읽기 전용]으로 열람됩니다. 임시저장된 문서를 확인하시겠습니까?";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_DELETE = "임시저장된 문서를 삭제하시겠습니까?<br />삭제된 문서는 복구되지 않습니다.";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_ALL_DOCUMENT_DELETE = "임시저장된 문서를 전체 삭제하시겠습니까?<br />삭제된 문서는 복구되지 않습니다.";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_DELETED_COMPLETE = "삭제가 완료되었습니다.";
var ID_RES_CONST_STRING_TEMP_SAVED_ALL_DOCUMENT_DELETED_COMPLETE = "전체 문서가 삭제되었습니다.";

var ID_RES_CONST_STRING_TEMP_SAVED_DOC_BOX = "임시저장 문서함";        // 1080
var ID_RES_CONST_STRING_TEMP_SAVE = "임시저장";
var ID_RES_CONST_STRING_OVERWRITE_ORG_DOC = "원본 덮어쓰기";
var ID_RES_CONST_STRING_DELETE_DOC = "문서삭제";
var ID_RES_CONST_STRING_ORG_DOCUMENT_INFO = "원본 문서 정보";
var ID_RES_CONST_STRING_DOCUMENT_LAST_UPDATE = "마지막 저장일자";
var ID_RES_CONST_STRING_DOCUMENT_WRITER = "작성자";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_OVERWRITE = "원본 문서에 임시저장 문서를 덮어쓰시겠습니까? <br />덮어쓰기된 원본 내용은 복구되지 않습니다.";
var ID_RES_CONST_STRING_OVERWRITE_ORG_DOC_COMPLETE = "덮어쓰기가 완료되었습니다.";
var ID_RES_CONST_STRING_ALERT_OVERWRITE_FAIL_READONLY_ATTR_DOCUMENT = "원본문서가 읽기전용으로 설정되어 있어 덮어쓰기할 수 없습니다.";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENT_NUM_STRING = "총 {0}개의 임시저장 문서";     // 1090
var ID_RES_CONST_STRING_DELETE_ALL_DOC = "전체삭제";
var ID_RES_CONST_STRING_TEMP_SAVED_DOCUMENTS = "임시 저장된 문서";
var ID_RES_CONST_STRING_CONFIRM_TEMP_SAVED_DOCUMENT_LIST_OPEN = "임시 저장된 문서가 있습니다.<br />확인하시겠습니까?";
var ID_RES_CONST_STRING_CLOSE_WINDOW = "창을 닫으시겠습니까?"

var ID_RES_STRING_CONTROL_HEIGHT = "높이 조절";
var ID_RES_STRING_CONTROL_WIDTH = "너비 조절";

var ID_RES_STRING_PAGE_BREAK_GUIDE = "――― 페이지 나누기 ―――";
var ID_RES_STRING_PASTE_CELL_INSERT_AS_TABLE = "표 중첩";

var ID_RES_CONST_STRING_REGIST_SCHEDULE = "일정등록";

var ID_RES_STRING_CHG_OWN = "문서 소유권 이전";
var ID_RES_STRING_CHG_OWN_ING = "소유권 이전 중";       //1100
var ID_RES_STRING_CHG_OWN_CANCEL = "소유권 이전 취소";
var ID_RES_STRING_CHG_OWN_TARGET = "이전 대상자";

var ID_RES_STRING_CHG_OWN_PLACEHOLDER = "이관 대상은 1인 선택 가능";
var ID_RES_STRING_CHG_OWN_SEL_ERR0 = "이관 대상을 선택해 주세요.";
var ID_RES_STRING_CHG_OWN_SEL_ERR1 = "이관 대상을 1명만 선택해 주세요.";
var ID_RES_STRING_CHG_OWN_SEL_ERR2 = "나에게 소유권을 이전할 수 없습니다.";
var ID_RES_STRING_CHG_OWN_SEL_ERR3 = "부서에게 소유권을 이전할 수 없습니다.";

var ID_RES_STRING_CHG_OWN_POP_REQ = "해당 사용자에게 문서 소유권 이전을 요청 하시겠습니까?\n(이전 대상자의 승인 후 최종 이전됩니다.)";
var ID_RES_STRING_CHG_OWN_POP_CANCEL = "해당 문서의 소유권 이전 요청을\n취소하시겠습니까?";
var ID_RES_STRING_CHG_OWN_POP_ACCEPT = "{0}님이 요청한 문서 소유권 이전을\n승인하시겠습니까?";  //1110

var ID_RES_STRING_CHG_OWN_TOAST = "소유권 이전이 요청 되었습니다.";
var ID_RES_STRING_CHG_OWN_TOAST1 = "소유권 이전이 완료되었습니다.";
var ID_RES_STRING_CHG_OWN_TOAST2 = "소유권 이전 요청을 거절하였습니다.";
var ID_RES_STRING_CHG_OWN_TOAST3 = "소유권 이전 요청이 취소되었습니다.";
var ID_RES_STRING_CHG_OWN_TOAST4 = "요청하신 {0}이 {1}되었습니다."; //bottom left toast msg
var ID_RES_STRING_CHG_OWN_TOAST5 = "{0}님이 문서 소유권 이전을 요청하였습니다. {1}";    //bottom left toast msg
var ID_RES_STRING_CHG_OWN_TOAST6 = "이관된 문서가 없습니다.";

var ID_RES_STRING_CHG_OWN_SEL_FOLDER = "소유권 이전 문서 저장";

var ID_RES_CONST_STRING_ACCEPT = "승인";
var ID_RES_CONST_STRING_REJECT = "거절";       //1120
var ID_RES_CONST_STRING_END = "완료";

var ID_RES_STRING_CHG_OWN_NOTE_MSG = "[문서 소유권 이전 요청 알림]\r\n\r\n{0} 님이 문서 소유권 이전을 요청 하였습니다.\r\n\r\n[요청 승인 바로가기]\r\n{1}";

var ID_RES_STRING_EDIT_WATERMARK = "워터마크";

var ID_RES_STRING_SEND_EXTERNAL = "외부 보내기";
var ID_RES_STRING_SEND_EXTERNAL_NOTI = "확인 시 ONEFFICE 문서는 PDF 변환 후 메일쓰기에 자동 첨부";

var ID_RES_STRING_TRANSFER_MOBILE_EDITOR_FAIL = "{0}님은 모바일로 편집중입니다. <br>모바일은 권한 요청 기능을 지원 하지 않습니다.";

var ID_RES_CONST_DOC_COMMENT_NOTI = "원피스 문서에 댓글이 등록되었습니다.";

var ID_RES_STRING_TOTAL_SEARCH = "ONEFFICE 통합검색";

var ID_RES_STRING_NEW_TEMPLATE = "새문서";
var ID_RES_STRING_TITLE_TEMPLATE = "새문서 템플릿";

var ID_RES_STRING_RECENT_TEMPATE = "최근 사용한 템플릿";
var ID_RES_STRING_MY_FAVOR_TITLE_TEMPLATE = "나의 템플릿";
var ID_RES_STRING_BUSS_REOPORT_TITLE_TEMPLATE = "업무보고";
var ID_RES_STRING_REOPORT_TITLE_TEMPLATE = "보고서";
var ID_RES_STRING_MEETING_TITLE_TEMPLATE = "회의록";

var ID_RES_CONST_STRING_DEST_SHARE_USER = "공유 대상을 입력해 주세요.";

var ID_RES_STRING_CHART_COLUMN = "계열";
var ID_RES_STRING_CHART_ITEM = "항목";

var ID_RES_STRING_CHART_LABEL = "표기함";

var ID_RES_STRING_DAY_REPORT_TEMPLATE = "일일 보고서";
var ID_RES_STRING_DAY_REPORT_CORONA = "재택근무 일일 보고서";
var ID_RES_STRING_TIME_REPORT_TEMPLATE = "수시 보고서";
var ID_RES_STRING_MEETING_REPORT_TEMPLATE = "회의록";
var ID_RES_STRING_MEETING_REPORT_2_TEMPLATE = "회의록 2";
var ID_RES_STRING_MEETING_REPORT_3_TEMPLATE = "회의록 3";
var ID_RES_STRING_MEETING_REPORT_4_TEMPLATE = "회의록 4";
var ID_RES_STRING_MEETING_REPORT_5_TEMPLATE = "회의록 5";

var ID_RES_STRING_DEV_REPORT_TEMPLATE = "개발 보고서";
var ID_RES_STRING_BUS_REPORT_TEMPLATE = "사업 계획 보고서";
var ID_RES_STRING_WEEK_REPORT_TEMPLATE  = "주간 보고서";
var ID_RES_STRING_BASIC_REPORT_TEMPLATE = "기본 보고서";
var ID_RES_STRING_ANALYZE_TEMPLATE  = "분석 보고서";

var ID_RES_STRING_GENERAL_FORM_TEMPLATE = "일반 보고서";
var ID_RES_STRING_GENERAL_FORM_2_TEMPLATE = "일반 보고서 2";
var ID_RES_STRING_GENERAL_FORM_3_TEMPLATE = "일반 보고서 3";
var ID_RES_STRING_PROJECT_FORM_1_TEMPLATE = "프로젝트 보고서 1";
var ID_RES_STRING_PROJECT_FORM_2_TEMPLATE = "프로젝트 보고서 2";

var ID_RES_STRING_PRODUCT_REPORT_TEMPLATE = "제품 보고서";

var ID_RES_STRING_SERVICE_FORM_TEMPLATE = "서비스 도입 보고서";
var ID_RES_STRING_ADJUST_METHOD_TEMPLATE = "조정 방안 검토 보고서";
var ID_RES_STRING_EVENT_PLAN_TEMPLATE = "행사 추진 계획서";

var ID_RES_STRING_IMPROVE_FORM_TEMPLATE = "개선 보고서";
var ID_RES_STRING_ISSUE_FORM_TEMPLATE = "이슈 보고서";
var ID_RES_STRING_CURRENT_FORM_TEMPLATE = "현황 보고서";

var ID_RES_STRING_TAX_NOTICE_TEMPLATE = "세무알람";
var ID_RES_STRING_TAX_NET_TEMPLATE = "텍스넷";

var ID_RES_STRING_TAX_LIST_TEMPLATE = "사업분석보고서";
var ID_RES_STRING_TAX_SAVING_TEMPLATE = "세금절약가이드";

var ID_RES_STRING_FORM_GROUP_BUSS = "업무 보고";
var ID_RES_STRING_FORM_GROUP_MEETING = "회의록";
var ID_RES_STRING_FORM_GROUP_REPORT = "보고서";
var ID_RES_STRING_FORM_GROUP_NORMAL = "일반 양식";
var ID_RES_STRING_FORM_GROUP_TAX = "세무 양식";
var ID_RES_STRING_FORM_GROUP_ARTICLE = "기사 양식";

var ID_RES_STRING_VIDEO_LEARN_ONEFFICE = "동영상으로 배우는\nONEFFICE";
var ID_RES_STRING_BUSS_ONEFFICE_WRITE = "원피스로 쓰는\n업무보고는 다르다!";

var ID_RES_STRING_INSERT_PAGE_BREAK = "페이지 나누기";

var ID_RES_STRING_TOP_BOTTOM_POSITION = "상하";
var ID_RES_STRING_LEFT_RIGHT_POSITION = "좌우";

var ID_RES_STRING_SELECTED_REPORT = "선택한 보고서";
var ID_RES_STRING_SELECTED_DOC = "선택한 문서";

var ID_RES_STRING_MERGE_SAME_ITEM = "같은항목끼리 취합";
var ID_RES_STRING_MERGE_IN_ORDER = "순서대로 붙이기";

var ID_RES_STRING_MERGE_REPORT_WARNING = "※ ONEFFICE로 작성된 보고서만 조회됩니다.<br />&nbsp;&nbsp;&nbsp;원하는 항목을 <span style='color:#ED7D31'><u>한번 클릭하여</u></span> 선택해 주세요.";
var ID_RES_STRING_REPORT_SEARCH_DATE = "날짜";
var ID_RES_STRING_REPORT_SEARCH_TITLE = "제목";

var ID_RES_STRING_TODAY = "오늘";
var ID_RES_STRING_LAST_WEEK = "최근 1주일";

var ID_RES_STRING_MY_TEMPLATE_1 = "나의 템플릿 1";
var ID_RES_STRING_MY_TEMPLATE_2 = "나의 템플릿 2";
var ID_RES_STRING_MY_TEMPLATE_3 = "나의 템플릿 3";
var ID_RES_STRING_MY_TEMPLATE_4 = "나의 템플릿 4";
var ID_RES_STRING_MY_TEMPLATE_5 = "나의 템플릿 5";

//파일 이동이나 복사 시 텍스트 추가.
var ID_RES_STRING_COPY_SUBJECT_TEXT = '(복사본)';

var ID_RES_STRING_HIDDEN_LINE = "선 숨김";

var ID_RES_STRING_LAYOUT_TABLE = "레이아웃 양식 생성";

var ID_RES_STRING_SUBTITLE = "부제목";
var ID_RES_STRING_BODY = "본문";
var ID_RES_STRING_VIDEO = "비디오";
var ID_RES_STRING_DATE = "날짜";

var ID_RES_STRING_ENTER_TITLE = "제목을 입력하세요.";
var ID_RES_STRING_ENTER_SUBTITLE = "부제목을 입력하세요.";
var ID_RES_STRING_ENTER_CONTENT = "내용을 입력하세요.";

var ID_RES_STRING_INSERT_IMG_AFTER_CLICK = "더블 클릭하여 이미지 삽입";
var ID_RES_STRING_INSERT_VIDEO_AFTER_CLICK = "더블 클릭하여 비디오 삽입";

var ID_RES_STRING_LIMT_CHAR_COUNT = "글자 수 제한";

var ID_RES_STRING_EDIT_TIMER_ALERT = "장기간 활동이 없어 읽기 모드로 전환됩니다.<br/>편집을 계속하려면 확인 버튼을 눌러주세요.";
var ID_RES_STRING_EDIT_TIMER_ALERT_READ = "장기간 활동이 없어 읽기 모드로 전환되었습니다.<br/>다시 편집을 하시려면 새로고침 하세요.";
var ID_RES_STRING_EDIT_TIMER_ALERT_READ2 = "장기간 활동이 없어 읽기 모드로 전환되었습니다.";
var ID_RES_STRING_EDIT_USER_CHECK = "편집 중인 사용자가 없습니다.<br/>확인을 누르면 편집모드로 전환됩니다.";

var ID_RES_CONST_STRING_SECURITY = "보안";

var ID_RES_CONST_STRING_SET_PASSWORD = "암호 설정";

var ID_RES_CONST_STRING_NOTI_DELETED_FOLDER = "{0}개의 폴더를 삭제하였습니다.";
var ID_RES_CONST_STRING_NOTI_DELETED_FOLDER_FILE = "{0}개의 폴더와 문서를 삭제하였습니다.";

var ID_RES_CONST_STRING_INVALID_IMG_URL = "은 유효하지 않은 이미지 URL 입니다.\n* 사용가능파일:";

var ID_RES_STRING_DOCUMENT_NAME = "문서 제목";
var ID_RES_STRING_GO_TO_HOME = "원피스 홈으로 이동";

var ID_RES_STRING_DOCUMENT_RENAMED = "문서 제목이 변경 되었습니다";
var ID_RES_STRING_DOCUMENT_RENAMED_FAIL = "문서 제목 변경을 실패 했습니다";

var ID_RES_STRING_SETTING = "설정";
var ID_RES_STRING_MINUTES = "분";
var ID_RES_STRING_NOT_USED = "사용안함";
var ID_RES_STRING_RIBBON_MENU = "리본 메뉴";
var ID_RES_STRING_TOOLBAR_MENU = "툴바 메뉴";

var ID_RES_STRING_GET_NEWS_LIST = "기사링크 가져오기";
var ID_RES_STRING_POST_NEWS = "기사 등록";
var ID_RES_STRING_GET_CLOUD_IMAGE = "이미지 클라우드";
var ID_RES_STRING_POST_IMAGE = "이미지 등록";
var ID_RES_STRING_SET_IMAGE_INFO = "이미지 정보 설정";
var ID_RES_CONST_STRING_DEFAULT_ARTICLE_NAME = "새 기사";

var ID_RES_STRING_PLACEHOLDER_NEWS_TITLE = "기사의 제목을 입력하세요 (100자)";
var ID_RES_STRING_PLACEHOLDER_NEWS_SUBTITLE = "기사의 부제목을 입력하세요. (150자)";

var ID_RES_STRING_VOC = "고객 문의함";
var ID_RES_STRING_SEND = "전송";
var ID_RES_STRING_VOC_PLACEHOLDER = "문의하실 내용을 작성해주세요.";
var ID_RES_STRING_VOC_SEND_COMPLETE = "문의가 접수되었습니다.";

var ID_RES_STRING_INSERT_TAB = "탭키 입력";

var ID_RES_STRING_DEFAULT = "기본";
var ID_RES_STRING_EMPHASIS1 = "강조1";
var ID_RES_STRING_EMPHASIS2 = "강조2";
var ID_RES_STRING_EMPHASIS3 = "강조3";
var ID_RES_STRING_BOX1 = "박스1";
var ID_RES_STRING_BOX2 = "박스2";
var ID_RES_STRING_BOX3 = "박스3";
var ID_RES_STRING_QUOTATION = "인용구";
var ID_RES_STRING_FIRST_LETTER_BIG = "첫글자 크게";
var ID_RES_STRING_REMOVE_FORMAT = "서식 지우기";
var ID_RES_STRING_SUBTITLE1 = "소제목1";
var ID_RES_STRING_SUBTITLE2 = "소제목2";

//var ID_RES_STRING_NO_MYINFO = "권한이 없어 사용이 제한됩니다.\r\n확인을 누르면 창이 닫힙니다.";
var ID_RES_STRING_NO_MYINFO = "관리자 권한에서 사용이 제한됩니다.\r\n사용자 권한으로 변경 후 다시 접속해 주세요.";

var ID_RES_STRING_INSERT_FORM_CONTROL = "컨트롤 삽입";
var ID_RES_STRING_FORM_TAG_RADIO = "라디오";

var ID_RES_STRING_CHECK_ALL_CORONA = "재택근무 체크리스트를 모두 작성해 주세요";

var ID_RES_STRING_CORONA_PC_CONFIG = "재택근무 PC 환경설정 메뉴얼";
var ID_RES_STRING_CORONA_SOFTWARE = "재택근무 솔루션 활용 메뉴얼";
var ID_RES_STRING_CORONA_WORK_PROCESS = "재택근무 프로세스 메뉴얼";
var ID_RES_STRING_CORONA_SECURITY = "재택근무 보안 점검 메뉴얼";

var ID_RES_STRING_ALL = "모두";
var ID_RES_STRING_OUTER = "바깥쪽";
var ID_RES_STRING_INNER = "안쪽";

var ID_RES_STRING_FIND_END = "문서의 끝까지 찾았습니다.";

var ID_RES_STRING_TEMP_SAVED = "임시 저장되었습니다.";
var ID_RES_STRING_MOD_SAVED = "수정내역이 저장 되었습니다.";

var ID_RES_STRING_SAVED_GO_REPORT = "내용을 업데이트 하였습니다.\n업무보고 페이지로 이동합니다."
var ID_RES_STRING_FAIL_SAVE_REPORT = "보고서 저장을 실패했습니다.";
var ID_RES_STRING_FAIL_GET_REPORT = "보고서 조회를 실패했습니다.";
var ID_RES_STRING_FAIL_GET_REPORT_LIST = "보고서 목록 조회를 실패 했습니다.";
var ID_RES_STRING_FAIL_SAVE_FOR_NO_REPORT = "대상 보고서 정보가 없어 저장 할 수 없습니다.";
var ID_RES_STRING_TRY_AGAIN_AFTER_CLOSE_WIN = "현재창을 닫고 다시 시도해 주세요";

var ID_RES_STRING_SHOW_CONTENT = "원문 보기"
var ID_RES_STRING_SHOW_CONTENT_AT_NEW_WIN = "새창으로 보고서 원문 보기"

var ID_RES_STRING_SELECT_REPORT = "보고서를 선택 해 주세요";
var ID_RES_STRING_MERGE_END = "병합이 완료되었습니다.";

var ID_RES_STRING_TITLE_EDIT_HEADER = "더블 클릭하여 머리글 편집";
var ID_RES_STRING_TITLE_EDIT_FOOTER = "더블 클릭하여 바닥글 편집";

var ID_RES_STRING_RECENT_DELETE = '목록 제거';
var ID_RES_STRING_RECENT_DELETE_FAIL = "최근 항목 목록 제거에 실패했습니다.";

var ID_RES_CONST_STRING_FILELIST_NO_SEARCH = "검색 결과가 없습니다";
var ID_RES_STRING_SELECTED_REPORT_NODATA = "선택한 보고서가 없습니다";
var ID_RES_STRING_SELECTED_DOC_NODATA = "선택한 문서가 없습니다";

var ID_RES_STRING_SECURITY_DOC_CANNOT_SEND_REPORT = "보안 문서는 업무보고를 보낼 수 없습니다";

var ID_RES_STRING_NO_BACKUP_AND_RECOVER = "읽기모드에서는 백업 및 복원 기능을 지원 하지 않습니다.";

var ID_RES_CONST_STRING_SHOW_NUMPAGES = "전체 페이지 표시";
var ID_RES_CONST_STRING_NUMPAGES = "전체 페이지";

var ID_RES_CONST_STRING_ADD_TASK_SCHEDULE = "주요일정/주요업무 추가";
var ID_RES_CONST_STRING_DELETE_TASK_SCHEDULE = "주요일정/주요업무 삭제";

var ID_RES_STRING_AUTO_SAVE_CYCLE = "자동 저장 주기";

var ID_RES_CONST_STRING_HOUR = "시";
var ID_RES_CONST_STRING_MINUTE = "분";
var ID_RES_CONST_LEGEND = "범례";

var ID_RES_STRING_ALERT_CHANGE_LANGUAGE = "원피스 표시 언어가 {0}로 변경 됩니다.";
var ID_RES_STRING_LANGUAGE_KO = "한국어";
var ID_RES_STRING_LANGUAGE_EN = "영어";
var ID_RES_STRING_LANGUAGE_JA = "일본어";
var ID_RES_STRING_LANGUAGE_CN = "중국어";

var ID_RES_STRING_MY_GROUP = "My그룹";

var ID_RES_CONST_STRING_PAGE_NUMBER_BOX_MSG = "페이지 번호를 입력하십시오";

var ID_RES_CONST_STRING_TABLE_INSERT = "표 삽입";
var ID_RES_STRING_LETTER = "글자";

var ID_RES_STRING_INSERT_IMG = "이미지 삽입";
var ID_RES_STRING_INSERT_VIDEO = "비디오 삽입";

/* WE000028862 */var ID_RES_STRING_LAYOUT_TABLE_LIMIT_ROW = "레이아웃 양식은 한 페이지를 넘길 수 없습니다";

/* WE000028863 */var ID_RES_STRING_SELECT_MULTI_ROW = "여러 행을 선택해 주세요";
/* WE000028864 */var ID_RES_STRING_SELECT_MULTI_COL = "여러 열을 선택해 주세요";

var ID_RES_CONST_STRING_RETURN_TO_ORIGIN_DOC = "원본문서";
var ID_RES_CONST_STRING_EXTERNAL_BOX = "외부입력 상자";
var ID_RES_STRING_CURRENT_LIST_STYLE = "현재 목록";
//기사편집기
var ID_RES_CONST_STRING_INSERT_IMAGE2 = "이미지";
var ID_RES_PROP_INSERT_IMAGE2 = "이미지 속성";
var ID_RES_PROP_TAG_STRING_IMAGE2 = "이미지";
var ID_RES_PROP_TAG_STRING_USER_IMAGE2 = "이미지 사용";
var ID_RES_PROP_TAG_STRING_IMAGE_FILE2 = "이미지 파일";
var ID_RES_CONST_STRING_IMAGE_REPLACE2 = "이미지 바꾸기";
var ID_RES_CONST_STRING_IMAGE_SAVEAS2 = "이미지로 저장";
var ID_RES_CONST_STRING_DELETE_IMAGE2 = "이미지 삭제";

var ID_RES_DIALOG_STRING_URL_INPUT_YOUTUBE = "YouTube";
var ID_RES_DIALOG_STRING_URL_INPUT_NAVERTV = "NaverTV";
var ID_RES_DIALOG_STRING_URL_INPUT_KAKAOTV = "KakaoTV";

var ID_RES_STRING_SET_LIST_START_NEW = "번호 새로 매기기";
var ID_RES_STRING_SET_LIST_START_CONTINUE = "번호 매기기 계속";

var ID_RES_CONST_STRING_BROWSER_NEWSROOM = "기사관리함";
var ID_RES_CONST_STRING_BROWSER_MYNEWS_LIST = "내 기사";
var ID_RES_CONST_STRING_BROWSER_SEND_MYNEWS_LIST = "등록한 기사";//
var ID_RES_CONST_STRING_POST_MYNEWS = "등록";//

var ID_RES_STRING_NEWS_IMAGE_INFO = "기사 이미지 추가 정보";
var ID_RES_STRING_CAPTION = "캡션";
var ID_RES_STRING_REPLACE_TEXT = "대체문구";
var ID_RES_STRING_LINK_URL = "링크 URL";
var ID_RES_STRING_SET_MAIN_IMAGE = "주 이미지 설정";

var ID_RES_STRING_NEWS_SEND_INFO = "출고설정";
var ID_RES_CONST_STRING_NEWS_JOURNALIST_INFO = "기자 정보";
var ID_RES_CONST_STRING_NEWS_CLASSIFY_INFO = "기사 분류";
var ID_RES_CONST_STRING_NEWS_GRADE_INFO = "기사 등급";
var ID_RES_CONST_STRING_NEWS_JOURNALIST_SEND_INFO = "기자 명 게시 구분";
var ID_RES_CONST_STRING_NEWS_TITLE_INFO = "제목 / 부제목";
var ID_RES_CONST_STRING_NEWS_TAG_INFO = "태그";
var ID_RES_CONST_STRING_NEWS_NAVER_CATEGORY_INFO = "네이버 카테고리";

var ID_RES_STRING_ETC_MEMO = "메모";
var ID_RES_STRING_ETC_TODO = "할일";

var ID_RES_STRING_ETC_MEMO_INPUT_PLEASE = "메모를 입력해 주세요";
var ID_RES_STRING_ETC_TODO_INPUT_PLEASE = "할일을 입력해 주세요";

var ID_RES_STRING_WEBSEARCH_IMG_DBCLICK = "이미지를 더블클릭하면 본문에 삽입됩니다.";

var ID_RES_CONST_STRING_NO_DATA_MEMO = "등록된 메모가 없습니다.";
var ID_RES_CONST_STRING_NO_DATA_TODO = "등록된 할일이 없습니다.";
var ID_RES_STRING_UPDATE_POSTED_NEWS = "기사 업데이트";
