var BizWatch=null;
onefficeExtContent&&(onefficeExtContent=BizWatch=createClassObj(onefficeExtContent),BizWatch.indexEnv=1,BizWatch.hostName="https://ams.",BizWatch.mainDomain=["bizwatch","taxwatch"],BizWatch.getArticleUrl="",BizWatch.arrStyleTemplateName=[ID_RES_STRING_DEFAULT,ID_RES_STRING_EMPHASIS1,ID_RES_STRING_EMPHASIS2,ID_RES_STRING_EMPHASIS3,ID_RES_STRING_BOX1,ID_RES_STRING_BOX2,ID_RES_STRING_BOX3,ID_RES_STRING_QUOTATION,ID_RES_STRING_FIRST_LETTER_BIG,-1,ID_RES_STRING_REMOVE_FORMAT,ID_RES_STRING_SUBTITLE1,ID_RES_STRING_SUBTITLE2],
BizWatch.arrStyleTemplateClass=" bw_color_navy bw_color_blue bw_color_pink bw_box bw_box_blue bw_box_pink bw_quote bw_text_first    ".split(" "),BizWatch.getStyleTemplateHtml=function(a,d){try{switch(a){case ID_RES_STRING_DEFAULT:return"<p>"+a+"</p>";case ID_RES_STRING_EMPHASIS1:return'<p class="bw_color_navy" style="line-height: normal;">'+a+"</p>";case ID_RES_STRING_EMPHASIS2:return'<p class="bw_color_blue" style="line-height: normal;">'+a+"</p>";case ID_RES_STRING_EMPHASIS3:return'<p class="bw_color_pink" style="line-height: normal;">'+
a+"</p>";case ID_RES_STRING_BOX1:return'<p class="bw_box" style="line-height: normal; padding: 5px 10px;">'+a+"</p>";case ID_RES_STRING_BOX2:return'<p class="bw_box_blue" style="line-height: normal; padding: 5px 10px;">'+a+"</p>";case ID_RES_STRING_BOX3:return'<p class="bw_box_pink" style="line-height: normal; padding: 5px 10px;">'+a+"</p>";case ID_RES_STRING_QUOTATION:return'<p class="bw_quote" style="'+("combo"===d?"margin-left:-16px;":"")+'">'+a+"</p>";case ID_RES_STRING_FIRST_LETTER_BIG:return'<p class="bw_text_first_half" style="line-height: normal;">'+
a+"</p>";case ID_RES_STRING_REMOVE_FORMAT:return"gallery"===d?'<p style="line-height: normal; text-align: center;">'+ID_RES_STRING_REMOVE_FORMAT.replace(" ","<br>")+"</p>":'<p style="line-height: normal;">'+ID_RES_STRING_REMOVE_FORMAT+"</p>";case ID_RES_STRING_SUBTITLE1:return'<p class="bw_subtitle1" style="line-height: normal;">'+a+"</p>";case ID_RES_STRING_SUBTITLE2:return'<p class="bw_subtitle2" style="line-height: normal;">'+a+"</p>"}return""}catch(b){dalert(b)}},BizWatch.getData=function(a){try{if(!0===
this.testMode){this.setNewsInfoHeader();var d=parseInt(a,10)+DZE_IFRAME_TMP_NO;g_objEditorDocument[d].documentElement.innerHTML="<p>\ubcf4\uace0\uc11c \ud14c\uc2a4\ud2b8 \uc911\uc785\ub2c8\ub2e41</p><p>\ubcf4\uace0\uc11c \ud14c\uc2a4\ud2b8 \uc911\uc785\ub2c8\ub2e42</p><p>\ubcf4\uace0\uc11c \ud14c\uc2a4\ud2b8 \uc911\uc785\ub2c8\ub2e43</p>";onefficeExtContent.showContent(g_objEditorDocument[d].body.innerHTML,a)}else oneffice.onErrorCheckSession(function(){var b=onefficeExtContent.extCallUrlInfo.searchObject.article_no,
c="";b?duzon_http.ajax({type:"get",url:onefficeExtContent.getArticleUrl+"?article_no="+b,async:!0,dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(b){if("success"!==b.result)cmnCtrlToast.showToastMsg(null,"\uae30\uc0ac \uc870\ud68c\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. \ud604\uc7ac\ucc3d\uc744 \ub2eb\uace0 \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694",5);else{var d=parseInt(a,10)+DZE_IFRAME_TMP_NO;"undefined"==typeof b.data||null==
b.data?cmnCtrlToast.showToastMsg(null,"\uae30\uc0ac \uc870\ud68c\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. \ud604\uc7ac\ucc3d\uc744 \ub2eb\uace0 \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694",5):(g_objEditorDocument[d].documentElement.innerHTML=b.data.contents,c=1==g_objEditorDocument[d].body.childNodes.length&&"div"==g_objEditorDocument[d].body.firstChild.nodeName.toLowerCase()&&"oneffice_content"==g_objEditorDocument[d].body.firstChild.id?g_objEditorDocument[d].body.firstChild.innerHTML:
g_objEditorDocument[d].body.innerHTML,onefficeExtContent.showContent(c,a))}},error:function(b){cmnCtrlToast.showToastMsg(null,"\uae30\uc0ac \uc870\ud68c\uc5d0 \uc2e4\ud328\ud588\uc2b5\ub2c8\ub2e4. \ud604\uc7ac\ucc3d\uc744 \ub2eb\uace0 \ub2e4\uc2dc \uc2dc\ub3c4\ud574 \uc8fc\uc138\uc694",1.5)}}):(c="<p><br /></p>",onefficeExtContent.setNewsInfoHeader(),onefficeExtContent.showContent(c,a))},dzeUiConfig.bAlwaysCheckSession)}catch(b){dalert(b)}},BizWatch.setUiConfig=function(){},BizWatch.setNewsInfoHeader=
function(a){try{var d=a?a.title:"",b=a?a.subtitle:"";d=d||"";b=b||"";a=g_objHeaderFooter;a.setOption({bUseEditMode:!1});var c=dzeUiConfig.nSettingPaperMargin;c.headerTop=c.top;var e=['<div contenteditable="false" dze_not_show_outline="true">','<input id="bizwatch_title" contenteditable="true" autocomplete="off" style="width:100%; height: 55px; text-align: left; font-size: 30px; font-weight: bold; line-height: 1.3em; margin-bottom: 8px;" maxlength="100" placeholder="'+ID_RES_STRING_PLACEHOLDER_NEWS_TITLE+
'" value="'+d+'">','</div><div contenteditable="false" dze_not_show_outline="true">','<textarea id="bizwatch_subtitle" contenteditable="true" style="width:100%; height: 95px; font-size: 20px; font-weight: bold; line-height: 1.3em; letter-spacing: -0.02em; margin-bottom: 4px; resize:none;" maxlength="150" placeholder="'+ID_RES_STRING_PLACEHOLDER_NEWS_SUBTITLE+'">'+b+"</textarea>",'</div><hr contenteditable="false">'].join("");a.strFirstHeader=e;a.bDiffFirstPage=!0}catch(f){dalert(f)}},BizWatch.getNewsInfoHeader=
function(){try{var a={},d=g_objHeaderFooter.getHeader(0),b=d.querySelector("#bizwatch_title");b&&(a.title=b.value);var c=d.querySelector("#bizwatch_subtitle");c&&(a.title=c.value);return a}catch(e){dalert(e)}},BizWatch.getNewsList=function(a,d,b,c,e,f){try{var h=BizWatch.hostName+BizWatch.mainDomain[BizWatch.indexEnv]+".co.kr/api/v1.0/news_list";if(!1===fnObjectCheckNull(b)&&!1===isNaN(b)){if(!0===fnObjectCheckNull(c)||!0===isNaN(c))c=20}else!1!==fnObjectCheckNull(c)||!1!==isNaN(c)||!0!==fnObjectCheckNull(b)&&
!0!==isNaN(b)||(b=1);!1===fnObjectCheckNull(b)&&!1===fnObjectCheckNull(c)&&(h+="/"+b+"/"+c);a={channel:"douzone",key:a};!1===fnObjectCheckNull(d)&&""!==d&&(a.keyword=d);duzon_http.ajax({type:"get",url:h,async:!0,data:a,dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],success:function(b){!1===fnObjectCheckNull(b)&&0===1*b.ret_cd?!1===fnObjectCheckNull(e)&&"function"===typeof e&&e(b):!1===fnObjectCheckNull(f)&&"function"===typeof f&&f()},error:function(b){!1===
fnObjectCheckNull(f)&&"function"===typeof f&&f()}})}catch(g){dalert(g)}},BizWatch.processForFigureCustomEle=function(a){try{var d=document.createElement("figure"),b=document.createElement("figcaption");d.className="img-container cke_widget_element img-align-center";d.setAttribute("data-cke-widget-keep-attr",0);d.setAttribute("data-widget","insertimage");b.className="img-caption";for(var c=null,e=!1,f=0;f<a.length;f++){var h=a[f];e=!1;var g=h.closest("figure");if(fnObjectCheckNull(g))g=d.cloneNode(!0),
alert("objFigureNew"),e=!0;else{g.className="img-container cke_widget_element img-align-center";g.setAttribute("data-cke-widget-keep-attr",0);g.setAttribute("data-widget","insertimage");c=g.getElementsByTagName(DZETAG.A);var m=c.length?c[0]:null;fnObjectCheckNull(m)||m.removeAttribute("style")}g.draggable=!1;switch(h.getAttribute("align")){case "left":g_objPropertyUtil.addClass(g,"img-align-left");break;case "right":g_objPropertyUtil.addClass(g,"img-align-right");break;default:g_objPropertyUtil.addClass(g,
"img-align-center")}h.removeAttribute("style");h.removeAttribute("align");e&&(h.parentNode.insertBefore(g,h),g.appendChild(h));c=g.getElementsByTagName(DZETAG.FIGCAP);var l=c.length?c[0]:null;fnObjectCheckNull(l)?(l=b.cloneNode(!0),h.getAttribute("img_caption")&&(l.textContent=h.getAttribute("img_caption"),h.removeAttribute("img_caption"),g.appendChild(l))):(l.className="img-caption",l.removeAttribute("style"));var k=g.closest("p");fnObjectCheckNull(k)||(k.parentNode.insertBefore(g,k),(0===k.childNodes.length||
1===k.childNodes.length&&"BR"===k.childNodes[0].nodeName)&&k.parentNode.removeChild(k))}}catch(n){dalert(n)}},BizWatch.processForVideoCustomEle=function(a){try{forEach(a,function(a,b){if((a=b.firstElementChild)&&"IFRAME"===a.nodeName){a.width=b.style.width;a.height=b.style.height;a.removeAttribute("style");a.setAttribute("allow",";");b.style.width="";b.style.height="";b.style.display="";b.removeAttribute("playtype");b.removeAttribute("contenteditable");b.classList.remove("dze_video_iframe_container_span");
b.classList.add("youtube-embed-wrapper");var c=b.lastElementChild;c&&"videoresize"==c.nodeName.toLowerCase()&&b.removeChild(c);c=document.createElement("div");g_objNodeUtil.copyAttribute(c,b);g_objNodeUtil.moveNodesTo(c,a);b.parentElement.replaceChild(c,b)}},this)}catch(d){dalert(d)}},BizWatch.postArticle=function(a,d,b){try{duzon_http.ajax({type:"post",url:BizWatch.hostName+BizWatch.mainDomain[BizWatch.indexEnv]+".co.kr/api/v1.0/post_article",async:!0,data:a,dataType:"json",timeout:3E4,loading_screen:!0,
loading_image_url:"",loading_image_size:[],success:function(a){!1===fnObjectCheckNull(a)&&0===1*a.ret_cd?!1===fnObjectCheckNull(d)&&"function"===typeof d&&d(a):!1===fnObjectCheckNull(b)&&"function"===typeof b&&b()},error:function(a){!1===fnObjectCheckNull(b)&&"function"===typeof b&&b()}})}catch(c){dalert(c)}},BizWatch.postImage=function(a,d,b,c){try{!0===fnObjectCheckNull(c)&&(c=!0),duzon_http.ajax({type:"post",url:BizWatch.hostName+BizWatch.mainDomain[BizWatch.indexEnv]+".co.kr/api/v1.0/media_register",
async:!0,data:a,dataType:"form-data",timeout:3E4,loading_screen:c,loading_image_url:"",loading_image_size:[],success:function(a){a=duzon_http.parseJSON(a);!1===fnObjectCheckNull(a)&&0===1*a.ret_cd?!1===fnObjectCheckNull(d)&&"function"===typeof d&&d(a):!1===fnObjectCheckNull(b)&&"function"===typeof b&&b()},error:function(a){!1===fnObjectCheckNull(b)&&"function"===typeof b&&b()}})}catch(e){dalert(e)}},BizWatch.getCloudImageList=function(a,d,b,c,e,f){try{var h=BizWatch.hostName+BizWatch.mainDomain[BizWatch.indexEnv]+
".co.kr/api/v1.0/media_list/image";if(!1===fnObjectCheckNull(b)&&!1===isNaN(b)){if(!0===fnObjectCheckNull(c)||!0===isNaN(c))c=20}else!1!==fnObjectCheckNull(c)||!1!==isNaN(c)||!0!==fnObjectCheckNull(b)&&!0!==isNaN(b)||(b=1);!1===fnObjectCheckNull(b)&&!1===fnObjectCheckNull(c)&&(h+="/"+b+"/"+c);a={channel:"douzone",key:a};!1===fnObjectCheckNull(d)&&""!==d&&(a.keyword=d);duzon_http.ajax({type:"get",url:h,async:!0,data:a,dataType:"json",timeout:3E4,loading_screen:!0,loading_image_url:"",loading_image_size:[],
success:function(a){!1===fnObjectCheckNull(a)&&0===1*a.ret_cd?!1===fnObjectCheckNull(e)&&"function"===typeof e&&e(a):!1===fnObjectCheckNull(f)&&"function"===typeof f&&f()},error:function(a){!1===fnObjectCheckNull(f)&&"function"===typeof f&&f()}})}catch(g){dalert(g)}},BizWatch.setExtContentsEnv=function(){try{switch(location.origin.split(".")[1]){case BizWatch.mainDomain[1]:BizWatch.indexEnv=1;break;default:case BizWatch.mainDomain[0]:BizWatch.indexEnv=0}}catch(a){dalert(a)}},BizWatch.checkImageContents=
function(a){try{var d=g_objEditorDocument[a].querySelectorAll("img[chart_id]");a=[];for(var b,c="ttcdn."+onefficeExtContent.mainDomain[onefficeExtContent.indexEnv]+".co.kr",e=0;e<d.length;e++)b=d[e],-1===b.src.indexOf(c)&&a.push(b);return a}catch(f){dalert(f)}});
