var PLATFORMTYPE={NONE:0,WIN32:1,WIN64:2,MAC:3,MAC_INTEL:4},BROWSERTYPE={NONE:0,IE:1,CR:2,SF:3,EG:4,OP:5,FF:6,WK:7};
function cm_bwcheck(){this.m_AgentInfo={platform:PLATFORMTYPE.NONE,browser:BROWSERTYPE.NONE};this.getPlatformType=function(a){switch(a){default:case "win32":return PLATFORMTYPE.WIN32;case "win64":return PLATFORMTYPE.WIN64;case "mac":return PLATFORMTYPE.MAC;case "macintel":return PLATFORMTYPE.MAC_INTEL}};this.getBrowserType=function(a){switch(e){case "firefox":return BROWSERTYPE.FF;case "safari":return BROWSERTYPE.SF;case "webkit":return BROWSERTYPE.WK;case "edge":return BROWSERTYPE.EG;case "opera":return BROWSERTYPE.OP;
case "chorme":return BROWSERTYPE.CR}};this.getBrowserName=function(){var a=navigator.userAgent,d=navigator.appName,c=""+parseFloat(navigator.appVersion),e,b,f;-1!=(b=a.indexOf("Opera"))?(d="Opera",c=a.substring(b+6),-1!=(b=a.indexOf("Version"))&&(c=a.substring(b+8))):-1!=(b=a.indexOf("MSIE"))?(d="Microsoft Internet Explorer",c=a.substring(b+5)):-1!==a.indexOf("Mozilla/5.0")&&-1!==a.indexOf("Trident/7.0;")&&-1!==(b=a.indexOf("rv:"))?(d="Microsoft Internet Explorer",c=a.substring(b+3,b+7)):-1!=(b=a.indexOf("Chrome"))?
(d="Chrome",c=a.substring(b+7)):-1!=(b=a.indexOf("Safari"))?(d="Safari",c=a.substring(b+7),-1!=(b=a.indexOf("Version"))&&(c=a.substring(b+8))):-1!=(b=a.indexOf("Firefox"))?(d="Firefox",c=a.substring(b+8)):(e=a.lastIndexOf(" ")+1)<(b=a.lastIndexOf("/"))&&(d=a.substring(e,b),c=a.substring(b+1),d.toLowerCase()==d.toUpperCase()&&(d=navigator.appName));-1!=(f=c.indexOf(";"))&&(c=c.substring(0,f));-1!=(f=c.indexOf(" "))&&(c=c.substring(0,f));return d+" "+c};this.isMacPC=function(){return g_browserCHK.m_AgentInfo.platform==
PLATFORMTYPE.MAC_INTEL||this.iOS&&this.isWebView()?!0:!1};this.isWebView=function(){return g_browserCHK.iOS?g_browserCHK.sf?!1:!0:g_browserCHK.android?-1<g_browserCHK.agent.indexOf("; wv)")?!0:!1:!1};this.agent=navigator.userAgent.toLowerCase();this.agent.split(" ");this.ff=this.edge=this.wk=this.cr=this.op=!1;this.ff=-1<this.agent.indexOf("firefox");this.wk=-1<this.agent.indexOf("webkit");this.sf=this.cr=!1;this.wk&&(-1<this.agent.indexOf("chrome")?this.cr=!0:-1<this.agent.indexOf("safari")&&(this.sf=
!0));this.op=-1<this.agent.indexOf("opera");this.edge=-1<this.agent.indexOf("edge");this.galaxyfold_open=this.galaxyfold=this.androidtablet=this.iPad=this.android=this.iOS=this.mobile=!1;this.orientation=null;if(navigator.platform){var e=navigator.platform.toLowerCase(),g=/iPad|iPhone|iPod/.test(navigator.platform)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints;if(0>"win16|win32|win64|mac|macintel".indexOf(e)||g){this.mobile=!0;if(-1<this.agent.indexOf("iphone")||-1<this.agent.indexOf("ipad")||
-1<this.agent.indexOf("ipot")||"MacIntel"===navigator.platform)if(this.iOS=!0,-1<this.agent.indexOf("ipad")||"MacIntel"===navigator.platform)this.iPad=!0;-1<this.agent.indexOf("android")&&(this.android=!0,-1==this.agent.indexOf("mobile")&&(this.androidtablet=!0),0<this.agent.indexOf("sm-f")&&(this.galaxyfold=!0));!1===this.iPad&&!1===this.androidtablet&&(this.orientation="portrait")}else this.m_AgentInfo.platform=this.getPlatformType(e)}this.ff||this.wk||this.op||(this.ie10=-1<this.agent.indexOf("msie 10"),
this.ie9=-1<this.agent.indexOf("msie 9")&&!this.ie10,this.ie8=-1<this.agent.indexOf("msie 8")&&!this.ie9&&!this.ie10,this.ie7=-1<this.agent.indexOf("msie 7")&&!this.ie8&&!this.ie9&&!this.ie10,this.ie6=-1<this.agent.indexOf("msie 6")&&!this.ie7&&!this.ie8&&!this.ie9&&!this.ie10,!(this.ie6||this.ie7||this.ie8||this.ie9||this.ie10)&&-1<this.agent.indexOf("mozilla/5.0")&&(this.ie11=!0),this.ie=this.ie6||this.ie7||this.ie8||this.ie9||this.ie10||this.ie11);this.ie&&(this.ie6?this.verInfo=6:this.ie7?this.verInfo=
7:this.ie8?this.verInfo=8:this.ie9?this.verInfo=9:this.ie10?this.verInfo=10:this.ie11&&(this.verInfo=11));this.ff&&(this.verInfo=99);this.bw=this.ie||this.ff||this.wk||this.op;this.language=navigator.userLanguage?navigator.userLanguage.toLowerCase():navigator.language?navigator.language.toLowerCase():null;return this}var g_browserCHK=new cm_bwcheck,ID_LANGUAGE_TYPE_EN="en",ID_LANGUAGE_TYPE_KO="ko",ID_LANGUAGE_TYPE_JA="ja",ID_LANGUAGE_TYPE_ZH="zh",ID_LANGUAGE_TYPE_ZH_CN="zh-cn";
(function(){var e=g_browserCHK.language;switch(e){case "en":case "ja":case "zh-cn":g_strBrowserLanguage=e;break;case "ko":case "ko-kr":g_strBrowserLanguage="ko";break;default:g_strBrowserLanguage="en"}})();
