CONST_DZE_UPLOAD_TYPE_NONE=0;CONST_DZE_UPLOAD_TYPE_IMAGE=1;CONST_DZE_UPLOAD_TYPE_BACKGROUND_IMAGE=2;CONST_DZE_UPLOAD_TYPE_VIDEO=3;CONST_DZE_UPLOAD_TYPE_FILE=4;
var g_objExtUploader=new function(){var g=[],k=["gif","jpg","jpeg","png","bmp"];this.initWithUploadList=function(a,b){g=b;"undefined"!=typeof onefficeWE&&(this.m_bOnefficeWe=!0);g_objExtUploader.onStartUploadList()};this.onStartUploadList=function(){try{for(onefficeWE.imgFileUrlList=[];0<g.length;){var a=g.shift(),b=a.name.split(".").pop().toLowerCase(),d=k.concat(g_objVideoControl.getAllowPlayVideoList(!1));if(!inArray(b,d))try{alert('"'+a.name+'" '+ID_RES_CONST_STRING_CANNOT_UPLOAD_FILE_TYPE+" "+
d.join(", "));break}catch(c){break}"mp4"==b?this.nUploadType="drag_movie":""==this.nUploadType&&(this.nUploadType="drag_image");onefficeWE.saveImgFileProcess(a,null,null)}}catch(c){dlog("onStartUploadList error: "+c)}};this.nUploadType="";this.initWithUploadItem=function(a,b){try{if(onefficeWE.imgFileUrlList=[],this.nUploadType=b,a=null,"undefined"!=typeof onefficeWE&&(this.m_bOnefficeWe=!0),"undefined"!==typeof b){switch(b){case CONST_DZE_UPLOAD_TYPE_IMAGE:var d=document.getElementById("idx_insertimage_upimage_txt").files;
if(1<d.length)return DZE_UPLOAD_EVENT.dragNdropInsertImage(d,g_nActiveEditNumber);a=d[0];break;case CONST_DZE_UPLOAD_TYPE_BACKGROUND_IMAGE:a=document.getElementById("fileBackgroundImage").files[0];break;case CONST_DZE_UPLOAD_TYPE_VIDEO:a=document.getElementById("idx_insertvideo_upvideo_txt").files[0]}onefficeWE.saveImgFileProcess(a,null,null)}}catch(c){dlog("initWithUploadItem Error: "+c)}};this.onStartUploadImage=function(a){try{var b="";if("undefined"!=typeof a&&a.length)if(b=a,this.nUploadType==
CONST_DZE_UPLOAD_TYPE_IMAGE)this._uploadImgCallback&&this._uploadImgCallback(b);else if(this.nUploadType==CONST_DZE_UPLOAD_TYPE_BACKGROUND_IMAGE)g_objLayerKit.getElementById("txtReadBackgroundImageURL").value=b;else if(this.nUploadType==CONST_DZE_UPLOAD_TYPE_VIDEO)g_objVideoControl.setUpVideoUrl(b);else if("paste"==this.nUploadType)g_bBrowserType_IE?g_objExtUploader.pastedImageObj&&(g_objExtUploader.pastedImageObj.src=b):addHTMLContent("<img src='"+b+"' />",null,0,0),g_objUndoRedo.registerUndoRedoStack(0,
0);else if("drag_movie"==this.nUploadType){var d=this.getDragNDropVideoUploadHTML(b);d&&(addHTMLContent(d,null,0,0),g_objUndoRedo.registerUndoRedoStack(0,0))}else"drag_image"==this.nUploadType&&(addHTMLContent("<img src='"+b+"' />",null,0,0),g_objUndoRedo.registerUndoRedoStack(0,0))}catch(c){dlog("onStartUploadImage Error: "+c)}};this.getDragNDropVideoUploadHTML=function(a){try{if(null==a||""==a)return null;var b="<span>";b=g_bBrowserType_IE?b+"<video width=320 height=240 contenteditable='false'>":
b+"<video width=320 height=240 controls='' contenteditable='false' draggable='true'>";b+="\t<source src='"+a+"' type='video/mp4'>";b+="\tYour browser does not support the video tag.";return b+"</video></span>"}catch(d){dalert(d)}};this.onStartUploadBGImage=function(){try{var a=g_objLayerKit.getElementById("ifrmImageFileUploadTarget").contentWindow.document.body.innerHTML,b=duzon_http.parseJSON(a);"success"!=b.result?(alert(ID_RES_DIALOG_ALERT_UPLOAD_ERROR),g_strBackgroundImageURL=null):(g_strBackgroundImageURL=
b.url,g_objLayerKit.getElementById("txtReadBackgroundImageURL").value=b.url)}catch(d){g_strBackgroundImageURL=null,g_objLayerKit.getElementById("txtReadBackgroundImageURL").value="",dlog("onStartUploadBGImage Error: "+d)}};this.onStartUploadVideo=function(){try{var a=g_objLayerKit.getElementById(duzon_dialog.idx_dze_upload_iframe).contentWindow.document.body.innerHTML,b=duzon_http.parseJSON(a);if("success"!=b.result)alert(ID_RES_DIALOG_ALERT_UPLOAD_ERROR);else{b.url=getFullUrlFromPath(b.url);var d=
b.filename.split(".").pop().toLowerCase();0==g_objVideoControl.canPlayVideo(d)?(alert(ID_RES_DIALOG_ALERT_SELECT_VALID_VIDEO),g_objLayerKit.getElementById("idx_insertvideo_upvideo_txt").focus(),g_objVideoControl.setUpVideoUrl(null)):(DZE_UPLOAD_EVENT.setComplete(duzon_dialog.nEditNumber,b),g_objVideoControl.setUpVideoUrl(b.url))}}catch(c){dlog("onStartUploadVideo Error: "+c)}};this.onStartUploadFile=function(){try{var a=g_objLayerKit.getElementById("idx_dze_upload_iframe").contentWindow.document.body.innerHTML,
b=duzon_http.parseJSON(a);if("success"!=b.result)alert(ID_RES_DIALOG_ALERT_UPLOAD_ERROR);else{DZE_UPLOAD_EVENT.setComplete(duzon_dialog.nEditNumber,b);b.url=getFullUrlFromPath(b.url);var d=g_objLayerKit.getElementById(duzon_dialog.idx_dze_up_extfile).value.split(".").pop().toLowerCase(),c=duzon_dialog.setFileExtIconPath(d),f=1==dzeUiConfig.attachFileExtIconView?"<a href='"+b.url+"' type='dzeExtFile' title=\"\" alt='"+b.filename+"' style=\"background-image: url("+c+');background-repeat: no-repeat;background-position: left top;padding:2px 0 2px 18px;margin:0 8px 0 8px;color:#000000;text-decoration:none;font-weight:bold;"  >'+
b.filename+"</a>"+duzon_dialog.dze_bookmark_last_tag+" ":"<a href='"+b.url+"' type='dzeExtFile' title=\"\" alt='"+b.filename+'\' style="color:#000000;text-decoration:none;font-weight:bold;"  >'+b.filename+"</a>"+duzon_dialog.dze_bookmark_last_tag+" ";g_objLayerKit.getElementById("idx_dze_insert_extfile_link_box").innerHTML=f;g_objLayerKit.getElementById("idx_dze_insert_extfile_text").value=b.filename}}catch(e){dlog("onStartUploadFile Error: "+e)}};this.pastedImageObj=null;this.pasteImageFromClipboard=
function(a,b){try{if(window.addEventListener)if(g_bBrowserType_IE||g_bBrowserType_FF)setTimeout(function(){for(var a=g_objEditorDocument[b].body.getElementsByTagName("img"),d=0;d<a.length;d++){var c=/^data:image\/png;base64,/i;if(c.test(a[d].src)){if("undefined"!=typeof onefficeWE)c=a[d].src.replace(c,""),c=b64toBlob(c,"image/png"),c.name="pasteimage_"+onefficeUtil.getNewSeq()+".png",g_objExtUploader.nUploadType="paste",g_objExtUploader.pastedImageObj=a[d],onefficeWE.saveImgFileProcess(c,null,null);
else{c=new XMLHttpRequest;c.open("POST",dzeEnvConfig.strSavePasteImageURL,!0);c.onload=function(){var c=duzon_http.parseJSON(this.responseText);"success"==c.result&&(c.url=getFullUrlFromPath(c.url),a[d].src=c.url,DZE_UPLOAD_EVENT.setComplete(b,c),g_objUndoRedo.registerUndoRedoStack(0,b))};c.onerror=function(){alert("Error")};var e=new FormData;e.append("dze_upimage_data",a[d].src);c.send(e)}break}}},0);else if(g_bBrowserType_WK||g_bBrowserType_OP){var d="";a.clipboardData&&a.clipboardData.getData&&
(d=a.clipboardData.getData("text/plain"));if(""!==d)setTimeout(function(){for(var a=g_objEditorDocument[b].body.getElementsByTagName("img"),c=0;c<a.length;c++)/^file:\/\//i.test(a[c].src)&&a[c].parentNode.removeChild(a[c])},0);else if("undefined"!=typeof onefficeWE){for(var c=(a.clipboardData||a.originalEvent.clipboardData).items,f=null,e=0;e<c.length;e++)0===c[e].type.indexOf("image")&&(f=c[e].getAsFile());null!==f&&(this.nUploadType="paste",onefficeWE.saveImgFileProcess(f,null,null))}else{var h=
new XMLHttpRequest;h.open("POST",dzeEnvConfig.strSavePasteImageURL,!0);h.onload=function(){var a=duzon_http.parseJSON(this.responseText);"success"==a.result&&(a.url=getFullUrlFromPath(a.url),addHTMLContent("<img src='"+a.url+"' />",null,0,b),g_objUndoRedo.registerUndoRedoStack(0,b))};h.onerror=function(){alert("Error")};c=(a.clipboardData||a.originalEvent.clipboardData).items;f=null;for(e=0;e<c.length;e++)0===c[e].type.indexOf("image")&&(f=c[e].getAsFile());if(null!==f){var g=new FileReader;g.onload=
function(a){var b=new FormData;b.append("dze_upimage_data",a.target.result);h.send(b)};g.readAsDataURL(f)}}}}catch(l){dlog("pasteInsertImageFromClipboard error: "+l)}};this.getFullUrlFromURL=function(a){try{var b="";return b=0==a.indexOf("http://")||0==a.indexOf("https://")||0==a.indexOf("//")?a:0==a.indexOf("/")?document.location.origin+a:document.location.href.substring(0,location.href.lastIndexOf("/"))+"/"+a}catch(d){dlog("getFullUrlFromURL error: "+d)}}};
