var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,d){a instanceof String&&(a=String(a));for(var c=a.length,f=0;f<c;f++){var g=a[f];if(b.call(d,g,f,a))return{i:f,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];f in d||(d[f]={});d=d[f]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,d){return $jscomp.findInternal(this,a,d).v}},"es6","es3");
window.onload=function(){try{var a=document.querySelector(".mentionContainer .commentBox .commentView.replyIn"),b=document.querySelector(".mentionContainer .editorBox .editFileBox .fileTitle .fileModifyTit");void 0!==b&&null!==b&&(b.onclick=function(){var c=document.querySelector(".mentionContainer .editorBox");void 0!==c&&null!==c&&void 0!==a&&null!==a&&(a.style.height="calc(100% - "+(c.offsetHeight+10)+"px)")});var d=document.querySelector(".mentionContainer .editorBox .editFileBox .fileTitle .fileUploadBtn input");
void 0!==d&&null!==d&&(d.onchange=function(){var c=document.querySelector(".mentionContainer .editorBox"),d=document.querySelector(".mentionContainer .commentBox .commentView .editorBox[name=editorBoxClone]"),b=document.querySelector(".mentionContainer .commentBox .commentView .commentDiv .editWrap .editorBox");void 0!==a&&null!==a&&(void 0!==d&&null!==d?a.style.height="calc(100% - 15px)":void 0!==b&&null!==b?$(b).parents(".commentDiv")===a.lastChild?a.style.height="calc(100% - 25px)":a.style.height=
"calc(100% - 15px)":void 0!==c&&null!==c&&(a.style.height="calc(100% - "+(c.offsetHeight+10)+"px)"));c=document.querySelectorAll(".mentionContainer .editorBox .editFileBox .fileGroup li .del_file");if(0<c.length)for(var e=0;e<c.length;e++)c[e].onclick=function(){var c=document.querySelector(".mentionContainer .editorBox");void 0!==a&&null!==a&&(void 0!==d&&null!==d?a.style.height="calc(100% - 15px)":void 0!==b&&null!==b?$(b).parents(".commentDiv")===a.lastChild?a.style.height="calc(100% - 25px)":
a.style.height="calc(100% - 15px)":void 0!==c&&null!==c&&(a.style.height="calc(100% - "+(c.offsetHeight+10)+"px)"))}});updateCommentContainer(!0);overrideSendBtn(!0);overrideCommentBtn();overrideDelBtn()}catch(c){parent.dalert(c)}};
var updateCommentContainer=function(a){try{setTimeout(function(){var a=document.querySelector(".mentionContainer .editorBox"),d=document.querySelector(".mentionContainer .commentBox .commentView.replyIn");void 0!==a&&null!==a&&void 0!==d&&null!==d&&(d.style.height="calc(100% - "+(a.offsetHeight+10)+"px)")},1E3)}catch(b){parent.dalert(b)}},checkHashTag=function(a){try{for(var b=a.childNodes,d,c="",f=0;f<b.length;f++)if(d=b[f],3===d.nodeType)for(var g=d.textContent,e=g.split(/[\s,]+/),k,l,h=0;h<e.length;h++)k=
e[h],c=0===k.indexOf("#")?c+("<span class='dze_comment_hashtag'>"+e[h]+"</span>"):c+e[h],void 0!==e[h+1]&&null!==e[h+1]&&""!==e[h+1]&&(l=g.substring(g.indexOf(e[h])+e[h].length,g.indexOf(e[h+1])),c+=l);else"BR"===d.nodeName&&(c+="<br>");0!==c.length&&(a.innerHTML=c)}catch(m){parent.dalert(m)}},overrideSendBtn=function(a){try{var b=document.querySelector(!0===a?".mentionContainer .editorBox .editTextBox .textBtn .submitBtn":".mentionContainer .commentView .editorBox .editTextBox .textBtn .submitBtn");
void 0!==b&&null!==b&&(b.onclick=function(){var a=$(this).parents("[editor_mode=edt],[editor_mode=rpy],[editor_mode=top]");0===$(a).find("[name=mentionSpan]").length&&""===$(a).find(".textDiv").text().trim()&&0===$(a).find(".fileGroup li").length?parent.alert("\uc800\uc7a5\ud560 \ucee8\ud150\uce20\uac00 \uc5c6\uc2b5\ub2c8\ub2e4.","error"):(fnAttFileUpload(),setTimeout(function(){updateCommentContainer(!0);overrideSendBtn(!0);overrideCommentBtn();overrideDelBtn()},500))})}catch(d){parent.dalert(d)}},
overrideCommentBtn=function(){try{var a=document.querySelectorAll(".commentBtn li[name=liRpy], .commentBtn li[name=liEdt]");if(0<a.length)for(var b=document.querySelector(".mentionContainer .commentBox .commentView.replyIn"),d=0;d<a.length;d++)a[d].onclick=function(){var a=document.querySelector(".mentionContainer .editorBox"),d=document.querySelector(".mentionContainer .commentBox .commentView .editorBox[name=editorBoxClone]"),g=document.querySelector(".mentionContainer .commentBox .commentView .commentDiv .editWrap .editorBox");
void 0!==b&&null!==b&&(void 0!==d&&null!==d?b.style.height="calc(100% - 15px)":void 0!==g&&null!==g?$(g).parents(".commentDiv")===b.lastChild?b.style.height="calc(100% - 25px)":b.style.height="calc(100% - 15px)":void 0!==a&&null!==a&&(b.style.height="calc(100% - "+(a.offsetHeight+10)+"px)"));a=document.querySelector(".mentionContainer .commentBox .commentView .editorBox .editCloseBtn");void 0!==a&&null!==a&&(a.onclick=function(){updateCommentContainer()});overrideSendBtn(!1)}}catch(c){parent.dalert(c)}},
overrideDelBtn=function(){try{var a=document.querySelectorAll(".commentBtn li[name=liDel] a");if(0<a.length)for(var b=0;b<a.length;b++)a[b].onclick=function(){parent.cmnMsg.showMsg("check","\uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?",void 0,["\ud655\uc778","\ucde8\uc18c"],function(){var a={},c={},b=parent.oneffice_cloud_myInfoData;c.companyInfo={bizSeq:b.biz_seq,compSeq:b.comp_id,deptSeq:b.org_id,emailAddr:b.mail_id,emailDomain:b.mail_domain,empSeq:b.id,groupSeq:b.group_seq};c.langCode="kr";
c.commentSeq=$(this).parents(".commentDiv").attr("comment_seq");c.topLevelCommentSeq=$(this).parents(".commentDiv").attr("top_level_comment_seq");a.header={};a.body=c;$.ajax({type:"post",url:"/gw/api/DeleteComment.do",contentType:"application/json",data:JSON.stringify(a),success:function(a){"0"==a.resultCode&&(searchCommentList(),updateCommentContainer(!0),overrideSendBtn(!0),overrideCommentBtn(),overrideDelBtn());parent.cmnMsg.hideMsg()},error:function(a){parent.cmnMsg.hideMsg()}})}.bind(this),function(){parent.cmnMsg.hideMsg()})}}catch(d){parent.dalert(d)}};
